---
title: "References"
author: Kathryn Kozak
format: html
editor: visual
---

## Data Sources:

(n.d.). Retrieved July 18, 2019, from https://www.idvbook.com/teaching-aid/data-sets/the-breakfast-cereal-data-set/ The Best Kids' Cereal. (n.d.). Retrieved July 18, 2019, from https://www.ranker.com/list/best-kids-cereal/ranker-food

(n.d.). Retrieved from https://www3.nd.edu/\~busiforc/handouts/Data and Stories/t test/Friday The Thirteenth/Friday The Thirteenth Data.html

(n.d.). Retrieved July 21, 2019, from https://www3.nd.edu/\~busiforc/handouts/Data and Stories/regression/us auto mileage/usautomileage.html

http://apps.who.int/gho/athena/data/download.xsl?format=xml&target=GHO/WHOSIS_000001&profile=excel&filter=COUNTRY:;SEX:;REGION:EUR

Aboriginal deaths in custody. (2013, September 26). Retrieved from \<http://www.statsci.org/data/oz/custody.html

Activities of Dolphin Groups. (n.d.). Retrieved July 12, 2019, from http://www.statsci.org/data/general/dolpacti.html

Advanced Solutions International, Inc. (n.d.). Retrieved July 16, 2019, from https://www.amstat.org/asa/News/ASA-Calls-Time-on-Statistically-Significant-in-Science-Research.aspx

Annual maximums of daily rainfall in Sydney. (2013, September 25). Retrieved from \<http://www.statsci.org/data/oz/sydrain.html\>

AP exam scores. (2013, November 20). Retrieved from \<http://wiki.stat.ucla.edu/socr/index.php/SOCR_Data_Dinov_030708_APExamScores\>

Appliance life expectancy. (2013, November 8). Retrieved from \<http://www.mrappliance.com/expert/life-guide/\>

Australian Human Rights Commission, (1996). Indigenous deaths in custody 1989 - 1996. Retrieved from website: \<http://www.humanrights.gov.au/publications/indigenous-deaths-custody\>

Bhat, R., & Kushtagi, P. (2006). A re-look at the duration of human pregnancy. Singapore Med J., 47(12), 1044-8. Retrieved from \<http://www.ncbi.nlm.nih.gov/pubmed/17139400\>

Boyle, P., Flowerdew, R., & Williams, A. (1997). Evaluating the goodness of fit in models of sparse medical data: A simulation approach. International Journal of Epidemiology, 26(3), 651-656. Retrieved from \<http://ije.oxfordjournals.org/content/26/3/651.full.pdf\> html

Brain2bodyweight. (2013, November 16). Retrieved from http://wiki.stat.ucla.edu/socr/index.php/SOCR_Data_Brain2BodyWeight

Buy sushi grade fish online. (2013, November 20). Retrieved from http://www.catalinaop.com/

Cancer survival story. (2013, December 04). Retrieved from \<http://lib.stat.cmu.edu/DASL/Stories/CancerSurvival.html\>

Calories datafile. (2013, December 07). Retrieved from \<http://lib.stat.cmu.edu/DASL/Datafiles/Calories.html\>

Capital and rental values of Auckland properties. (2013, September 26). Retrieved from http://www.statsci.org/data/oz/rentcap.html

Car Preferences. (n.d.). Retrieved July 11, 2019, from http://www.statsci.org/data/oz/carprefs.html

CDC-data and statistics, autism spectrum disorders - ncbdd. (2013, October 21). Retrieved from \<http://www.cdc.gov/ncbddd/autism/data.html\>

CDC features - new data on autism spectrum disorders. (2013, November 26). Retrieved from \<http://www.cdc.gov/features/countingautism/\>

Center for Disease Control and Prevention, Prevalence of Autism Spectrum Disorders - Autism and Developmental Disabilities Monitoring Network. (2008). Autism and developmental disabilities monitoring network-2012. Retrieved from website: \<http://www.cdc.gov/ncbddd/autism/documents/ADDM-2012-Community-Report.pdf\>

CO2 emissions (metric tons per capita). (n.d.). Retrieved July 18, 2019, from https://data.worldbank.org/indicator/EN.ATM.CO2E.PC

College Board, SAT. (2012). Total group profile report. Retrieved from website: \<http://media.collegeboard.com/digitalServices/pdf/research/TotalGroup-2012.pdf\>

Consumer Price Index Data from 1913 to 2019. (2019, June 12). Retrieved July 10, 2019, from https://www.usinflationcalculator.com/inflation/consumer-price-index-and-annual-percent-changes-from-1913-to-2008/

CPS News Releases. (n.d.). Retrieved July 8, 2019, from https://www.bls.gov/cps/

Cuckoo eggs in nest of other birds. (2013, December 04). Retrieved from \<http://lib.stat.cmu.edu/DASL/Stories/cuckoo.html\>

Current health expenditure (% of GDP). (n.d.). Retrieved July 9, 2019, from https://data.worldbank.org/indicator/SH.XPD.CHEX.GD.ZS

11 little-known facts about left-handers. (2013, October 21). Retrieved from \<http://www.huffingtonpost.com/2012/10/29/left-handed-facts-lefties_n\_2005864.html\>

Education by age datafile. (2013, December 05). Retrieved from \<http://lib.stat.cmu.edu/DASL/Datafiles/Educationbyage.html\>

Encyclopedia Titanica. (2013, November 09). Retrieved from \<http://www.encyclopedia-titanica.org/\>

Deaths from firearms. (2013, September 26). Retrieved from http://www.statsci.org/data/oz/firearms.html

Flanagan, R., Rooney, C., & Griffiths, C. (2005). Fatal poisoning in childhood, england & wales 1968-2000. Forensic Science International, 148:121-129, Retrieved from \<http://www.cdc.gov/nchs/data/ice/fatal_poisoning_child.pdf\>

Federal Trade Commission, (2008). Consumer fraud and identity theft complaint data: January-December 2007. Retrieved from website: \<http://www.ftc.gov/opa/2008/02/fraud.pdf\>

Fertility rate, total (births per woman). (n.d.). Retrieved July 8, 2019, from https://data.worldbank.org/indicator/SP.DYN.TFRT.IN

Find Out How Many Calories in Beer? (n.d.). Retrieved July 21, 2019, from https://www.beer100.com/beer-calories/

Gettler, L. T., McDade, T. W., Feranil, A. B., & Kuzawa, C. W. (2011). Longitudinal evidence that fatherhood decreases testosterone in human males. The Proceedings of the National Academy of Sciences, PNAS 2011, doi: 10.1073/pnas.1105403108

Global health observatory data respository. (2013, October 09). Retrieved from \[http://apps.who.int/gho/athena/data/download.xsl?format=xml&target=GHO/MORT\\\\\\\_400&profile=excel&filter=AGEGROUP:YEARS05-14;AGEGROUP:YEARS15-29;AGEGROUP:YEARS30-49;AGEGROUP:YEARS50-69;AGEGROUP:YEARS70\](http://apps.who.int/gho/athena/data/download.xsl?format=xml&target=GHO/MORT\\\_400&profile=excel&filter=AGEGROUP:YEARS05-14;AGEGROUP:YEARS15-29;AGEGROUP:YEARS30-49;AGEGROUP:YEARS50-69;AGEGROUP:YEARS70){.uri} ;MGHEREG:REG6_AFR;GHECAUSES:\\;SEX:\\

Health Insurance Market Place Retrieved from website: http://aspe.hhs.gov/health/reports/2013/marketplacepremiums/ib_premiumslandscape.pdf

Helmet Sizes for New Zealand Airforce. (n.d.). Retrieved July 20, 2019, from http://www.statsci.org/data/oz/nzhelmet.html

Ho, P. M., Bryson, C. L., & Rumsfeld, J. S. (2009). Medication adherence. Circulation, 119(23), 3028-3035. Retrieved from \<http://circ.ahajournals.org/content/119/23/3028\>

Households by age of householder and size of household: 1990 to 2010. (2013, October 19). Retrieved from \<http://www.census.gov/compendia/statab/2012/tables/12s0062.pdf\>

Janssen, P. A., Thiessen, P., Klein, M. C., Whitfield, M. F., MacNab, Y. C., & Cullis-Kuhl, S. C. (2007). Standards for the measurement of birth weight, length and head circumference at term in neonates of european, chinese and south asian ancestry. Open Medicine, 1(2), e74-e88. Retrieved from \<http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2802014/\>

John Matic provided the data from a company he worked with. The company's name is fictitious, but the data is from an actual company.

Kiama blowhole eruptions. (2013, September 25). Retrieved from \<http://www.statsci.org/data/oz/kiama.html\>

Kozak K (2019). Survey results form surveys collected in statistics class at Coconino Community College.

Kuulasmaa, K., Hense, H., & Tolonen, H. World Health Organization (WHO), WHO Monica Project. (1998). Quality assessment of data on blood pressure in the who monica project (ISSN 2242-1246). Retrieved from WHO MONICA Project e-publications website: \<http://www.thl.fi/publications/monica/bp/bpqa.htm\>

Labor force participation rate, female (% of female population ages 15 ) (modeled ILO estimate). (n.d.). Retrieved July 20, 2019, from https://data.worldbank.org/indicator/SL.TLF.CACT.FE.ZS

Lange TL, Royals HE, Connor LL (1993) Influence of water chemistry on mercury concentration in largemouth bass from Florida lakes. Trans Am Fish Soc 122:74-84. Michael K. Saiki, Darell G. Slotton, Thomas W. May, Shaun M. Ayers, and Charles N. Alpers (2000) Summary of Total Mercury Concentrations in Fillets of Selected Sport Fishes Collected during 2000--2003 from Lake Natoma, Sacramento County, California (Raw data is included in appendix), U.S. Geological Survey Data Series 103, 1-21. NISER 081107 ID Data. (n.d.). Retrieved July 18, 2019, from http://wiki.stat.ucla.edu/socr/index.php/NISER_081107_ID_Data

Lawes, C., Hoorn, S., Law, M., & Rodgers, A. (2004). High cholesterol. In M. Ezzati, A. Lopez, A. Rodgers & C. Murray (Eds.), Comparative Quantification of Health Risks (1 ed., Vol. 1, pp. 391-496). Retrieved from \<http://www.who.int/publications/cra/chapters/volume1/0391-0496.pdf\>

Lee, A. (1994). Data analysis: An introduction based on r. Auckland. Retrieved from \<http://www.statsci.org/data/oz/nzrivers.html\>

Life expectancy at birth. (2013, October 14). Retrieved from http://data.worldbank.org/indicator/SP.DYN.LE00.IN

Life expectancy in southeast Asia. (2013, September 23). Retrieved from \<http://apps.who.int/gho/data/node.main.688\>

Madison, J. (2013, October 15). M&M's color distribution analysis. Retrieved from \<http://joshmadison.com/2007/12/02/mms-color-distribution-analysis/\>

Magazine ads readability. (2013, December 04). Retrieved from \<http://lib.stat.cmu.edu/DASL/Datafiles/magadsdat.html\>

M&M's Color Distribution Analysis. (n.d.). Retrieved July 11, 2019, from https://joshmadison.com/2007/12/02/mms-color-distribution-analysis/

Maintaining Balance while Concentrating. (n.d.). Retrieved July 19, 2019, from http://www.statsci.org/data/general/balaconc.html

MLB heightsweights. (2013, November 16). Retrieved from http://wiki.stat.ucla.edu/socr/index.php/SOCR_Data_MLB_HeightsWeights

OECD economic development. (2013, December 04). Retrieved from http://lib.stat.cmu.edu/DASL/Datafiles/oecdat.html

Olson, K., & Hanson, J. (1997). Using reiki to manage pain: a preliminary report. Cancer Prev Control, 1(2), 108-13. Retrieved from \<http://www.ncbi.nlm.nih.gov/pubmed/9765732\>

Ovegard, M., Berndt, K., & Lunneryd, S. (2012). Condition indices of Atlantic cod (gadus morhua) biased by capturing method. ICES Journal of Marine Science, doi: 10.1093/icesjms/fss145

Popular kids datafile. (2013, December 05). Retrieved from \<http://lib.stat.cmu.edu/DASL/Datafiles/PopularKids.html\>

Population density (people per sq. km of land area). (n.d.). Retrieved July 9, 2019, from https://data.worldbank.org/indicator/EN.POP.DNST

Population reference bureau. (2013, October 8). Retrieved from \<http://www.prb.org/DataFinder/Topic/Rankings.aspx?ind=25\>

Prediction of Height from Metacarpal Bone Length. (n.d.). Retrieved July 9, 2019, from http://www.statsci.org/data/general/stature.html

Pregnant women receiving prenatal care (%). (n.d.). Retrieved July 9, 2019, from https://data.worldbank.org/indicator/SH.STA.ANVC.ZS

Pulse rates before and after exercise. (2013, September 25). Retrieved from \<http://www.statsci.org/data/oz/ms212.html\>

Reserve Bank of Australia. (2019, May 13). Statistical Tables. Retrieved July 10, 2019, from https://www.rba.gov.au/statistics/tables/

Ryan, B. F., Joiner, B. L., & Ryan, Jr, T. A. (1985). Cholesterol levels after heart attack. Retrieved from \<http://www.statsci.org/data/general/cholest.html\>

Sanchez, Y. W. (2016, October 20). Poll: Arizona voters still favor legalizing marijuana. Retrieved from https://www.azcentral.com/story/news/politics/elections/2016/10/20/poll-arizona-marijuana-legalization-proposition-205/92417690/

Schultz, S. T., Klonoff-Cohen, H. S., Wingard, D. L., Askhoomoff, N. A., Macera, C. A., Ji, M., & Bacher, C. (2006). Breastfeeding, infant formula supplementation, and autistic disorder: the results of a parent survey. International Breastfeeding Journal, 1(16), doi: 10.1186/1746-4358-1-16

Seafood online. (2013, November 20). Retrieved from http://www.allfreshseafood.com/

Smoking and cancer. (2013, December 04). Retrieved from http://lib.stat.cmu.edu/DASL/Datafiles/cigcancerdat.html

SOCR 012708 id data hotdogs. (2013, November 13). Retrieved from http://wiki.stat.ucla.edu/socr/index.php/SOCR_012708_ID_Data_HotDogs

SOCR Data 2008 World CountriesRankings. (n.d.). Retrieved July 19, 2019, from http://wiki.stat.ucla.edu/socr/index.php/SOCR_Data_2008_World_CountriesRankings#SOCR_Data\_-\_Ranking_of_the_top_100_Countries_based_on_Political.2C_Economic.2C_Health.2C_and_Quality-of-Life_Factors

SOCR data Oct2009 id ni. (2013, November 16). Retrieved from http://wiki.stat.ucla.edu/socr/index.php/SOCR_Data_Oct2009_ID_NI

SOCR data nips infantvitK shotdata. (2013, November 16). Retrieved from http://wiki.stat.ucla.edu/socr/index.php/SOCR_Data_NIPS_InfantVitK_ShotData

Staff nurse - RN salary. (2013, November 08). Retrieved from \<http://www1.salary.com/Staff-Nurse-RN-salary.html\>

Time between nerve pulses. (2019, July 3). Retrieved from \<http://www.statsci.org/data/general/nerve.html\>

Time of passages of play in rugby. (2013, September 25). Retrieved from \<http://www.statsci.org/data/oz/rugby.html\>

Tuition and Fees, 1998-99 Through 2018-19. (2018, December 31). Retrieved from https://www.chronicle.com/interactives/tuition-and-fees

U.S. Census Bureau, Current Population Survey, Annual Social and Economic Supplements.

US Department of Agriculture, Agricultural Research Service. (2012). What we eat in America. Retrieved from website: \<http://www.ars.usda.gov/Services/docs.htm?docid=18349\>

US Department of Commerce, & Noaa. (2016, November 15). 1950 Oklahoma Tornadoes. Retrieved from https://www.weather.gov/oun/tornadodata-ok-1950

UV radiation: Burden of disease by country. (2013, September 4). Retrieved from \<http://apps.who.int/gho/data/node.main.165?lang=en\>

Waste run up. (2013, December 04). Retrieved from \<http://lib.stat.cmu.edu/DASL/Stories/wasterunup.html\>

What percentage of people have green eyes?. (2013, October 21). Retrieved from \<http://www.ask.com/question/what-percentage-of-people-have-green-eyes\>
