{
  "hash": "825da05ba204a00295fb4d8264792e99",
  "result": {
    "markdown": "---\ntitle: \"Continuous Probability Distribution\"\nformat: docx\neditor: visual\n---\n\n\n\n\nChapter 5 dealt with probability distributions arising from discrete random variables. Mostly that chapter focused on the binomial experiment. There are many other experiments from discrete random variables that exist but are not covered in this book.\n\nChapter 6 deals with probability distributions that arise from continuous random variables. The focus of this chapter is a distribution known as the normal distribution, though realize that there are many other distributions that exist. A few others are examined in future chapters.\n\nLooking at the density plot of a quantitative variable, one can guess what the distribution of that variable is. As an example, consider the NHANES data frame. One variable to consider is Weight. The density plot of Weight is\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Density plot of the Weight of a Person](Continuous-Probability-Distribution_files/figure-docx/fig-density-cap-1.png){#fig-density-cap fig-alt='Density plot of a person\\'s weight. Appears to be symmetric, and maybe bell shaped'}\n:::\n:::\n\n\n@fig-density-cap looks somewhat symmetric, and maybe bell shaped.\n\nConsider, the variable head circumference (HeadCirc) in the NHANES data frame. The density plot for this variable is @fig-HeadCirc-density\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Density plot of head circumference of a person](Continuous-Probability-Distribution_files/figure-docx/fig-HeadCirc-density-1.png){#fig-HeadCirc-density fig-alt='Density plot of head circumference of a person. Appears to be skewed left.'}\n:::\n:::\n\n\n@fig-HeadCirc-density looks somewhat skewed left.\n\nNow consider the variable BMI from the NHANES data frame. The density plot is\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Density Plot of BMI of a Person](Continuous-Probability-Distribution_files/figure-docx/fig-BMI-density-1.png){#fig-BMI-density fig-alt='Density plot of BMI of a person that is skewed right.'}\n:::\n:::\n\n\nThis density plot @fig-BMI-density appears to be skewed right\n\nNow consider the variable SmokeAge. Its density plot is @fig-Smoking-density\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Density Plot of Age when Person Started Smoking](Continuous-Probability-Distribution_files/figure-docx/fig-Smoking-density-1.png){#fig-Smoking-density fig-alt='Density plot of age when a person started smoking. Appears to be bimodal.'}\n:::\n:::\n\n\nThis distribution appears to be bimodal.\n\nlastly, consider the variable Pulse. The density plot is @fig-Pulse-density\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Density Plot of Pulse Rate of a person](Continuous-Probability-Distribution_files/figure-docx/fig-Pulse-density-1.png){#fig-Pulse-density fig-alt='Density plot of pulse rate of a person. Appears to be symmetric.'}\n:::\n:::\n\n\nThis density plot appears to be symmetric and could almost be considered bell shaped.\n\nThe reason that one considers the density plots to understand the distribution of the population, is that in some cases the distribution can be approximated with a known distribution that has certain properties. There are many known distribution. Some examples are the Uniform distribution, the Chi-Squared distribution, the Student's T distribution, and the normal distribution. The normal distribution is one of the more common distributions to use as a model, and it will be explored in this chapter. But do realize that there are many other distributions that one can use.\n\n## Normal Distribution\n\nMany populations have a distribution that is a symmetric, unimodal, and bell-shaped. For example: height, blood pressure, and cholesterol level. However, not every bell shaped curve is a normal curve. In a normal curve, there is a specific relationship between its \"height\" and its \"width.\" Normal curves can be tall and skinny or they can be short and fat. They are all symmetric, unimodal, and centered at $\\mu$, the population mean.\n\n@fig-normal-curvea and @fig-normal-curveb show two different normal curves drawn on the same scale. Both have $\\mu=2$ but the one in @fig-normal-curvea has a standard deviation of 1 and the one in @fig-normal-curveb has a standard deviation of 4. Notice that the larger standard deviation makes the graph wider (more spread out) and shorter.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Normal curve with mean 2 and standard deviation 1](Continuous-Probability-Distribution_files/figure-docx/fig-normal-curvea-1.png){#fig-normal-curvea fig-alt='Bell curve with mean 2 and standard deviation of 1'}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Normal curve with mean 2 and standard deviation 4](Continuous-Probability-Distribution_files/figure-docx/fig-normal-curveb-1.png){#fig-normal-curveb fig-alt='Bell curve with mean 2 and standard deviation of 4'}\n:::\n:::\n\n\nEvery normal curve has common features.\n\n-   The center, or the highest point, is at the population mean, $\\mu$.\n-   The transition points are the places where the curve changes from a \"hill\" to a \"valley\". The distance from the mean to the transition point is one standard deviation.\n-   The area under the whole curve is exactly 1. Therefore, the area under the half below or above the mean is 0.5.\n\nJust as in a discrete probability distribution, the object is to find the probability of an event occurring. However, unlike in a discrete probability distribution where the event can be a single value, in a continuous probability distribution the event must be a range. You are interested in finding the probability of $x$ occurring in the range between $a$ and $b$, or $P(a \\le x \\le b) = P(a<x<b)$. Calculus tells us this probability is the area under the curve in the interval from $a$ to $b$.\n\nBefore looking at the process for finding the probabilities under the normal curve, it is somewhat useful to look at the **Empirical Rule** that gives approximate values for these areas. The Empirical Rule is just an approximation and it will only be used in this section to give you an idea of what the size of the probabilities is for different shadings. A more precise method for finding probabilities for the normal curve will be demonstrated in the next section. Please do not use the empirical rule except for real rough estimates.\n\n**The Empirical Rule** for any normal distribution: Approximately 68% of the data is within one standard deviation of the mean. Approximately 95% of the data is within two standard deviations of the mean. Approximately 99.7% of the data is within three standard deviations of the mean.\n\n![Empirical Rule Graph](Empirical_rule.png){fig-alt=\"Empirical Rule graph with 68% of data between -1 and 1 standard deviation of mean, 95% between -2 and 2, and 99.7% between -3 and 3\"}\n\nBe careful, there is still some area left over in each end. Remember, the maximum a probability can be is 100%, so if you calculate you will see that for both ends together there is 0.3% of the curve. Because of symmetry, you can divide this equally between both ends and find that there is 0.15% in each tail beyond the 3rd standard deviations.\n\n## Finding Probabilities for the Normal Distribution\n\nThe Empirical Rule is just an approximation and only works for certain values. What if you want to find the probability for $x$ values that are not integer multiples of the standard deviation? The probability is the area under the curve. To find areas under the curve, you need calculus. Before technology, you needed to convert every $x$ value to a standardized number, called the $z$-score or $z$-value or simply just $z$. The $z$-score is a measure of how many standard deviations an $x$ value is from the mean. To convert from a normally distributed $x$ value to a $z$-score, you use the following formula.\n\n$z-score=\\frac{x-\\mu}{\\sigma}$\n\nwhere $\\mu$ = mean of the population of the $x$ value and $\\sigma$ = standard deviation for the population of the $x$ value\n\nThe $z$-score is normally distributed, with a mean of 0 and a standard deviation of 1. It is known as the standard normal curve. The $z$-score is a measure of how many standard deviations a data value is from its mean. If the $z$ - score is positive, the data value is above the mean. If the $z$-score is negative, the data value is below the mean. The farther the $z$-value is from 0, the farther the data value is from the mean.\n\nThese days technology can find probabilities without converting to the $z$-score and looking the probabilities up in a table. There are many programs available that will calculate the probability for a normal curve. The command on r to find the area to the left $P(x<value)$ is\n\npnorm(value, mean, standard_deviation, lower.tail=TRUE)\n\nThe command on r to find the area to the right, $P(x>value)$ is\n\npnorm(value, mean, standard_deviation, lower.tail=FALSE)\n\n### Example: General Normal Distribution\n\nThe length of a human pregnancy is normally distributed with a mean of 272 days with a standard deviation of 9 days (Bhat & Kushtagi, 2006).\n\na.  State the random variable\nb.  Find the probability of a pregnancy lasting more than 280 days.\nc.  Find the probability of a pregnancy lasting less than 250 days.\nd.  Find the probability that a pregnancy lasts between 265 and 280 days.\ne.  Find the length of pregnancy that 10% of all pregnancies last less than.\nf.  Suppose you meet a woman who says that she was pregnant for less than 250 days. Would this be unusual and what might you think?\n\n#### **Solution**\n\na.  State the random variable.\n\n$x$ = length of a human pregnancy\n\nb.  Find the probability of a pregnancy lasting more than 280 days.\n\nFirst translate the statement into a mathematical statement. $P(x>280)$\n\nNow, draw a picture @fig-normal-curve61.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Normally distributed with mean 272 and standard deviation 9, and P(x>280)](Continuous-Probability-Distribution_files/figure-docx/fig-normal-curve61-1.png){#fig-normal-curve61 fig-alt='Density plot of pregnancy length. Normally distributed with mean 272 and standard deviation 9. Shaded above 280'}\n:::\n:::\n\n\nThe probability of a pregnancy lasting longer than 280 days is $P(x>280)=0.187$. The command in rStudio is\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(280, 272, 9, lower.tail=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1870314\n```\n:::\n:::\n\n\nThus 18.7% of all pregnancies last more than 280 days. This is not unusual since the probability is greater than 5%.\n\nc.  Find the probability of a pregnancy lasting less than 250 days.\n\nFirst translate the statement into a mathematical statement. $P(x<250)$\n\nNow, draw a picture @fig-normal-curve62.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Density plot of pregnancy length. Normally distributed with mean 272 and standard deviation 9, and P(x<250)](Continuous-Probability-Distribution_files/figure-docx/fig-normal-curve62-1.png){#fig-normal-curve62 fig-alt='Density plot of pregnancy length. Normally distributed with mean 272 and standard deviation 9. Shaded below 250'}\n:::\n:::\n\n\nThe probability of a pregnancy lasting longer than 250 days is $P(x<250)=0.0073$. The command in r Studio is\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(250, 272, 9, lower.tail=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.007253771\n```\n:::\n:::\n\n\nThus 0.73% of all pregnancies last less than 250 days. This is unusual since the probability is less than 5%.\n\nd.  Find the probability that a pregnancy lasts between 265 and 280 days.\n\nFirst translate the statement into a mathematical statement. $P(265<x<280)$\n\nNow draw a picture @fig-normal-curve63.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Density plot of pregnancy length. Normally distributed with mean 272 and standard deviation 9, and P(265<x<280)](Continuous-Probability-Distribution_files/figure-docx/fig-normal-curve63-1.png){#fig-normal-curve63 fig-alt='Density plot of pregnancy length. Normally distributed with mean 272 and standard deviation 9. Shaded from 265 to 280'}\n:::\n:::\n\n\nThe probability of a pregnancy lasting between 265 days and 280 days is $P(265<x<280)=0.187$. To find the area between two values on the normal distribution, first, find the area to the left of the lower value, Graphically, this looks like @fig-normal-curve-preg\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Density plot of pregnancy length. Normally distributed with mean 272 and standard deviation 9, and P(x<265)](Continuous-Probability-Distribution_files/figure-docx/fig-normal-curve-preg-1.png){#fig-normal-curve-preg fig-alt='Density plot of pregnancy length. Normally distributed with mean 272 and standard deviation 9. Shaded below 265'}\n:::\n:::\n\n\nNow find the area less than 280. Graphically this looks like @fig-normal-curve-preg1\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Density plot of pregnancy length. Normally distributed with mean 272 and standard deviation 9, and P(x<280)](Continuous-Probability-Distribution_files/figure-docx/fig-normal-curve-preg1-1.png){#fig-normal-curve-preg1 fig-alt='Density plot of pregnancy length. Normally distributed with mean 272 and standard deviation 9. Shaded below 280'}\n:::\n:::\n\n\nLooking at the three figures, if you take the area in @fig-normal-curve-preg1 and subtract the area in @fig-normal-curve-preg you get the area in @fig-normal-curve63. In rStudio, the way to find the probability the probability of a pregnancy lasting between 265 days and 280 days, $P(265<x<280)=0.595$ use the following command\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(280, 272, 9, lower.tail=TRUE)-pnorm(265, 272, 9, lower.tail=TRUE) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5946186\n```\n:::\n:::\n\n\nThus 59.5% of all pregnancies last between 265 and 280 days.\n\ne.  Find the length of pregnancy that 10% of all pregnancies last less than.\n\nThis problem is asking you to find an $x$ value from a probability. You want to find the $x$ value that has 10% of the length of pregnancies to the left of it. In this case, you are given the probability. In r, the command is\n\nqnorm(area, mean, standard_deviation, lower.tail=TRUE or FALSE)\n\nFor this example since you know the area in the lower tail, then use lower.tail=TRUE. So the command is\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(0.1, 272, 9, lower.tail = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 260.466\n```\n:::\n:::\n\n\nThus 10% of all pregnancies last less than approximately 260 days.\n\nf.  Suppose you meet a woman who says that she was pregnant for less than 250 days. Would this be unusual and what might you think?\n\nFrom part (c) you found the probability that a pregnancy lasts less than 250 days is 0.73%. Since this is less than 5%, it is very unusual. You would think that either the woman had a premature baby, or that she may be wrong about when she actually became pregnant.\n\n### Example: General Normal Distribution\n\nThe mean mathematics SAT score in 2012 was 514 with a standard deviation of 117 (\"Total group profile,\" 2012). Assume the mathematics SAT score is normally distributed.\n\na.  State the random variable.\nb.  Find the probability that a person has a mathematics SAT score over 700.\nc.  Find the probability that a person has a mathematics SAT score of less than 400.\nd.  Find the probability that a person has a mathematics SAT score between a 500 and a 650.\ne.  Find the mathematics SAT score that represents the top 1% of all scores.\n\n#### **Solution**\n\na.  State the random variable.\n\n$x$ = mathematics SAT score\n\nb.  Find the probability that a person has a mathematics SAT score over 700.\n\nFirst translate the statement into a mathematical statement. $P(x>700)$\n\nNow, draw a picture @fig-normal-curve-SAT\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Density plot of SAT mathematics score. Normally distributed with mean 514 and standard deviation 117 and P(x>700)](Continuous-Probability-Distribution_files/figure-docx/fig-normal-curve-SAT-1.png){#fig-normal-curve-SAT fig-alt='Density plot of SAT mathematics score. Normally distributed with mean 514 and standard deviation 117. Shaded above 700'}\n:::\n:::\n\n\nTo find $P(x>700)=0.0559$, the command in r would be\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(700, 514,117, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05594631\n```\n:::\n:::\n\n\nThere is a 5.6% chance that a person scored above a 700 on the mathematics SAT test. This is not unusual.\n\nc.  Find the probability that a person has a mathematics SAT score of less than 400.\n\nFirst translate the statement into a mathematical statement. $P(x<400)$\n\nNow, draw a picture @fig-normal-curve-SAT1\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Density plot of SAT mathematics score. Normally distributed with mean 514 and standard deviation 117 and P(x<400)](Continuous-Probability-Distribution_files/figure-docx/fig-normal-curve-SAT1-1.png){#fig-normal-curve-SAT1 fig-alt='Density plot of SAT mathematics score. Normally distributed with mean 514 and standard deviation 117. Shaded below 400'}\n:::\n:::\n\n\nTo find $P(x<400)=0.165$, the command in r would be\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(400, 514, 117, lower.tail = TRUE) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1649392\n```\n:::\n:::\n\n\nSo, there is a 16.5% chance that a person scores less than a 400 on the mathematics part of the SAT.\n\nd.  Find the probability that a person has a mathematics SAT score between a 500 and a 650.\n\nFirst translate the statement into a mathematical statement $P(500<x<650)$\n\nNow, draw a picture @fig-normal-curve-SAT2\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Density plot of SAT mathematics score. Normally distributed with mean 514 and standard deviation 117 and P(514<x<650)](Continuous-Probability-Distribution_files/figure-docx/fig-normal-curve-SAT2-1.png){#fig-normal-curve-SAT2 fig-alt='Density plot of SAT mathematics score. Normally distributed with mean 514 and standard deviation 117. Shaded from 514 to 650'}\n:::\n:::\n\n\nTo find $P(500<x<650)=0.425$, the command in r would be\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(650, 514, 117, lower.tail = TRUE)-pnorm(500, 514, 117, lower.tail=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4250851\n```\n:::\n:::\n\n\nSo, there is a 42.5% chance that a person has a mathematical SAT score between 500 and 650.\n\ne.  Find the mathematics SAT score that represents the top 1% of all scores.\n\nThis problem is asking you to find an $x$ value from a probability. You want to find the $x$ value that has 1% of the mathematics SAT scores to the right of it. In this case you are using the upper tail of the curve. To find this $x$ value on rStudio, use the command\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(0.01, 514, 117, lower.tail=FALSE) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 786.1827\n```\n:::\n:::\n\n\nSo, 1% of all people who took the SAT scored over about 786 points on the mathematics SAT.\n\n### Homework for Normal Distribution Section\n\n1.  Find each of the probabilities, where $z$ is a $z$-score from the standard normal distribution with mean of $\\mu=0$ and standard deviation $\\sigma=1$. It helps to draw a picture for each problem.\n\n<!-- -->\n\na.  $P(z<2.36)$\nb.  $P(z>0.67)$\nc.  $P(0<x<2.11)$\nd.  $P(-2.78<z<1.97)$\n\n<!-- -->\n\n2.  Find the *z*-score corresponding to the given area. Remember, *z* is distributed as the standard normal distribution with mean of $\\mu=0$ and standard deviation $\\sigma=1$.\n\n<!-- -->\n\na.  The area to the left of $z$ is 15%.\n\nb.  The area to the right of $z$ is 65%.\n\nc.  The area to the left of $z$ is 10%.\n\nd.  The area to the right of $z$ is 5%.\n\ne.  The area between $-z$ and $z$ is 95%. (Hint draw a picture and figure out the area to the left of $-z$.)\n\nf.  The area between $-z$ and $z$ is 99%.\n\n<!-- -->\n\n3.  If a random variable that is normally distributed has a mean of 25 and a standard deviation of 3, convert the given value to a $z$-score.\n\n<!-- -->\n\na.  $x$ = 23\nb.  $x$ = 33\nc.  $x$ = 19\nd.  $x$ = 45\n\n<!-- -->\n\n4.  According to the WHO MONICA Project the mean blood pressure for people in China is 128 mmHg with a standard deviation of 23 mmHg (Kuulasmaa, Hense & Tolonen, 1998). Assume that blood pressure is normally distributed.\n\n<!-- -->\n\na.  State the random variable.\nb.  Find the probability that a person in China has blood pressure of 135 mmHg or more.\nc.  Find the probability that a person in China has blood pressure of 141 mmHg or less.\nd.  Find the probability that a person in China has blood pressure between 120 and 125 mmHg.\ne.  Is it unusual for a person in China to have a blood pressure of 135 mmHg? Why or why not?\nf.  What blood pressure do 90% of all people in China have less than?\n\n<!-- -->\n\n5.  The size of fish is very important to commercial fishing. A study conducted in 2012 found the length of Atlantic cod caught in nets in Karlskrona to have a mean of 49.9 cm and a standard deviation of 3.74 cm (Ovegard, Berndt & Lunneryd, 2012). Assume the length of fish is normally distributed.\n\n<!-- -->\n\na.  State the random variable.\nb.  Find the probability that an Atlantic cod has a length less than 52 cm.\nc.  Find the probability that an Atlantic cod has a length of more than 74 cm.\nd.  Find the probability that an Atlantic cod has a length between 40.5 and 57.5 cm.\ne.  If you found an Atlantic cod to have a length of more than 74 cm, what could you conclude?\nf.  What length are 15% of all Atlantic cod longer than?\n\n<!-- -->\n\n6.  The mean cholesterol levels of women age 45-59 in Ghana, Nigeria, and Seychelles is 5.1 mmol/l and the standard deviation is 1.0 mmol/l (Lawes, Hoorn, Law & Rodgers, 2004). Assume that cholesterol levels are normally distributed.\n\n<!-- -->\n\na.  State the random variable.\nb.  Find the probability that a woman age 45-59 in Ghana, Nigeria, or Seychelles has a cholesterol level above 6.2 mmol/l (considered a high level).\nc.  Find the probability that a woman age 45-59 in Ghana, Nigeria, or Seychelles has a cholesterol level below 5.2 mmol/l (considered a normal level).\nd.  Find the probability that a woman age 45-59 in Ghana, Nigeria, or Seychelles has a cholesterol level between 5.2 and 6.2 mmol/l (considered borderline high).\ne.  If you found a woman age 45-59 in Ghana, Nigeria, or Seychelles having a cholesterol level above 6.2 mmol/l, what could you conclude?\nf.  What value do 5% of all woman ages 45-59 in Ghana, Nigeria, or Seychelles have a cholesterol level less than?\n\n<!-- -->\n\n7.  In the United States, males between the ages of 40 and 49 eat on average 103.1 g of fat every day with a standard deviation of 4.32 g (\"What we eat,\" 2012). Assume that the amount of fat a person eats is normally distributed.\n\n<!-- -->\n\na.  State the random variable.\nb.  Find the probability that a man age 40-49 in the U.S. eats more than 110 g of fat every day.\nc.  Find the probability that a man age 40-49 in the U.S. eats less than 93 g of fat every day.\nd.  Find the probability that a man age 40-49 in the U.S. eats less than 65 g of fat every day.\ne.  If you found a man age 40-49 in the U.S. who says he eats less than 65 g of fat every day, would you believe him? Why or why not?\nf.  What daily fat level do 5% of all men age 40-49 in the U.S. eat more than?\n\n<!-- -->\n\n8.  A dishwasher has a mean life of 12 years with an estimated standard deviation of 1.25 years (\"Appliance life expectancy,\" 2013). Assume the life of a dishwasher is normally distributed.\n\n<!-- -->\n\na.  State the random variable.\nb.  Find the probability that a dishwasher will last more than 15 years.\nc.  Find the probability that a dishwasher will last less than 6 years.\nd.  Find the probability that a dishwasher will last between 8 and 10 years.\ne.  If you found a dishwasher that lasted less than 6 years, would you think that you have a problem with the manufacturing process? Why or why not?\nf.  A manufacturer of dishwashers only wants to replace free of charge 5% of all dishwashers. How long should the manufacturer make the warranty period?\n\n<!-- -->\n\n9.  The mean starting salary for nurses is \\\\\\$67,694 nationally (\"Staff nurse -,\" 2013). The standard deviation is approximately \\$10,333. Assume that the starting salary is normally distributed.\n\n<!-- -->\n\na.  State the random variable.\nb.  Find the probability that a starting nurse will make more than \\\\\\$80,000.\nc.  Find the probability that a starting nurse will make less than \\\\\\$60,000.\nd.  Find the probability that a starting nurse will make between \\\\\\$55,000 and \\\\\\$72,000.\ne.  If a nurse made less than \\\\\\$50,000, would you think the nurse was under paid? Why or why not?\nf.  What salary do 30% of all nurses make more than?\n\n<!-- -->\n\n10. The mean yearly rainfall in Sydney, Australia, is about 137 mm and the standard deviation is about 69 mm (\"Annual maximums of,\"2013). Assume rainfall is normally distributed.\n\n<!-- -->\n\na.  State the random variable.\nb.  Find the probability that the yearly rainfall is less than 100 mm.\nc.  Find the probability that the yearly rainfall is more than 240 mm.\nd.  Find the probability that the yearly rainfall is between 140 and 250 mm.\ne.  If a year has a rainfall less than 100mm, does that mean it is an unusually dry year? Why or why not?\nf.  What rainfall amount are 90% of all yearly rainfalls more than?\n\n## Assessing Normality\n\nThe distributions you have seen up to this point have been assumed to be normally distributed, but how do you determine if it is normally distributed. One way is to take a sample and look at the sample to determine if it appears normal. If the sample looks normal, then most likely the population is also. Here are some guidelines that are use to help make that determination.\n\n1.  **Density Plot**: Make a density plot. For a normal distribution, the density plot should be roughly bell-shaped. For small samples, this is not very accurate, and another method is needed. A distribution may not look normally distributed from the density plot, but it still may be normally distributed.\n\n2.  **Normal quantile plot (or normal probability plot)**: This plot is provided through statistical software on a computer. If the points lie close to a line, the data comes from a distribution that is approximately normally distributed. If the points do not lie close to a line or they show a pattern that is not a line, the data are likely to come from a distribution that is not normally distributed.\n\n### **To create a density plot on rStudio:**\n\nRead the Data Frame into r Studio. The command for density is\n\ngf_density(\\~variable, data=Data_Frame)\n\nSee chapter 2 for more examples of this.\n\n### **To create a normal quantile plot on rStudio**\n\nRead the Data Frame into rStudio. The command for normal quantile plot is\n\ngf_qqnorm(\\~variable, data=Data_Frame)\n\nRealize that your random variable may be normally distributed, even if the sample fails the two tests. However, if the density plot definitely doesn't look symmetric and bell shaped, and the normal probability plot doesn't look linear, then you can be fairly confident that the data set does not come from a population that is normally distributed.\n\n### Example: Is It Normal?\n\nIn Kiama, NSW, Australia, there is a blowhole. The data in @tbl-Eruption are times in seconds between eruptions (\"Kiama blowhole eruptions,\" 2013). Do the data come from a population that is normally distributed?\n\n\n::: {#tbl-Eruption .cell tbl-alt='Time (in Seconds) Between Kiama Blowhole Eruptions' tbl-cap='Time (in Seconds) Between Kiama Blowhole Eruptions'}\n\n```{.r .cell-code}\nEruption<-read.csv( \"https://krkozak.github.io/MAT160/Blowhole_eruptions.csv\") \nknitr::kable(head(Eruption))\n```\n\n::: {.cell-output-display}\n| Interval|\n|--------:|\n|       83|\n|       51|\n|       87|\n|       60|\n|       28|\n|       95|\n:::\n:::\n\n\n**Code book for Data Frame Eruption**\n\n**Description** The ocean swell produces spectacular eruptions of water through a hole in the cliff at Kiama, about 120km south of Sydney, known as the Blowhole. The times at which 65 successive eruptions occurred from 1340 hours on 12 July 1998 were observed using a digital watch.\n\nFormat This data frame contains the following columns:\n\nInterval: Waiting time between eruptions (seconds)\n\nSource Kiama Blowhole Eruptions. (n.d.). Retrieved from http://www.statsci.org/data/oz/kiama.html\n\nReferences The data was collected and contributed by Jim Irish, Faculty of Engineering, University of Technology, Sydney.\n\na.  State the random variable\nb.  Draw a Density plot\nc.  Draw the normal quantile plot.\nd.  Do the data come from a population that is normally distributed?\n\n#### **Solution**\n\na.  State the random variable\n\n$x$ = time in seconds between eruptions of Kiama Blowhole\n\nb.  Draw a Density plot\n\nThe density plot produced is in @fig-blowhole-density\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_density(~Interval, data=Eruption, title=\"Eruption times for Kiama Blowhole\", xlab=\"Time (seconds)\") \n```\n\n::: {.cell-output-display}\n![Density Plot of Eruption Times for Kiama Blowhole](Continuous-Probability-Distribution_files/figure-docx/fig-blowhole-density-1.png){#fig-blowhole-density fig-alt='Density plot of eruption times for Kiama blowhole. Appears skewed right.'}\n:::\n:::\n\n\nThis looks skewed right and not symmetric.\n\nc.  Draw the normal quantile plot.\n\nThe normal quantile plot is in @fig-blowhole-qq\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_qq(~Interval, data=Eruption, title=\"Eruption times for Kiama Blowhole\")\n```\n\n::: {.cell-output-display}\n![Normal Quantile Plot of Eruption Times for Kiama blowhole.](Continuous-Probability-Distribution_files/figure-docx/fig-blowhole-qq-1.png){#fig-blowhole-qq fig-alt='Normal quantile plot of eruption times for Kiama blowhole. Appears exponential.'}\n:::\n:::\n\n\n@fig-blowhole-qq looks more like an exponential growth than linear.\n\nd.  Do the data come from a population that is normally distributed?\n\nConsidering the density plot is skewed right, and the normal probability plot does not look linear, then the conclusion is that this sample is not from a population that is normally distributed.\n\n### Example: Is It Normal?\n\nThe US National Center for Health Statistics (NCHS) conducted a series of health and nutrition surveys called NHANES. One of the many variables in NHANES is pulse. Determine if pulse is a normally distributed variable. The NHANES data frame is @tbl-NHANES.\n\na.  State the random variable\nb.  Draw a density plot\nc.  Draw the normal quantile plot.\nd.  Do the data come from a population that is normally distributed?\n\n#### **Solution**\n\na.  State the random variable\n\n$x$ = pulse\n\nb.  Draw a density plot\n\nThe density plot is in @fig-pulse-density\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_density(~Pulse, data=NHANES, title=\"Pulse Rate\", xlab=\"Pulse Rate (bpm)\")\n```\n\n::: {.cell-output-display}\n![Density plot of Pulse Rate (bpm)](Continuous-Probability-Distribution_files/figure-docx/fig-pulse-density-1.png){#fig-pulse-density fig-alt='Density plot of pulse rate. Appears to be bell shapped.'}\n:::\n:::\n\n\nThis looks somewhat symmetric and bell shaped.\n\nc.  Draw the normal quantile plot.\n\nThe normal quantile plot is in @fig-pulse-qq\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_qq(~Pulse, data=NHANES, title=\"Pulse Rate\") \n```\n\n::: {.cell-output-display}\n![Normal Quantile Plot of Pulse Rate (bmp)](Continuous-Probability-Distribution_files/figure-docx/fig-pulse-qq-1.png){#fig-pulse-qq fig-alt='Normal quantile plot of pulse rate. Appears to be linear.'}\n:::\n:::\n\n\n@fig-pulse-qq looks fairly linear.\n\nd.  Do the data come from a population that is normally distributed?\n\nConsidering the density plot is bell shaped and the normal probability plot looks linear. The conclusion is that this sample is from a population that is normally distributed.\n\n### Homework for Assessing Normality Section\n\n1.  Cholesterol data was collected on patients four days after having a heart attack. The data is in @tbl-Cholesterol. Assess if the data is from a population that is normally distributed.\n\n**Code Book for Cholesterol** See is below @tbl-Cholesterol.\n\n2.  The size of fish is very important to commercial fishing. A study conducted in 2012 collected the lengths of Atlantic cod caught in nets in Karlskrona (Ovegard, Berndt & Lunneryd, 2012). Data based on information from the study is in @tbl-Cod. Determine if the data is from a population that is normally distributed.\n\n\n::: {#tbl-Cod .cell tbl-alt='Atlantic Cod Lengths' tbl-cap='Atlantic Cod Lengths'}\n\n```{.r .cell-code}\nCod<-read.csv( \"https://krkozak.github.io/MAT160/cod.csv\") \nknitr::kable(head(Cod))\n```\n\n::: {.cell-output-display}\n| length|\n|------:|\n|     48|\n|     50|\n|     50|\n|     55|\n|     53|\n|     50|\n:::\n:::\n\n\n3.  The WHO MONICA Project collected blood pressure data for people in China (Kuulasmaa, Hense & Tolonen, 1998). Data based on information from the study is in @tbl-BP. Determine if the data is from a population that is normally distributed.\n\n\n::: {#tbl-BP .cell tbl-alt='Blood Pressure Values for People in China' tbl-cap='Blood Pressure Values for People in China'}\n\n```{.r .cell-code}\nBP<-read.csv( \"https://krkozak.github.io/MAT160/bp.csv\") \nknitr::kable(head(BP))\n```\n\n::: {.cell-output-display}\n| pressure|\n|--------:|\n|      114|\n|      141|\n|      154|\n|      137|\n|      131|\n|      132|\n:::\n:::\n\n\n4.  Annual rainfalls for Sydney, Australia are given in @tbl-Annual (\"Annual maximums of,\" 2013). Can you assume rainfall is normally distributed?\n\n\n::: {#tbl-Annual .cell tbl-alt='Annual Rainfall in Sydney, Australia' tbl-cap='Annual Rainfall in Sydney, Australia'}\n\n```{.r .cell-code}\nAnnual<-read.csv( \"https://krkozak.github.io/MAT160/annual.csv\") \nknitr::kable(head(Annual))\n```\n\n::: {.cell-output-display}\n| amount|\n|------:|\n|  146.8|\n|  383.0|\n|   90.9|\n|  178.1|\n|  267.5|\n|   95.5|\n:::\n:::\n\n\n## Sampling Distribution and the Central Limit Theorem\n\nYou now have most of the skills to start statistical inference, but you need one more concept.\n\nFirst, it would be helpful to state what statistical inference is in more accurate terms.\n\n**Statistical Inference**: to make accurate decisions about parameters from statistics\n\nWhen it says \"accurate decision,\" you want to be able to measure how accurate. You measure how accurate using probability. In both binomial and normal distributions, you needed to know that the random variable followed either distribution. You need to know how the statistic is distributed and then you can find probabilities. In other words, you need to know the shape of the sample mean or whatever statistic you want to make a decision about.\n\nHow is the statistic distributed? This is answered with a sampling distribution.\n\n**Sampling Distribution**: how a sample statistic is distributed when repeated trials of size $n$ are taken.\n\n### Example: Sampling Distribution\n\nThe NHANES data frame has the pulse rates for approximately 50,000 individuals. The random variable is $x$ = pulse rate. The probability distribution of this random variable is presented in @fig-NHANES6h-density. Although pulse rates from 50,000 individuals isn't the entire population, the sample is most likely a good representation of the population. Thus, it is safe to assume the population is normally distributed. An estimate for the population mean is 73.6 pbm, and the population standard deviation estimate is 12.2 bpm.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_density(~Pulse, data=NHANES, title = \"Pulse Rate\", xlab=\"Pulse (bpm)\") \ndf_stats(~Pulse, data=NHANES, mean, sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  response     mean       sd\n1    Pulse 73.55973 12.15542\n```\n:::\n\n::: {.cell-output-display}\n![Distribution of Pulse Rate](Continuous-Probability-Distribution_files/figure-docx/fig-NHANES6h-density-1.png){#fig-NHANES6h-density fig-alt='Density plot of pulse rate. Appears to be normally distributed.'}\n:::\n:::\n\n\nSuppose you take a random sample of 10 pulse rates from those 50,000 individuals. A random sample of data from 10 individuals is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES|> \n  sample_n(size=10) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 76\n      ID SurveyYr Gender   Age AgeDecade AgeMonths Race1 Race3 Education Marit…¹\n   <int> <fct>    <fct>  <int> <fct>         <int> <fct> <fct> <fct>     <fct>  \n 1 65822 2011_12  male      63 \" 60-69\"         NA White White 9 - 11th… Widowed\n 2 57814 2009_10  female    56 \" 50-59\"        683 White <NA>  College … NeverM…\n 3 58130 2009_10  male      40 \" 40-49\"        491 White <NA>  Some Col… Married\n 4 55227 2009_10  male      14 \" 10-19\"        171 White <NA>  <NA>      <NA>   \n 5 64746 2011_12  male      29 \" 20-29\"         NA Black Black College … NeverM…\n 6 63296 2011_12  female    55 \" 50-59\"         NA Other Asian College … Married\n 7 53345 2009_10  female    23 \" 20-29\"        282 White <NA>  High Sch… NeverM…\n 8 68108 2011_12  male       2 \" 0-9\"           NA Black Black <NA>      <NA>   \n 9 66147 2011_12  female    57 \" 50-59\"         NA Other Asian College … Widowed\n10 58270 2009_10  female    30 \" 30-39\"        366 White <NA>  High Sch… NeverM…\n# … with 66 more variables: HHIncome <fct>, HHIncomeMid <int>, Poverty <dbl>,\n#   HomeRooms <int>, HomeOwn <fct>, Work <fct>, Weight <dbl>, Length <dbl>,\n#   HeadCirc <dbl>, Height <dbl>, BMI <dbl>, BMICatUnder20yrs <fct>,\n#   BMI_WHO <fct>, Pulse <int>, BPSysAve <int>, BPDiaAve <int>, BPSys1 <int>,\n#   BPDia1 <int>, BPSys2 <int>, BPDia2 <int>, BPSys3 <int>, BPDia3 <int>,\n#   Testosterone <dbl>, DirectChol <dbl>, TotChol <dbl>, UrineVol1 <int>,\n#   UrineFlow1 <dbl>, UrineVol2 <int>, UrineFlow2 <dbl>, Diabetes <fct>, …\n```\n:::\n:::\n\n\nIt might be useful to find the mean pulse rate from a random sample of size 10.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n  response     mean\n1    Pulse 75.42857\n```\n:::\n:::\n\n\nNow suppose you took another random sample of size 10 and found the mean pulse rate for that sample. Repeat this process 100 times. At this point you would basically have a new sample of 100 mean pulse rates. You could assess how this sample is distributed by creating a density plot @fig-NHANES6e-density\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTrials <- do(100) * { NHANES |> \n    sample_n(size = 10) |>\n    df_stats( ~Pulse, means = mean)}\ngf_density( ~means, data = Trials, title = \"Density plot of sample mean when n=10\")\n\ndf_stats(~means, data=Trials, mean, sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  response     mean       sd\n1    means 73.31903 4.077039\n```\n:::\n\n::: {.cell-output-display}\n![Density Plot of Sample Means When n = 10](Continuous-Probability-Distribution_files/figure-docx/fig-NHANES6e-density-1.png){#fig-NHANES6e-density fig-alt='Density plot of sample means when sample size is 10. Appears to be bell shaped.'}\n:::\n:::\n\n\nThis distribution is a sampling distribution. That is all a sampling distribution is. It is a distribution created from statistics.\n\nNotice the distribution does look a great deal like the distribution of the original random variable. Notice the mean of the sample means $\\mu_{\\bar{x}} = 73.8$ bpm which is almost the same of as the mean of the population. The standard deviation of the sample means, $\\sigma_{\\bar{x}}=4.35$ pbm is about $\\frac{1}{3}$ of the population standard deviation.\n\nWhat does this distribution look like if instead of repeating the experiment 10 times you repeat it 50 times instead?\n\nThis density plot of the sampling distribution is displayed in @fig-NHANES6f-density\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTrials <- do(100) * { NHANES |>\n    sample_n(size = 50) |>\n    df_stats( ~Pulse, means = mean) }\ngf_density( ~means, data = Trials, title=\"Sample means when n=50\")|>\n  gf_lims(x=c(68,79))\ndf_stats(~means, data=Trials, mean, sd) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  response     mean       sd\n1    means 73.93181 1.844015\n```\n:::\n\n::: {.cell-output-display}\n![Density Plot of Sample Means When n = 50](Continuous-Probability-Distribution_files/figure-docx/fig-NHANES6f-density-1.png){#fig-NHANES6f-density fig-alt='Density plot of sample means when sample size is 50. Appears to be bell shaped.'}\n:::\n:::\n\n\nNotice this density plot of the sample mean looks approximately symmetrical and could almost be called normal. Notice, the mean of the sample means is 73.6 bpm which is approximately what the population mean is. The standard deviation of the sample means is 1.77 bpm which is around $\\frac{1}{7}$ of the population standard deviation. What if you keep increasing $n$? What will the sampling distribution of the sample mean look like? In other words, what does the sampling distribution of $\\bar{x}$ look like as $n$ gets even larger?\n\nThis depends on how the original distribution is distributed. In [Example: Sampling Distribution], the random variable was approximately normally distributed. When $n$ was 10, the distribution of the mean looked approximately normal. What if the original distribution wasn't normal? How big would $n$ have to be? Consider a different variable in the NHANES data frame that isn't normally distributed such as age when a participant started to smoke cigarettes (SmokeAge). The density plot for the large sample is in @fig-NHANES6g-density. The mean for the large sample is 17.8 years and the standard deviation is 5.3 years, so $\\mu=17.8$ dollars and $\\sigma=5.3$ dollars approximately.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_density(~SmokeAge, data=NHANES, title = \"Density Plot of Age when Person Started Smoking\", xlab=\"Age\") \ndf_stats(~SmokeAge, data=NHANES, mean, sd) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  response     mean      sd\n1 SmokeAge 17.82662 5.32666\n```\n:::\n\n::: {.cell-output-display}\n![Density Plot of Age When Person Started Smoking.](Continuous-Probability-Distribution_files/figure-docx/fig-NHANES6g-density-1.png){#fig-NHANES6g-density fig-alt='Density plot of age when person started smoking. Appears to not be bell shaped.'}\n:::\n:::\n\n\nNow take 100 samples of size 50 individuals from the NHANES Data Frame. Then graph a density plot of SmokeAge, the age when someone started to smoke. Notice the the sampling distribution of the sample means looks fairly normally distributed even though the original random variable was not normally distributed. The mean of the sample mean. $\\mu_{ \\bar{x}}=$ 17.8 years and the standard deviation of the sample mean, $\\sigma_{\\bar{x}}=$ 1.56 years. The mean of the sample mean is the same as the mean of the population, but the standard deviation of the sample mean is much less than the standard deviation of the original data.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n  response     mean       sd\n1    means 18.00709 1.468003\n```\n:::\n\n::: {.cell-output-display}\n![Density Plot of Age When Person Started Smoking when sample size is 50.](Continuous-Probability-Distribution_files/figure-docx/fig-NHANES6-random-density-1.png){#fig-NHANES6-random-density fig-alt='Density plot of mean age a person starts to smoke of a sample of size 50. Appears to be bell shaped.'}\n:::\n:::\n\n\nOne question is, why is the mean of the sample means the same as the mean of the population? Suppose you have a random variable that has a population mean, $\\mu$, and a population standard deviation, $\\sigma$. If a sample of size $n$ is taken, then the sample mean, has a mean $\\mu_{ \\bar{x}}=\\mu$ and standard deviation of $\\sigma_{ \\bar{x}}=\\frac{\\sigma}{\\sqrt{n}}$ . The standard deviation of the sample mean is lower because by taking the mean you are averaging out the extreme values, which makes the distribution of the sample mean less spread out.\n\nYou now know the center and the variability of $\\bar{x}$. You also want to know the shape of the distribution of $\\bar{x}$. You hope it is normal, since you know how to find probabilities using the normal curve. The following theorem tells you the requirement to have $\\bar{x}$ be normally distributed.\n\n### **Central Limit Theorem**\n\nSuppose a random variable is from any distribution. If a sample of size $n$ is taken, the the sample mean, $\\bar{x}$, becomes normally distributed as $n$ increases.\n\nWhat this says is that no matter what $x$ looks like, $\\bar{x}$ would look normal if $n$ is large enough. Now, what size of $n$ is large enough? That depends on how $x$ is distributed in the first place. If the original random variable is normally distributed, then $n$ just needs to be 2 or more data points. If the original random variable is somewhat mound shaped and symmetrical, then $n$ needs to be greater than or equal to 30. Sometimes the sample size can be smaller, but this is a good general rule to use. The sample size may have to be much larger if the original random variable is really skewed one way or another.\n\nNow that you know when the sample mean will look like a normal distribution, then you can find the probability related to the sample mean. Remember that the mean of the sample mean is just the mean of the original data ($\\mu_{\\bar{x}}=\\mu$), but the standard deviation of the sample mean, $\\sigma_{\\bar{x}}$, also known as the standard error of the mean, is actually $\\sigma_{\\bar{x}}=\\frac{\\sigma}{\\sqrt{n}}$. Make sure you use this in all calculations. If you are using the $z$-score, the formula when working with $\\bar{x}$ is $z=\\frac{x-\\mu_{\\bar{x}}}{\\sigma_{\\bar{x}}}=\\frac{x-\\mu}{\\frac{\\sigma}{\\sqrt{n}}}$. To use rStudio to calculate probabilities use $P(\\bar{x}<a)= pnorm(a, \\mu_{\\bar{x}}, \\sigma_{\\bar{x}}, lower.tail=TRUE)$ $P(\\bar{x}>a)= pnorm(a, \\mu_{\\bar{x}}, \\sigma_{\\bar{x}}, lower.tail=FALSE)$.\n\n### Example: Finding Probabilities for Sample Means\n\nThe birth weight of boy babies of European descent who were delivered at 40 weeks is normally distributed with a mean of 3687.6 g with a standard deviation of 410.5 g (Janssen, Thiessen, Klein, Whitfield, MacNab & Cullis-Kuhl, 2007). Suppose there were nine European descent boy babies born on a given day and the mean birth weight is calculated.\n\na.  State the random variable.\nb.  What is the mean of the sample mean?\nc.  What is the standard deviation of the sample mean?\nd.  What distribution is the sample mean distributed as?\ne.  Find the probability that the mean weight of the nine boy babies born was less than 3500.4 g.\nf.  Find the probability that the mean weight of the nine babies born was less than 3452.5 g.\n\n#### **Solution**\n\na.  State the random variable.\n\n$x$ = birth weight of boy babies (Note: the random variable is something you measure, and it is not the mean birth weight. Mean weight is calculated.)\n\nb.  What is the mean of the sample mean?\n\n$\\mu_{\\bar{x}}=\\mu=3687.4g$\n\nc.  What is the standard deviation of the sample mean?\n\n$\\sigma_{\\bar{x}}=\\frac{\\sigma}{\\sqrt{n}}=\\frac{410.5g}{\\sqrt{9}}=136.8g$\n\nd.  What distribution is the sample mean distributed as?\n\nSince the original random variable is distributed normally, then the sample mean is distributed normally.\n\ne.  Find the probability that the mean weight of the nine boy babies born was less than 3500.4 g.\n\nTo find $P(\\bar{x}<3500.4)=0.086$. use the rStudio command\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(3500.4,3687.6, 410.5/sqrt(9), lower.tail = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.08564231\n```\n:::\n:::\n\n\nThere is an 8.6% chance that the mean birth weight of the nine boy babies born would be less than 3500.4 g. Since this is more than 5%, this is not unusual.\n\nf.  Find the probability that the mean weight of the nine babies born was less than 3452.5 g.\n\nYou are looking for the $P(\\bar{x}<3452.5)$.\n\nTo find in rStudio, $P(\\bar{x}<3452.5)=0.043$ use the command\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(3452.5, 3687.4, 410.5/sqrt(9), lower.tail = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04301819\n```\n:::\n:::\n\n\nThere is a 4.3% chance that the mean birth weight of the nine boy babies born would be less than 3452.5 g. Since this is less than 5% this would be an unusual event. If it actually happened, then you may think there is something unusual about this sample. Maybe some of the nine babies were born as multiples, which brings the mean weight down, or some or all of the babies were not of European descent (in fact the mean weight of South Asian boy babies is 3452.5 g), or some were born before 40 weeks, or the babies were born at high altitudes.\n\n### Example: Finding Probabilities for Sample Means\n\nFor Americans that smoke, the average age that they started smoking is 17.8 years, with a standard deviation of approximately 1.56 years from the NHANES data. This random variable is not normally distributed, though it is somewhat mound shaped.\n\na.  State the random variable.\nb.  Suppose a sample of 35 smoking American's is taken. Find the probability that the mean age that these 35 smoking Americans started to smoke is more than 21 years.\n\n#### **Solution**\n\na.  State the random variable.\n\n$x$ = age that smoking Americans started to smoke\n\nb.  Suppose a sample of 35 smoking American's is taken. Find the probability that the mean age that these 35 smoking Americans started to smoke is more than 21 years.\n\nEven though the original random variable is not normally distributed, the sample size is over 30, by the central limit theorem the sample mean will be normally distributed. The mean of the sample mean is $\\mu_{\\bar{x}}=17.8$. The standard deviation of the sample mean is $\\sigma_{\\bar{x}}=\\frac{\\sigma}{\\sqrt{n}}=\\frac{1.56}{\\sqrt{35}}$. You have all the information you need to use the normal command using rStudio. Without the central limit theorem, you couldn't use the normal command, and you would not be able to answer this question.\n\nThe probability that the mean age that 35 smoking Americans start to smoke is more than 21 years, is the mathematical statement $P(\\bar{x}>21)$\n\nTo find $P(\\bar{x}>21)= 3.42X10^{-34}$ using r studio, use the command:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(21, 17.8, 1.56/sqrt(35), lower.tail=FALSE) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3.422499e-34\n```\n:::\n:::\n\n\nThe probability of a sample mean of 35 smoking Americans being more than 21 years when they smoked for the first time is very small. This is extremely unlikely to happen. If it does, it may make you wonder about the sample. Could the population mean have increased from the 17.8 years as was stated? Could the sample not have been random, and instead have been a group of smoking Americans who had started to smoke much later? These questions, and more, are ones that you would want to ask as a researcher\n\n### Homework for Sampling Distribution and the Central Limit Theorem Section\n\n1.  A random variable is not normally distributed, but it is mound shaped. It has a mean of 14 and a standard deviation of 3.\n\n<!-- -->\n\na.  If you take a sample of size 10, can you say what the shape of the sampling distribution for the sample mean is? Why?\nb.  For a sample of size 10, state the mean of the sample mean and the standard deviation of the sample mean.\nc.  If you take a sample of size 35, can you say what the shape of the distribution of the sample mean is? Why?\nd.  For a sample of size 35, state the mean of the sample mean and the standard deviation of the sample mean.\n\n<!-- -->\n\n2.  A random variable is normally distributed. It has a mean of 245 and a standard deviation of 21.\n\n<!-- -->\n\na.  If you take a sample of size 10, can you say what the shape of the distribution for the sample mean is? Why?\nb.  For a sample of size 10, state the mean of the sample mean and the standard deviation of the sample mean.\nc.  For a sample of size 10, find the probability that the sample mean is more than 241.\nd.  If you take a sample of size 35, can you say what the shape of the distribution of the sample mean is? Why?\ne.  For a sample of size 35, state the mean of the sample mean and the standard deviation of the sample mean.\nf.  For a sample of size 35, find the probability that the sample mean is more than 241.\ng.  Compare your answers in part c and f. Why is one smaller than the other?\n\n<!-- -->\n\n3.  The mean starting salary for nurses is \\\\\\$67,694 nationally (\"Staff nurse -,\" 2013). The standard deviation is approximately \\$10,333. The starting salary is not normally distributed but it is mound shaped. A sample of 42 starting salaries for nurses is taken.\n\n<!-- -->\n\na.  State the random variable.\nb.  What is the mean of the sample mean?\nc.  What is the standard deviation of the sample mean?\nd.  What is the shape of the sampling distribution of the sample mean? Why?\ne.  Find the probability that the sample mean is more than \\\\\\$75,000.\nf.  Find the probability that the sample mean is less than \\\\\\$60,000.\ng.  If you did find a sample mean of more than \\\\\\$75,000 would you find that unusual? What could you conclude?\n\n<!-- -->\n\n4.  According to the WHO MONICA Project the mean blood pressure for people in China is 128 mmHg with a standard deviation of 23 mmHg (Kuulasmaa, Hense & Tolonen, 1998). Blood pressure is normally distributed.\n\n<!-- -->\n\na.  State the random variable.\nb.  Suppose a sample of size 15 is taken. State the shape of the distribution of the sample mean.\nc.  Suppose a sample of size 15 is taken. State the mean of the sample mean.\nd.  Suppose a sample of size 15 is taken. State the standard deviation of the sample mean.\ne.  Suppose a sample of size 15 is taken. Find the probability that the sample mean blood pressure is more than 135 mmHg.\nf.  Would it be unusual to find a sample mean of 15 people in China of more than 135 mmHg? Why or why not?\ng.  If you did find a sample mean for 15 people in China to be more than 135 mmHg, what might you conclude?\n\n<!-- -->\n\n5.  The size of fish is very important to commercial fishing. A study conducted in 2012 found the length of Atlantic cod caught in nets in Karlskrona to have a mean of 49.9 cm and a standard deviation of 3.74 cm (Ovegard, Berndt & Lunneryd, 2012). The length of fish is normally distributed. A sample of 15 fish is taken.\n\n<!-- -->\n\na.  State the random variable.\nb.  Find the mean of the sample mean.\nc.  Find the standard deviation of the sample mean\nd.  What is the shape of the distribution of the sample mean? Why?\ne.  Find the probability that the sample mean length of the Atlantic cod is less than 52 cm.\nf.  Find the probability that the sample mean length of the Atlantic cod is more than 74 cm.\ng.  If you found sample mean length for Atlantic cod to be more than 74 cm, what could you conclude?\n\n<!-- -->\n\n6.  The mean cholesterol levels of women age 45-59 in Ghana, Nigeria, and Seychelles is 5.1 mmol/l and the standard deviation is 1.0 mmol/l (Lawes, Hoorn, Law & Rodgers, 2004). Assume that cholesterol levels are normally distributed.\n\n<!-- -->\n\na.  State the random variable.\nb.  Find the probability that a woman age 45-59 in Ghana has a cholesterol level above 6.2 mmol/l (considered a high level).\nc.  Suppose doctors decide to test the woman's cholesterol level again and average the two values. Find the probability that this woman's mean cholesterol level for the two tests is above 6.2 mmol/l.\nd.  Suppose doctors being very conservative decide to test the woman's cholesterol level a third time and average the three values. Find the probability that this woman's mean cholesterol level for the three tests is above 6.2 mmol/l.\ne.  If the sample mean cholesterol level for this woman after three tests is above 6.2 mmol/l, what could you conclude?\n\n<!-- -->\n\n7.  In the United States, males between the ages of 40 and 49 eat on average 103.1 g of fat every day with a standard deviation of 4.32 g (\"What we eat,\" 2012). The amount of fat a person eats is not normally distributed but it is relatively mound shaped.\n\n<!-- -->\n\na.  State the random variable.\nb.  Find the probability that a sample mean amount of daily fat intake for 35 men age 40-59 in the U.S. is more than 100 g.\nc.  Find the probability that a sample mean amount of daily fat intake for 35 men age 40-59 in the U.S. is less than 93 g.\nd.  If you found a sample mean amount of daily fat intake for 35 men age 40-59 in the U.S. less than 93 g, what would you conclude?\n\n<!-- -->\n\n8.  A dishwasher has a mean life of 12 years with an estimated standard deviation of 1.25 years (\"Appliance life expectancy,\" 2013). The life of a dishwasher is normally distributed. Suppose you are a manufacturer and you take a sample of 10 dishwashers that you made.\n\n<!-- -->\n\na.  State the random variable.\nb.  Find the mean of the sample mean.\nc.  Find the standard deviation of the sample mean.\nd.  What is the shape of the sampling distribution of the sample mean? Why?\ne.  Find the probability that the sample mean of the dishwashers is less than 6 years.\nf.  If you found the sample mean life of the 10 dishwashers to be less than 6 years, would you think that you have a problem with the manufacturing process? Why or why not?\n",
    "supporting": [
      "Continuous-Probability-Distribution_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}