<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kathryn Kozak">

<title>Statistics Using Technology, 4th Edition - 11&nbsp; Chi-squared and ANOVA Tests</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./References.html" rel="next">
<link href="./Regression.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Chi-Square and ANOVA Tests.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Chi-squared and ANOVA Tests</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics Using Technology, 4th Edition</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Statistical Basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Statistical Basics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Graphical Description of Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Graphical Description of Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Numerical Description of Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Numerical Description of Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Discrete Probability Distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Discrete Probability Distribution</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Continuous Probability Distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Continuous Probability Distribution</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./One Sample Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">One Sample Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Two Sample Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Two Sample Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chi-Square and ANOVA Tests.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Chi-squared and ANOVA Tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./References.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#chi-square-test-for-independence" id="toc-chi-square-test-for-independence" class="nav-link active" data-scroll-target="#chi-square-test-for-independence"><span class="header-section-number">11.1</span> Chi-Square Test for Independence</a>
  <ul class="collapse">
  <li><a href="#hypothesis-test-for-chi-square-test" id="toc-hypothesis-test-for-chi-square-test" class="nav-link" data-scroll-target="#hypothesis-test-for-chi-square-test"><span class="header-section-number">11.1.1</span> Hypothesis Test for Chi-Square Test</a></li>
  <li><a href="#homework-for-chi-square-test-for-independence-section" id="toc-homework-for-chi-square-test-for-independence-section" class="nav-link" data-scroll-target="#homework-for-chi-square-test-for-independence-section"><span class="header-section-number">11.1.2</span> Homework for Chi-Square Test for Independence Section</a></li>
  </ul></li>
  <li><a href="#chi-square-goodness-of-fit" id="toc-chi-square-goodness-of-fit" class="nav-link" data-scroll-target="#chi-square-goodness-of-fit"><span class="header-section-number">11.2</span> Chi-Square Goodness of Fit</a>
  <ul class="collapse">
  <li><a href="#hypothesis-test-for-goodness-of-fit-test" id="toc-hypothesis-test-for-goodness-of-fit-test" class="nav-link" data-scroll-target="#hypothesis-test-for-goodness-of-fit-test"><span class="header-section-number">11.2.1</span> Hypothesis Test for Goodness of Fit Test</a></li>
  <li><a href="#example-goodness-of-fit-test" id="toc-example-goodness-of-fit-test" class="nav-link" data-scroll-target="#example-goodness-of-fit-test"><span class="header-section-number">11.2.2</span> Example: Goodness of Fit Test</a></li>
  <li><a href="#homework-for-chi-square-goodness-of-fit-section" id="toc-homework-for-chi-square-goodness-of-fit-section" class="nav-link" data-scroll-target="#homework-for-chi-square-goodness-of-fit-section"><span class="header-section-number">11.2.3</span> Homework for Chi-Square Goodness of Fit Section</a></li>
  </ul></li>
  <li><a href="#analysis-of-variance-anova" id="toc-analysis-of-variance-anova" class="nav-link" data-scroll-target="#analysis-of-variance-anova"><span class="header-section-number">11.3</span> Analysis of Variance (ANOVA)</a>
  <ul class="collapse">
  <li><a href="#hypothesis-test-using-anova-to-compare-k-means" id="toc-hypothesis-test-using-anova-to-compare-k-means" class="nav-link" data-scroll-target="#hypothesis-test-using-anova-to-compare-k-means"><span class="header-section-number">11.3.1</span> Hypothesis test using ANOVA to compare <span class="math inline">\(k\)</span> means</a></li>
  <li><a href="#example-hypothesis-test-involving-several-means" id="toc-example-hypothesis-test-involving-several-means" class="nav-link" data-scroll-target="#example-hypothesis-test-involving-several-means"><span class="header-section-number">11.3.2</span> Example: Hypothesis Test Involving Several Means</a></li>
  <li><a href="#homework-for-analysis-of-variance-anova-section" id="toc-homework-for-analysis-of-variance-anova-section" class="nav-link" data-scroll-target="#homework-for-analysis-of-variance-anova-section"><span class="header-section-number">11.3.3</span> Homework for Analysis of Variance (ANOVA) Section</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Chi-squared and ANOVA Tests</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Kathryn Kozak </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<p>This chapter presents material on three more hypothesis tests. One is used to determine significant relationship between two qualitative variables, the second is used to determine if the sample data has a particular distribution, and the last is used to determine significant relationships between means of 3 or more samples.</p>
<section id="chi-square-test-for-independence" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="chi-square-test-for-independence"><span class="header-section-number">11.1</span> Chi-Square Test for Independence</h2>
<p>Remember, qualitative data is where you collect data on individuals that are categories or names. Then you would count how many of the individuals had particular qualities. An example is that there is a theory that there is a relationship between breastfeeding and autism. To determine if there is a relationship, researchers could collect the time period that a mother breastfed her child and if that child was diagnosed with autism. Then you would have a table containing this information. Now you want to know if each cell is independent of each other cell. Remember, independence says that one event does not affect another event. Here it means that having autism is independent of being breastfed. What you really want is to see if they are not independent. In other words, does one affect the other? If you were to do a hypothesis test, this is your alternative hypothesis and the null hypothesis is that they are independent. There is a hypothesis test for this and it is called the <strong>Chi-Square Test for Independence</strong>. Technically it should be called the Chi-Square Test for Dependence, but for historical reasons it is known as the test for independence. Just as with previous hypothesis tests, all the steps are the same except for the conditions and the test statistic.</p>
<section id="hypothesis-test-for-chi-square-test" class="level3" data-number="11.1.1">
<h3 data-number="11.1.1" class="anchored" data-anchor-id="hypothesis-test-for-chi-square-test"><span class="header-section-number">11.1.1</span> Hypothesis Test for Chi-Square Test</h3>
<ol type="1">
<li>State the null and alternative hypotheses and the level of significance</li>
</ol>
<p><span class="math inline">\(H_o:\)</span> the two variables are independent (this means that the one variable is not affected by the other)</p>
<p><span class="math inline">\(H_a:\)</span> the two variables are dependent (this means that the one variable is affected by the other)</p>
<p>Also, state your <span class="math inline">\(\alpha\)</span> level here.</p>
<ol start="2" type="1">
<li>State and check the conditions for the hypothesis test</li>
</ol>
<!-- -->
<ol type="a">
<li><p>State: A random sample is taken. Check: describe the process used to collect sample.</p></li>
<li><p>State: Expected frequencies for each cell are greater than or equal to 5, which means <span class="math inline">\(E\ge5\)</span>. Check: The expected frequencies, <span class="math inline">\(E\)</span>, will be calculated later.</p></li>
</ol>
<p>3. Find the test statistic and p-value</p>
<p>Finding the test statistic involves several steps. First the data is collected and counted, and then it is organized into a table (in a table each entry is called a cell). These values are known as the observed frequencies, which the symbol for an observed frequency is <span class="math inline">\(O\)</span>. Each table is made up of rows and columns. Then each row is totaled to give a row total and each column is totaled to give a column total.</p>
<p>The null hypothesis is that the variables are independent. Using the multiplication rule for independent events you can calculate the probability of being one value of the first variable, <span class="math inline">\(A\)</span>, and one value of the second variable, <span class="math inline">\(B\)</span> (the probability of a particular cell). Remember in a hypothesis test, you assume that is true, the two variables are assumed to be independent.</p>
<p>Now you want to find out how many individuals you expect to be in a certain cell. To find the expected frequencies, you just need to multiply the probability of that cell times the total number of individuals. Do not round the expected frequencies.</p>
<p>If the variables are independent the expected frequencies and the observed frequencies should be the same. The test statistic here will involve looking at the difference between the expected frequency and the observed frequency for each cell. Then you want to find the “total difference” of all of these differences. The larger the total, the smaller the chances that you could find that test statistic given that the condition of independence is true. That means that the condition of independence is not true. How do you find the test statistic? First find the differences between the observed and expected frequencies. Because some of these differences will be positive and some will be negative, you need to square these differences. These squares could be large just because the frequencies are large, you need to divide by the expected frequencies to scale them. Then finally add up all of these fractional values. This is the test statistic.</p>
<p>Test Statistic:</p>
<p>Using r: See <a href="#example-hypothesis-test-with-chi-square-test">Example: Hypothesis Test with Chi-Square Test</a> for the process</p>
<ol start="4" type="1">
<li>Conclusion</li>
</ol>
<p>This is where you write reject <span class="math inline">\(H_o\)</span> or fail to reject <span class="math inline">\(H_o\)</span>. The rule is: if the p-value <span class="math inline">\(&lt;\alpha\)</span>, then reject <span class="math inline">\(H_o\)</span>. If the p-value<span class="math inline">\(\ge \alpha\)</span>, then fail to reject <span class="math inline">\(H_o\)</span></p>
<ol start="5" type="1">
<li>Interpretation</li>
</ol>
<p>This is where you interpret in real world terms the conclusion to the test. The conclusion for a hypothesis test is that you either have enough evidence to support <span class="math inline">\(H_a\)</span>, or you do not have enough evidence to support <span class="math inline">\(H_a\)</span>.</p>
<section id="example-hypothesis-test-with-chi-square-test" class="level4" data-number="11.1.1.1">
<h4 data-number="11.1.1.1" class="anchored" data-anchor-id="example-hypothesis-test-with-chi-square-test"><span class="header-section-number">11.1.1.1</span> Example: Hypothesis Test with Chi-Square Test</h4>
<p>Is there a relationship between autism and breastfeeding? To determine if there is, a researcher asked mothers of autistic and non-autistic children to say what time period they breastfed their children. The data is in <a href="#autism-versus-breastfeeding">Autism Versus Breastfeeding</a> (Schultz, Klonoff-Cohen, Wingard, Askhoomoff, Macera, Ji &amp; Bacher, 2006). Do the data provide enough evidence to support that breastfeeding and autism are independent? Test at the 1% level.</p>
<section id="autism-versus-breastfeeding" class="level5" data-number="11.1.1.1.1">
<h5 data-number="11.1.1.1.1" class="anchored" data-anchor-id="autism-versus-breastfeeding"><span class="header-section-number">11.1.1.1.1</span> Autism Versus Breastfeeding</h5>
<table class="table">
<caption>Breast Feeding</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Autism</th>
<th>Not Breast Feed</th>
<th>Breast Feed less than 2 months</th>
<th>Breast Feed 2 to 6 months</th>
<th>Breast Feed more than 6 months</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>yes</td>
<td>241</td>
<td>198</td>
<td>164</td>
<td>215</td>
</tr>
<tr class="even">
<td>no</td>
<td>20</td>
<td>25</td>
<td>27</td>
<td>44</td>
</tr>
</tbody>
</table>
<p>To put this data into r, use the following commands:</p>
<p>If you have the data frame instead of the summary table as in this example, you can use the tally command to create the table in r. Just save the tally command with a name.</p>
</section>
</section>
<section id="solution" class="level4" data-number="11.1.1.2">
<h4 data-number="11.1.1.2" class="anchored" data-anchor-id="solution"><span class="header-section-number">11.1.1.2</span> Solution</h4>
<ol type="1">
<li>State the null and alternative hypotheses and the level of significance</li>
</ol>
<p><span class="math inline">\(H_o\)</span>: Breastfeeding and autism are independent</p>
<p><span class="math inline">\(H_a\)</span>: Breastfeeding and autism are dependent</p>
<ol start="2" type="1">
<li>State and check the conditions for the hypothesis test</li>
</ol>
<!-- -->
<ol type="a">
<li><p>State: A random sample of breastfeeding time frames and autism incidence was taken. Check: this was stated in the problem.</p></li>
<li><p>State: Expected frequencies for each cell are greater than or equal to 5, <span class="math inline">\(E\ge 5\)</span>. Check: See step 3. All expected frequencies are more than 5.</p></li>
</ol>
<!-- -->
<ol start="3" type="1">
<li>Find the test statistic and p-value On rStudio, the command is</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(autism_table) <span class="co">#calculates the test statistics and p-value </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  autism_table
X-squared = 11.217, df = 3, p-value = 0.01061</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(autism_table)<span class="sc">$</span>expected <span class="co"># shows all the expected frequencies </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         [,1]      [,2]      [,3]      [,4]
yes 228.58458 195.30407 167.27837 226.83298
no   32.41542  27.69593  23.72163  32.16702</code></pre>
</div>
</div>
<p>The test statistic is 11.217 and the p-value is 0.01061.</p>
<ol start="4" type="1">
<li>Conclusion</li>
</ol>
<p>Fail to reject <span class="math inline">\(H_o\)</span> since the p-value is more than 0.01.</p>
<ol start="5" type="1">
<li>Interpretation</li>
</ol>
<p>There is not enough evidence to support that breastfeeding and autism are dependent. This means that you cannot say whether a child is breastfed or not will indicate if that the child will be diagnosed with autism.</p>
</section>
</section>
<section id="homework-for-chi-square-test-for-independence-section" class="level3" data-number="11.1.2">
<h3 data-number="11.1.2" class="anchored" data-anchor-id="homework-for-chi-square-test-for-independence-section"><span class="header-section-number">11.1.2</span> Homework for Chi-Square Test for Independence Section</h3>
<p><strong>In each problem show all steps of the hypothesis test. If some of the conditions are not met, note that the results of the test may not be correct and then continue the process of the hypothesis test.</strong></p>
<ol type="1">
<li>The number of people who survived the Titanic based on class and sex is in <a href="#tbl-Titanic_table">Table&nbsp;<span>11.1</span></a> (“Encyclopedia Titanica,” 2013). Is there enough evidence to show that the class and the sex of a person who survived the Titanic are independent? Test at the 5% level.</li>
</ol>
<div class="cell" data-tbl-alt="Head of Surviving the Titanic">
<div class="cell-output-display">
<div id="tbl-Titanic_table" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11.1: Surviving the Titanic</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">female</th>
<th style="text-align: right;">male</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">first</td>
<td style="text-align: right;">134</td>
<td style="text-align: right;">59</td>
</tr>
<tr class="even">
<td style="text-align: left;">second</td>
<td style="text-align: right;">94</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">third</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">58</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<ol start="2" type="1">
<li>Researchers watched groups of dolphins off the coast of Ireland in 1998 to determine what activities the dolphins partake in at certain times of the day (“Activities of dolphin,” 2013). The numbers in <a href="#tbl-Dolphin_table">Table&nbsp;<span>11.2</span></a> represent the number of groups of dolphins that were partaking in an activity at certain times of days. Is there enough evidence to show that the activity and the time period are independent for dolphins? Test at the 1% level.</li>
</ol>
<div class="cell" data-tbl-alt="Head of Dolphin Activity">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>Dolphin<span class="ot">&lt;-</span> <span class="fu">read.csv</span>( <span class="st">"https://krkozak.github.io/MAT160/dolphins.csv"</span>) </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>Dolphin_table<span class="ot">&lt;-</span><span class="fu">tally</span>(<span class="sc">~</span>activity<span class="sc">+</span>period, <span class="at">data=</span>Dolphin)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(Dolphin_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-Dolphin_table" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11.2: Dolphin Activity</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Afternoon</th>
<th style="text-align: right;">Evening</th>
<th style="text-align: right;">Morning</th>
<th style="text-align: right;">Noon</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Feed</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Social</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Travel</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<ol start="3" type="1">
<li>Is there a relationship between autism and what an infant is fed? To determine if there is, a researcher asked mothers of autistic and non-autistic children to say what they fed their infant. The data is in <a href="#tbl-Feeding_table">Table&nbsp;<span>11.3</span></a> (Schultz, Klonoff-Cohen, Wingard, Askhoomoff, Macera, Ji &amp; Bacher, 2006). Do the data provide enough evidence to show that that what an infant is fed and autism are independent? Breast-feeding (BF), Formula with DHA/ARA (For with), and Formula without DHA/ARA (Form without)Test at the 1% level.</li>
</ol>
<div class="cell" data-tbl-alt="Autism Versus Breastfeeding">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>Feeding<span class="ot">&lt;-</span> <span class="fu">read.csv</span>( <span class="st">"https://krkozak.github.io/MAT160/Mothers.csv"</span>) </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>Feeding_table<span class="ot">&lt;-</span><span class="fu">tally</span>(<span class="sc">~</span>autism<span class="sc">+</span>feeding, <span class="at">data=</span>Feeding)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(Feeding_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-Feeding_table" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11.3: Autism Versus Breastfeeding</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">breast</th>
<th style="text-align: right;">formula_with</th>
<th style="text-align: right;">formula_without</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">no</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">yes</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">65</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<ol start="4" type="1">
<li>Students at multiple grade schools were asked what their personal goal (get good grades, be popular, be good at sports) was and how important good grades were to them (1 very important and 4 least important). The data is in <a href="#tbl-Goal_Grades_table">Table&nbsp;<span>11.4</span></a> (“Popular kids datafile,” 2013). Do the data provide enough evidence to show that goal attainment and importance of grades are independent? Test at the 5% level.</li>
</ol>
<div class="cell" data-tbl-alt="Personal Goal and Importance of Grades">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>Goal<span class="ot">&lt;-</span> <span class="fu">read.csv</span>( <span class="st">"https://krkozak.github.io/MAT160/Popular_Kids_clean.csv"</span>) </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>Goal_Grades_table<span class="ot">&lt;-</span><span class="fu">tally</span>(<span class="sc">~</span>Goals<span class="sc">+</span>Grades, <span class="at">data=</span>Goal)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(Goal_Grades_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-Goal_Grades_table" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11.4: Personal Goal and Importance of Grades</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">1</th>
<th style="text-align: right;">2</th>
<th style="text-align: right;">3</th>
<th style="text-align: right;">4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Grades</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">56</td>
</tr>
<tr class="even">
<td style="text-align: left;">Popular</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">49</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sports</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">23</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<ol start="5" type="1">
<li>Students at multiple grade schools were asked what their personal goal (get good grades, be popular, be good at sports) was and how important being good at sports were to them (1 very important and 4 least important). The data is in <a href="#tbl-Goal_Sports_table">Table&nbsp;<span>11.5</span></a> (“Popular kids datafile,” 2013). Do the data provide enough evidence to show that goal attainment and importance of sports are independent? Test at the 5% level.</li>
</ol>
<div class="cell" data-tbl-alt="Personal Goal and Importance of Sports">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>Goal<span class="ot">&lt;-</span> <span class="fu">read.csv</span>( <span class="st">"https://krkozak.github.io/MAT160/Popular_Kids_clean.csv"</span>) </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>Goal_Sports_table<span class="ot">&lt;-</span><span class="fu">tally</span>(<span class="sc">~</span>Goals<span class="sc">+</span>Sports, <span class="at">data=</span>Goal)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(Goal_Sports_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-Goal_Sports_table" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11.5: Personal Goal and Importance of Sports</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">1</th>
<th style="text-align: right;">2</th>
<th style="text-align: right;">3</th>
<th style="text-align: right;">4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Grades</td>
<td style="text-align: right;">83</td>
<td style="text-align: right;">81</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">28</td>
</tr>
<tr class="even">
<td style="text-align: left;">Popular</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">49</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">17</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sports</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">2</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<ol start="6" type="1">
<li>Students at multiple grade schools were asked what their personal goal (get good grades, be popular, be good at sports) was and how important having good looks were to them (1 very important and 4 least important). The data is in <a href="#tbl-Goal_Looks_table">Table&nbsp;<span>11.6</span></a> (“Popular kids datafile,” 2013). Do the data provide enough evidence to show that goal attainment and importance of looks are independent? Test at the 5% level.</li>
</ol>
<div class="cell" data-tbl-alt="Personal Goal and Importance of Looks">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>Goal<span class="ot">&lt;-</span> <span class="fu">read.csv</span>( <span class="st">"https://krkozak.github.io/MAT160/Popular_Kids_clean.csv"</span>) </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>Goal_Looks_table<span class="ot">&lt;-</span><span class="fu">tally</span>(<span class="sc">~</span>Goals<span class="sc">+</span>Looks, <span class="at">data=</span>Goal)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(Goal_Looks_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-Goal_Looks_table" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11.6: Personal Goal and Importance of Looks</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">1</th>
<th style="text-align: right;">2</th>
<th style="text-align: right;">3</th>
<th style="text-align: right;">4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Grades</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">35</td>
</tr>
<tr class="even">
<td style="text-align: left;">Popular</td>
<td style="text-align: right;">81</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sports</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">19</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<ol start="7" type="1">
<li>Students at multiple grade schools were asked what their personal goal (get good grades, be popular, be good at sports) was and how important having money were to them (1 very important and 4 least important). The data is in <a href="#tbl-Goal_Money_table">Table&nbsp;<span>11.7</span></a> (“Popular kids datafile,” 2013). Do the data provide enough evidence to show that goal attainment and importance of money are independent? Test at the 5% level.</li>
</ol>
<div class="cell" data-tbl-alt="Personal Goal and Importance of Money">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>Goal<span class="ot">&lt;-</span> <span class="fu">read.csv</span>( <span class="st">"https://krkozak.github.io/MAT160/Popular_Kids_clean.csv"</span>) </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>Goal_Money_table<span class="ot">&lt;-</span><span class="fu">tally</span>(<span class="sc">~</span>Goals<span class="sc">+</span>Money, <span class="at">data=</span>Goal)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(Goal_Money_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-Goal_Money_table" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11.7: Personal Goal and Importance of Money</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">1</th>
<th style="text-align: right;">2</th>
<th style="text-align: right;">3</th>
<th style="text-align: right;">4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Grades</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">128</td>
</tr>
<tr class="even">
<td style="text-align: left;">Popular</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">63</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sports</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">46</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
</section>
<section id="chi-square-goodness-of-fit" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="chi-square-goodness-of-fit"><span class="header-section-number">11.2</span> Chi-Square Goodness of Fit</h2>
<p>In probability, you calculated probabilities using both experimental and theoretical methods. There are times when it is important to determine how well the experimental values match the theoretical values. An example of this is if you wish to verify if a die is fair. To determine if observed values fit the expected values, you want to see if the difference between observed values and expected values is large enough to say that the test statistic is unlikely to happen if you assume that the observed values fit the expected values. The test statistic in this case is also the chi-square. The process is the same as for the chi-square test for independence.</p>
<section id="hypothesis-test-for-goodness-of-fit-test" class="level3" data-number="11.2.1">
<h3 data-number="11.2.1" class="anchored" data-anchor-id="hypothesis-test-for-goodness-of-fit-test"><span class="header-section-number">11.2.1</span> Hypothesis Test for Goodness of Fit Test</h3>
<ol type="1">
<li>State the null and alternative hypotheses and the level of significance</li>
</ol>
<p><span class="math inline">\(H_o:\)</span> The data are consistent with a specific distribution</p>
<p><span class="math inline">\(H_a:\)</span> The data are not consistent with a specific distribution</p>
<p>Also, state your <span class="math inline">\(\alpha\)</span> level here.</p>
<ol start="2" type="1">
<li>State and check the conditions for the hypothesis test</li>
</ol>
<!-- -->
<ol type="a">
<li><p>State: A random sample is taken. Check: State how the sample is collected.</p></li>
<li><p>State: Expected frequencies for each cell are greater than or equal to 5. Check: The expected frequencies, *E*, will be calculated later.</p></li>
</ol>
<!-- -->
<ol start="3" type="1">
<li>Find the test statistic and p-value</li>
</ol>
<p>Using rStudio see example 11.2.1</p>
<ol start="4" type="1">
<li>Conclusion</li>
</ol>
<p>This is where you write reject <span class="math inline">\(H_o\)</span> or fail to reject <span class="math inline">\(H_o\)</span>. The rule is: if the p-value <span class="math inline">\(&lt;\alpha\)</span>, then reject <span class="math inline">\(H_o\)</span>. If the p-value <span class="math inline">\(\ge \alpha\)</span>, then fail to reject <span class="math inline">\(H_0\)</span></p>
<ol start="5" type="1">
<li>Interpretation</li>
</ol>
<p>This is where you interpret in real world terms the conclusion to the test. The conclusion for a hypothesis test is that you either have enough evidence to support <span class="math inline">\(H_a\)</span>, or you do not have enough evidence to support <span class="math inline">\(H_a\)</span>.</p>
</section>
<section id="example-goodness-of-fit-test" class="level3" data-number="11.2.2">
<h3 data-number="11.2.2" class="anchored" data-anchor-id="example-goodness-of-fit-test"><span class="header-section-number">11.2.2</span> Example: Goodness of Fit Test</h3>
<p>Suppose you have a die that you are curious if it is fair or not. If it is fair then the proportion for each value should be the same. You need to find the observed frequencies and to accomplish this you roll the die 500 times and count how often each side comes up. The data is in table <a href="#tbl-Die">Table&nbsp;<span>11.8</span></a>. Do the data show that the die is fair? Test at the 5% level.</p>
<div class="cell" data-tbl-alt="Observed Frequencies of Die for sides 1 through 6">
<div class="cell-output-display">
<div id="tbl-Die" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11.8: Observed Frequencies of Die for sides 1 through 6</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Sides</th>
<th style="text-align: right;">observed….c.78..87..87..76..85..87.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">78</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">87</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: right;">87</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: right;">76</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: right;">85</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: right;">87</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<section id="solution-1" class="level4" data-number="11.2.2.1">
<h4 data-number="11.2.2.1" class="anchored" data-anchor-id="solution-1"><span class="header-section-number">11.2.2.1</span> Solution</h4>
<ol type="1">
<li>State the null and alternative hypotheses and the level of significance</li>
</ol>
<p><span class="math inline">\(H_o:\)</span> The observed frequencies are consistent with the distribution for fair die (the die is fair)</p>
<p><span class="math inline">\(H_a:\)</span> The observed frequencies are not consistent with the distribution for fair die (the die is not fair)</p>
<p><span class="math inline">\(\alpha=0.05\)</span></p>
<ol start="2" type="1">
<li>State and check the conditions for the hypothesis test</li>
</ol>
<!-- -->
<ol type="a">
<li>State: A random sample is taken. check: This is true since each throw of a die is a random event.</li>
<li>State: Expected frequencies for each cell are greater than or equal to 5. Check: See step 3.</li>
</ol>
<!-- -->
<ol start="3" type="1">
<li>Find the test statistic and p-value</li>
</ol>
<p>On rStudio, this would be</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>fair_die<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>) </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>observed<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">78</span>, <span class="dv">87</span>, <span class="dv">87</span>, <span class="dv">76</span>, <span class="dv">85</span>, <span class="dv">87</span>) </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(observed, <span class="at">p=</span>fair_die) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test for given probabilities

data:  observed
X-squared = 1.504, df = 5, p-value = 0.9126</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(observed, <span class="at">p=</span>fair_die)<span class="sc">$</span>expected </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 83.33333 83.33333 83.33333 83.33333 83.33333 83.33333</code></pre>
</div>
</div>
<p>Test Statistic: The test statistic is 1.504. The p-value is 0.9126.</p>
<ol start="4" type="1">
<li>Conclusion</li>
</ol>
<p>Fail to reject <span class="math inline">\(H_o\)</span> since the p-value is greater than 0.05.</p>
<ol start="5" type="1">
<li>Interpretation</li>
</ol>
<p>There is not enough evidence to support that the die is not consistent with the distribution for a fair die. There is not enough evidence to support that the die is not fair.</p>
</section>
</section>
<section id="homework-for-chi-square-goodness-of-fit-section" class="level3" data-number="11.2.3">
<h3 data-number="11.2.3" class="anchored" data-anchor-id="homework-for-chi-square-goodness-of-fit-section"><span class="header-section-number">11.2.3</span> Homework for Chi-Square Goodness of Fit Section</h3>
<p><strong>In each problem show all steps of the hypothesis test. If some of the conditions are not met, note that the results of the test may not be correct and then continue the process of the hypothesis test.</strong></p>
<ol type="1">
<li>According to the M&amp;M candy company, the expected proportion can be found in <a href="#tbl-MandM">Table&nbsp;<span>11.9</span></a>. In addition, the table contains the number of M&amp;M’s of each color that were found in a case of candy (Madison, 2013). At the 5% level, do the observed frequencies support the claim of M&amp;M?</li>
</ol>
<div class="cell" data-tbl-alt="M&amp;M Observed and Expected">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>MandM <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Color =</span> <span class="fu">c</span>(<span class="st">"Blue"</span>, <span class="st">"Brown"</span>, <span class="st">"Green"</span>, <span class="st">"Orange"</span>, <span class="st">"Red"</span>, <span class="st">"Yellow"</span>),</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Observed =</span> <span class="fu">c</span>(<span class="dv">78</span>, <span class="dv">87</span>, <span class="dv">87</span>, <span class="dv">76</span>, <span class="dv">85</span>, <span class="dv">87</span>),</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Expected =</span> <span class="fu">c</span>(<span class="fl">0.24</span>, <span class="fl">0.13</span>, <span class="fl">0.16</span>, <span class="fl">0.20</span>, <span class="fl">0.13</span>, <span class="fl">0.14</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(MandM)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-MandM" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11.9: M&amp;M Observed and Expected</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Color</th>
<th style="text-align: right;">Observed</th>
<th style="text-align: right;">Expected</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Blue</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">0.24</td>
</tr>
<tr class="even">
<td style="text-align: left;">Brown</td>
<td style="text-align: right;">87</td>
<td style="text-align: right;">0.13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Green</td>
<td style="text-align: right;">87</td>
<td style="text-align: right;">0.16</td>
</tr>
<tr class="even">
<td style="text-align: left;">Orange</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">0.20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Red</td>
<td style="text-align: right;">85</td>
<td style="text-align: right;">0.13</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yellow</td>
<td style="text-align: right;">87</td>
<td style="text-align: right;">0.14</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<ol start="2" type="1">
<li><p>Eyeglassomatic manufactures eyeglasses for different retailers. The data frame is in <a href="Graphical Description of Data.html#tbl-Defects">Table&nbsp;<span>2.4</span></a>. They test to see how many defective lenses they made the time period of January 1 to March 31. <a href="#tbl-Defect_table">Table&nbsp;<span>11.10</span></a> gives the defect and the number of defects.</p>
<p><strong>Code book for Data Frame Defects</strong> below <a href="Graphical Description of Data.html#tbl-Defects">Table&nbsp;<span>2.4</span></a>.</p></li>
</ol>
<div class="cell" data-tbl-alt="Number of Defective Lenses">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>Defect_table <span class="ot">&lt;-</span> <span class="fu">tally</span>(<span class="sc">~</span>type, <span class="at">data=</span>Defects)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(Defect_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-Defect_table" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11.10: Number of Defective Lenses</caption>
<thead>
<tr class="header">
<th style="text-align: left;">type</th>
<th style="text-align: right;">Freq</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">axis</td>
<td style="text-align: right;">1838</td>
</tr>
<tr class="even">
<td style="text-align: left;">big</td>
<td style="text-align: right;">1105</td>
</tr>
<tr class="odd">
<td style="text-align: left;">chamfer</td>
<td style="text-align: right;">1596</td>
</tr>
<tr class="even">
<td style="text-align: left;">cracks</td>
<td style="text-align: right;">1546</td>
</tr>
<tr class="odd">
<td style="text-align: left;">flaked</td>
<td style="text-align: right;">1992</td>
</tr>
<tr class="even">
<td style="text-align: left;">height</td>
<td style="text-align: right;">1130</td>
</tr>
<tr class="odd">
<td style="text-align: left;">intern</td>
<td style="text-align: right;">976</td>
</tr>
<tr class="even">
<td style="text-align: left;">lost</td>
<td style="text-align: right;">976</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pd</td>
<td style="text-align: right;">1398</td>
</tr>
<tr class="even">
<td style="text-align: left;">scratch</td>
<td style="text-align: right;">5865</td>
</tr>
<tr class="odd">
<td style="text-align: left;">shape</td>
<td style="text-align: right;">1485</td>
</tr>
<tr class="even">
<td style="text-align: left;">small</td>
<td style="text-align: right;">4613</td>
</tr>
<tr class="odd">
<td style="text-align: left;">spot</td>
<td style="text-align: right;">1371</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Do the data support the notion that each defect type occurs in the same proportion? Test at the 5% level.</p>
<ol start="3" type="1">
<li><p>On occasion, medical studies need to model the proportion of the population that has a disease and compare that to observed frequencies of the disease actually occurring. Suppose the end-stage renal failure in south-west Wales was collected for different age groups. Do the data in <a href="#tbl-Renal">Table&nbsp;<span>11.11</span></a> show that the observed frequencies are in agreement with proportion of people in each age group (Boyle, Flowerdew &amp; Williams, 1997)? Test at the 1% level.</p>
<p><strong>Table Renal Failure Frequencies</strong></p>
<div class="cell" data-tbl-alt="Renal Failure Frequencies">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>Renal <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Age_group =</span> <span class="fu">c</span>(<span class="st">"16-29"</span>, <span class="st">"30-44"</span>, <span class="st">"45-59"</span>, <span class="st">"60-75"</span>, <span class="st">"75+"</span>),</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Observed =</span> <span class="fu">c</span>(<span class="dv">32</span>, <span class="dv">66</span>, <span class="dv">132</span>, <span class="dv">218</span>, <span class="dv">91</span>),</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Expected =</span> <span class="fu">c</span>(<span class="fl">0.23</span>, <span class="fl">0.25</span>, <span class="fl">0.22</span>, <span class="fl">0.21</span>, <span class="fl">0.09</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(Renal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-Renal" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11.11: Renal Failure Frequencies</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Age_group</th>
<th style="text-align: right;">Observed</th>
<th style="text-align: right;">Expected</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">16-29</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">0.23</td>
</tr>
<tr class="even">
<td style="text-align: left;">30-44</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">0.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">45-59</td>
<td style="text-align: right;">132</td>
<td style="text-align: right;">0.22</td>
</tr>
<tr class="even">
<td style="text-align: left;">60-75</td>
<td style="text-align: right;">218</td>
<td style="text-align: right;">0.21</td>
</tr>
<tr class="odd">
<td style="text-align: left;">75+</td>
<td style="text-align: right;">91</td>
<td style="text-align: right;">0.09</td>
</tr>
</tbody>
</table>
</div>
</div>
</div></li>
<li><p>In Africa in 2011, the number of deaths of a female from cardiovascular disease for different age groups are in <a href="#tbl-Deaths">Table&nbsp;<span>11.12</span></a> (“Global health observatory,” 2013). In addition, the proportion of deaths of females from all causes for the same age groups are also in table Deaths of Females for Different Age Groups. Do the data show that the death from cardiovascular disease are in the same proportion as all deaths for the different age groups? Test at the 5% level.</p>
<div class="cell" data-tbl-alt="Deaths of Females for Different Age Groups">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>Deaths <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Age =</span> <span class="fu">c</span>(<span class="st">"5-14"</span>, <span class="st">"14-29"</span>, <span class="st">"30-49"</span>, <span class="st">"50-69"</span>),</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Observed =</span> <span class="fu">c</span>(<span class="dv">8</span>, <span class="dv">16</span>, <span class="dv">56</span>, <span class="dv">433</span>),</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Expected =</span> <span class="fu">c</span>(<span class="fl">0.10</span>, <span class="fl">0.12</span>, <span class="fl">0.226</span>, <span class="fl">0.52</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(Deaths)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-Deaths" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11.12: Deaths of Females for Different Age Groups</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Age</th>
<th style="text-align: right;">Observed</th>
<th style="text-align: right;">Expected</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">5-14</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.100</td>
</tr>
<tr class="even">
<td style="text-align: left;">14-29</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">0.120</td>
</tr>
<tr class="odd">
<td style="text-align: left;">30-49</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">0.226</td>
</tr>
<tr class="even">
<td style="text-align: left;">50-69</td>
<td style="text-align: right;">433</td>
<td style="text-align: right;">0.520</td>
</tr>
</tbody>
</table>
</div>
</div>
</div></li>
</ol>
<!-- -->
<ol start="5" type="1">
<li><p>In Australia in 1995, there was a question of whether indigenous people are more likely to die in prison than non-indigenous people. To figure out, the data in <a href="#tbl-Prisoners">Table&nbsp;<span>11.13</span></a> was collected. (“Aboriginal deaths in,” 2013). Do the data show that indigenous people die in the same proportion as non-indigenous people? Test at the 1% level.</p>
<div class="cell" data-tbl-alt="Death of Indigenous Prisoners">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>Prisoners <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Died =</span> <span class="fu">c</span>(<span class="st">"Yes"</span>, <span class="st">"No"</span>),</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Observed =</span> <span class="fu">c</span>(<span class="dv">17</span>, <span class="dv">3890</span>),</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Expected =</span> <span class="fu">c</span>(<span class="fl">0.003</span>, <span class="fl">0.997</span>))</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(Prisoners)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-Prisoners" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11.13: Death of Indigenous Prisoners</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Died</th>
<th style="text-align: right;">Observed</th>
<th style="text-align: right;">Expected</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">0.003</td>
</tr>
<tr class="even">
<td style="text-align: left;">No</td>
<td style="text-align: right;">3890</td>
<td style="text-align: right;">0.997</td>
</tr>
</tbody>
</table>
</div>
</div>
</div></li>
<li><p>A project conducted by the Australian Federal Office of Road Safety asked people many questions about their cars. One question was the reason that a person chooses a given car, and that data is in <a href="#tbl-Car_table">Table&nbsp;<span>11.14</span></a> (“Car preferences,” 2013).</p></li>
</ol>
<div class="cell" data-tbl-alt="Reason for Choosing a Car">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>Car_table <span class="ot">&lt;-</span> <span class="fu">tally</span>(<span class="sc">~</span>Reason, <span class="at">data=</span>Car_pref)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(Car_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-Car_table" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11.14: Reason for Choosing a Car</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Reason</th>
<th style="text-align: right;">Freq</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">comfort</td>
<td style="text-align: right;">47</td>
</tr>
<tr class="even">
<td style="text-align: left;">cost</td>
<td style="text-align: right;">46</td>
</tr>
<tr class="odd">
<td style="text-align: left;">looks</td>
<td style="text-align: right;">27</td>
</tr>
<tr class="even">
<td style="text-align: left;">performance</td>
<td style="text-align: right;">34</td>
</tr>
<tr class="odd">
<td style="text-align: left;">reliability</td>
<td style="text-align: right;">62</td>
</tr>
<tr class="even">
<td style="text-align: left;">safety</td>
<td style="text-align: right;">84</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Do the data show that the frequencies observed substantiate the claim that the reasons for choosing a car are equally likely? Test at the 5% level.</p>
</section>
</section>
<section id="analysis-of-variance-anova" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="analysis-of-variance-anova"><span class="header-section-number">11.3</span> Analysis of Variance (ANOVA)</h2>
<p>There are times where you want to compare three or more population means. One idea is to just test different combinations of two means. The problem with that is that your chance for a type I error increases. Instead you need a process for analyzing all of them at the same time. This process is known as <strong>analysis of variance (ANOVA)</strong>. The test statistic for the ANOVA is fairly complicated, you will want to use technology to find the test statistic and p-value. The test statistic is distributed as an F-distribution, which is skewed right and depends on degrees of freedom. Since you will use technology to find these, the distribution and the test statistic will not be presented. Remember, all hypothesis tests are the same process. Note that to obtain a statistically significant result there need only be a difference between any two of the <span class="math inline">\(k\)</span> means.</p>
<p>Before conducting the hypothesis test, it is helpful to look at the means and standard deviations for each data set. If the sample means with consideration of the sample standard deviations are different, it may mean that some of the population means are different. However, do realize that if they are different, it doesn’t provide enough evidence to show the population means are different. Calculating the sample statistics just gives you an idea that conducting the hypothesis test is a good idea.</p>
<section id="hypothesis-test-using-anova-to-compare-k-means" class="level3" data-number="11.3.1">
<h3 data-number="11.3.1" class="anchored" data-anchor-id="hypothesis-test-using-anova-to-compare-k-means"><span class="header-section-number">11.3.1</span> Hypothesis test using ANOVA to compare <span class="math inline">\(k\)</span> means</h3>
<ol type="1">
<li><p>State the random variables and the parameters in words</p></li>
<li><p>State the null and alternative hypotheses and the level of significance</p></li>
</ol>
<p><span class="math inline">\(H_o:\)</span> all the means are the same</p>
<p><span class="math inline">\(H_a:\)</span> at least two of the means are different</p>
<p>Also, state your <span class="math inline">\(\alpha\)</span> level here.</p>
<ol start="3" type="1">
<li>State and check the conditions for the hypothesis test</li>
</ol>
<p>a. State: A random sample of size is taken from each population. Check: discuss how the samples were taken.</p>
<ol start="2" type="a">
<li><p>State: All the samples are independent of each other. Check: Discuss how they are all independent.</p></li>
<li><p>State: Each population is normally distributed. Check: Create density plots and normal quantile plot of each sample. Note: the ANOVA test is fairly robust to the condition especially if the sample sizes are fairly close to each other. Unless the populations are really not normally distributed and the sample sizes are close to each other, then this is a loose condition.</p></li>
<li><p>State: The population variances are all equal. Check: See if the sample variances are close to each other. If the sample sizes are close to each other, then this is a loose condition.</p></li>
</ol>
<p>4. Find the test statistic and p-value</p>
<p>The test statistic is <span class="math inline">\(F\)</span>. To find the test statistic, use technology such r Studio.</p>
<p>The test statistic, <span class="math inline">\(F\)</span>, is distributed as an F-distribution, where both degrees of freedom are needed in this distribution. The p-value is also calculated r Studio.</p>
<ol start="5" type="1">
<li>Conclusion</li>
</ol>
<p>This is where you write reject <span class="math inline">\(H_O\)</span> or fail to reject <span class="math inline">\(H_O\)</span>. The rule is: if the p-value <span class="math inline">\(&lt;\alpha\)</span>, then reject <span class="math inline">\(H_o\)</span>. If the p-value <span class="math inline">\(\ge \alpha\)</span>, then fail to reject <span class="math inline">\(H_o\)</span></p>
<ol start="6" type="1">
<li>Interpretation</li>
</ol>
<p>This is where you interpret in real world terms the conclusion to the test. The conclusion for a hypothesis test is that you either have enough evidence to support <span class="math inline">\(H_a\)</span>, or you do not have enough evidence to support <span class="math inline">\(H_a\)</span>.</p>
<p>If you do in fact reject <span class="math inline">\(H_o\)</span>, then you know that at least two of the means are different. The next question you might ask is which are different? You can look at the sample means, but realize that these only give a preliminary result. To actually determine which means are different, you need to conduct other tests. Some of these tests are the range test, multiple comparison tests, Duncan test, Student-Newman-Keuls test, Tukey test, Scheffé test, Dunnett test, least significant different test, and the Bonferroni test. There is no consensus on which test to use.</p>
</section>
<section id="example-hypothesis-test-involving-several-means" class="level3" data-number="11.3.2">
<h3 data-number="11.3.2" class="anchored" data-anchor-id="example-hypothesis-test-involving-several-means"><span class="header-section-number">11.3.2</span> Example: Hypothesis Test Involving Several Means</h3>
<p>Cancer is a terrible disease. Surviving may depend on the type of cancer the person has. To see if the mean survival time for several types of cancer are different, data was collected on the survival time in days of patients with one of these cancer in advanced stage. The data is in <a href="#tbl-Cancer">Table&nbsp;<span>11.15</span></a> (“Cancer survival story,” 2013). (Please realize that this data is from 1978. There have been many advances in cancer treatment, so do not use this data as an indication of survival rates from these cancers.) Do the data indicate that at least two of the mean survival time for these types of cancer are not all equal? Test at the 1% level.</p>
<div class="cell" data-tbl-alt="Survival Times in Days of Five Cancer Types">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>Cancer <span class="ot">&lt;-</span> <span class="fu">read.csv</span>( <span class="st">"https://krkozak.github.io/MAT160/cancer.csv"</span>) </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(Cancer))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-Cancer" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11.15: Survival Times in Days of Five Cancer Types</caption>
<thead>
<tr class="header">
<th style="text-align: right;">survival</th>
<th style="text-align: left;">organ</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">124</td>
<td style="text-align: left;">Stomach</td>
</tr>
<tr class="even">
<td style="text-align: right;">42</td>
<td style="text-align: left;">Stomach</td>
</tr>
<tr class="odd">
<td style="text-align: right;">25</td>
<td style="text-align: left;">Stomach</td>
</tr>
<tr class="even">
<td style="text-align: right;">45</td>
<td style="text-align: left;">Stomach</td>
</tr>
<tr class="odd">
<td style="text-align: right;">412</td>
<td style="text-align: left;">Stomach</td>
</tr>
<tr class="even">
<td style="text-align: right;">51</td>
<td style="text-align: left;">Stomach</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Code book for data frame Cancer</strong></p>
<p><strong>Description</strong> Survival time for several types of cancer was collected.</p>
<p>This data frame contains the following columns:</p>
<p>survival: survival times (months)</p>
<p>organ: the organ that the cancer is in</p>
<p>Source Cancer survival story. (2013, December 04). Retrieved from &lt;http://lib.stat.cmu.edu/DASL/Stories/CancerSurvival.html&gt;</p>
<p>References &lt;http://lib.stat.cmu.edu/DASL&gt;</p>
<section id="solution-2" class="level4" data-number="11.3.2.1">
<h4 data-number="11.3.2.1" class="anchored" data-anchor-id="solution-2"><span class="header-section-number">11.3.2.1</span> Solution</h4>
<ol type="1">
<li>State the random variables and the parameters in words</li>
</ol>
<p><span class="math inline">\(x_1:\)</span> survival time of patient with Stomach cancer</p>
<p><span class="math inline">\(x_2:\)</span> survival time of patient with Bronchus (lung) cancer</p>
<p><span class="math inline">\(x_3:\)</span> survival time of patient with Colon cancer</p>
<p><span class="math inline">\(x_4:\)</span> survival time of patient with Ovarian cancer</p>
<p><span class="math inline">\(x_5:\)</span> survival time of patient with Breast cancer</p>
<p><span class="math inline">\(\mu_1:\)</span> mean survival time of patient with Stomach cancer</p>
<p><span class="math inline">\(\mu_2:\)</span> mean survival time of patient with Bronchus (lung) cancer</p>
<p><span class="math inline">\(\mu_3:\)</span> mean survival time of patient with Colon cancer</p>
<p><span class="math inline">\(\mu_4:\)</span> mean survival time of patient with Ovarian cancer</p>
<p><span class="math inline">\(\mu_5:\)</span> mean survival time of patient with Brest cancer</p>
<p>Now before conducting the hypothesis test, look at the means and standard deviations. There appears to be a difference between at least two of the means, but realize that the standard deviations are very different. The difference you see may not be significant.</p>
<p>Notice the sample sizes are not the same.</p>
<ol start="2" type="1">
<li>State the null and alternative hypotheses and the level of significance</li>
</ol>
<p><span class="math inline">\(H_o:\)</span> all the means are equal</p>
<p><span class="math inline">\(H_a:\)</span> some of the means are different</p>
<p><span class="math inline">\(\alpha=0.01\)</span></p>
<ol start="3" type="1">
<li>State and check the conditions for the hypothesis test</li>
</ol>
<!-- -->
<ol type="a">
<li><p>State: A random sample of 13 survival times from stomach cancer was taken. A random sample of 17 survival times from bronchus cancer was taken. A random sample of 17 survival times from colon cancer was taken. A random sample of 6 survival times from ovarian cancer was taken. A random sample of 11 survival times from breast cancer was taken.</p>
<p>Check: These statements may not be true. This information was not shared as to whether the samples were random or not but it may be safe to assume that.</p></li>
<li><p>State: The samples are all independent.</p>
<p>Check: Since the individuals have different cancers, then the samples are independent.</p></li>
<li><p>State: Population of all survival times from stomach cancer is normally distributed. Population of all survival times from bronchus cancer is normally distributed. Population of all survival times from colon cancer is normally distributed. Population of all survival times from ovarian cancer is normally distributed. Population of all survival times from breast cancer is normally distributed.</p>
<p>Check: Looking at the density plots and normal quantile plots for each sample, it appears that none of the populations are normally distributed. The sample sizes are somewhat different for the problem. This condition may not be true.</p>
<p>(ref:cancer-density–graphs-cap) Density Plot of Survival Times for Different Cancers</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_density</span>(<span class="sc">~</span>survival<span class="sc">|</span>organ, <span class="at">data=</span>Cancer, <span class="at">title=</span><span class="st">"Survival times for Different Cancers"</span>, <span class="at">xlab =</span> <span class="st">"Survival Times"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Cancer-density" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Chi-Square-and-ANOVA-Tests_files/figure-html/fig-Cancer-density-1.png" class="img-fluid figure-img" alt="Density Plot of Survival Times for Different Cancers" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;11.1: Density Plot of Survival Times for Different Cancers</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_qq</span>(<span class="sc">~</span>survival<span class="sc">|</span>organ, <span class="at">data=</span>Cancer, <span class="at">title=</span><span class="st">"Survival times for Different Cancers"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Cancer-quantile" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Chi-Square-and-ANOVA-Tests_files/figure-html/fig-Cancer-quantile-1.png" class="img-fluid figure-img" alt="Quantile plots of survival times for diffent cancers. All do appear exponential" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;11.2: Quantile Plot of Survival Times for Different Cancers</figcaption>
</figure>
</div>
</div>
</div></li>
<li><p>State: The population variances are all equal.</p>
<p>Check: The sample standard deviations are approximately 346.3, 209.9, 427.2, 1098.6, and 1239.0 respectively. This condition does not appear to be met, since the sample standard deviations are very different. The sample sizes are somewhat different for the problem. This condition may not be true.</p></li>
</ol>
<p>4. Find the test statistic and p-value</p>
<p>To find the test statistic and p-value on r Studio, the commands would be:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>results<span class="ot">=</span><span class="fu">aov</span>(survival<span class="sc">~</span>organ, <span class="at">data=</span>Cancer) </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df   Sum Sq Mean Sq F value   Pr(&gt;F)    
organ        4 11535761 2883940   6.433 0.000229 ***
Residuals   59 26448144  448274                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The test statistic is F = 6.433 and the p-value = 0.000229.</p>
<ol start="5" type="1">
<li>Conclusion</li>
</ol>
<p>Reject <span class="math inline">\(H_o:\)</span> since the p-value is less than 0.01.</p>
<ol start="6" type="1">
<li>Interpretation</li>
</ol>
<p>There is enough evidence to support that at least two of the mean survival times from different cancers are not equal.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">df_stats</span>(survival<span class="sc">~</span>organ, <span class="at">data=</span>Cancer, mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  response    organ      mean
1 survival   Breast 1395.9091
2 survival Bronchus  211.5882
3 survival    Colon  457.4118
4 survival    Ovary  884.3333
5 survival  Stomach  286.0000</code></pre>
</div>
</div>
<p>By examination of the means, it appears that the mean survival time for breast cancer is different from the mean survival times for both stomach and bronchus cancers. It may also be different for the mean survival time for colon cancer. The others may not be different enough to actually say for sure.</p>
</section>
</section>
<section id="homework-for-analysis-of-variance-anova-section" class="level3" data-number="11.3.3">
<h3 data-number="11.3.3" class="anchored" data-anchor-id="homework-for-analysis-of-variance-anova-section"><span class="header-section-number">11.3.3</span> Homework for Analysis of Variance (ANOVA) Section</h3>
<p><strong>In each problem show all steps of the hypothesis test. If some of the conditions are not met, note that the results of the test may not be correct and then continue the process of the hypothesis test.</strong></p>
<ol type="1">
<li>Cuckoo birds are in the habit of laying their eggs in other birds’ nest. The other birds adopt and hatch the eggs. The lengths (in cm) of cuckoo birds’ eggs in the other species nests were measured and are in <a href="#tbl-Eggs">Table&nbsp;<span>11.16</span></a> (“Cuckoo eggs in,” 2013). Do the data show that the mean length of cuckoo bird’s eggs is not all the same when put into different nests? Test at the 5% level.</li>
</ol>
<div class="cell" data-tbl-alt="Lengths of Cuckoo Bird Eggs in Different Species Nest">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>Eggs <span class="ot">&lt;-</span> <span class="fu">read.csv</span>( <span class="st">"https://krkozak.github.io/MAT160/Birds_eggs.csv"</span>) </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(Eggs))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-Eggs" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11.16: Lengths of Cuckoo Bird Eggs in Different Species Nest</caption>
<thead>
<tr class="header">
<th style="text-align: right;">length</th>
<th style="text-align: left;">bird</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">19.65</td>
<td style="text-align: left;">Meadow</td>
</tr>
<tr class="even">
<td style="text-align: right;">20.05</td>
<td style="text-align: left;">Meadow</td>
</tr>
<tr class="odd">
<td style="text-align: right;">20.65</td>
<td style="text-align: left;">Meadow</td>
</tr>
<tr class="even">
<td style="text-align: right;">20.85</td>
<td style="text-align: left;">Meadow</td>
</tr>
<tr class="odd">
<td style="text-align: right;">21.65</td>
<td style="text-align: left;">Meadow</td>
</tr>
<tr class="even">
<td style="text-align: right;">21.65</td>
<td style="text-align: left;">Meadow</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Code book for data frame Eggs</strong></p>
<p><strong>Description</strong> Cuckoo birds are in the habit of laying their eggs in other birds’ nest. The other birds adopt and hatch the eggs. The lengths (in cm) of cuckoo birds’ eggs in the other species nests were measured</p>
<p>This data frame contains the following columns:</p>
<p>length: length of cuckoo bird’s eggs in other species nets (cm)</p>
<p>bird: bids where eggs were found in their nests. The birds are Meadow Pipit, Tree Pipit, Hedge Sparrow, Robin, Pied Wagtail, and Wren</p>
<p>Source Cuckoo eggs in nest of other birds. (2013, December 04). Retrieved from &lt;http://lib.stat.cmu.edu/DASL/Stories/cuckoo.html&gt;</p>
<p>References SOCR Home page: &lt;http://www.socr.ucla.edu&gt;</p>
<ol start="2" type="1">
<li>Levi-Strauss Co manufactures clothing. The quality control department measures weekly values of different suppliers for the percentage difference of waste between the layout on the computer and the actual waste when the clothing is made (called run-up). The data is in <a href="#tbl-Levi">Table&nbsp;<span>11.17</span></a> (“Waste run up,” 2013). Do the data show that there is a difference between some of the suppliers? Test at the 1% level.</li>
</ol>
<div class="cell" data-tbl-alt="Run-ups for Different Plants Making Levi Strauss Clothing">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>Levi <span class="ot">&lt;-</span> <span class="fu">read.csv</span>( <span class="st">"https://krkozak.github.io/MAT160/Levi_jeans.csv"</span>) </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(Levi))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-Levi" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11.17: Run-ups for Different Plants Making Levi Strauss Clothing</caption>
<thead>
<tr class="header">
<th style="text-align: right;">run_up</th>
<th style="text-align: left;">plant</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1.2</td>
<td style="text-align: left;">Plant_1</td>
</tr>
<tr class="even">
<td style="text-align: right;">10.1</td>
<td style="text-align: left;">Plant_1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-2.0</td>
<td style="text-align: left;">Plant_1</td>
</tr>
<tr class="even">
<td style="text-align: right;">1.5</td>
<td style="text-align: left;">Plant_1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-3.0</td>
<td style="text-align: left;">Plant_1</td>
</tr>
<tr class="even">
<td style="text-align: right;">-0.7</td>
<td style="text-align: left;">Plant_1</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Code book for data frame Levi</strong></p>
<p><strong>Description</strong> Levi-Strauss Co manufactures clothing. The quality control department measures weekly values of different suppliers for the percentage difference of waste between the layout on the computer and the actual waste when the clothing is made (called run-up).</p>
<p>This data frame contains the following columns:</p>
<p>run_up: percentage difference of waste between the layout on the computer and the actual waste when the clothing is made. There are some negative values because sometimes the supplier is able to layout the pattern better than the computer</p>
<p>plant: Which suppliers</p>
<p>Source Waste run up. (2013, December 04). Retrieved from &lt;http://lib.stat.cmu.edu/DASL/Stories/wasterunup.html&gt;</p>
<p>References &lt;http://lib.stat.cmu.edu/DASL&gt;</p>
<ol start="3" type="1">
<li>Several magazines were grouped into three categories based on what level of education of their readers the magazines are geared towards: high, medium, or low level. Then random samples of the magazines were selected to determine the number of three-plus-syllable words were in the advertising copy, and the data is in <a href="#tbl-Advertising">Table&nbsp;<span>11.18</span></a> (“Magazine ads readability,” 2013). Is there enough evidence to show that the mean number of three-plus-syllable words in advertising copy is different for at least two of the education levels? Test at the 5% level.</li>
</ol>
<div class="cell" data-tbl-alt="Number of Three Plus Syllable Words in Advertising Copy">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>Advertising <span class="ot">&lt;-</span> <span class="fu">read.csv</span>( <span class="st">"https://krkozak.github.io/MAT160/three_syllable_words.csv"</span>) </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(Advertising))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-Advertising" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11.18: Number of Three Plus Syllable Words in Advertising Copy</caption>
<thead>
<tr class="header">
<th style="text-align: right;">number</th>
<th style="text-align: left;">education</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">34</td>
<td style="text-align: left;">High</td>
</tr>
<tr class="even">
<td style="text-align: right;">21</td>
<td style="text-align: left;">High</td>
</tr>
<tr class="odd">
<td style="text-align: right;">37</td>
<td style="text-align: left;">High</td>
</tr>
<tr class="even">
<td style="text-align: right;">31</td>
<td style="text-align: left;">High</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: left;">High</td>
</tr>
<tr class="even">
<td style="text-align: right;">24</td>
<td style="text-align: left;">High</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Code book for data frame Advertising</strong></p>
<p><strong>Description</strong> Several magazines were grouped into three categories based on what level of education of their readers the magazines are geared towards: high, medium, or low level. Then random samples of the magazines were selected to determine the number of three-plus-syllable words were in the advertising copy</p>
<p>This data frame contains the following columns:</p>
<p>number: number of three=plus-syllable words in advertising copy</p>
<p>education: level of education the magazine is geared towards: high, medium, or low</p>
<p>Source Magazine ads readability. (2013, December 04). Retrieved from &lt;http://lib.stat.cmu.edu/DASL/Datafiles/magadsdat.html&gt;</p>
<p>References &lt;http://lib.stat.cmu.edu/DASL&gt;</p>
<ol start="4" type="1">
<li>A study was undertaken to see how accurate food labeling for calories on food that is considered reduced calorie. The group measured the amount of calories for each item of food and then found the percent difference between measured and labeled food. The group also looked at food that was nationally advertised, regionally distributed, or locally prepared. The data is in <a href="#tbl-Food">Table&nbsp;<span>11.19</span></a> (“Calories datafile,” 2013). Do the data indicate that at least two of the mean percent differences between the three groups are different? Test at the 5% level.</li>
</ol>
<div class="cell" data-tbl-alt="Percent Differences Between Measured and Labeled Food">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>Food <span class="ot">&lt;-</span> <span class="fu">read.csv</span>( <span class="st">"https://krkozak.github.io/MAT160/Food_calories_percent_diff.csv"</span>) </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(Food))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-Food" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11.19: Percent Differences Between Measured and Labeled Food</caption>
<thead>
<tr class="header">
<th style="text-align: right;">percent_diff</th>
<th style="text-align: left;">food</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: left;">national</td>
</tr>
<tr class="even">
<td style="text-align: right;">-28</td>
<td style="text-align: left;">national</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-6</td>
<td style="text-align: left;">national</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: left;">national</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: left;">national</td>
</tr>
<tr class="even">
<td style="text-align: right;">-1</td>
<td style="text-align: left;">national</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Code book for data frame Food</strong></p>
<p><strong>Description</strong> A study was undertaken to see how accurate food labeling for calories on food that is considered reduced calorie. The group measured the amount of calories for each item of food and then found the percent difference between measured and labeled food. The group also looked at food that was nationally advertised, regionally distributed, or locally prepared.</p>
<p>This data frame contains the following columns:</p>
<p>percent_diff: percent difference between the number of calories that are measured in the food and the amount that is labeled on the food.</p>
<p>food: Where the food is created: nationally advertised, regionally distributed, or locally prepared.</p>
<p>Source Calories datafile. (2013, December 07). Retrieved from &lt;http://lib.stat.cmu.edu/DASL/Datafiles/Calories.html&gt;</p>
<p>References &lt;http://lib.stat.cmu.edu/DASL&gt;</p>
<ol start="5" type="1">
<li>The amount of sodium (in mg) in different types of hot dogs is in <a href="#tbl-Food">Table&nbsp;<span>11.19</span></a> (“Hot dogs story,” 2013). Is there sufficient evidence to show that the mean amount of sodium in the types of hot dogs are not all equal? Test at the 5% level.</li>
</ol>
<p><strong>Code book for data frame Food is below <a href="#tbl-Food">Table&nbsp;<span>11.19</span></a>.</strong></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Regression.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./References.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">References</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>