<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Continuous Probability Distribution – Statistics Using Technology: Rguroo Edition</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./One Sample Inference.html" rel="next">
<link href="./Discrete Probability Distribution.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Continuous Probability Distribution.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Continuous Probability Distribution</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics Using Technology: Rguroo Edition</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Statistical Basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Statistical Basics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Graphical Description of Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Graphical Description of Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Numerical-description-of-Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Numerical Description of Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Discrete Probability Distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Discrete Probability Distribution</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Continuous Probability Distribution.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Continuous Probability Distribution</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./One Sample Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">One Sample Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Two Sample Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Two Sample Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chi-Square and ANOVA Tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Chi-squared and ANOVA Tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./References.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#normal-distribution" id="toc-normal-distribution" class="nav-link active" data-scroll-target="#normal-distribution"><span class="header-section-number">6.1</span> Normal Distribution</a></li>
  <li><a href="#finding-probabilities-for-the-normal-distribution" id="toc-finding-probabilities-for-the-normal-distribution" class="nav-link" data-scroll-target="#finding-probabilities-for-the-normal-distribution"><span class="header-section-number">6.2</span> Finding Probabilities for the Normal Distribution</a>
  <ul class="collapse">
  <li><a href="#example-general-normal-distribution" id="toc-example-general-normal-distribution" class="nav-link" data-scroll-target="#example-general-normal-distribution"><span class="header-section-number">6.2.1</span> Example: General Normal Distribution</a></li>
  <li><a href="#example-general-normal-distribution-1" id="toc-example-general-normal-distribution-1" class="nav-link" data-scroll-target="#example-general-normal-distribution-1"><span class="header-section-number">6.2.2</span> Example: General Normal Distribution</a></li>
  <li><a href="#homework-for-normal-distribution-section" id="toc-homework-for-normal-distribution-section" class="nav-link" data-scroll-target="#homework-for-normal-distribution-section"><span class="header-section-number">6.2.3</span> Homework for Normal Distribution Section</a></li>
  </ul></li>
  <li><a href="#assessing-normality" id="toc-assessing-normality" class="nav-link" data-scroll-target="#assessing-normality"><span class="header-section-number">6.3</span> Assessing Normality</a>
  <ul class="collapse">
  <li><a href="#to-create-a-density-plot-on-rstudio" id="toc-to-create-a-density-plot-on-rstudio" class="nav-link" data-scroll-target="#to-create-a-density-plot-on-rstudio"><span class="header-section-number">6.3.1</span> <strong>To create a density plot on rStudio:</strong></a></li>
  <li><a href="#to-create-a-normal-quantile-plot-on-rstudio" id="toc-to-create-a-normal-quantile-plot-on-rstudio" class="nav-link" data-scroll-target="#to-create-a-normal-quantile-plot-on-rstudio"><span class="header-section-number">6.3.2</span> <strong>To create a normal quantile plot on rStudio</strong></a></li>
  <li><a href="#example-is-it-normal" id="toc-example-is-it-normal" class="nav-link" data-scroll-target="#example-is-it-normal"><span class="header-section-number">6.3.3</span> Example: Is It Normal?</a></li>
  <li><a href="#example-is-it-normal-1" id="toc-example-is-it-normal-1" class="nav-link" data-scroll-target="#example-is-it-normal-1"><span class="header-section-number">6.3.4</span> Example: Is It Normal?</a></li>
  <li><a href="#homework-for-assessing-normality-section" id="toc-homework-for-assessing-normality-section" class="nav-link" data-scroll-target="#homework-for-assessing-normality-section"><span class="header-section-number">6.3.5</span> Homework for Assessing Normality Section</a></li>
  </ul></li>
  <li><a href="#sampling-distribution-and-the-central-limit-theorem" id="toc-sampling-distribution-and-the-central-limit-theorem" class="nav-link" data-scroll-target="#sampling-distribution-and-the-central-limit-theorem"><span class="header-section-number">6.4</span> Sampling Distribution and the Central Limit Theorem</a>
  <ul class="collapse">
  <li><a href="#example-sampling-distribution" id="toc-example-sampling-distribution" class="nav-link" data-scroll-target="#example-sampling-distribution"><span class="header-section-number">6.4.1</span> Example: Sampling Distribution</a></li>
  <li><a href="#central-limit-theorem" id="toc-central-limit-theorem" class="nav-link" data-scroll-target="#central-limit-theorem"><span class="header-section-number">6.4.2</span> <strong>Central Limit Theorem</strong></a></li>
  <li><a href="#example-finding-probabilities-for-sample-means" id="toc-example-finding-probabilities-for-sample-means" class="nav-link" data-scroll-target="#example-finding-probabilities-for-sample-means"><span class="header-section-number">6.4.3</span> Example: Finding Probabilities for Sample Means</a></li>
  <li><a href="#example-finding-probabilities-for-sample-means-1" id="toc-example-finding-probabilities-for-sample-means-1" class="nav-link" data-scroll-target="#example-finding-probabilities-for-sample-means-1"><span class="header-section-number">6.4.4</span> Example: Finding Probabilities for Sample Means</a></li>
  <li><a href="#homework-for-sampling-distribution-and-the-central-limit-theorem-section" id="toc-homework-for-sampling-distribution-and-the-central-limit-theorem-section" class="nav-link" data-scroll-target="#homework-for-sampling-distribution-and-the-central-limit-theorem-section"><span class="header-section-number">6.4.5</span> Homework for Sampling Distribution and the Central Limit Theorem Section</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Continuous Probability Distribution</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Chapter 5 dealt with probability distributions arising from discrete random variables. Mostly that chapter focused on the binomial experiment. There are many other experiments from discrete random variables that exist but are not covered in this book.</p>
<p>Chapter 6 deals with probability distributions that arise from continuous random variables. The focus of this chapter is a distribution known as the normal distribution, though realize that there are many other distributions that exist. A few others are examined in future chapters.</p>
<p>Looking at the density plot of a quantitative variable, one can guess what the distribution of that variable is. As an example, consider the NHANES data frame. One variable to consider is Weight. The density plot of Weight is</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-density-cap" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Density plot of a person's weight. Appears to be symmetric, and maybe bell shaped">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-density-cap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Continuous-Probability-Distribution_files/figure-html/fig-density-cap-1.png" class="img-fluid figure-img" alt="Density plot of a person's weight. Appears to be symmetric, and maybe bell shaped" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-density-cap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: Density plot of the Weight of a Person
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-density-cap" class="quarto-xref">Figure&nbsp;<span>6.1</span></a> looks somewhat symmetric, and maybe bell shaped.</p>
<p>Consider, the variable head circumference (HeadCirc) in the NHANES data frame. The density plot for this variable is <a href="#fig-HeadCirc-density" class="quarto-xref">Figure&nbsp;<span>6.2</span></a></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-HeadCirc-density" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Density plot of head circumference of a person. Appears to be skewed left.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-HeadCirc-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Continuous-Probability-Distribution_files/figure-html/fig-HeadCirc-density-1.png" class="img-fluid figure-img" alt="Density plot of head circumference of a person. Appears to be skewed left." width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-HeadCirc-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.2: Density plot of head circumference of a person
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-HeadCirc-density" class="quarto-xref">Figure&nbsp;<span>6.2</span></a> looks somewhat skewed left.</p>
<p>Now consider the variable BMI from the NHANES data frame. The density plot is</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-BMI-density" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Density plot of BMI of a person that is skewed right.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-BMI-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Continuous-Probability-Distribution_files/figure-html/fig-BMI-density-1.png" class="img-fluid figure-img" alt="Density plot of BMI of a person that is skewed right." width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-BMI-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.3: Density Plot of BMI of a Person
</figcaption>
</figure>
</div>
</div>
</div>
<p>This density plot <a href="Estimation.html#fig-BMI-density" class="quarto-xref">Figure&nbsp;<span>8.1</span></a> appears to be skewed right</p>
<p>Now consider the variable SmokeAge. Its density plot is <a href="#fig-Smoking-density" class="quarto-xref">Figure&nbsp;<span>6.4</span></a></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-Smoking-density" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Density plot of age when a person started smoking. Appears to be bimodal.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-Smoking-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Continuous-Probability-Distribution_files/figure-html/fig-Smoking-density-1.png" class="img-fluid figure-img" alt="Density plot of age when a person started smoking. Appears to be bimodal." width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-Smoking-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.4: Density Plot of Age when Person Started Smoking
</figcaption>
</figure>
</div>
</div>
</div>
<p>This distribution appears to be bimodal.</p>
<p>lastly, consider the variable Pulse. The density plot is <a href="#fig-Pulse-density" class="quarto-xref">Figure&nbsp;<span>6.5</span></a></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-Pulse-density" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Density plot of pulse rate of a person. Appears to be symmetric.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-Pulse-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Continuous-Probability-Distribution_files/figure-html/fig-Pulse-density-1.png" class="img-fluid figure-img" alt="Density plot of pulse rate of a person. Appears to be symmetric." width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-Pulse-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.5: Density Plot of Pulse Rate of a person
</figcaption>
</figure>
</div>
</div>
</div>
<p>This density plot appears to be symmetric and could almost be considered bell shaped.</p>
<p>The reason that one considers the density plots to understand the distribution of the population, is that in some cases the distribution can be approximated with a known distribution that has certain properties. There are many known distribution. Some examples are the Uniform distribution, the Chi-Squared distribution, the Student’s T distribution, and the normal distribution. The normal distribution is one of the more common distributions to use as a model, and it will be explored in this chapter. But do realize that there are many other distributions that one can use.</p>
<section id="normal-distribution" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="normal-distribution"><span class="header-section-number">6.1</span> Normal Distribution</h2>
<p>Many populations have a distribution that is a symmetric, unimodal, and bell-shaped. For example: height, blood pressure, and cholesterol level. However, not every bell shaped curve is a normal curve. In a normal curve, there is a specific relationship between its “height” and its “width.” Normal curves can be tall and skinny or they can be short and fat. They are all symmetric, unimodal, and centered at <span class="math inline">\(\mu\)</span>, the population mean.</p>
<p><a href="#fig-normal-curvea" class="quarto-xref">Figure&nbsp;<span>6.6</span></a> and <a href="#fig-normal-curveb" class="quarto-xref">Figure&nbsp;<span>6.7</span></a> show two different normal curves drawn on the same scale. Both have <span class="math inline">\(\mu=2\)</span> but the one in <a href="#fig-normal-curvea" class="quarto-xref">Figure&nbsp;<span>6.6</span></a> has a standard deviation of 1 and the one in <a href="#fig-normal-curveb" class="quarto-xref">Figure&nbsp;<span>6.7</span></a> has a standard deviation of 4. Notice that the larger standard deviation makes the graph wider (more spread out) and shorter.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-normal-curvea" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Bell curve with mean 2 and standard deviation of 1">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-normal-curvea-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Continuous-Probability-Distribution_files/figure-html/fig-normal-curvea-1.png" class="img-fluid figure-img" alt="Bell curve with mean 2 and standard deviation of 1" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-normal-curvea-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.6: Normal curve with mean 2 and standard deviation 1
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-normal-curveb" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Bell curve with mean 2 and standard deviation of 4">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-normal-curveb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Continuous-Probability-Distribution_files/figure-html/fig-normal-curveb-1.png" class="img-fluid figure-img" alt="Bell curve with mean 2 and standard deviation of 4" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-normal-curveb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.7: Normal curve with mean 2 and standard deviation 4
</figcaption>
</figure>
</div>
</div>
</div>
<p>Every normal curve has common features.</p>
<ul>
<li>The center, or the highest point, is at the population mean, <span class="math inline">\(\mu\)</span>.</li>
<li>The transition points are the places where the curve changes from a “hill” to a “valley”. The distance from the mean to the transition point is one standard deviation.</li>
<li>The area under the whole curve is exactly 1. Therefore, the area under the half below or above the mean is 0.5.</li>
</ul>
<p>Just as in a discrete probability distribution, the object is to find the probability of an event occurring. However, unlike in a discrete probability distribution where the event can be a single value, in a continuous probability distribution the event must be a range. You are interested in finding the probability of <span class="math inline">\(x\)</span> occurring in the range between <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>, or <span class="math inline">\(P(a \le x \le b) = P(a&lt;x&lt;b)\)</span>. Calculus tells us this probability is the area under the curve in the interval from <span class="math inline">\(a\)</span> to <span class="math inline">\(b\)</span>.</p>
<p>Before looking at the process for finding the probabilities under the normal curve, it is somewhat useful to look at the <strong>Empirical Rule</strong> that gives approximate values for these areas. The Empirical Rule is just an approximation and it will only be used in this section to give you an idea of what the size of the probabilities is for different shadings. A more precise method for finding probabilities for the normal curve will be demonstrated in the next section. Please do not use the empirical rule except for real rough estimates.</p>
<p><strong>The Empirical Rule</strong> for any normal distribution: Approximately 68% of the data is within one standard deviation of the mean. Approximately 95% of the data is within two standard deviations of the mean. Approximately 99.7% of the data is within three standard deviations of the mean.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Empirical_rule.png" class="img-fluid figure-img" alt="Empirical Rule graph with 68% of data between -1 and 1 standard deviation of mean, 95% between -2 and 2, and 99.7% between -3 and 3"></p>
<figcaption>Empirical Rule Graph</figcaption>
</figure>
</div>
<p>Be careful, there is still some area left over in each end. Remember, the maximum a probability can be is 100%, so if you calculate you will see that for both ends together there is 0.3% of the curve. Because of symmetry, you can divide this equally between both ends and find that there is 0.15% in each tail beyond the 3rd standard deviations.</p>
</section>
<section id="finding-probabilities-for-the-normal-distribution" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="finding-probabilities-for-the-normal-distribution"><span class="header-section-number">6.2</span> Finding Probabilities for the Normal Distribution</h2>
<p>The Empirical Rule is just an approximation and only works for certain values. What if you want to find the probability for <span class="math inline">\(x\)</span> values that are not integer multiples of the standard deviation? The probability is the area under the curve. To find areas under the curve, you need calculus. Before technology, you needed to convert every <span class="math inline">\(x\)</span> value to a standardized number, called the <span class="math inline">\(z\)</span>-score or <span class="math inline">\(z\)</span>-value or simply just <span class="math inline">\(z\)</span>. The <span class="math inline">\(z\)</span>-score is a measure of how many standard deviations an <span class="math inline">\(x\)</span> value is from the mean. To convert from a normally distributed <span class="math inline">\(x\)</span> value to a <span class="math inline">\(z\)</span>-score, you use the following formula.</p>
<p><span class="math inline">\(z-score=\frac{x-\mu}{\sigma}\)</span></p>
<p>where <span class="math inline">\(\mu\)</span> = mean of the population of the <span class="math inline">\(x\)</span> value and <span class="math inline">\(\sigma\)</span> = standard deviation for the population of the <span class="math inline">\(x\)</span> value</p>
<p>The <span class="math inline">\(z\)</span>-score is normally distributed, with a mean of 0 and a standard deviation of 1. It is known as the standard normal curve. The <span class="math inline">\(z\)</span>-score is a measure of how many standard deviations a data value is from its mean. If the <span class="math inline">\(z\)</span> - score is positive, the data value is above the mean. If the <span class="math inline">\(z\)</span>-score is negative, the data value is below the mean. The farther the <span class="math inline">\(z\)</span>-value is from 0, the farther the data value is from the mean.</p>
<p>These days technology can find probabilities without converting to the <span class="math inline">\(z\)</span>-score and looking the probabilities up in a table. There are many programs available that will calculate the probability for a normal curve. The command on r to find the area to the left <span class="math inline">\(P(x&lt;value)\)</span> is</p>
<p>pnorm(value, mean, standard_deviation, lower.tail=TRUE)</p>
<p>The command on r to find the area to the right, <span class="math inline">\(P(x&gt;value)\)</span> is</p>
<p>pnorm(value, mean, standard_deviation, lower.tail=FALSE)</p>
<section id="example-general-normal-distribution" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="example-general-normal-distribution"><span class="header-section-number">6.2.1</span> Example: General Normal Distribution</h3>
<p>The length of a human pregnancy is normally distributed with a mean of 272 days with a standard deviation of 9 days (Bhat &amp; Kushtagi, 2006).</p>
<ol type="a">
<li>State the random variable</li>
<li>Find the probability of a pregnancy lasting more than 280 days.</li>
<li>Find the probability of a pregnancy lasting less than 250 days.</li>
<li>Find the probability that a pregnancy lasts between 265 and 280 days.</li>
<li>Find the length of pregnancy that 10% of all pregnancies last less than.</li>
<li>Suppose you meet a woman who says that she was pregnant for less than 250 days. Would this be unusual and what might you think?</li>
</ol>
<section id="solution" class="level4" data-number="6.2.1.1">
<h4 data-number="6.2.1.1" class="anchored" data-anchor-id="solution"><span class="header-section-number">6.2.1.1</span> <strong>Solution</strong></h4>
<ol type="a">
<li>State the random variable.</li>
</ol>
<p><span class="math inline">\(x\)</span> = length of a human pregnancy</p>
<ol start="2" type="a">
<li>Find the probability of a pregnancy lasting more than 280 days.</li>
</ol>
<p>First translate the statement into a mathematical statement. <span class="math inline">\(P(x&gt;280)\)</span></p>
<p>Now, draw a picture <a href="#fig-normal-curve61" class="quarto-xref">Figure&nbsp;<span>6.8</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-normal-curve61" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Density plot of pregnancy length. Normally distributed with mean 272 and standard deviation 9. Shaded above 280">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-normal-curve61-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Continuous-Probability-Distribution_files/figure-html/fig-normal-curve61-1.png" class="img-fluid figure-img" alt="Density plot of pregnancy length. Normally distributed with mean 272 and standard deviation 9. Shaded above 280" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-normal-curve61-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.8: Normally distributed with mean 272 and standard deviation 9, and P(x&gt;280)
</figcaption>
</figure>
</div>
</div>
</div>
<p>The probability of a pregnancy lasting longer than 280 days is <span class="math inline">\(P(x&gt;280)=0.187\)</span>. The command in rStudio is</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">280</span>, <span class="dv">272</span>, <span class="dv">9</span>, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1870314</code></pre>
</div>
</div>
<p>Thus 18.7% of all pregnancies last more than 280 days. This is not unusual since the probability is greater than 5%.</p>
<ol start="3" type="a">
<li>Find the probability of a pregnancy lasting less than 250 days.</li>
</ol>
<p>First translate the statement into a mathematical statement. <span class="math inline">\(P(x&lt;250)\)</span></p>
<p>Now, draw a picture <a href="#fig-normal-curve62" class="quarto-xref">Figure&nbsp;<span>6.9</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-normal-curve62" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Density plot of pregnancy length. Normally distributed with mean 272 and standard deviation 9. Shaded below 250">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-normal-curve62-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Continuous-Probability-Distribution_files/figure-html/fig-normal-curve62-1.png" class="img-fluid figure-img" alt="Density plot of pregnancy length. Normally distributed with mean 272 and standard deviation 9. Shaded below 250" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-normal-curve62-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.9: Density plot of pregnancy length. Normally distributed with mean 272 and standard deviation 9, and P(x&lt;250)
</figcaption>
</figure>
</div>
</div>
</div>
<p>The probability of a pregnancy lasting longer than 250 days is <span class="math inline">\(P(x&lt;250)=0.0073\)</span>. The command in r Studio is</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">250</span>, <span class="dv">272</span>, <span class="dv">9</span>, <span class="at">lower.tail=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.007253771</code></pre>
</div>
</div>
<p>Thus 0.73% of all pregnancies last less than 250 days. This is unusual since the probability is less than 5%.</p>
<ol start="4" type="a">
<li>Find the probability that a pregnancy lasts between 265 and 280 days.</li>
</ol>
<p>First translate the statement into a mathematical statement. <span class="math inline">\(P(265&lt;x&lt;280)\)</span></p>
<p>Now draw a picture <a href="#fig-normal-curve63" class="quarto-xref">Figure&nbsp;<span>6.10</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-normal-curve63" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Density plot of pregnancy length. Normally distributed with mean 272 and standard deviation 9. Shaded from 265 to 280">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-normal-curve63-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Continuous-Probability-Distribution_files/figure-html/fig-normal-curve63-1.png" class="img-fluid figure-img" alt="Density plot of pregnancy length. Normally distributed with mean 272 and standard deviation 9. Shaded from 265 to 280" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-normal-curve63-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.10: Density plot of pregnancy length. Normally distributed with mean 272 and standard deviation 9, and P(265&lt;x&lt;280)
</figcaption>
</figure>
</div>
</div>
</div>
<p>The probability of a pregnancy lasting between 265 days and 280 days is <span class="math inline">\(P(265&lt;x&lt;280)=0.187\)</span>. To find the area between two values on the normal distribution, first, find the area to the left of the lower value, Graphically, this looks like <a href="#fig-normal-curve-preg" class="quarto-xref">Figure&nbsp;<span>6.11</span></a></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-normal-curve-preg" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Density plot of pregnancy length. Normally distributed with mean 272 and standard deviation 9. Shaded below 265">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-normal-curve-preg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Continuous-Probability-Distribution_files/figure-html/fig-normal-curve-preg-1.png" class="img-fluid figure-img" alt="Density plot of pregnancy length. Normally distributed with mean 272 and standard deviation 9. Shaded below 265" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-normal-curve-preg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.11: Density plot of pregnancy length. Normally distributed with mean 272 and standard deviation 9, and P(x&lt;265)
</figcaption>
</figure>
</div>
</div>
</div>
<p>Now find the area less than 280. Graphically this looks like <a href="#fig-normal-curve-preg1" class="quarto-xref">Figure&nbsp;<span>6.12</span></a></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-normal-curve-preg1" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Density plot of pregnancy length. Normally distributed with mean 272 and standard deviation 9. Shaded below 280">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-normal-curve-preg1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Continuous-Probability-Distribution_files/figure-html/fig-normal-curve-preg1-1.png" class="img-fluid figure-img" alt="Density plot of pregnancy length. Normally distributed with mean 272 and standard deviation 9. Shaded below 280" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-normal-curve-preg1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.12: Density plot of pregnancy length. Normally distributed with mean 272 and standard deviation 9, and P(x&lt;280)
</figcaption>
</figure>
</div>
</div>
</div>
<p>Looking at the three figures, if you take the area in <a href="#fig-normal-curve-preg1" class="quarto-xref">Figure&nbsp;<span>6.12</span></a> and subtract the area in <a href="#fig-normal-curve-preg" class="quarto-xref">Figure&nbsp;<span>6.11</span></a> you get the area in <a href="#fig-normal-curve63" class="quarto-xref">Figure&nbsp;<span>6.10</span></a>. In rStudio, the way to find the probability the probability of a pregnancy lasting between 265 days and 280 days, <span class="math inline">\(P(265&lt;x&lt;280)=0.595\)</span> use the following command</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">280</span>, <span class="dv">272</span>, <span class="dv">9</span>, <span class="at">lower.tail=</span><span class="cn">TRUE</span>)<span class="sc">-</span><span class="fu">pnorm</span>(<span class="dv">265</span>, <span class="dv">272</span>, <span class="dv">9</span>, <span class="at">lower.tail=</span><span class="cn">TRUE</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5946186</code></pre>
</div>
</div>
<p>Thus 59.5% of all pregnancies last between 265 and 280 days.</p>
<ol start="5" type="a">
<li>Find the length of pregnancy that 10% of all pregnancies last less than.</li>
</ol>
<p>This problem is asking you to find an <span class="math inline">\(x\)</span> value from a probability. You want to find the <span class="math inline">\(x\)</span> value that has 10% of the length of pregnancies to the left of it. In this case, you are given the probability. In r, the command is</p>
<p>qnorm(area, mean, standard_deviation, lower.tail=TRUE or FALSE)</p>
<p>For this example since you know the area in the lower tail, then use lower.tail=TRUE. So the command is</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.1</span>, <span class="dv">272</span>, <span class="dv">9</span>, <span class="at">lower.tail =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 260.466</code></pre>
</div>
</div>
<p>Thus 10% of all pregnancies last less than approximately 260 days.</p>
<ol start="6" type="a">
<li>Suppose you meet a woman who says that she was pregnant for less than 250 days. Would this be unusual and what might you think?</li>
</ol>
<p>From part (c) you found the probability that a pregnancy lasts less than 250 days is 0.73%. Since this is less than 5%, it is very unusual. You would think that either the woman had a premature baby, or that she may be wrong about when she actually became pregnant.</p>
</section>
</section>
<section id="example-general-normal-distribution-1" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="example-general-normal-distribution-1"><span class="header-section-number">6.2.2</span> Example: General Normal Distribution</h3>
<p>The mean mathematics SAT score in 2012 was 514 with a standard deviation of 117 (“Total group profile,” 2012). Assume the mathematics SAT score is normally distributed.</p>
<ol type="a">
<li>State the random variable.</li>
<li>Find the probability that a person has a mathematics SAT score over 700.</li>
<li>Find the probability that a person has a mathematics SAT score of less than 400.</li>
<li>Find the probability that a person has a mathematics SAT score between a 500 and a 650.</li>
<li>Find the mathematics SAT score that represents the top 1% of all scores.</li>
</ol>
<section id="solution-1" class="level4" data-number="6.2.2.1">
<h4 data-number="6.2.2.1" class="anchored" data-anchor-id="solution-1"><span class="header-section-number">6.2.2.1</span> <strong>Solution</strong></h4>
<ol type="a">
<li>State the random variable.</li>
</ol>
<p><span class="math inline">\(x\)</span> = mathematics SAT score</p>
<ol start="2" type="a">
<li>Find the probability that a person has a mathematics SAT score over 700.</li>
</ol>
<p>First translate the statement into a mathematical statement. <span class="math inline">\(P(x&gt;700)\)</span></p>
<p>Now, draw a picture <a href="#fig-normal-curve-SAT" class="quarto-xref">Figure&nbsp;<span>6.13</span></a></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-normal-curve-SAT" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Density plot of SAT mathematics score. Normally distributed with mean 514 and standard deviation 117. Shaded above 700">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-normal-curve-SAT-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Continuous-Probability-Distribution_files/figure-html/fig-normal-curve-SAT-1.png" class="img-fluid figure-img" alt="Density plot of SAT mathematics score. Normally distributed with mean 514 and standard deviation 117. Shaded above 700" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-normal-curve-SAT-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.13: Density plot of SAT mathematics score. Normally distributed with mean 514 and standard deviation 117 and P(x&gt;700)
</figcaption>
</figure>
</div>
</div>
</div>
<p>To find <span class="math inline">\(P(x&gt;700)=0.0559\)</span>, the command in r would be</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">700</span>, <span class="dv">514</span>,<span class="dv">117</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.05594631</code></pre>
</div>
</div>
<p>There is a 5.6% chance that a person scored above a 700 on the mathematics SAT test. This is not unusual.</p>
<ol start="3" type="a">
<li>Find the probability that a person has a mathematics SAT score of less than 400.</li>
</ol>
<p>First translate the statement into a mathematical statement. <span class="math inline">\(P(x&lt;400)\)</span></p>
<p>Now, draw a picture <a href="#fig-normal-curve-SAT1" class="quarto-xref">Figure&nbsp;<span>6.14</span></a></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-normal-curve-SAT1" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Density plot of SAT mathematics score. Normally distributed with mean 514 and standard deviation 117. Shaded below 400">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-normal-curve-SAT1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Continuous-Probability-Distribution_files/figure-html/fig-normal-curve-SAT1-1.png" class="img-fluid figure-img" alt="Density plot of SAT mathematics score. Normally distributed with mean 514 and standard deviation 117. Shaded below 400" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-normal-curve-SAT1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.14: Density plot of SAT mathematics score. Normally distributed with mean 514 and standard deviation 117 and P(x&lt;400)
</figcaption>
</figure>
</div>
</div>
</div>
<p>To find <span class="math inline">\(P(x&lt;400)=0.165\)</span>, the command in r would be</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">400</span>, <span class="dv">514</span>, <span class="dv">117</span>, <span class="at">lower.tail =</span> <span class="cn">TRUE</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1649392</code></pre>
</div>
</div>
<p>So, there is a 16.5% chance that a person scores less than a 400 on the mathematics part of the SAT.</p>
<ol start="4" type="a">
<li>Find the probability that a person has a mathematics SAT score between a 500 and a 650.</li>
</ol>
<p>First translate the statement into a mathematical statement <span class="math inline">\(P(500&lt;x&lt;650)\)</span></p>
<p>Now, draw a picture <a href="#fig-normal-curve-SAT2" class="quarto-xref">Figure&nbsp;<span>6.15</span></a></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-normal-curve-SAT2" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Density plot of SAT mathematics score. Normally distributed with mean 514 and standard deviation 117. Shaded from 514 to 650">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-normal-curve-SAT2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Continuous-Probability-Distribution_files/figure-html/fig-normal-curve-SAT2-1.png" class="img-fluid figure-img" alt="Density plot of SAT mathematics score. Normally distributed with mean 514 and standard deviation 117. Shaded from 514 to 650" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-normal-curve-SAT2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.15: Density plot of SAT mathematics score. Normally distributed with mean 514 and standard deviation 117 and P(514&lt;x&lt;650)
</figcaption>
</figure>
</div>
</div>
</div>
<p>To find <span class="math inline">\(P(500&lt;x&lt;650)=0.425\)</span>, the command in r would be</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">650</span>, <span class="dv">514</span>, <span class="dv">117</span>, <span class="at">lower.tail =</span> <span class="cn">TRUE</span>)<span class="sc">-</span><span class="fu">pnorm</span>(<span class="dv">500</span>, <span class="dv">514</span>, <span class="dv">117</span>, <span class="at">lower.tail=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4250851</code></pre>
</div>
</div>
<p>So, there is a 42.5% chance that a person has a mathematical SAT score between 500 and 650.</p>
<ol start="5" type="a">
<li>Find the mathematics SAT score that represents the top 1% of all scores.</li>
</ol>
<p>This problem is asking you to find an <span class="math inline">\(x\)</span> value from a probability. You want to find the <span class="math inline">\(x\)</span> value that has 1% of the mathematics SAT scores to the right of it. In this case you are using the upper tail of the curve. To find this <span class="math inline">\(x\)</span> value on rStudio, use the command</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.01</span>, <span class="dv">514</span>, <span class="dv">117</span>, <span class="at">lower.tail=</span><span class="cn">FALSE</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 786.1827</code></pre>
</div>
</div>
<p>So, 1% of all people who took the SAT scored over about 786 points on the mathematics SAT.</p>
</section>
</section>
<section id="homework-for-normal-distribution-section" class="level3" data-number="6.2.3">
<h3 data-number="6.2.3" class="anchored" data-anchor-id="homework-for-normal-distribution-section"><span class="header-section-number">6.2.3</span> Homework for Normal Distribution Section</h3>
<ol type="1">
<li>Find each of the probabilities, where <span class="math inline">\(z\)</span> is a <span class="math inline">\(z\)</span>-score from the standard normal distribution with mean of <span class="math inline">\(\mu=0\)</span> and standard deviation <span class="math inline">\(\sigma=1\)</span>. It helps to draw a picture for each problem.</li>
</ol>
<!-- -->
<ol type="a">
<li><span class="math inline">\(P(z&lt;2.36)\)</span></li>
<li><span class="math inline">\(P(z&gt;0.67)\)</span></li>
<li><span class="math inline">\(P(0&lt;x&lt;2.11)\)</span></li>
<li><span class="math inline">\(P(-2.78&lt;z&lt;1.97)\)</span></li>
</ol>
<!-- -->
<ol start="2" type="1">
<li>Find the <em>z</em>-score corresponding to the given area. Remember, <em>z</em> is distributed as the standard normal distribution with mean of <span class="math inline">\(\mu=0\)</span> and standard deviation <span class="math inline">\(\sigma=1\)</span>.</li>
</ol>
<!-- -->
<ol type="a">
<li><p>The area to the left of <span class="math inline">\(z\)</span> is 15%.</p></li>
<li><p>The area to the right of <span class="math inline">\(z\)</span> is 65%.</p></li>
<li><p>The area to the left of <span class="math inline">\(z\)</span> is 10%.</p></li>
<li><p>The area to the right of <span class="math inline">\(z\)</span> is 5%.</p></li>
<li><p>The area between <span class="math inline">\(-z\)</span> and <span class="math inline">\(z\)</span> is 95%. (Hint draw a picture and figure out the area to the left of <span class="math inline">\(-z\)</span>.)</p></li>
<li><p>The area between <span class="math inline">\(-z\)</span> and <span class="math inline">\(z\)</span> is 99%.</p></li>
</ol>
<!-- -->
<ol start="3" type="1">
<li>If a random variable that is normally distributed has a mean of 25 and a standard deviation of 3, convert the given value to a <span class="math inline">\(z\)</span>-score.</li>
</ol>
<!-- -->
<ol type="a">
<li><span class="math inline">\(x\)</span> = 23</li>
<li><span class="math inline">\(x\)</span> = 33</li>
<li><span class="math inline">\(x\)</span> = 19</li>
<li><span class="math inline">\(x\)</span> = 45</li>
</ol>
<!-- -->
<ol start="4" type="1">
<li>According to the WHO MONICA Project the mean blood pressure for people in China is 128 mmHg with a standard deviation of 23 mmHg (Kuulasmaa, Hense &amp; Tolonen, 1998). Assume that blood pressure is normally distributed.</li>
</ol>
<!-- -->
<ol type="a">
<li>State the random variable.</li>
<li>Find the probability that a person in China has blood pressure of 135 mmHg or more.</li>
<li>Find the probability that a person in China has blood pressure of 141 mmHg or less.</li>
<li>Find the probability that a person in China has blood pressure between 120 and 125 mmHg.</li>
<li>Is it unusual for a person in China to have a blood pressure of 135 mmHg? Why or why not?</li>
<li>What blood pressure do 90% of all people in China have less than?</li>
</ol>
<!-- -->
<ol start="5" type="1">
<li>The size of fish is very important to commercial fishing. A study conducted in 2012 found the length of Atlantic cod caught in nets in Karlskrona to have a mean of 49.9 cm and a standard deviation of 3.74 cm (Ovegard, Berndt &amp; Lunneryd, 2012). Assume the length of fish is normally distributed.</li>
</ol>
<!-- -->
<ol type="a">
<li>State the random variable.</li>
<li>Find the probability that an Atlantic cod has a length less than 52 cm.</li>
<li>Find the probability that an Atlantic cod has a length of more than 74 cm.</li>
<li>Find the probability that an Atlantic cod has a length between 40.5 and 57.5 cm.</li>
<li>If you found an Atlantic cod to have a length of more than 74 cm, what could you conclude?</li>
<li>What length are 15% of all Atlantic cod longer than?</li>
</ol>
<!-- -->
<ol start="6" type="1">
<li>The mean cholesterol levels of women age 45-59 in Ghana, Nigeria, and Seychelles is 5.1 mmol/l and the standard deviation is 1.0 mmol/l (Lawes, Hoorn, Law &amp; Rodgers, 2004). Assume that cholesterol levels are normally distributed.</li>
</ol>
<!-- -->
<ol type="a">
<li>State the random variable.</li>
<li>Find the probability that a woman age 45-59 in Ghana, Nigeria, or Seychelles has a cholesterol level above 6.2 mmol/l (considered a high level).</li>
<li>Find the probability that a woman age 45-59 in Ghana, Nigeria, or Seychelles has a cholesterol level below 5.2 mmol/l (considered a normal level).</li>
<li>Find the probability that a woman age 45-59 in Ghana, Nigeria, or Seychelles has a cholesterol level between 5.2 and 6.2 mmol/l (considered borderline high).</li>
<li>If you found a woman age 45-59 in Ghana, Nigeria, or Seychelles having a cholesterol level above 6.2 mmol/l, what could you conclude?</li>
<li>What value do 5% of all woman ages 45-59 in Ghana, Nigeria, or Seychelles have a cholesterol level less than?</li>
</ol>
<!-- -->
<ol start="7" type="1">
<li>In the United States, males between the ages of 40 and 49 eat on average 103.1 g of fat every day with a standard deviation of 4.32 g (“What we eat,” 2012). Assume that the amount of fat a person eats is normally distributed.</li>
</ol>
<!-- -->
<ol type="a">
<li>State the random variable.</li>
<li>Find the probability that a man age 40-49 in the U.S. eats more than 110 g of fat every day.</li>
<li>Find the probability that a man age 40-49 in the U.S. eats less than 93 g of fat every day.</li>
<li>Find the probability that a man age 40-49 in the U.S. eats less than 65 g of fat every day.</li>
<li>If you found a man age 40-49 in the U.S. who says he eats less than 65 g of fat every day, would you believe him? Why or why not?</li>
<li>What daily fat level do 5% of all men age 40-49 in the U.S. eat more than?</li>
</ol>
<!-- -->
<ol start="8" type="1">
<li>A dishwasher has a mean life of 12 years with an estimated standard deviation of 1.25 years (“Appliance life expectancy,” 2013). Assume the life of a dishwasher is normally distributed.</li>
</ol>
<!-- -->
<ol type="a">
<li>State the random variable.</li>
<li>Find the probability that a dishwasher will last more than 15 years.</li>
<li>Find the probability that a dishwasher will last less than 6 years.</li>
<li>Find the probability that a dishwasher will last between 8 and 10 years.</li>
<li>If you found a dishwasher that lasted less than 6 years, would you think that you have a problem with the manufacturing process? Why or why not?</li>
<li>A manufacturer of dishwashers only wants to replace free of charge 5% of all dishwashers. How long should the manufacturer make the warranty period?</li>
</ol>
<!-- -->
<ol start="9" type="1">
<li>The mean starting salary for nurses is \$67,694 nationally (“Staff nurse -,” 2013). The standard deviation is approximately $10,333. Assume that the starting salary is normally distributed.</li>
</ol>
<!-- -->
<ol type="a">
<li>State the random variable.</li>
<li>Find the probability that a starting nurse will make more than \$80,000.</li>
<li>Find the probability that a starting nurse will make less than \$60,000.</li>
<li>Find the probability that a starting nurse will make between \$55,000 and \$72,000.</li>
<li>If a nurse made less than \$50,000, would you think the nurse was under paid? Why or why not?</li>
<li>What salary do 30% of all nurses make more than?</li>
</ol>
<!-- -->
<ol start="10" type="1">
<li>The mean yearly rainfall in Sydney, Australia, is about 137 mm and the standard deviation is about 69 mm (“Annual maximums of,”2013). Assume rainfall is normally distributed.</li>
</ol>
<!-- -->
<ol type="a">
<li>State the random variable.</li>
<li>Find the probability that the yearly rainfall is less than 100 mm.</li>
<li>Find the probability that the yearly rainfall is more than 240 mm.</li>
<li>Find the probability that the yearly rainfall is between 140 and 250 mm.</li>
<li>If a year has a rainfall less than 100mm, does that mean it is an unusually dry year? Why or why not?</li>
<li>What rainfall amount are 90% of all yearly rainfalls more than?</li>
</ol>
</section>
</section>
<section id="assessing-normality" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="assessing-normality"><span class="header-section-number">6.3</span> Assessing Normality</h2>
<p>The distributions you have seen up to this point have been assumed to be normally distributed, but how do you determine if it is normally distributed. One way is to take a sample and look at the sample to determine if it appears normal. If the sample looks normal, then most likely the population is also. Here are some guidelines that are use to help make that determination.</p>
<ol type="1">
<li><p><strong>Density Plot</strong>: Make a density plot. For a normal distribution, the density plot should be roughly bell-shaped. For small samples, this is not very accurate, and another method is needed. A distribution may not look normally distributed from the density plot, but it still may be normally distributed.</p></li>
<li><p><strong>Normal quantile plot (or normal probability plot)</strong>: This plot is provided through statistical software on a computer. If the points lie close to a line, the data comes from a distribution that is approximately normally distributed. If the points do not lie close to a line or they show a pattern that is not a line, the data are likely to come from a distribution that is not normally distributed.</p></li>
</ol>
<section id="to-create-a-density-plot-on-rstudio" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="to-create-a-density-plot-on-rstudio"><span class="header-section-number">6.3.1</span> <strong>To create a density plot on rStudio:</strong></h3>
<p>Read the Data Frame into r Studio. The command for density is</p>
<p>gf_density(~variable, data=Data_Frame)</p>
<p>See chapter 2 for more examples of this.</p>
</section>
<section id="to-create-a-normal-quantile-plot-on-rstudio" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="to-create-a-normal-quantile-plot-on-rstudio"><span class="header-section-number">6.3.2</span> <strong>To create a normal quantile plot on rStudio</strong></h3>
<p>Read the Data Frame into rStudio. The command for normal quantile plot is</p>
<p>gf_qqnorm(~variable, data=Data_Frame)</p>
<p>Realize that your random variable may be normally distributed, even if the sample fails the two tests. However, if the density plot definitely doesn’t look symmetric and bell shaped, and the normal probability plot doesn’t look linear, then you can be fairly confident that the data set does not come from a population that is normally distributed.</p>
</section>
<section id="example-is-it-normal" class="level3" data-number="6.3.3">
<h3 data-number="6.3.3" class="anchored" data-anchor-id="example-is-it-normal"><span class="header-section-number">6.3.3</span> Example: Is It Normal?</h3>
<p>In Kiama, NSW, Australia, there is a blowhole. The data in <a href="#tbl-Eruption" class="quarto-xref">Table&nbsp;<span>6.1</span></a> are times in seconds between eruptions (“Kiama blowhole eruptions,” 2013). Do the data come from a population that is normally distributed?</p>
<div class="cell" data-tbl-alt="Time (in Seconds) Between Kiama Blowhole Eruptions">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>Eruption<span class="ot">&lt;-</span><span class="fu">read.csv</span>( <span class="st">"https://krkozak.github.io/MAT160/Blowhole_eruptions.csv"</span>) </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(Eruption))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-Eruption" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Time (in Seconds) Between Kiama Blowhole Eruptions">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Eruption-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.1: Time (in Seconds) Between Kiama Blowhole Eruptions
</figcaption>
<div aria-describedby="tbl-Eruption-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Interval</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">83</td>
</tr>
<tr class="even">
<td style="text-align: right;">51</td>
</tr>
<tr class="odd">
<td style="text-align: right;">87</td>
</tr>
<tr class="even">
<td style="text-align: right;">60</td>
</tr>
<tr class="odd">
<td style="text-align: right;">28</td>
</tr>
<tr class="even">
<td style="text-align: right;">95</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><strong>Code book for Data Frame Eruption</strong></p>
<p><strong>Description</strong> The ocean swell produces spectacular eruptions of water through a hole in the cliff at Kiama, about 120km south of Sydney, known as the Blowhole. The times at which 65 successive eruptions occurred from 1340 hours on 12 July 1998 were observed using a digital watch.</p>
<p>Format This data frame contains the following columns:</p>
<p>Interval: Waiting time between eruptions (seconds)</p>
<p>Source Kiama Blowhole Eruptions. (n.d.). Retrieved from http://www.statsci.org/data/oz/kiama.html</p>
<p>References The data was collected and contributed by Jim Irish, Faculty of Engineering, University of Technology, Sydney.</p>
<ol type="a">
<li>State the random variable</li>
<li>Draw a Density plot</li>
<li>Draw the normal quantile plot.</li>
<li>Do the data come from a population that is normally distributed?</li>
</ol>
<section id="solution-2" class="level4" data-number="6.3.3.1">
<h4 data-number="6.3.3.1" class="anchored" data-anchor-id="solution-2"><span class="header-section-number">6.3.3.1</span> <strong>Solution</strong></h4>
<ol type="a">
<li>State the random variable</li>
</ol>
<p><span class="math inline">\(x\)</span> = time in seconds between eruptions of Kiama Blowhole</p>
<ol start="2" type="a">
<li>Draw a Density plot</li>
</ol>
<p>The density plot produced is in <a href="#fig-blowhole-density" class="quarto-xref">Figure&nbsp;<span>6.16</span></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_density</span>(<span class="sc">~</span>Interval, <span class="at">data=</span>Eruption, <span class="at">title=</span><span class="st">"Eruption times for Kiama Blowhole"</span>, <span class="at">xlab=</span><span class="st">"Time (seconds)"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-blowhole-density" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Density plot of eruption times for Kiama blowhole. Appears skewed right.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-blowhole-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Continuous-Probability-Distribution_files/figure-html/fig-blowhole-density-1.png" class="img-fluid figure-img" alt="Density plot of eruption times for Kiama blowhole. Appears skewed right." width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-blowhole-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.16: Density Plot of Eruption Times for Kiama Blowhole
</figcaption>
</figure>
</div>
</div>
</div>
<p>This looks skewed right and not symmetric.</p>
<ol start="3" type="a">
<li>Draw the normal quantile plot.</li>
</ol>
<p>The normal quantile plot is in <a href="#fig-blowhole-qq" class="quarto-xref">Figure&nbsp;<span>6.17</span></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_qq</span>(<span class="sc">~</span>Interval, <span class="at">data=</span>Eruption, <span class="at">title=</span><span class="st">"Eruption times for Kiama Blowhole"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-blowhole-qq" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Normal quantile plot of eruption times for Kiama blowhole. Appears exponential.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-blowhole-qq-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Continuous-Probability-Distribution_files/figure-html/fig-blowhole-qq-1.png" class="img-fluid figure-img" alt="Normal quantile plot of eruption times for Kiama blowhole. Appears exponential." width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-blowhole-qq-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.17: Normal Quantile Plot of Eruption Times for Kiama blowhole.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-blowhole-qq" class="quarto-xref">Figure&nbsp;<span>6.17</span></a> looks more like an exponential growth than linear.</p>
<ol start="4" type="a">
<li>Do the data come from a population that is normally distributed?</li>
</ol>
<p>Considering the density plot is skewed right, and the normal probability plot does not look linear, then the conclusion is that this sample is not from a population that is normally distributed.</p>
</section>
</section>
<section id="example-is-it-normal-1" class="level3" data-number="6.3.4">
<h3 data-number="6.3.4" class="anchored" data-anchor-id="example-is-it-normal-1"><span class="header-section-number">6.3.4</span> Example: Is It Normal?</h3>
<p>The US National Center for Health Statistics (NCHS) conducted a series of health and nutrition surveys called NHANES. One of the many variables in NHANES is pulse. Determine if pulse is a normally distributed variable. The NHANES data frame is <a href="Graphical Description of Data.html#tbl-NHANES" class="quarto-xref">Table&nbsp;<span>2.5</span></a>.</p>
<ol type="a">
<li>State the random variable</li>
<li>Draw a density plot</li>
<li>Draw the normal quantile plot.</li>
<li>Do the data come from a population that is normally distributed?</li>
</ol>
<section id="solution-3" class="level4" data-number="6.3.4.1">
<h4 data-number="6.3.4.1" class="anchored" data-anchor-id="solution-3"><span class="header-section-number">6.3.4.1</span> <strong>Solution</strong></h4>
<ol type="a">
<li>State the random variable</li>
</ol>
<p><span class="math inline">\(x\)</span> = pulse</p>
<ol start="2" type="a">
<li>Draw a density plot</li>
</ol>
<p>The density plot is in <a href="#fig-pulse-density" class="quarto-xref">Figure&nbsp;<span>6.18</span></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_density</span>(<span class="sc">~</span>Pulse, <span class="at">data=</span>NHANES, <span class="at">title=</span><span class="st">"Pulse Rate"</span>, <span class="at">xlab=</span><span class="st">"Pulse Rate (bpm)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-pulse-density" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Density plot of pulse rate. Appears to be bell shapped.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pulse-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Continuous-Probability-Distribution_files/figure-html/fig-pulse-density-1.png" class="img-fluid figure-img" alt="Density plot of pulse rate. Appears to be bell shapped." width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pulse-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.18: Density plot of Pulse Rate (bpm)
</figcaption>
</figure>
</div>
</div>
</div>
<p>This looks somewhat symmetric and bell shaped.</p>
<ol start="3" type="a">
<li>Draw the normal quantile plot.</li>
</ol>
<p>The normal quantile plot is in <a href="#fig-pulse-qq" class="quarto-xref">Figure&nbsp;<span>6.19</span></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_qq</span>(<span class="sc">~</span>Pulse, <span class="at">data=</span>NHANES, <span class="at">title=</span><span class="st">"Pulse Rate"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-pulse-qq" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Normal quantile plot of pulse rate. Appears to be linear.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pulse-qq-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Continuous-Probability-Distribution_files/figure-html/fig-pulse-qq-1.png" class="img-fluid figure-img" alt="Normal quantile plot of pulse rate. Appears to be linear." width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pulse-qq-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.19: Normal Quantile Plot of Pulse Rate (bmp)
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-pulse-qq" class="quarto-xref">Figure&nbsp;<span>6.19</span></a> looks fairly linear.</p>
<ol start="4" type="a">
<li>Do the data come from a population that is normally distributed?</li>
</ol>
<p>Considering the density plot is bell shaped and the normal probability plot looks linear. The conclusion is that this sample is from a population that is normally distributed.</p>
</section>
</section>
<section id="homework-for-assessing-normality-section" class="level3" data-number="6.3.5">
<h3 data-number="6.3.5" class="anchored" data-anchor-id="homework-for-assessing-normality-section"><span class="header-section-number">6.3.5</span> Homework for Assessing Normality Section</h3>
<ol type="1">
<li>Cholesterol data was collected on patients four days after having a heart attack. The data is in <a href="Numerical-description-of-Data.html#tbl-Cholesterol" class="quarto-xref">Table&nbsp;<span>3.2</span></a>. Assess if the data is from a population that is normally distributed.</li>
</ol>
<p><strong>Code Book for Cholesterol</strong> See is below <a href="Numerical-description-of-Data.html#tbl-Cholesterol" class="quarto-xref">Table&nbsp;<span>3.2</span></a>.</p>
<ol start="2" type="1">
<li>The size of fish is very important to commercial fishing. A study conducted in 2012 collected the lengths of Atlantic cod caught in nets in Karlskrona (Ovegard, Berndt &amp; Lunneryd, 2012). Data based on information from the study is in <a href="#tbl-Cod" class="quarto-xref">Table&nbsp;<span>6.2</span></a>. Determine if the data is from a population that is normally distributed.</li>
</ol>
<div class="cell" data-tbl-alt="Atlantic Cod Lengths">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>Cod<span class="ot">&lt;-</span><span class="fu">read.csv</span>( <span class="st">"https://krkozak.github.io/MAT160/cod.csv"</span>) </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(Cod))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-Cod" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Atlantic Cod Lengths">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Cod-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.2: Atlantic Cod Lengths
</figcaption>
<div aria-describedby="tbl-Cod-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">length</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">48</td>
</tr>
<tr class="even">
<td style="text-align: right;">50</td>
</tr>
<tr class="odd">
<td style="text-align: right;">50</td>
</tr>
<tr class="even">
<td style="text-align: right;">55</td>
</tr>
<tr class="odd">
<td style="text-align: right;">53</td>
</tr>
<tr class="even">
<td style="text-align: right;">50</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<ol start="3" type="1">
<li>The WHO MONICA Project collected blood pressure data for people in China (Kuulasmaa, Hense &amp; Tolonen, 1998). Data based on information from the study is in <a href="#tbl-BP" class="quarto-xref">Table&nbsp;<span>6.3</span></a>. Determine if the data is from a population that is normally distributed.</li>
</ol>
<div class="cell" data-tbl-alt="Blood Pressure Values for People in China">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>BP<span class="ot">&lt;-</span><span class="fu">read.csv</span>( <span class="st">"https://krkozak.github.io/MAT160/bp.csv"</span>) </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(BP))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-BP" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Blood Pressure Values for People in China">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-BP-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.3: Blood Pressure Values for People in China
</figcaption>
<div aria-describedby="tbl-BP-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">pressure</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">114</td>
</tr>
<tr class="even">
<td style="text-align: right;">141</td>
</tr>
<tr class="odd">
<td style="text-align: right;">154</td>
</tr>
<tr class="even">
<td style="text-align: right;">137</td>
</tr>
<tr class="odd">
<td style="text-align: right;">131</td>
</tr>
<tr class="even">
<td style="text-align: right;">132</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<ol start="4" type="1">
<li>Annual rainfalls for Sydney, Australia are given in <a href="#tbl-Annual" class="quarto-xref">Table&nbsp;<span>6.4</span></a> (“Annual maximums of,” 2013). Can you assume rainfall is normally distributed?</li>
</ol>
<div class="cell" data-tbl-alt="Annual Rainfall in Sydney, Australia">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>Annual<span class="ot">&lt;-</span><span class="fu">read.csv</span>( <span class="st">"https://krkozak.github.io/MAT160/annual.csv"</span>) </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(Annual))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-Annual" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Annual Rainfall in Sydney, Australia">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Annual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.4: Annual Rainfall in Sydney, Australia
</figcaption>
<div aria-describedby="tbl-Annual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">amount</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">146.8</td>
</tr>
<tr class="even">
<td style="text-align: right;">383.0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">90.9</td>
</tr>
<tr class="even">
<td style="text-align: right;">178.1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">267.5</td>
</tr>
<tr class="even">
<td style="text-align: right;">95.5</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
</section>
<section id="sampling-distribution-and-the-central-limit-theorem" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="sampling-distribution-and-the-central-limit-theorem"><span class="header-section-number">6.4</span> Sampling Distribution and the Central Limit Theorem</h2>
<p>You now have most of the skills to start statistical inference, but you need one more concept.</p>
<p>First, it would be helpful to state what statistical inference is in more accurate terms.</p>
<p><strong>Statistical Inference</strong>: to make accurate decisions about parameters from statistics</p>
<p>When it says “accurate decision,” you want to be able to measure how accurate. You measure how accurate using probability. In both binomial and normal distributions, you needed to know that the random variable followed either distribution. You need to know how the statistic is distributed and then you can find probabilities. In other words, you need to know the shape of the sample mean or whatever statistic you want to make a decision about.</p>
<p>How is the statistic distributed? This is answered with a sampling distribution.</p>
<p><strong>Sampling Distribution</strong>: how a sample statistic is distributed when repeated trials of size <span class="math inline">\(n\)</span> are taken.</p>
<section id="example-sampling-distribution" class="level3" data-number="6.4.1">
<h3 data-number="6.4.1" class="anchored" data-anchor-id="example-sampling-distribution"><span class="header-section-number">6.4.1</span> Example: Sampling Distribution</h3>
<p>The NHANES data frame has the pulse rates for approximately 50,000 individuals. The random variable is <span class="math inline">\(x\)</span> = pulse rate. The probability distribution of this random variable is presented in <a href="#fig-NHANES6h-density" class="quarto-xref">Figure&nbsp;<span>6.20</span></a>. Although pulse rates from 50,000 individuals isn’t the entire population, the sample is most likely a good representation of the population. Thus, it is safe to assume the population is normally distributed. An estimate for the population mean is 73.6 pbm, and the population standard deviation estimate is 12.2 bpm.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_density</span>(<span class="sc">~</span>Pulse, <span class="at">data=</span>NHANES, <span class="at">title =</span> <span class="st">"Pulse Rate"</span>, <span class="at">xlab=</span><span class="st">"Pulse (bpm)"</span>) </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">df_stats</span>(<span class="sc">~</span>Pulse, <span class="at">data=</span>NHANES, mean, sd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  response     mean       sd
1    Pulse 73.55973 12.15542</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-NHANES6h-density" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Density plot of pulse rate. Appears to be normally distributed.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-NHANES6h-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Continuous-Probability-Distribution_files/figure-html/fig-NHANES6h-density-1.png" class="img-fluid figure-img" alt="Density plot of pulse rate. Appears to be normally distributed." width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-NHANES6h-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.20: Distribution of Pulse Rate
</figcaption>
</figure>
</div>
</div>
</div>
<p>Suppose you take a random sample of 10 pulse rates from those 50,000 individuals. A random sample of data from 10 individuals is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>NHANES<span class="sc">|&gt;</span> </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample_n</span>(<span class="at">size=</span><span class="dv">10</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 76
      ID SurveyYr Gender   Age AgeDecade AgeMonths Race1 Race3 Education   
   &lt;int&gt; &lt;fct&gt;    &lt;fct&gt;  &lt;int&gt; &lt;fct&gt;         &lt;int&gt; &lt;fct&gt; &lt;fct&gt; &lt;fct&gt;       
 1 54769 2009_10  male      64 " 60-69"        768 White &lt;NA&gt;  College Grad
 2 61558 2009_10  male       2 " 0-9"           34 White &lt;NA&gt;  &lt;NA&gt;        
 3 52535 2009_10  male      43 " 40-49"        520 White &lt;NA&gt;  High School 
 4 60136 2009_10  female    26 " 20-29"        317 Other &lt;NA&gt;  Some College
 5 60566 2009_10  male      25 " 20-29"        311 White &lt;NA&gt;  Some College
 6 69502 2011_12  female    50 " 50-59"         NA White White College Grad
 7 58176 2009_10  male      73 " 70+"          884 White &lt;NA&gt;  Some College
 8 62235 2011_12  female     2 " 0-9"           NA White White &lt;NA&gt;        
 9 56368 2009_10  female    43 " 40-49"        519 White &lt;NA&gt;  High School 
10 55668 2009_10  male      21 " 20-29"        256 White &lt;NA&gt;  High School 
# ℹ 67 more variables: MaritalStatus &lt;fct&gt;, HHIncome &lt;fct&gt;, HHIncomeMid &lt;int&gt;,
#   Poverty &lt;dbl&gt;, HomeRooms &lt;int&gt;, HomeOwn &lt;fct&gt;, Work &lt;fct&gt;, Weight &lt;dbl&gt;,
#   Length &lt;dbl&gt;, HeadCirc &lt;dbl&gt;, Height &lt;dbl&gt;, BMI &lt;dbl&gt;,
#   BMICatUnder20yrs &lt;fct&gt;, BMI_WHO &lt;fct&gt;, Pulse &lt;int&gt;, BPSysAve &lt;int&gt;,
#   BPDiaAve &lt;int&gt;, BPSys1 &lt;int&gt;, BPDia1 &lt;int&gt;, BPSys2 &lt;int&gt;, BPDia2 &lt;int&gt;,
#   BPSys3 &lt;int&gt;, BPDia3 &lt;int&gt;, Testosterone &lt;dbl&gt;, DirectChol &lt;dbl&gt;,
#   TotChol &lt;dbl&gt;, UrineVol1 &lt;int&gt;, UrineFlow1 &lt;dbl&gt;, UrineVol2 &lt;int&gt;, …</code></pre>
</div>
</div>
<p>It might be useful to find the mean pulse rate from a random sample of size 10.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  response     mean
1    Pulse 65.42857</code></pre>
</div>
</div>
<p>Now suppose you took another random sample of size 10 and found the mean pulse rate for that sample. Repeat this process 100 times. At this point you would basically have a new sample of 100 mean pulse rates. You could assess how this sample is distributed by creating a density plot <a href="#fig-NHANES6e-density" class="quarto-xref">Figure&nbsp;<span>6.21</span></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>Trials <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">100</span>) <span class="sc">*</span> { NHANES <span class="sc">|&gt;</span> </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sample_n</span>(<span class="at">size =</span> <span class="dv">10</span>) <span class="sc">|&gt;</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">df_stats</span>( <span class="sc">~</span>Pulse, <span class="at">means =</span> mean)}</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_density</span>( <span class="sc">~</span>means, <span class="at">data =</span> Trials, <span class="at">title =</span> <span class="st">"Density plot of sample mean when n=10"</span>)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="fu">df_stats</span>(<span class="sc">~</span>means, <span class="at">data=</span>Trials, mean, sd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  response     mean       sd
1    means 73.69963 4.594354</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-NHANES6e-density" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Density plot of sample means when sample size is 10. Appears to be bell shaped.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-NHANES6e-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Continuous-Probability-Distribution_files/figure-html/fig-NHANES6e-density-1.png" class="img-fluid figure-img" alt="Density plot of sample means when sample size is 10. Appears to be bell shaped." width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-NHANES6e-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.21: Density Plot of Sample Means When n = 10
</figcaption>
</figure>
</div>
</div>
</div>
<p>This distribution is a sampling distribution. That is all a sampling distribution is. It is a distribution created from statistics.</p>
<p>Notice the distribution does look a great deal like the distribution of the original random variable. Notice the mean of the sample means <span class="math inline">\(\mu_{\bar{x}} = 73.8\)</span> bpm which is almost the same of as the mean of the population. The standard deviation of the sample means, <span class="math inline">\(\sigma_{\bar{x}}=4.35\)</span> pbm is about <span class="math inline">\(\frac{1}{3}\)</span> of the population standard deviation.</p>
<p>What does this distribution look like if instead of repeating the experiment 10 times you repeat it 50 times instead?</p>
<p>This density plot of the sampling distribution is displayed in <a href="#fig-NHANES6f-density" class="quarto-xref">Figure&nbsp;<span>6.22</span></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>Trials <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">100</span>) <span class="sc">*</span> { NHANES <span class="sc">|&gt;</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sample_n</span>(<span class="at">size =</span> <span class="dv">50</span>) <span class="sc">|&gt;</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">df_stats</span>( <span class="sc">~</span>Pulse, <span class="at">means =</span> mean) }</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_density</span>( <span class="sc">~</span>means, <span class="at">data =</span> Trials, <span class="at">title=</span><span class="st">"Sample means when n=50"</span>)<span class="sc">|&gt;</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_lims</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="dv">68</span>,<span class="dv">79</span>))</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="fu">df_stats</span>(<span class="sc">~</span>means, <span class="at">data=</span>Trials, mean, sd) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  response     mean       sd
1    means 73.21699 1.824683</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-NHANES6f-density" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Density plot of sample means when sample size is 50. Appears to be bell shaped.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-NHANES6f-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Continuous-Probability-Distribution_files/figure-html/fig-NHANES6f-density-1.png" class="img-fluid figure-img" alt="Density plot of sample means when sample size is 50. Appears to be bell shaped." width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-NHANES6f-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.22: Density Plot of Sample Means When n = 50
</figcaption>
</figure>
</div>
</div>
</div>
<p>Notice this density plot of the sample mean looks approximately symmetrical and could almost be called normal. Notice, the mean of the sample means is 73.6 bpm which is approximately what the population mean is. The standard deviation of the sample means is 1.77 bpm which is around <span class="math inline">\(\frac{1}{7}\)</span> of the population standard deviation. What if you keep increasing <span class="math inline">\(n\)</span>? What will the sampling distribution of the sample mean look like? In other words, what does the sampling distribution of <span class="math inline">\(\bar{x}\)</span> look like as <span class="math inline">\(n\)</span> gets even larger?</p>
<p>This depends on how the original distribution is distributed. In <a href="#example-sampling-distribution">Example: Sampling Distribution</a>, the random variable was approximately normally distributed. When <span class="math inline">\(n\)</span> was 10, the distribution of the mean looked approximately normal. What if the original distribution wasn’t normal? How big would <span class="math inline">\(n\)</span> have to be? Consider a different variable in the NHANES data frame that isn’t normally distributed such as age when a participant started to smoke cigarettes (SmokeAge). The density plot for the large sample is in <a href="#fig-NHANES6g-density" class="quarto-xref">Figure&nbsp;<span>6.23</span></a>. The mean for the large sample is 17.8 years and the standard deviation is 5.3 years, so <span class="math inline">\(\mu=17.8\)</span> dollars and <span class="math inline">\(\sigma=5.3\)</span> dollars approximately.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_density</span>(<span class="sc">~</span>SmokeAge, <span class="at">data=</span>NHANES, <span class="at">title =</span> <span class="st">"Density Plot of Age when Person Started Smoking"</span>, <span class="at">xlab=</span><span class="st">"Age"</span>) </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">df_stats</span>(<span class="sc">~</span>SmokeAge, <span class="at">data=</span>NHANES, mean, sd) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  response     mean      sd
1 SmokeAge 17.82662 5.32666</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-NHANES6g-density" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Density plot of age when person started smoking. Appears to not be bell shaped.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-NHANES6g-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Continuous-Probability-Distribution_files/figure-html/fig-NHANES6g-density-1.png" class="img-fluid figure-img" alt="Density plot of age when person started smoking. Appears to not be bell shaped." width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-NHANES6g-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.23: Density Plot of Age When Person Started Smoking.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Now take 100 samples of size 50 individuals from the NHANES Data Frame. Then graph a density plot of SmokeAge, the age when someone started to smoke. Notice the the sampling distribution of the sample means looks fairly normally distributed even though the original random variable was not normally distributed. The mean of the sample mean. <span class="math inline">\(\mu_{ \bar{x}}=\)</span> 17.8 years and the standard deviation of the sample mean, <span class="math inline">\(\sigma_{\bar{x}}=\)</span> 1.56 years. The mean of the sample mean is the same as the mean of the population, but the standard deviation of the sample mean is much less than the standard deviation of the original data.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  response     mean       sd
1    means 17.75968 1.282919</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-NHANES6-random-density" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Density plot of mean age a person starts to smoke of a sample of size 50. Appears to be bell shaped.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-NHANES6-random-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Continuous-Probability-Distribution_files/figure-html/fig-NHANES6-random-density-1.png" class="img-fluid figure-img" alt="Density plot of mean age a person starts to smoke of a sample of size 50. Appears to be bell shaped." width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-NHANES6-random-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.24: Density Plot of Age When Person Started Smoking when sample size is 50.
</figcaption>
</figure>
</div>
</div>
</div>
<p>One question is, why is the mean of the sample means the same as the mean of the population? Suppose you have a random variable that has a population mean, <span class="math inline">\(\mu\)</span>, and a population standard deviation, <span class="math inline">\(\sigma\)</span>. If a sample of size <span class="math inline">\(n\)</span> is taken, then the sample mean, has a mean <span class="math inline">\(\mu_{ \bar{x}}=\mu\)</span> and standard deviation of <span class="math inline">\(\sigma_{ \bar{x}}=\frac{\sigma}{\sqrt{n}}\)</span> . The standard deviation of the sample mean is lower because by taking the mean you are averaging out the extreme values, which makes the distribution of the sample mean less spread out.</p>
<p>You now know the center and the variability of <span class="math inline">\(\bar{x}\)</span>. You also want to know the shape of the distribution of <span class="math inline">\(\bar{x}\)</span>. You hope it is normal, since you know how to find probabilities using the normal curve. The following theorem tells you the requirement to have <span class="math inline">\(\bar{x}\)</span> be normally distributed.</p>
</section>
<section id="central-limit-theorem" class="level3" data-number="6.4.2">
<h3 data-number="6.4.2" class="anchored" data-anchor-id="central-limit-theorem"><span class="header-section-number">6.4.2</span> <strong>Central Limit Theorem</strong></h3>
<p>Suppose a random variable is from any distribution. If a sample of size <span class="math inline">\(n\)</span> is taken, the the sample mean, <span class="math inline">\(\bar{x}\)</span>, becomes normally distributed as <span class="math inline">\(n\)</span> increases.</p>
<p>What this says is that no matter what <span class="math inline">\(x\)</span> looks like, <span class="math inline">\(\bar{x}\)</span> would look normal if <span class="math inline">\(n\)</span> is large enough. Now, what size of <span class="math inline">\(n\)</span> is large enough? That depends on how <span class="math inline">\(x\)</span> is distributed in the first place. If the original random variable is normally distributed, then <span class="math inline">\(n\)</span> just needs to be 2 or more data points. If the original random variable is somewhat mound shaped and symmetrical, then <span class="math inline">\(n\)</span> needs to be greater than or equal to 30. Sometimes the sample size can be smaller, but this is a good general rule to use. The sample size may have to be much larger if the original random variable is really skewed one way or another.</p>
<p>Now that you know when the sample mean will look like a normal distribution, then you can find the probability related to the sample mean. Remember that the mean of the sample mean is just the mean of the original data (<span class="math inline">\(\mu_{\bar{x}}=\mu\)</span>), but the standard deviation of the sample mean, <span class="math inline">\(\sigma_{\bar{x}}\)</span>, also known as the standard error of the mean, is actually <span class="math inline">\(\sigma_{\bar{x}}=\frac{\sigma}{\sqrt{n}}\)</span>. Make sure you use this in all calculations. If you are using the <span class="math inline">\(z\)</span>-score, the formula when working with <span class="math inline">\(\bar{x}\)</span> is <span class="math inline">\(z=\frac{x-\mu_{\bar{x}}}{\sigma_{\bar{x}}}=\frac{x-\mu}{\frac{\sigma}{\sqrt{n}}}\)</span>. To use rStudio to calculate probabilities use <span class="math inline">\(P(\bar{x}&lt;a)= pnorm(a, \mu_{\bar{x}}, \sigma_{\bar{x}}, lower.tail=TRUE)\)</span> <span class="math inline">\(P(\bar{x}&gt;a)= pnorm(a, \mu_{\bar{x}}, \sigma_{\bar{x}}, lower.tail=FALSE)\)</span>.</p>
</section>
<section id="example-finding-probabilities-for-sample-means" class="level3" data-number="6.4.3">
<h3 data-number="6.4.3" class="anchored" data-anchor-id="example-finding-probabilities-for-sample-means"><span class="header-section-number">6.4.3</span> Example: Finding Probabilities for Sample Means</h3>
<p>The birth weight of boy babies of European descent who were delivered at 40 weeks is normally distributed with a mean of 3687.6 g with a standard deviation of 410.5 g (Janssen, Thiessen, Klein, Whitfield, MacNab &amp; Cullis-Kuhl, 2007). Suppose there were nine European descent boy babies born on a given day and the mean birth weight is calculated.</p>
<ol type="a">
<li>State the random variable.</li>
<li>What is the mean of the sample mean?</li>
<li>What is the standard deviation of the sample mean?</li>
<li>What distribution is the sample mean distributed as?</li>
<li>Find the probability that the mean weight of the nine boy babies born was less than 3500.4 g.</li>
<li>Find the probability that the mean weight of the nine babies born was less than 3452.5 g.</li>
</ol>
<section id="solution-4" class="level4" data-number="6.4.3.1">
<h4 data-number="6.4.3.1" class="anchored" data-anchor-id="solution-4"><span class="header-section-number">6.4.3.1</span> <strong>Solution</strong></h4>
<ol type="a">
<li>State the random variable.</li>
</ol>
<p><span class="math inline">\(x\)</span> = birth weight of boy babies (Note: the random variable is something you measure, and it is not the mean birth weight. Mean weight is calculated.)</p>
<ol start="2" type="a">
<li>What is the mean of the sample mean?</li>
</ol>
<p><span class="math inline">\(\mu_{\bar{x}}=\mu=3687.4g\)</span></p>
<ol start="3" type="a">
<li>What is the standard deviation of the sample mean?</li>
</ol>
<p><span class="math inline">\(\sigma_{\bar{x}}=\frac{\sigma}{\sqrt{n}}=\frac{410.5g}{\sqrt{9}}=136.8g\)</span></p>
<ol start="4" type="a">
<li>What distribution is the sample mean distributed as?</li>
</ol>
<p>Since the original random variable is distributed normally, then the sample mean is distributed normally.</p>
<ol start="5" type="a">
<li>Find the probability that the mean weight of the nine boy babies born was less than 3500.4 g.</li>
</ol>
<p>To find <span class="math inline">\(P(\bar{x}&lt;3500.4)=0.086\)</span>. use the rStudio command</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">3500.4</span>,<span class="fl">3687.6</span>, <span class="fl">410.5</span><span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">9</span>), <span class="at">lower.tail =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.08564231</code></pre>
</div>
</div>
<p>There is an 8.6% chance that the mean birth weight of the nine boy babies born would be less than 3500.4 g. Since this is more than 5%, this is not unusual.</p>
<ol start="6" type="a">
<li>Find the probability that the mean weight of the nine babies born was less than 3452.5 g.</li>
</ol>
<p>You are looking for the <span class="math inline">\(P(\bar{x}&lt;3452.5)\)</span>.</p>
<p>To find in rStudio, <span class="math inline">\(P(\bar{x}&lt;3452.5)=0.043\)</span> use the command</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">3452.5</span>, <span class="fl">3687.4</span>, <span class="fl">410.5</span><span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">9</span>), <span class="at">lower.tail =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.04301819</code></pre>
</div>
</div>
<p>There is a 4.3% chance that the mean birth weight of the nine boy babies born would be less than 3452.5 g. Since this is less than 5% this would be an unusual event. If it actually happened, then you may think there is something unusual about this sample. Maybe some of the nine babies were born as multiples, which brings the mean weight down, or some or all of the babies were not of European descent (in fact the mean weight of South Asian boy babies is 3452.5 g), or some were born before 40 weeks, or the babies were born at high altitudes.</p>
</section>
</section>
<section id="example-finding-probabilities-for-sample-means-1" class="level3" data-number="6.4.4">
<h3 data-number="6.4.4" class="anchored" data-anchor-id="example-finding-probabilities-for-sample-means-1"><span class="header-section-number">6.4.4</span> Example: Finding Probabilities for Sample Means</h3>
<p>For Americans that smoke, the average age that they started smoking is 17.8 years, with a standard deviation of approximately 1.56 years from the NHANES data. This random variable is not normally distributed, though it is somewhat mound shaped.</p>
<ol type="a">
<li>State the random variable.</li>
<li>Suppose a sample of 35 smoking American’s is taken. Find the probability that the mean age that these 35 smoking Americans started to smoke is more than 21 years.</li>
</ol>
<section id="solution-5" class="level4" data-number="6.4.4.1">
<h4 data-number="6.4.4.1" class="anchored" data-anchor-id="solution-5"><span class="header-section-number">6.4.4.1</span> <strong>Solution</strong></h4>
<ol type="a">
<li>State the random variable.</li>
</ol>
<p><span class="math inline">\(x\)</span> = age that smoking Americans started to smoke</p>
<ol start="2" type="a">
<li>Suppose a sample of 35 smoking American’s is taken. Find the probability that the mean age that these 35 smoking Americans started to smoke is more than 21 years.</li>
</ol>
<p>Even though the original random variable is not normally distributed, the sample size is over 30, by the central limit theorem the sample mean will be normally distributed. The mean of the sample mean is <span class="math inline">\(\mu_{\bar{x}}=17.8\)</span>. The standard deviation of the sample mean is <span class="math inline">\(\sigma_{\bar{x}}=\frac{\sigma}{\sqrt{n}}=\frac{1.56}{\sqrt{35}}\)</span>. You have all the information you need to use the normal command using rStudio. Without the central limit theorem, you couldn’t use the normal command, and you would not be able to answer this question.</p>
<p>The probability that the mean age that 35 smoking Americans start to smoke is more than 21 years, is the mathematical statement <span class="math inline">\(P(\bar{x}&gt;21)\)</span></p>
<p>To find <span class="math inline">\(P(\bar{x}&gt;21)= 3.42X10^{-34}\)</span> using r studio, use the command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">21</span>, <span class="fl">17.8</span>, <span class="fl">1.56</span><span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">35</span>), <span class="at">lower.tail=</span><span class="cn">FALSE</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.422499e-34</code></pre>
</div>
</div>
<p>The probability of a sample mean of 35 smoking Americans being more than 21 years when they smoked for the first time is very small. This is extremely unlikely to happen. If it does, it may make you wonder about the sample. Could the population mean have increased from the 17.8 years as was stated? Could the sample not have been random, and instead have been a group of smoking Americans who had started to smoke much later? These questions, and more, are ones that you would want to ask as a researcher</p>
</section>
</section>
<section id="homework-for-sampling-distribution-and-the-central-limit-theorem-section" class="level3" data-number="6.4.5">
<h3 data-number="6.4.5" class="anchored" data-anchor-id="homework-for-sampling-distribution-and-the-central-limit-theorem-section"><span class="header-section-number">6.4.5</span> Homework for Sampling Distribution and the Central Limit Theorem Section</h3>
<ol type="1">
<li>A random variable is not normally distributed, but it is mound shaped. It has a mean of 14 and a standard deviation of 3.</li>
</ol>
<!-- -->
<ol type="a">
<li>If you take a sample of size 10, can you say what the shape of the sampling distribution for the sample mean is? Why?</li>
<li>For a sample of size 10, state the mean of the sample mean and the standard deviation of the sample mean.</li>
<li>If you take a sample of size 35, can you say what the shape of the distribution of the sample mean is? Why?</li>
<li>For a sample of size 35, state the mean of the sample mean and the standard deviation of the sample mean.</li>
</ol>
<!-- -->
<ol start="2" type="1">
<li>A random variable is normally distributed. It has a mean of 245 and a standard deviation of 21.</li>
</ol>
<!-- -->
<ol type="a">
<li>If you take a sample of size 10, can you say what the shape of the distribution for the sample mean is? Why?</li>
<li>For a sample of size 10, state the mean of the sample mean and the standard deviation of the sample mean.</li>
<li>For a sample of size 10, find the probability that the sample mean is more than 241.</li>
<li>If you take a sample of size 35, can you say what the shape of the distribution of the sample mean is? Why?</li>
<li>For a sample of size 35, state the mean of the sample mean and the standard deviation of the sample mean.</li>
<li>For a sample of size 35, find the probability that the sample mean is more than 241.</li>
<li>Compare your answers in part c and f.&nbsp;Why is one smaller than the other?</li>
</ol>
<!-- -->
<ol start="3" type="1">
<li>The mean starting salary for nurses is \$67,694 nationally (“Staff nurse -,” 2013). The standard deviation is approximately $10,333. The starting salary is not normally distributed but it is mound shaped. A sample of 42 starting salaries for nurses is taken.</li>
</ol>
<!-- -->
<ol type="a">
<li>State the random variable.</li>
<li>What is the mean of the sample mean?</li>
<li>What is the standard deviation of the sample mean?</li>
<li>What is the shape of the sampling distribution of the sample mean? Why?</li>
<li>Find the probability that the sample mean is more than \$75,000.</li>
<li>Find the probability that the sample mean is less than \$60,000.</li>
<li>If you did find a sample mean of more than \$75,000 would you find that unusual? What could you conclude?</li>
</ol>
<!-- -->
<ol start="4" type="1">
<li>According to the WHO MONICA Project the mean blood pressure for people in China is 128 mmHg with a standard deviation of 23 mmHg (Kuulasmaa, Hense &amp; Tolonen, 1998). Blood pressure is normally distributed.</li>
</ol>
<!-- -->
<ol type="a">
<li>State the random variable.</li>
<li>Suppose a sample of size 15 is taken. State the shape of the distribution of the sample mean.</li>
<li>Suppose a sample of size 15 is taken. State the mean of the sample mean.</li>
<li>Suppose a sample of size 15 is taken. State the standard deviation of the sample mean.</li>
<li>Suppose a sample of size 15 is taken. Find the probability that the sample mean blood pressure is more than 135 mmHg.</li>
<li>Would it be unusual to find a sample mean of 15 people in China of more than 135 mmHg? Why or why not?</li>
<li>If you did find a sample mean for 15 people in China to be more than 135 mmHg, what might you conclude?</li>
</ol>
<!-- -->
<ol start="5" type="1">
<li>The size of fish is very important to commercial fishing. A study conducted in 2012 found the length of Atlantic cod caught in nets in Karlskrona to have a mean of 49.9 cm and a standard deviation of 3.74 cm (Ovegard, Berndt &amp; Lunneryd, 2012). The length of fish is normally distributed. A sample of 15 fish is taken.</li>
</ol>
<!-- -->
<ol type="a">
<li>State the random variable.</li>
<li>Find the mean of the sample mean.</li>
<li>Find the standard deviation of the sample mean</li>
<li>What is the shape of the distribution of the sample mean? Why?</li>
<li>Find the probability that the sample mean length of the Atlantic cod is less than 52 cm.</li>
<li>Find the probability that the sample mean length of the Atlantic cod is more than 74 cm.</li>
<li>If you found sample mean length for Atlantic cod to be more than 74 cm, what could you conclude?</li>
</ol>
<!-- -->
<ol start="6" type="1">
<li>The mean cholesterol levels of women age 45-59 in Ghana, Nigeria, and Seychelles is 5.1 mmol/l and the standard deviation is 1.0 mmol/l (Lawes, Hoorn, Law &amp; Rodgers, 2004). Assume that cholesterol levels are normally distributed.</li>
</ol>
<!-- -->
<ol type="a">
<li>State the random variable.</li>
<li>Find the probability that a woman age 45-59 in Ghana has a cholesterol level above 6.2 mmol/l (considered a high level).</li>
<li>Suppose doctors decide to test the woman’s cholesterol level again and average the two values. Find the probability that this woman’s mean cholesterol level for the two tests is above 6.2 mmol/l.</li>
<li>Suppose doctors being very conservative decide to test the woman’s cholesterol level a third time and average the three values. Find the probability that this woman’s mean cholesterol level for the three tests is above 6.2 mmol/l.</li>
<li>If the sample mean cholesterol level for this woman after three tests is above 6.2 mmol/l, what could you conclude?</li>
</ol>
<!-- -->
<ol start="7" type="1">
<li>In the United States, males between the ages of 40 and 49 eat on average 103.1 g of fat every day with a standard deviation of 4.32 g (“What we eat,” 2012). The amount of fat a person eats is not normally distributed but it is relatively mound shaped.</li>
</ol>
<!-- -->
<ol type="a">
<li>State the random variable.</li>
<li>Find the probability that a sample mean amount of daily fat intake for 35 men age 40-59 in the U.S. is more than 100 g.</li>
<li>Find the probability that a sample mean amount of daily fat intake for 35 men age 40-59 in the U.S. is less than 93 g.</li>
<li>If you found a sample mean amount of daily fat intake for 35 men age 40-59 in the U.S. less than 93 g, what would you conclude?</li>
</ol>
<!-- -->
<ol start="8" type="1">
<li>A dishwasher has a mean life of 12 years with an estimated standard deviation of 1.25 years (“Appliance life expectancy,” 2013). The life of a dishwasher is normally distributed. Suppose you are a manufacturer and you take a sample of 10 dishwashers that you made.</li>
</ol>
<!-- -->
<ol type="a">
<li>State the random variable.</li>
<li>Find the mean of the sample mean.</li>
<li>Find the standard deviation of the sample mean.</li>
<li>What is the shape of the sampling distribution of the sample mean? Why?</li>
<li>Find the probability that the sample mean of the dishwashers is less than 6 years.</li>
<li>If you found the sample mean life of the 10 dishwashers to be less than 6 years, would you think that you have a problem with the manufacturing process? Why or why not?</li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Discrete Probability Distribution.html" class="pagination-link" aria-label="Discrete Probability Distribution">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Discrete Probability Distribution</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./One Sample Inference.html" class="pagination-link" aria-label="One Sample Inference">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">One Sample Inference</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>