<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Discrete Probability Distribution – Introductory Statistics: A Conceptual Approach Using Rguroo</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Continuous Probability Distribution.html" rel="next">
<link href="./Probability.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-c574c73dd0d0ff61020859ffc61752ee.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Discrete Probability Distribution.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Discrete Probability Distribution</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introductory Statistics: A Conceptual Approach Using Rguroo</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Statistical Basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Statistical Basics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Graphical_Description_of_Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Tabular and Graphical Description of Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Numerical-description-of-Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Numerical Description of Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Discrete Probability Distribution.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Discrete Probability Distribution</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Continuous Probability Distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Continuous Probability Distribution</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Sampling Distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Sampling Distributions and the Central Limit Theorem</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations_of_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Foundations of Statistical Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./proportion inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Inference for Population Proportions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mean inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Statistical Inference for Means</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./One Sample Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">One Sample Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Two Sample Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Two Sample Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chi-Square and ANOVA Tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Chi-squared and ANOVA Tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./References.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#basics-of-probability-distributions" id="toc-basics-of-probability-distributions" class="nav-link active" data-scroll-target="#basics-of-probability-distributions"><span class="header-section-number">5.1</span> Basics of Probability Distributions</a>
  <ul class="collapse">
  <li><a href="#random-variables-and-probability-distributions" id="toc-random-variables-and-probability-distributions" class="nav-link" data-scroll-target="#random-variables-and-probability-distributions"><span class="header-section-number">5.1.1</span> Random Variables and Probability Distributions</a></li>
  <li><a href="#mean-or-expected-value-and-standard-deviation" id="toc-mean-or-expected-value-and-standard-deviation" class="nav-link" data-scroll-target="#mean-or-expected-value-and-standard-deviation"><span class="header-section-number">5.1.2</span> Mean or Expected Value and Standard Deviation</a></li>
  <li><a href="#unusual-events" id="toc-unusual-events" class="nav-link" data-scroll-target="#unusual-events"><span class="header-section-number">5.1.3</span> Unusual Events</a></li>
  <li><a href="#homework-for-section-5.1" id="toc-homework-for-section-5.1" class="nav-link" data-scroll-target="#homework-for-section-5.1"><span class="header-section-number">5.1.4</span> Homework for Section 5.1</a></li>
  </ul></li>
  <li><a href="#binomial-probability-distribution" id="toc-binomial-probability-distribution" class="nav-link" data-scroll-target="#binomial-probability-distribution"><span class="header-section-number">5.2</span> Binomial Probability Distribution</a>
  <ul class="collapse">
  <li><a href="#calculating-binomial-probabilities" id="toc-calculating-binomial-probabilities" class="nav-link" data-scroll-target="#calculating-binomial-probabilities"><span class="header-section-number">5.2.1</span> Calculating Binomial Probabilities</a></li>
  <li><a href="#mean-and-standard-deviation" id="toc-mean-and-standard-deviation" class="nav-link" data-scroll-target="#mean-and-standard-deviation"><span class="header-section-number">5.2.2</span> Mean and Standard Deviation</a></li>
  <li><a href="#creating-probability-distributions" id="toc-creating-probability-distributions" class="nav-link" data-scroll-target="#creating-probability-distributions"><span class="header-section-number">5.2.3</span> Creating Probability Distributions</a></li>
  <li><a href="#homework-for-section-5.2" id="toc-homework-for-section-5.2" class="nav-link" data-scroll-target="#homework-for-section-5.2"><span class="header-section-number">5.2.4</span> Homework for Section 5.2</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Discrete Probability Distribution</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Chapter 5 Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<p>By the end of Chapter 5, you should be able to:</p>
<ul>
<li>Recognize, describe, and verify discrete probability distributions.</li>
<li>Calculate and interpret expected value (mean) and standard deviation.</li>
<li>Recognize, verify, and analyze binomial proability distributions.</li>
<li>Calculate and intertpret binomial probabilities.</li>
<li>Create binomial probability distributions.</li>
</ul>
</div>
</div>
<p><strong>Before you begin, review the process for importing a dataset.</strong> Click on the box below to expand the directions for importing a dataset into your Data Toolbox.</p>
<div id="Importing-Data-to-Rguroo-Chapter-5" class="callout callout-style-simple callout-note callout-titled" title="![](Rguroo_Icons/R_circle_logo.svg){width=22px style='vertical-align:middle;'}  Importing Data to Rguroo">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span><img src="Rguroo_Icons/R_circle_logo.svg" class="img-fluid" style="vertical-align:middle;" width="22"> Importing Data to Rguroo
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Open the <strong>Data</strong> toolbox in Rguroo.<br>
</li>
<li>From the <span class="dpd">Data Import</span> dropdown, select <span class="fun">Dataset Repository</span>.<br>
</li>
<li>In the top search box, type <span class="typein">kozak</span>, then select the <span class="repo">Statistics Using Technology – Kozak</span> repository.<br>
</li>
<li>In the middle search box, type the first few letters of the dataset, and choose your dataset that appears in the lower panel.<br>
</li>
<li>Click the <span class="button">Import</span>. The dataset will be imported into your Rguroo account.<br>
</li>
<li>Click the <span class="button">Close</span> to close the dialog.<br>
</li>
<li>To view the dataset, double-click the dataset under the <strong>Data</strong> toolbox list.</li>
</ol>
</div>
</div>
</div>
<p>When calculating probabilities, we begin by identifying the sample space—the complete set of all possible outcomes of an experiment. When each of these outcomes is assigned a probability, the combination forms a probability distribution. This distribution allows us to examine the overall shape of the random variable’s distribution, compute measures such as the mean and standard deviation, and determine the likelihood of specific events. The methods used to find these values depend on the type of random variable involved. Recall that numerical variables fall into two categories: discrete and continuous. <strong>Discrete data</strong> can only take specific, separate values within a given range, while <strong>continuous data</strong> can take on any value within that range. Typically, discrete data arise from counting, whereas continuous data come from measurement. Discrete probability distributions provide a way to model and understand situations in which outcomes can be counted.</p>
<div id="exm-discrete-continuous-review" class="theorem example">
<p><span class="theorem-title"><strong>Example 5.1 (Review of Discrete or Continuous Variables)</strong></span> Classify the numerical variable as discrete or continuous.</p>
<ol type="a">
<li><p>The height of a tree measured in inches.</p></li>
<li><p>The number of A’s you receive on your college transcript.</p></li>
</ol>
</div>
<div class="solution-callout callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>🔎 Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><p>The heigt of a tree in inches is continuous since it is something you measure and can take on fractional values.</p></li>
<li><p>The number of A’s you receive on your college transcript is discrete since it is something you count.</p></li>
</ol>
</div>
</div>
</div>
<section id="basics-of-probability-distributions" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="basics-of-probability-distributions"><span class="header-section-number">5.1</span> Basics of Probability Distributions</h2>
<p>A probability distribution can be illustrated with a simple experiment such as tossing a fair coin twice. The sample space, which lists all possible outcomes, is: <span class="math display">\[\{HH,&nbsp;HT,&nbsp;TH,&nbsp;TT\}\]</span></p>
<p>where H represents heads and T represents tails. Since the coin is fair, each outcome has an equal probability of <span class="math inline">\(1/4\)</span>.</p>
<p>But, what if we wanted to ask other questions such as</p>
<ul>
<li>What is the probability of getting exactly one heads?</li>
<li>What is the probability of getting at most one tails?</li>
</ul>
<p>These questions can be answered more easily with a discrete probability distribution.</p>
<section id="random-variables-and-probability-distributions" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="random-variables-and-probability-distributions"><span class="header-section-number">5.1.1</span> Random Variables and Probability Distributions</h3>
<p>A <strong>random variable</strong> is a numerical measure of each outcome of an experiment. Usually, we use capital <span class="math inline">\(X\)</span> to describe the random variable in words and use lower case <span class="math inline">\(x\)</span> to denote the values that the random variable can take on. For example, in the fair coin toss experiment above, we can let <span class="math inline">\(X\)</span> = the number of heads. Then, <span class="math inline">\(x\)</span> could be 0 (no heads - TT), 1 (one heads - HT or TH), or 2 (two heads - HH). So</p>
<p><span class="math display">\[X= \text{number of heads}\]</span> <span class="math display">\[x=\{0, 1, 2\}\]</span></p>
<p>Now suppose you put all the values of the random variable together with the probability of each random variable. You would then have a <strong>probability distribution</strong>, a table of values that lists the random variable values with their corresponding probabilities. For the random variable <span class="math inline">\(X\)</span> = the number of heads (in the coin toss example), we would need to calculate the probabilities for each outcome. So, for <span class="math inline">\(x = 0\)</span>, that would be zero heads (or TT) and occurs one out of four times in the sample space. As a result, the probability for <span class="math inline">\(x\)</span> = 0 is <span class="math inline">\(1/4\)</span>. For <span class="math inline">\(x = 1\)</span> (or one head), this could occur as HT or TH. So, the probability of <span class="math inline">\(x = 1\)</span> would be two possible ways in the sample space out of four or <span class="math inline">\(2/4\)</span> which reduces to <span class="math inline">\(1/2\)</span>. Finally, for <span class="math inline">\(x = 2\)</span> (or two heads), this occurs as HH in the sample space and the probability would be <span class="math inline">\(1/4\)</span>. Putting this all together in a table, we get the probability distribution below.</p>
<div style="width: 50%; margin: auto;">
<div id="tbl-prob-dist-coin" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Probability distribution showing the values of the random variable x in the first column and probabilities in the second column">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-prob-dist-coin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.1: Probability Distribution for Number of Heads
</figcaption>
<div aria-describedby="tbl-prob-dist-coin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(x\)</span></th>
<th><span class="math inline">\(P(x)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(0\)</span></td>
<td><span class="math inline">\(1/4\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(1\)</span></td>
<td><span class="math inline">\(1/2\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(2\)</span></td>
<td><span class="math inline">\(1/4\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
<p>As with probabilities, probability distributions have to follow the rules of probabilities, <span class="math inline">\(0 \le P(\text{outcome})\le1\)</span> and <span class="math inline">\(\sum{P(\text{outcomes})}=1\)</span>. We can check these rules with the probability distribution above. First we can verify that each probability, <span class="math inline">\(P(x)\)</span>, is between 0 and 1. And, if we add up all the probabilities, <span class="math inline">\(1/4 + 1/2 + 1/4\)</span> we get 1.</p>
<div id="exm-verify-distribution" class="theorem example">
<p><span class="theorem-title"><strong>Example 5.2 (Verifying Probability Distributions)</strong></span> Determine if the following distributions are discrete probability distributions. If it is not a discrete probability distribution, state why.</p>
<ol type="a">
<li>Suppose a traffic study records the number of accidents that happen at a busy intersection in one week. Let <span class="math inline">\(X\)</span> = number of accidents per week. The probabilities are shown in the table below.</li>
</ol>
<div style="width: 50%; margin: auto;">
<div id="tbl-accidents" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Table showing values of the random variable as 0, 1, 2, and 3. The probabilities in the second column are 0.30, 0.40, 0.10, and 0.20">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-accidents-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.2: Distribution for number of accidents
</figcaption>
<div aria-describedby="tbl-accidents-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(x\)</span></th>
<th><span class="math inline">\(P(x)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>0.30</td>
</tr>
<tr class="even">
<td>1</td>
<td>0.40</td>
</tr>
<tr class="odd">
<td>2</td>
<td>0.10</td>
</tr>
<tr class="even">
<td>3</td>
<td>0.20</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
<ol start="2" type="a">
<li>Suppose a researcher records the number of texts people receive. Let <span class="math inline">\(X\)</span> = number of texts in one hour. The probabilities are shown in the table below.</li>
</ol>
<div style="width: 50%; margin: auto;">
<div id="tbl-texts" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Table showing values of the random variable as 0, 1, 2, 3, 4, and 5. The probabilities in the second column are 0.10, 0.15, 0.25, 0.33, 0.12, and 0.10">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-texts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.3: Distribution for number of texts received in one hour
</figcaption>
<div aria-describedby="tbl-texts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(x\)</span></th>
<th><span class="math inline">\(P(x)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>0.10</td>
</tr>
<tr class="even">
<td>1</td>
<td>0.15</td>
</tr>
<tr class="odd">
<td>2</td>
<td>0.25</td>
</tr>
<tr class="even">
<td>3</td>
<td>0.33</td>
</tr>
<tr class="odd">
<td>4</td>
<td>0.12</td>
</tr>
<tr class="even">
<td>5</td>
<td>0.10</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</div>
<div class="solution-callout callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>🔎 Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>To determine if each is a discrete probability disribution, we must verify the two rules of probability.</p>
<ol type="a">
<li><p>Verify Rule 1: Each probability is between 0 and 1.</p>
<p>Verify Rule 2: <span class="math inline">\(0.30 + 0.40 + 0.10 + 0.20 = 1.00\)</span></p>
<p>Both rules are satisfied, so this is a valid discrete probability distribution.</p></li>
<li><p>Verify Rule 1: Each probability is between 0 and 1.</p>
<p>Verify Rule 2: <span class="math inline">\(0.10 + 0.15 + 0.25 + 0.33 + 0.12 + 0.10 = 1.05\)</span></p>
<p>The probabilities do not add up to exactly <span class="math inline">\(1\)</span>, so this is not a valid discrete probability distribution.</p></li>
</ol>
</div>
</div>
</div>
<div id="exm-prob-dist" class="theorem example">
<p><span class="theorem-title"><strong>Example 5.3 (Using a Probability Distribution)</strong></span> The 2010 U.S. Census found the chance of a household being a certain size. The data is in <a href="#tbl-Household" class="quarto-xref">Table&nbsp;<span>5.4</span></a> (\“Households by age,\” 2013). Note, the category 7 is really 7 or more people in the household. Use the probability distribution to answer the following questions.</p>
<p><img src="Rguroo_Icons/Rguroo_repo_logo.png" class="img-fluid" alt="Rguroo dataset logo"> The dataset for this example is available in the Rguroo dataset repository <span class="repo">Kozak</span>, with the dataset name <span class="data">table_5_1_1</span>.</p>
<div class="cell" data-tbl-alt="Table showing household size">
<div id="tbl-Household" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Table showing household size">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Household-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.4: Household Size from U.S. Census of 2010
</figcaption>
<div aria-describedby="tbl-Household-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">size</th>
<th style="text-align: right;">prob</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.267</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.336</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.158</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.137</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.063</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.024</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.015</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<ol type="a">
<li><p>What is the probability that a randomly selected household has exactly 2 people?</p></li>
<li><p>What is the probability that a randomly selected household has at most 3 people?</p></li>
<li><p>What is the probability that a randomly selected household has at least 4 people?</p></li>
</ol>
</div>
<div class="solution-callout callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>🔎 Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><p>We want to find the probability of exactly 2 people in the household. We can denote that with <span class="math inline">\(P(2)\)</span>. To find this, we can use the table and find the probability that corresponds to <span class="math inline">\(x = 2\)</span>. So, <span class="math inline">\(P(2) = 0.336\)</span>.</p></li>
<li><p>“At most 3” people means 3 or less (including 3), so we would need to find <span class="math inline">\(P(x\le 3)\)</span>, meaning <span class="math inline">\(P(x) = 1\)</span> or <span class="math inline">\(P(x) = 2\)</span> or <span class="math inline">\(P(x) = 3\)</span>. Remember that “or” means add in probability. So, to find <span class="math inline">\(P(x \le 3)\)</span>, we add up the probabilities from <span class="math inline">\(x=1\)</span> to <span class="math inline">\(x=3\)</span>. So, <span class="math inline">\(P(x \le 3) = 0.267 + 0.336 + 0.158  = 0.761\)</span>.</p></li>
<li><p>“At least 4” people means 4 people or more. Similarly to part (b) we need to add. In this case, we would calculate <span class="math inline">\(P(x \ge 4) = P(4) + P(5) + P(6) + P(7) = 0.137 + 0.063 + 0.024 + 0.015 = 0.239\)</span></p></li>
</ol>
</div>
</div>
</div>
<p>We can also display probability distributions in graphical form, called a <strong>probability histogram</strong>. Probability histograms are similar to the histograms in Chapter 2, only the x axis will contain the random variable <span class="math inline">\(x\)</span> and the y-axis will contain the <span class="math inline">\(P(x)\)</span>. We will use Rguroo to create probability histograms.</p>
<div id="exm-prob-histogram" class="theorem example">
<p><span class="theorem-title"><strong>Example 5.4 (Creating a Probability Histogram)</strong></span> Use the 2010 U.S. census for number of people in a household to create a probability histogram.</p>
<p><img src="Rguroo_Icons/Rguroo_repo_logo.png" class="img-fluid" alt="Rguroo dataset logo"> The dataset for this example is available in the Rguroo dataset repository <span class="repo">Kozak</span>, with the dataset name <span class="data">table_5_1_1</span>.</p>
</div>
<div class="solution-callout callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>🔎 Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Click to expand the box below see how to create a probability histogram for <span class="data">table_5_1_1</span>.</p>
<div id="Creating-Probability-Histogram-in-Rguroo" class="callout callout-style-simple callout-note callout-titled" title="![](Rguroo_Icons/R_circle_logo.svg){width=22px style='vertical-align:middle;'} Creating a Probability Histogram in Rgruoo">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span><img src="Rguroo_Icons/R_circle_logo.svg" class="img-fluid" style="vertical-align:middle;" width="22"> Creating a Probability Histogram in Rgruoo
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Before you begin:</strong> Make sure you have already imported the <span class="data">table_5_1_1</span> dataset into your Rguroo account, as was shown <a href="#Importing-Data-to-Rguroo-Chapter-5">here</a>.</p>
<ol type="1">
<li>Open the <strong>Plots</strong> toolbox in Rguroo.<br>
</li>
<li>Open the <span class="dpd">Create Plot</span> dropdown, and select <span class="fun">Histogram</span>. This opens the Histogram dialog.<br>
</li>
<li>In the Histogram dialog, choose the <span class="data">table_5_1_1</span> dataset from the <span class="dpd">Dataset</span> dropdown.</li>
<li>Then, select <span class="var">size</span> in the <span class="dpd">Variable</span> dropdown menu and <span class="var">prob</span> in the <span class="dpd">Frequency</span> dropdown menu.</li>
<li>Type in a title for your table, and label the x and y axes. Since this graph represents a probability histogram, we can use “Probability Histogram for Household Size” as the title, “Household size (x)” for the x-axis, and “Probability, P(x)” as for the y-axis.</li>
<li>Select “Relative Frequency” in the Type box, since this is probability.<br>
</li>
<li>Click the preview icon <img src="Rguroo_Icons/preview_inline.png" class="img-fluid" alt="preview icon"> to see a preview of the probability histogram.</li>
</ol>
<div class="inner-callout callout callout-style-simple callout-tip callout-titled" title="Click here to see the Rguroo dialog">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Click here to see the Rguroo dialog
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Rguroo_dialogs/Discrete_Probability/dialog_household_5.png" class="img-fluid figure-img" width="500"></p>
<figcaption>Histogram dialog showing settings for creating probability histogram.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>Now, since this is a probability histogram, we need to adjust the graph. To do this, follow the steps below.</p>
<ol type="1">
<li>Click on the Details box.</li>
<li>Select Bins, Bars, and Smoothing.</li>
<li>In the Bin Breakpoints box, select center and enter <span class="typein">1</span> for start and <span class="typein">1</span> for the width. This will start the probability histogram at the fist value of our random variable and center the bars.</li>
<li>Click the preview icon <img src="Rguroo_Icons/preview_inline.png" class="img-fluid" alt="preview icon"> to see a preview of the final probability histogram.</li>
</ol>
<div class="inner-callout callout callout-style-simple callout-tip callout-titled" title="Click here to see the Rguroo dialog">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Click here to see the Rguroo dialog
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Rguroo_dialogs/Discrete_Probability/dialog_household_details.png" class="img-fluid figure-img" width="500"></p>
<figcaption>Histogram dialog showing settings for editing details for probability histogram.</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-prob-hist" class="quarto-float quarto-figure quarto-figure-center anchored" alt="See the description of the graph below the graph">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-prob-hist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Rguroo_outputs/Discrete_Probability_Distribution/prob_hist_household.svg" class="img-fluid figure-img" alt="See the description of the graph below the graph">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-prob-hist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.1: Probability histogram of household size
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-prob-hist" class="quarto-xref">Figure&nbsp;<span>5.1</span></a> shows the probability distribution of household sizes, with the highest probabilities occurring at households with 1–2 people. As the household size increases from 3 to 7, the probability steadily decreases, indicating that larger households are less common. Overall, the distribution is right-skewed, demonstrating that most households tend to be small, while very large households are not as common.</p>
</div>
</div>
</div>
</section>
<section id="mean-or-expected-value-and-standard-deviation" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="mean-or-expected-value-and-standard-deviation"><span class="header-section-number">5.1.2</span> Mean or Expected Value and Standard Deviation</h3>
<p>In probability distributions, the <strong>mean</strong>, also called the <strong>expected value</strong>, represents the long-run average outcome of a random variable. Recall from Chapter 4, the Law of Large Numbers states that as the number of trials, <span class="math inline">\(n\)</span>, of an experiment increases, the relative frequency of an event gets closer and closer to the true probability of that event. So, the long-term average, the mean (or expected value) of a probability distribution, is the average you would expect if the number of trials were repeated an infinite number of times. Since the expected value of a random variable is a theoretical, long-run average, it is treated as a population parameter and is labeled as <span class="math inline">\(\mu\)</span>. We can calculate the expected value using the formula below or using statistical software, like Rgruoo.</p>
<p><span class="math display">\[\mu = \sum (x \cdot P(x))\]</span></p>
<p>The standard deviation is</p>
<p><span class="math display">\[\sigma = \sqrt{\sum[(x-\mu)^2 \cdot P(x)]}\]</span></p>
<p>Since the formula for standard deviation is a little more complicated, we will only find this using technology.</p>
<div id="exm-expected-value1" class="theorem example">
<p><span class="theorem-title"><strong>Example 5.5 (Calculating Expected Value and Standard Deviation)</strong></span> Use the 2010 U.S. census for number of people in a household to find the expected value and standard deviation. Interpret the expected value.</p>
<p><img src="Rguroo_Icons/Rguroo_repo_logo.png" class="img-fluid" alt="Rguroo dataset logo"> The dataset for this example is available in the Rguroo dataset repository <span class="repo">Kozak</span>, with the dataset name <span class="data">table_5_1_1</span>.</p>
</div>
<div class="solution-callout callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>🔎 Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Click to expand the box below to see how to find the mean and standard deviation for <span class="data">table_5_1_1</span>.</p>
<div id="Finding-Expected-Value-in-Rguroo" class="callout callout-style-simple callout-note callout-titled" title="![](Rguroo_Icons/R_circle_logo.svg){width=22px style='vertical-align:middle;'} Finding Expected Value and Standard Deviation in Rgruoo">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span><img src="Rguroo_Icons/R_circle_logo.svg" class="img-fluid" style="vertical-align:middle;" width="22"> Finding Expected Value and Standard Deviation in Rgruoo
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Before you begin:</strong> Make sure you have already imported the <span class="data">table_5_1_1</span> dataset into your Rguroo account, as was shown <a href="#Importing-Data-to-Rguroo-Chapter-5">here</a>.</p>
<ol type="1">
<li>Open the <strong>Analysis</strong> toolbox in Rguroo.<br>
</li>
<li>Select <span class="fun">Numerical Summaries</span>. This opens the Numerical Summaries dialog.<br>
</li>
<li>In the Numerical Summaries dialog, choose the <span class="data">table_5_1_1</span> dataset from the <span class="dpd">Dataset</span> dropdown.</li>
<li>Then, select <span class="var">size</span> and either click the right arrow or drag it over to the Selected box.</li>
<li>Select <span class="var">prob</span> in the <span class="dpd">Frequency</span> dropdown menu.</li>
<li>Click the univariate button, then select mean and population standard deviation. We select the population standard deviation since the probability distribution accounts for 100% of the outcomes.<br>
</li>
<li>Click the preview icon <img src="Rguroo_Icons/preview_inline.png" class="img-fluid" alt="preview icon"> to see a preview of the mean (expected value).</li>
</ol>
<div class="inner-callout callout callout-style-simple callout-tip callout-titled" title="Click here to see the Rguroo dialog">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Click here to see the Rguroo dialog
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Rguroo_dialogs/Discrete_Probability/dialog_expected_value.png" class="img-fluid figure-img" width="500"></p>
<figcaption>Numerical Summaries dialog showing settings for finding expected value and standard deviation.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Rguroo_dialogs/Discrete_Probability/expected_value_std_dev_household.png" class="img-fluid figure-img" width="500"></p>
<figcaption>Univariate dialog showing settings for finding expected value and standard deviation.</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-exp-value" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Rguroo output of mean equal to 2.525 and standard deviation equal to 1.422454">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-exp-value-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Rguroo_outputs/Discrete_Probability_Distribution/output_exp_value_std_dev_household.png" class="img-fluid figure-img" alt="Rguroo output of mean equal to 2.525 and standard deviation equal to 1.422454">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-exp-value-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.2: Rguroo Output of Expected Value (Mean) and Standard Deviation
</figcaption>
</figure>
</div>
</div>
</div>
<p>Rguroo gives us <span class="math inline">\(\mu = 2.525\)</span> and <span class="math inline">\(\sigma = 1.422454\)</span></p>
<p>The expected value means that on average, across many households, you can expect about 2.525 people per household. In other words, most households have between 2 and 3 people.</p>
</div>
</div>
</div>
<div id="exm-expected-value2" class="theorem example">
<p><span class="theorem-title"><strong>Example 5.6 (Calculating Expected Value)</strong></span> In the Arizona lottery game called Pick 3, a player pays \$1 and then picks a three-digit number. If those three numbers are picked in that specific order the person wins \$500. What is the expected value to the player in this game? Interpret the expected value.</p>
</div>
<div class="solution-callout callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>🔎 Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>To find the expected value, we need to create a probability distribution with all possible outcomes. Since we are finding the expected value to the player, the random varibale <span class="math inline">\(x\)</span> = winnings to the player.</p>
<p>In the lottery, there are two outcomes for the player: win or lose. If you pick the right numbers in the right order, then you win \$500, but remember, you paid \$1 to play, so you actually win \$499. If you didn’t pick the right numbers, you lose the \$1, and the <span class="math inline">\(x\)</span> value is $-1$.</p>
<p>You also need the probability of winning and losing. Since you are picking a three-digit number, and for each digit there are 10 numbers you can pick with each independent of the others, you can use the multiplication rule. To win, you have to pick the right numbers in the right order. The first digit, you pick 1 number out of 10, the second digit you pick 1 number out of 10, and the third digit you pick 1 number out of 10. So there are <span class="math inline">\(10 \cdot 10 \cdot 10 = 1000\)</span> ways to pick three numbers.</p>
<p>The probability of picking the right number in the right order is $$. The probability of losing (not winning) would be</p>
<p><span class="math inline">\(1-\frac{1}{1000}=\frac{999}{1000}\)</span>.</p>
<p>This can be best orgainized in a table.</p>
<div id="tbl-texts" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Table showing toe outcomes, win or lose. Value of winning is 499, with a probability of 0.001 and value of losing is -1, with a probability of 0.999.">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-texts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.5: Probability distribution for winning lottery
</figcaption>
<div aria-describedby="tbl-texts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>outcome</th>
<th>amount</th>
<th>probability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>win</td>
<td>499</td>
<td>0.001</td>
</tr>
<tr class="even">
<td>lose</td>
<td>-1</td>
<td>0.999</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>We can create this table in Rguroo so we can find the expected value.</p>
<p>Click to expand the box below see how to create a new dataset.</p>
<div id="Creating-Dataset-in-Rguroo" class="callout callout-style-simple callout-note callout-titled" title="![](Rguroo_Icons/R_circle_logo.svg){width=22px style='vertical-align:middle;'} Creating a Dataset in Rgruoo">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span><img src="Rguroo_Icons/R_circle_logo.svg" class="img-fluid" style="vertical-align:middle;" width="22"> Creating a Dataset in Rgruoo
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Open the <strong>Data</strong> toolbox in Rguroo.<br>
</li>
<li>Select <span class="fun">Data Import</span> and select Create New Dataset.</li>
<li>Enter the number of rows and columns. In this case, we only enter the numbers, so enter <span class="typein">2</span> for the No.&nbsp;of Rows and <span class="typein">2</span> for the No.&nbsp;of Columns.</li>
<li>Click, create dataset.</li>
<li>Enter the values in the table. You can use the tab key on your computer to move from cell to cell.</li>
<li>Click the three horizontal line icon by Var1, and select rename. Rename to <span class="typein">Amount</span>. Repeat this process for Var2, and rename to <span class="typein">Probability</span>.<br>
</li>
<li>In Save As… textbox, name the new dataset <span class="typein">Arizona Lottery</span> and click the <span class="button">Save As…</span> button.</li>
</ol>
<div class="inner-callout callout callout-style-simple callout-tip callout-titled" title="Click here to see the Rguroo dataset">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Click here to see the Rguroo dataset
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Rguroo_outputs/Discrete_Probability_Distribution/arizona_lottery_dataset.png" class="img-fluid figure-img" width="500"></p>
<figcaption>Rguroo output showing settings for new dataset.</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>Use Rguroo and the steps from the last example <a href="#exm-expected-value1">here</a> to find the expected value.</p>
<div class="inner-callout callout callout-style-simple callout-tip callout-titled" title="Click here to see the Rguroo dialog">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Click here to see the Rguroo dialog
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Rguroo_dialogs/Discrete_Probability/dialog_expected_value_lottery.png" class="img-fluid figure-img" width="500"></p>
<figcaption>Numerical Summaries dialog showing settings for finding expected value.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Rguroo_dialogs/Discrete_Probability/dialog_exp_value_lottery_mean.png" class="img-fluid figure-img" width="500"></p>
<figcaption>Univariate dialog showing settings for finding expected value.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-exp-value-lottery" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Rguroo output of mean equal to -0.50">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-exp-value-lottery-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Rguroo_outputs/Discrete_Probability_Distribution/expected_value_lottery.png" class="img-fluid figure-img" alt="Rguroo output of mean equal to -0.50">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-exp-value-lottery-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.3: Rguroo Output of Expected Value (Mean) for Arizona Lottery
</figcaption>
</figure>
</div>
</div>
</div>
<p>From Rguroo, we get <span class="math inline">\(\mu_{\text{winnings}} = -0.50\)</span></p>
<p>This means that if you played the lottery <em>many</em> times, you would expect to lose about \$0.50 each game. Remember that expected value is the long-run average. We know we lose exactly \$1 each time, but from winning and losing if we played the game often, we would average a loss of 50 cents per game. Another way to think of this is if we played the game 100 times, we would expect to lose about <span class="math inline">\(0.50 \cdot 1000 =\)</span> \$50.</p>
</div>
</div>
</div>
<div id="exm-expected-value3" class="theorem example">
<p><span class="theorem-title"><strong>Example 5.7 (Using Expected Value)</strong></span> Suppose an auto insurance company collects data on the number of accidents per year for both males and females. Based on the data, the following are probability distributions where <span class="math inline">\(x\)</span> = number of accidents per year.</p>
<div style="width: 50%; margin: auto;">
<div id="tbl-texts" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Table showing values of the random variable as 0, 1, 2, 3, and 4. The probabilities in the second column are 0.50, 0.25, 0.15, 0.07, and 0.03">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-texts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.6: Distribution for number of accidents per year for males
</figcaption>
<div aria-describedby="tbl-texts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(x\)</span></th>
<th><span class="math inline">\(P(x)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>0.50</td>
</tr>
<tr class="even">
<td>1</td>
<td>0.25</td>
</tr>
<tr class="odd">
<td>2</td>
<td>0.15</td>
</tr>
<tr class="even">
<td>3</td>
<td>0.07</td>
</tr>
<tr class="odd">
<td>4</td>
<td>0.03</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
<div style="width: 50%; margin: auto;">
<div id="tbl-texts" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Table showing values of the random variable as 0, 1, 2, 3, and 4. The probabilities in the second column are 0.60, 0.22, 0.10, 0.05, and 0.03">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-texts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.7: Distribution for number of accidents per year for females
</figcaption>
<div aria-describedby="tbl-texts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(x\)</span></th>
<th><span class="math inline">\(P(x)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>0.60</td>
</tr>
<tr class="even">
<td>1</td>
<td>0.22</td>
</tr>
<tr class="odd">
<td>2</td>
<td>0.10</td>
</tr>
<tr class="even">
<td>3</td>
<td>0.05</td>
</tr>
<tr class="odd">
<td>4</td>
<td>0.03</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
<p>How could the insurance company use this data to inform auto policy premiums?</p>
</div>
<div class="solution-callout callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>🔎 Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Insurance companies could compare the expected values of the number of accidents per year for both males and females. Let’s compute both and compare.</p>
<div class="inner-callout callout callout-style-simple callout-tip callout-titled" title="Click here to see the Rguroo dialog">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Click here to see the Rguroo dialog
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Rguroo_dialogs/Discrete_Probability/dialog_male_accidents.png" class="img-fluid figure-img" width="500"></p>
<figcaption>Numerical Summaries dialog showing settings for finding expected value for male accidents.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Rguroo_dialogs/Discrete_Probability/dialog_female_accidents.png" class="img-fluid figure-img" width="500"></p>
<figcaption>Numerical Summaries dialog showing settings for finding expected value for female accidents.</figcaption>
</figure>
</div>
<p>For each summary, don’t forget to click the univariate button and select mean.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Rguroo_dialogs/Discrete_Probability/dialog_exp_value_lottery_mean.png" class="img-fluid figure-img" width="500"></p>
<figcaption>Univariate dialog showing settings for finding expected value.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-exp-value-male-accidents" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Rguroo output of expected value for male accidents">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-exp-value-male-accidents-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Rguroo_outputs/Discrete_Probability_Distribution/output_male_accidents.png" class="img-fluid figure-img" alt="Rguroo output of expected value for male accidents">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-exp-value-male-accidents-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.4: Rguroo Output of Expected Value (Mean) for Male Accidents
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-exp-value-female-accidents" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Rguroo output of expected value for female accidents">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-exp-value-female-accidents-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Rguroo_outputs/Discrete_Probability_Distribution/output_female_accidents.png" class="img-fluid figure-img" alt="Rguroo output of expected value for female accidents">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-exp-value-female-accidents-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.5: Rguroo Output of Expected Value (Mean) for Female Accidents
</figcaption>
</figure>
</div>
</div>
</div>
<p>Using Rguroo, we get the following expected values.</p>
<p><span class="math inline">\(\mu_{\text{males}} = 0.88\)</span></p>
<p><span class="math inline">\(\mu_{\text{females}} = 0.69\)</span></p>
<p>This means, on average (in the long run), males are expected to have about 0.88 accidents per year, while females are expected to have about 0.69 accidents per year. Since males are expected to have more accidents per year, the insurance company could assign higher yearly premiums to male drivers to account for more expected payouts from accidents.</p>
</div>
</div>
</div>
</section>
<section id="unusual-events" class="level3" data-number="5.1.3">
<h3 data-number="5.1.3" class="anchored" data-anchor-id="unusual-events"><span class="header-section-number">5.1.3</span> Unusual Events</h3>
<p>Imagine flipping a fair coin 10 times and getting heads every single time. While it is possible, it is extremely unlikely and would make most people question whether the coin is truly fair. In statistics, this type of outcome is called an <strong>unusual event</strong>, meaning it has a very low probability of occurring under normal conditions. Typically, events with a probability of 5% (or 0.05) or less are considered unusual, and those with a probability of 1% (or 0.01) or less are considered very unusual. Recognizing unusual events helps statisticians determine whether a result is simply due to chance or if there may be an underlying factor influencing the outcome.</p>
<div id="exm-unusual1" class="theorem example">
<p><span class="theorem-title"><strong>Example 5.8 (Determining if an Event is Unusual)</strong></span> Use the 2010 U.S. Census for household size to answer the following questions. The data is in <a href="#tbl-Household" class="quarto-xref">Table&nbsp;<span>5.4</span></a> (\“Households by age,\” 2013).</p>
<ol type="a">
<li><p>Is it unusual to have at most 2 people in a household?</p></li>
<li><p>Is it unusual to have between 3 and 5 people in a household?</p></li>
<li><p>Is it unusual to have more than 7 people in a household?</p></li>
</ol>
</div>
<div class="solution-callout callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>🔎 Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Below is a copy of the dataset for number of people in a household. Remember, the category 7 is really 7 or more people in the household.</p>
<div class="cell" data-tbl-alt="Table showing household size">
<div id="tbl-Household2" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Table showing household size">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Household2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.8: Household Size from U.S. Census of 2010
</figcaption>
<div aria-describedby="tbl-Household2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">size</th>
<th style="text-align: right;">prob</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.267</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.336</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.158</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.137</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.063</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.024</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.015</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<ol type="a">
<li><p>At most two people means either having one or two people in the household. This can also be written as <span class="math inline">\(P(x\le 2)\)</span>. Remember from Chapter 4 that “or” means add, so we get</p>
<p><span class="math inline">\(P(x\le 2) = P(1) + P(2) = 0.267 + 0.336 = 0.603\)</span>.</p>
<p>Since this probability is not less than 0.05, it is not unusual to have at most 2 people in a household.</p></li>
<li><p>Between 3 and 5 people means either 3 or 4 or 5 people. Just as before, we can add all the probabilities together.</p>
<p><span class="math inline">\(P(3\le x \le 5)= P(3) + P(4) + P(5) = 0.158 + 0.137 + 0.063 = 0.358\)</span>.</p>
<p>Again, because this probability is not less than 0.05, it is not ususaul to have between 3 and 5 people in a household.</p></li>
<li><p>For 7 or more people in a household, remember that the row with 7 is really 7 or more people. For this we take the value given in the table,</p>
<p><span class="math inline">\(P(x\ge 7) = 0.015\)</span>.</p>
<p>This probability is less than 0.05, so it is unusual to have 7 or more people in a household.</p></li>
</ol>
</div>
</div>
</div>
</section>
<section id="homework-for-section-5.1" class="level3" data-number="5.1.4">
<h3 data-number="5.1.4" class="anchored" data-anchor-id="homework-for-section-5.1"><span class="header-section-number">5.1.4</span> Homework for Section 5.1</h3>
<ol type="1">
<li>Eyeglassomatic manufactures eyeglasses for different retailers. The number of days it takes to fix defects in an eyeglass and the probability that it will take that number of days are in <a href="#tbl-Days" class="quarto-xref">Table&nbsp;<span>5.9</span></a>.</li>
</ol>
<div tabindex="0" style="width:85%; margin:auto;">
<p><img src="Rguroo_Icons/Rguroo_repo_logo.png" class="img-fluid" alt="Rguroo dataset logo"> The dataset for this exercise is available in the Rguroo dataset repository <span class="repo">Kozak</span>, with the dataset name <span class="data">table_5_1_3</span>.</p>
</div>
<div class="cell" data-tbl-alt="Table showing Number of Days to Fix Eyeglasses">
<div id="tbl-Days" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Table showing Number of Days to Fix Eyeglasses">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Days-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.9: Number of Days to fix Eyeglasses
</figcaption>
<div aria-describedby="tbl-Days-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">days</th>
<th style="text-align: right;">prob</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.249</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.108</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.091</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.123</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.133</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.114</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.070</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.046</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.019</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.013</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: right;">0.010</td>
</tr>
<tr class="even">
<td style="text-align: right;">12</td>
<td style="text-align: right;">0.008</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13</td>
<td style="text-align: right;">0.006</td>
</tr>
<tr class="even">
<td style="text-align: right;">14</td>
<td style="text-align: right;">0.004</td>
</tr>
<tr class="odd">
<td style="text-align: right;">15</td>
<td style="text-align: right;">0.002</td>
</tr>
<tr class="even">
<td style="text-align: right;">16</td>
<td style="text-align: right;">0.002</td>
</tr>
<tr class="odd">
<td style="text-align: right;">17</td>
<td style="text-align: right;">0.001</td>
</tr>
<tr class="even">
<td style="text-align: right;">18</td>
<td style="text-align: right;">0.001</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<ol type="a">
<li>State the random variable.</li>
<li>Draw a histogram of the number of days to fix defects</li>
<li>Find the mean number of days to fix defects.</li>
<li>Find the standard deviation for the number of days to fix defects.</li>
<li>Find probability that a lens will take at least 16 days to make a fix the defect.</li>
<li>Is it unusual for a lens to take 16 days to fix a defect?</li>
<li>If it does take 16 days for eyeglasses to be repaired, what would you think?</li>
</ol>
<ol start="2" type="1">
<li>Suppose you have an experiment where you flip a coin three times. You then count the number of heads.</li>
</ol>
<!-- -->
<ol type="a">
<li>State the random variable.</li>
<li>Write the probability distribution for the number of heads.</li>
<li>Draw a histogram for the number of heads.</li>
<li>Find the mean number of heads.</li>
<li>Find the variance for the number of heads.</li>
<li>Find the standard deviation for the number of heads.</li>
<li>Find the probability of having two or more number of heads.</li>
<li>Is it unusual for to flip two heads?</li>
</ol>
<!-- -->
<ol start="3" type="1">
<li><p>The Ohio lottery has a game called Pick 4 where a player pays \$1 and picks a four-digit number. If the four numbers come up in the order you picked, then you win \$2,500. What is your expected value? Interpret the results.</p></li>
<li><p>An LG Dishwasher, which costs \$800, has a 20% chance of needing to be replaced in the first 2 years of purchase. A two-year extended warranty costs \$112.10 on a dishwasher. What is the expected value of the extended warranty assuming it is replaced in the first 2 years? Interpret the results.</p></li>
</ol>
</section>
</section>
<section id="binomial-probability-distribution" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="binomial-probability-distribution"><span class="header-section-number">5.2</span> Binomial Probability Distribution</h2>
<p>Imagine a factory that produces light bulbs, where each bulb can either be defective or not defective. If a company tests 20 bulbs and wants to know the probability that exactly 3 are defective, they need a systematic way to calculate that likelihood. In Section 5.1, we learned about probability distributions. One important type of probability distribution is the <strong>binomial probability distribution</strong>, which comes from a <strong>binomial experiment</strong>. In a binomial experiment, each trial is called a <strong>Bernoulli trial</strong>. This type of experiment allows us to calculate a specific number of successes.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Properties of a Binomial Experiment
</div>
</div>
<div class="callout-body-container callout-body">
<p>Let <span class="math inline">\(X\)</span> be the random variable representing the number of successes in <span class="math inline">\(n\)</span> trials</p>
<ol type="1">
<li><p>The experiment has a fixed number of trials, <span class="math inline">\(n\)</span>.</p></li>
<li><p>The <span class="math inline">\(n\)</span> trials are independent, which means that what happens on one trial does not influence the outcomes of other trials.</p></li>
<li><p>There are only two disjoint outcomes, which are called a success and a failure.</p></li>
<li><p>The probability of a success doesn’t change from trial to trial, where <span class="math inline">\(p\)</span> = probability of success and <span class="math inline">\(q = 1-p\)</span> = probability of failure.</p></li>
</ol>
</div>
</div>
<p>If you know you have a binomial experiment, then you can calculate binomial probabilities. This is important because binomial probabilities come up often in real life. Examples of binomial experiments are:</p>
<p>Toss a fair coin ten times, and find the probability of getting two heads.</p>
<p>Question twenty people in class, and look for the probability of more than half being women?</p>
<p>Shoot five arrows at a target, and find the probability of hitting it five times?</p>
<div id="exm-binomial-conditions" class="theorem example">
<p><span class="theorem-title"><strong>Example 5.9 (Verify if Experiment is Binomial)</strong></span> Determine if the following represent a binomial experiment. If it is not binomial, explain why.</p>
<ol type="a">
<li><p>You survey 200 people at random and ask if they think gas prices are too high.</p></li>
<li><p>You roll a six-sided fair die 8 times and record the face value.</p></li>
<li><p>You select 5 cards from a standard deck without replacement and record the number of Aces.</p></li>
<li><p>You select 3 marbles from a bag with replacement and record the number of green marbles.</p></li>
</ol>
</div>
<div class="solution-callout callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>🔎 Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In each case we will define <span class="math inline">\(X\)</span> as the number of successes in <span class="math inline">\(n\)</span> trials. We need to verify that all four properties of a binomial experiment are met.</p>
<p><em>Property 1: Fixed number of trials.</em></p>
<p><em>Property 2: Trials are independent.</em></p>
<p><em>Property 3: Two disjoint outcomes.</em></p>
<p><em>Property 4: Probability of success is the same for each trial.</em></p>
<ol type="a">
<li><p>Let <span class="math inline">\(X\)</span> = the&nbsp;number&nbsp;of&nbsp;people&nbsp;(out&nbsp;of&nbsp;200)&nbsp;who&nbsp;think&nbsp;gas&nbsp;prices&nbsp;are&nbsp;too&nbsp;high.</p>
<p>Property 1: Since we survey 200 people, <span class="math inline">\(n=200\)</span> is fixed.</p>
<p>Property 2: One person’s answer does not affect the next person’s answer, so the trials are independent.</p>
<p>Property 3: The person can answer yes or no, so there are two disjoint outcomes.</p>
<p>Property 4: The probability that a person says “yes” is 50% and is the same for each trial.</p>
<p>Since all four properties are met, this is a binomial experiment.</p></li>
<li><p>Let <span class="math inline">\(X\)</span> = the&nbsp;face&nbsp;value&nbsp;obtained&nbsp;on&nbsp;a&nbsp;single&nbsp;roll&nbsp;of&nbsp;the&nbsp;die.</p>
<p>Property 1: Since we roll the die 8 times, <span class="math inline">\(n=8\)</span> is fixed.</p>
<p>Property 2: Rolling a die does not affect the next roll, so the trials are independent.</p>
<p>Property 3: Since you record the face value of the die, there are 6 outcomes (1, 2, 3, 4, 5, 6).</p>
<p>Since there are 6 outcomes, this is not a binomial experiment and we do not need to continue verifying the properties.</p></li>
<li><p>Let <span class="math inline">\(X\)</span> = the&nbsp;number&nbsp;of&nbsp;Aces&nbsp;obtained&nbsp;in&nbsp;the&nbsp;5&nbsp;cards&nbsp;selected.</p>
<p>Property 1: Since we select 5 cards, <span class="math inline">\(n=5\)</span> is fixed.</p>
<p>Property 2: Since you draw the cards without replacement, the first draw is out of 52 cards, the next draw is out of 51 card, and so on. So the trials are not independent.</p>
<p>Since the trials are not independent, this is not a binomial experiment and we do not need to continue verifying properties.</p></li>
<li><p>Let <span class="math inline">\(X\)</span> = the&nbsp;number&nbsp;of&nbsp;green&nbsp;marbles&nbsp;obtained&nbsp;in&nbsp;the&nbsp;3&nbsp;selections.</p>
<p>Property 1: Since we draw 3 marbles, <span class="math inline">\(n=3\)</span> is fixed.</p>
<p>Property 2: Since we draw <em>with replacement</em>, we will be always drawing out of the original bag of marbles. So, the trials are independent.</p>
<p>Property 3: When we draw a marble, we record if it is green or not green, so there are two disjoint outcomes.</p>
<p>Property 4: Again, since we draw with replacement, the probability of drawing a green is the same for all trials.</p>
<p>Since all four properties are met, this is a binomial experiment.</p></li>
</ol>
</div>
</div>
</div>
<section id="calculating-binomial-probabilities" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="calculating-binomial-probabilities"><span class="header-section-number">5.2.1</span> Calculating Binomial Probabilities</h3>
<p>Just as we did in Section 5.1, we need to define our random variable <span class="math inline">\(X\)</span>. Since we measure success in a binomial experiment, the random variable is <span class="math inline">\(X\)</span> = number of successes.</p>
<p>Note, success does not always mean a positive outcome. For example, for medication trials, you may want to measure the number of side effects. In this case, the side effects would be considered the “success.” So, a success just means you observed the outcome you are measuring.</p>
<p>To calculate binomial probabilities, there are two methods, a formula and using technology, such as Rguroo.</p>
<p>The Binomial Formula for the probability is</p>
<p><span class="math display">\[P(X=r)=_nC_r\cdot p^r \cdot q^{n-r}\]</span></p>
<p>where <span class="math inline">\(n\)</span> is the number of trials, <span class="math inline">\(r\)</span> is the number of successes, <span class="math inline">\(p\)</span> is the probability of success, and <span class="math inline">\(q = (1-p)\)</span> is the probability of failure. Note: <span class="math inline">\(_nC_r\)</span> is the number of combinations of <span class="math inline">\(n\)</span> things taking <span class="math inline">\(r\)</span> at a time (from Chapter 4).</p>
<p>When solving problems, make sure you define your random variable and state what <span class="math inline">\(n\)</span>, <span class="math inline">\(p\)</span>, and <span class="math inline">\(r\)</span> are. This makes calculating binomial probabilities much easier. Also, remember that binomial probabilities still follow the probability rules that each probability is between 0 and 1, inclusive and all probabilities add to a total of 1.</p>
<div id="exm-calculating-binomial1" class="theorem example">
<p><span class="theorem-title"><strong>Example 5.10 (Calculating Binomial Probability)</strong></span> When looking at a person’s eye color, it turns out that 1% of people in the world have green eyes (“What percentage of,” 2013). Consider a group of 20 people. Use the formula to find the probabilities.</p>
<ol type="a">
<li>Verify that this is a binomial experiment.</li>
<li>State the random variable, the number of trials, and the probability of success.</li>
<li>Find the probability that none of the 20 people have green eyes.</li>
<li>Find the probability that exactly 9 of the people have green eyes.</li>
<li>Find the probability that at most 1 person has green eyes.</li>
</ol>
</div>
<div class="solution-callout callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>🔎 Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><p>To verify that this is a binomial distribution, we need to check all four properties.</p>
<p>Property 1: There are a fixed number of trials since we have 20 people total.</p>
<p>Property 2: Since the eye color of one person does not affect the eye color of another person, the trials are independent.</p>
<p>Property 3: Since we are recording if the eye color is green or not green, there are two disjoint outcomes.</p>
<p>Property 4: The probability of a person having green eyes is 0.01 and that probability is the same for each person in this experiment.</p></li>
<li><p>Since we wish to measure the number of people with green eyes, we have the following</p>
<p><span class="math inline">\(x\)</span> = number of people with green eyes</p>
<p><span class="math inline">\(n = 20\)</span></p>
<p><span class="math inline">\(p = 0.01\)</span></p></li>
<li><p>If none of the 20 people have green eyes, <span class="math inline">\(r=0\)</span>. Plugging into the formula, we get</p>
<p><span class="math inline">\(P(X=0)=_{20}C_0\cdot (0.01)^0 \cdot (1-0.01)^{20-0}\)</span></p>
<p><span class="math inline">\(= _{20}C_0\cdot (0.01)^0 \cdot (0.99)^{20}\)</span></p>
<p><span class="math inline">\(= (1)(1)(0.8179) = 0.8179\)</span></p></li>
<li><p>For exactly 9 people to have green eyes, we use the same technique, only <span class="math inline">\(r=9\)</span></p>
<p><span class="math inline">\(P(X=9)=_{20}C_9\cdot (0.01)^9 \cdot (1-0.01)^{20-9}\)</span></p>
<p><span class="math inline">\(= _{20}C_9\cdot (0.01)^9 \cdot (0.99)^{11}\)</span></p>
<p><span class="math inline">\(= 1.5 \cdot 10^{-13}\)</span></p>
<p><span class="math inline">\(1.5 \cdot 10^{-13}\)</span> is scientific notation, where if we converted this to a standard number, we would need to move the decimal place left 13 places. This means the probability of 9 people out of 20 having green eyes is extremly small, almost 0. Finding 9 people out of 20 that have green eyes would be considered unusual.</p></li>
<li><p>If we want the probability of at most 1 person, then <span class="math inline">\(r\)</span> could be 0 or 1 people having green eyes. Just as we did before, we will find the probabilities and add them together.</p>
<p><span class="math inline">\(P(x\le 1) = P(X=0) + P(X=1)\)</span></p>
<p>This means we will need to use the formula twice and add the values together. Luckily, we already found <span class="math inline">\(P(X=0) = 0.8179\)</span> in part b. So we will focus on finding <span class="math inline">\(P(X=1)\)</span></p>
<p><span class="math inline">\(P(X=1)=_{20}C_1\cdot (0.01)^1 \cdot (1-0.01)^{20-1}\)</span></p>
<p><span class="math inline">\(= _{20}C_1\cdot (0.01)^1 \cdot (0.99)^{19}\)</span></p>
<p><span class="math inline">\(= 0.1652\)</span></p>
<p>So <span class="math inline">\(P(x\le 1) = P(X=0) + P(X=1) = 0.8179 + 0.1652 = 0.9831\)</span></p></li>
</ol>
</div>
</div>
</div>
<p>Notice that the formula for binomial probabilities only calculates <em>exact</em> probabilities. As we saw in part (e) of the last example, we needed to use the formula twice. Only using the formula for binomial probabilities can be time consuming since we do not always want to find exact probabilities. That is where technology, such as Rguroo, comes in!</p>
<div id="exm-calculating-binomial2" class="theorem example">
<p><span class="theorem-title"><strong>Example 5.11 (Calculating Binomial Probability)</strong></span> According to the Center for Disease Control (CDC), about 1 in 88 children in the U.S. have been diagnosed with autism (“CDC-data and statistics,” 2013). Suppose you consider a group of 10 children. Use Rguroo to find the probabilities.</p>
<ol type="a">
<li>Verify that this is a binomial experiment.</li>
<li>State the random variable, the number of trials, and the probability of success.</li>
<li>Find the probability that none have autism.</li>
<li>Find the probability that at least five have autism.</li>
<li>Find the probability that at most two have autism.</li>
<li>Find the probability that between 1 and 4, inclusive of 1 but not 4, have autism.</li>
<li>Suppose six children out of ten have autism. Is this unusual? What does that tell you?</li>
</ol>
</div>
<div class="solution-callout callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-29-contents" aria-controls="callout-29" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>🔎 Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-29" class="callout-29-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><p>We again need to verify all four properties.</p>
<p>Property 1: There are 10 children, and each child is a trial, so there are a fixed number of trials.</p>
<p>Property 2: Whether a child has autism does not affect the chance that the next child has autism. Thus the trials are independent.</p>
<p>Property 3: Either a child has autism or they do not have autism, so there are two disjoint outcomes.</p>
<p>Property 4: The probability of a child having autism is <span class="math inline">\(\frac{1}{88}\)</span>. This is the same for every trial since each child has the same chance of having autism.</p></li>
<li><p>Since we wish to measure whether the child has autism, we have the following</p>
<p><span class="math inline">\(x\)</span> = number of children with autism</p>
<p><span class="math inline">\(n = 10\)</span></p>
<p><span class="math inline">\(p = \frac{1}{88}\)</span></p></li>
<li><p>To find the probability that none have autism, <span class="math inline">\(r=0\)</span> and we find <span class="math inline">\(P(X=0)\)</span></p></li>
</ol>
<p>Click to expand the box below to see how to calculate binomial probabilities.</p>
<div id="Calculate-Bin_Prob-in-Rguroo" class="callout callout-style-simple callout-note callout-titled" title="![](Rguroo_Icons/R_circle_logo.svg){width=22px style='vertical-align:middle;'} Calculating Binomial Probabilities in Rgruoo">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span><img src="Rguroo_Icons/R_circle_logo.svg" class="img-fluid" style="vertical-align:middle;" width="22"> Calculating Binomial Probabilities in Rgruoo
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Open the <strong>Probability-Simulation</strong> toolbox in Rguroo.<br>
</li>
<li>Click on the <span class="dpd">Probability</span>, hover over <span class="fun">Probability Calculator</span>, and select <span class="fun">Discrete</span>. This opens the <span class="dialog">Discrete Distributions Probability Calculator</span> dialog.</li>
<li>In the <span class="dialog">Discrete Distributions Probability Calculator</span> dialog, select <span class="dpd">Binomial</span> from the dropdown menu (it usually defaults to this).</li>
<li>Select Values <span class="math inline">\(\Rightarrow\)</span> Probability, since we will be inputting values and we want the probability.</li>
<li>Enter <span class="typein">20</span> for the No.&nbsp;of Trials and <span class="typein">1/88</span> for the Prob. of Success.</li>
<li>Since we want the probability of exactly 0, select <span class="dpd">Equal</span> in the dropdown menu. Then enter <span class="typein">0</span> in the next box.</li>
<li>Click the preview icon <img src="Rguroo_Icons/preview_inline.png" class="img-fluid" alt="preview icon"> to see the probability.</li>
</ol>
<div class="inner-callout callout callout-style-simple callout-tip callout-titled" title="Click here to see the Rguroo dialog">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Click here to see the Rguroo dialog
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Rguroo_dialogs/Discrete_Probability/binomial_autism_x_0.png" class="img-fluid figure-img" width="500"></p>
<figcaption>Rguroo dialog showing binomial probability.</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>Rguroo gives <span class="math inline">\(P(X=0)=0.892\)</span></p>
<ol start="4" type="a">
<li>At least 5 have autism would be finidng <span class="math inline">\(P(X\ge 5)\)</span>. Follow the same steps as in part (c), but adjust for the values and inequality sign. In this case, we would select <span class="dpd">Above</span> in the dropdown since we want greater than. Notice also that a little check box appears. When the box is checked, it means to include the value. Since we want greater than <em>or equal to</em> keep the box checked.</li>
</ol>
<div class="inner-callout callout callout-style-simple callout-tip callout-titled" title="Click here to see the Rguroo dialog">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-25-contents" aria-controls="callout-25" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Click here to see the Rguroo dialog
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-25" class="callout-25-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Rguroo_dialogs/Discrete_Probability/binomial_autism_x_5.png" class="img-fluid figure-img" width="500"></p>
<figcaption>Rguroo dialog showing binomial probability.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>Rguroo gives <span class="math inline">\(P(X\ge 5) = 4.5534 e-08\)</span></p>
<p>This is scientific notation, and if we were to write in standard form we would move the decimal left 8 places. Taht means that the probability is very small.</p>
<ol start="5" type="a">
<li>At most two have autism would be finding <span class="math inline">\(P(\le2)\)</span>. We will use Rguroo again. In this case, we would select <span class="dpd">Below</span> and keep the little box checked.</li>
</ol>
<div class="inner-callout callout callout-style-simple callout-tip callout-titled" title="Click here to see the Rguroo dialog">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-26-contents" aria-controls="callout-26" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Click here to see the Rguroo dialog
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-26" class="callout-26-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Rguroo_dialogs/Discrete_Probability/binomial_autism_x_2.png" class="img-fluid figure-img" width="500"></p>
<figcaption>Rguroo dialog showing binomial probability.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>Rguroo gives <span class="math inline">\(P(X\le2) = 0.99983\)</span></p>
<ol start="6" type="a">
<li>Between 1 and 4, inclusive of 1 but not 4, have autism would be finding <span class="math inline">\(P(1\le X&lt;4)\)</span></li>
</ol>
<p>In the Rguroo probability calculator, select <span class="dpd">Between</span>. Notice that two boxes appear with two little boxes next to them. We will enter <span class="typein">1</span> in the Lower tail box and <span class="typein">4</span> in the Upper tail box. Since we want to inlcude 1, we leave the little check box next to 1. Since we do not want to include 4, we uncheck the little box next to 4.</p>
<div class="inner-callout callout callout-style-simple callout-tip callout-titled" title="Click here to see the Rguroo dialog">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-27-contents" aria-controls="callout-27" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Click here to see the Rguroo dialog
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-27" class="callout-27-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Rguroo_dialogs/Discrete_Probability/binomial_autism_x_1_4.png" class="img-fluid figure-img" width="500"></p>
<figcaption>Rguroo dialog showing binomial probability.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>Rguroo gives <span class="math inline">\(P(1\le X&lt;4) = 0.110799\)</span></p>
<ol start="7" type="a">
<li>To find if 6 out of 10 children having autism is unusual, we need to find the probability of <span class="math inline">\(P(X=6)\)</span>.</li>
</ol>
<div class="inner-callout callout callout-style-simple callout-tip callout-titled" title="Click here to see the Rguroo dialog">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-28-contents" aria-controls="callout-28" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Click here to see the Rguroo dialog
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-28" class="callout-28-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Rguroo_dialogs/Discrete_Probability/binomial_autism_x_6.png" class="img-fluid figure-img" width="500"></p>
<figcaption>Rguroo dialog showing binomial probability.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>Rguroo gives <span class="math inline">\(P(X=6) = 4.3199e-10\)</span>. If we change this to a standard number, we would get <span class="math inline">\(0.00000000043199\)</span>. Since this is less than 0.05, it is unusual for 6 children out of 10 to have autism. If this does happen, then one may think that the proportion of children diagnosed with autism is actually more than <span class="math inline">\(\frac{1}{88}\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="mean-and-standard-deviation" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="mean-and-standard-deviation"><span class="header-section-number">5.2.2</span> Mean and Standard Deviation</h3>
<p>If you list all possible values of <span class="math inline">\(x\)</span> in a Binomial distribution, you get the <strong>Binomial Probability Distribution</strong>. When working with a binomial probability distribution, we are often interested not only in the probability of specific outcomes but also in the overall behavior of the distribution. Two important measures that describe this behavior are the mean and standard deviation. The mean tells us the expected number of successes in a given number of trials, while the standard deviation measures how much the results typically vary from that expected value. Together, these values provide a clearer understanding of where most outcomes are likely to fall and how spread out the distribution is, helping us interpret binomial experiments more effectively.</p>
<p>Just like calculating expected value, there are two ways to compute the mean and standard deviation of a binomial distribution; a formula and using technology.</p>
<p>For a binomial random variable, the formulas for the mean, <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span> are</p>
<p><span class="math inline">\(\mu = np\)</span> <span class="math inline">\(\;\)</span> and <span class="math inline">\(\;\)</span> <span class="math inline">\(\sigma = \sqrt{np(1-p)}\)</span></p>
<p>These formulas are useful since they are simple. However, you can also use technology to find the mean and standard deviation as we did in Section 5.1.</p>
<div id="exm-calculating-binomial-mean-std-dev" class="theorem example">
<p><span class="theorem-title"><strong>Example 5.12 (Calculating Mean and Standard Deviation for Binomial Probability)</strong></span> A hospital finds that a vaccine is effective 95% of the time. A nurse administers the vaccine to 20 patients. Let <span class="math inline">\(X\)</span> represent the number of patients for whom the vaccine is effective.</p>
<ol type="a">
<li><p>Find the mean and standard deviation of the distribution.</p></li>
<li><p>Interpret both values in the context of this scenario.</p></li>
</ol>
</div>
<div class="solution-callout callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-30-contents" aria-controls="callout-30" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>🔎 Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-30" class="callout-30-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Note: You should always verify that the experiment is a binomial experiment (satisfies the four properties) <em>before</em> using the binomial distribution formulas for the mean and standard deviation. This experiment is a binomial experiment, with <span class="math inline">\(n = 20\)</span> and <span class="math inline">\(p = 0.95\)</span>.</p>
<ol type="a">
<li><p>The mean is <span class="math inline">\(\mu = np = (20)(0.95) = 19\)</span></p>
<p>The standard deviation is <span class="math inline">\(\sigma = \sqrt{np(1-p)} = \sqrt{(20)(0.95)(1-0.95)} = \sqrt{(20)(0.95)(0.05)} = 0.975\)</span></p></li>
<li><p>A mean of 19 means that, on average, we expect about 19 out of 20 patients to have an effective response to the vaccine. The standard deviation of about 0.98 indicates that the number of successful outcomes typically varies by about 1 patient from the mean.</p></li>
</ol>
</div>
</div>
</div>
</section>
<section id="creating-probability-distributions" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3" class="anchored" data-anchor-id="creating-probability-distributions"><span class="header-section-number">5.2.3</span> Creating Probability Distributions</h3>
<p>When a situation meets the conditions of a binomial experiment (satisfying all four properties), we can build a binomial probability distribution using the values of <span class="math inline">\(n\)</span> (number of trials) and <span class="math inline">\(p\)</span> (probability of success). This distribution shows the likelihood of obtaining each possible number of successes, from <span class="math inline">\(0\)</span> up to <span class="math inline">\(n\)</span>. By using Rguroo to find the probability for each value of the random variable <span class="math inline">\(x\)</span>, we can construct the full distribution and better understand how probable different outcomes are in a real-world scenario.</p>
<div id="exm-binomial-distribution" class="theorem example">
<p><span class="theorem-title"><strong>Example 5.13 (Creating a Distribution for Binomial Probability)</strong></span> Imagine a quality inspector at a factory is checking boxes of batteries for defects. Each battery has a 1% chance of being defective, and the inspector selects a box of 15 batteries. A sample of 3 batteries from the box is selected at random with replacement. Define the random variable X as the number of defective batteries in the box.</p>
<ol type="a">
<li><p>Construct a binomial distribution for X.</p></li>
<li><p>What is the expected value of X? Interpret the results.</p></li>
</ol>
</div>
<div class="solution-callout callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-31-contents" aria-controls="callout-31" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>🔎 Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-31" class="callout-31-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Note: You should always verify that the experiment is a binomial experiment (satisfies the four properties) <em>before</em> using the binomial distribution formulas for the mean and standard deviation. This experiment is a binomial experiment.</p>
<ol type="a">
<li>To construct a binomial distribution, we need to create a table that lists all the possible values of the random variable <span class="math inline">\(X\)</span> along with their probabilities. Since we are sampling 3 batteries, <span class="math inline">\(n = 3\)</span>, and the number of defective batteries could be <span class="math inline">\(x=0, 1, 2, 3\)</span> in that sample. We also know that <span class="math inline">\(p=0.01\)</span>. Now we need to find the probability of each outcome.</li>
</ol>
<p>For <span class="math inline">\(P(X=0)\)</span>, we will use Rguroo to find the exact probability as we did in <a href="#exm-calculating-binomial2">Example 5.11</a>, with No.&nbsp;of Trials being <span class="typein">3</span>, Prob. of Success being <span class="typein">0.01</span>, using <span class="dpd">Equal</span> and <span class="typein">0</span>. Then, we will repeat the process for all the values of <span class="math inline">\(x\)</span>. To easily repeat the process in Rguroo, simply change the value next to the <span class="dpd">Equal</span> and click on the preview button.</p>
<p>Organizing this into a table, we get</p>
<div style="width: 50%; margin: auto;">
<div id="tbl-texts" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Table showing values of the random variable as 0, 1, 2, and 3. The binomial probabilities in the second column are 0.60, 0.22, 0.10, 0.05, and 0.03">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-texts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.10: Binomial distribution for number of defective batteries in a sample of 3
</figcaption>
<div aria-describedby="tbl-texts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(x\)</span></th>
<th><span class="math inline">\(P(x)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>0.9703</td>
</tr>
<tr class="even">
<td>1</td>
<td>0.0294</td>
</tr>
<tr class="odd">
<td>2</td>
<td>0.0003</td>
</tr>
<tr class="even">
<td>3</td>
<td>0.000001</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
<ol start="2" type="a">
<li><p>Since this is a binomial experiment, we can use the formula to find the expected value.</p>
<p>The expected value is <span class="math inline">\(\mu = np = (3)(0.01) = 0.03\)</span></p>
<p>This means that on average, we expect about 0.03 defective batteries in a sample of 3 batteries. So, in most samples of 3, we would expect no defective batteries.</p></li>
</ol>
</div>
</div>
</div>
</section>
<section id="homework-for-section-5.2" class="level3" data-number="5.2.4">
<h3 data-number="5.2.4" class="anchored" data-anchor-id="homework-for-section-5.2"><span class="header-section-number">5.2.4</span> Homework for Section 5.2</h3>
<ol type="1">
<li>Approximately 10% of all people are left-handed (\“11 little-known facts,\” 2013). Consider a grouping of fifteen people.</li>
</ol>
<ol type="a">
<li>Verify that this is a binomial experiment.</li>
<li>State the random variable, the number of trials, and the probability of success.</li>
<li>Find the probability that none are left-handed.</li>
<li>Find the probability that seven are left-handed.</li>
<li>Find the probability that at least two are left-handed.</li>
<li>Find the probability that at most three are left-handed.</li>
<li>Find the probability that at least seven are left-handed.</li>
<li>Seven of the last 15 U.S. Presidents were left-handed. Is this unusual? What does that tell you?</li>
</ol>
<ol start="2" type="1">
<li>According to an article in the American Heart Association’s publication *Circulation*, 24% of patients who had been hospitalized for an acute myocardial infarction did not fill their cardiac medication by the seventh day of being discharged (Ho, Bryson &amp; Rumsfeld, 2009). Suppose there are twelve people who have been hospitalized for an acute myocardial infarction.</li>
</ol>
<ol type="a">
<li>Verify that this is a binomial experiment.</li>
<li>State the random variable, the number of trials, and the probability of success.</li>
<li>Find the probability that all filled their cardiac medication.</li>
<li>Find the probability that seven did not fill their cardiac medication.</li>
<li>Find the probability that none filled their cardiac medication.</li>
<li>Find the probability that at most two did not fill their cardiac medication.</li>
<li>Find the probability that at least three did not fill their cardiac medication.</li>
<li>Find the probability that at least ten did not fill their cardiac medication.</li>
<li>Suppose of the next twelve patients discharged, ten did not fill their cardiac medication, would this be unusual? What does this tell you?</li>
</ol>
<ol start="3" type="1">
<li>Eyeglassomatic manufactures eyeglasses for different retailers. In March 2010, they tested to see how many defective lenses they made, and there were 16.9% defective lenses due to scratches. Suppose Eyeglassomatic examined twenty eyeglasses.</li>
</ol>
<ol type="a">
<li>Verify that this is a binomial experiment.</li>
<li>State the random variable, the number of trials, and the probability of success.</li>
<li>Find the probability that none are scratched.</li>
<li>Find the probability that all are scratched.</li>
<li>Find the probability that at least three are scratched.</li>
<li>Find the probability that at most five are scratched.</li>
<li>Find the probability that at least ten are scratched.</li>
<li>Is it unusual for ten lenses to be scratched? If it turns out that ten lenses out of twenty are scratched, what might that tell you about the manufacturing process?</li>
</ol>
<ol start="4" type="1">
<li>The proportion of brown M&amp;M’s in a milk chocolate packet is approximately 14% (Madison, 2013). Suppose a package of M&amp;M’s typically contains 52 M&amp;M’s.</li>
</ol>
<ol type="a">
<li>Verify that this is a binomial experiment.</li>
<li>State the random variable, the number of trials, and the probability of success.</li>
<li>Find the probability that six M&amp;M’s are brown.</li>
<li>Find the probability that twenty-five M&amp;M’s are brown.</li>
<li>Find the probability that all of the M&amp;M’s are brown.</li>
<li>Would it be unusual for a package to have only brown M&amp;M’s? If this were to happen, what would you think is the reason?</li>
</ol>
<ol start="5" type="1">
<li>Suppose a random variable, <span class="math inline">\(x\)</span>, arises from a binomial experiment. Suppose <span class="math inline">\(n = 6\)</span>, and <span class="math inline">\(p = 0.13\)</span>.</li>
</ol>
<ol type="a">
<li>Create a probability distribution.</li>
<li>Find the mean.</li>
<li>Find the standard deviation.</li>
</ol>
<ol start="6" type="1">
<li>Suppose a random variable, <span class="math inline">\(x\)</span>, arises from a binomial experiment. Suppose <span class="math inline">\(n = 10\)</span>, and <span class="math inline">\(p = 0.81\)</span>.</li>
</ol>
<ol type="a">
<li>Create a probability distribution.</li>
<li>Find the mean.</li>
<li>Find the standard deviation.</li>
</ol>
<ol start="7" type="1">
<li>Suppose a random variable, <span class="math inline">\(x\)</span>, arises from a binomial experiment. Suppose <span class="math inline">\(n = 7\)</span>, and <span class="math inline">\(p = 0.50\)</span>.</li>
</ol>
<ol type="a">
<li>Create a probability distribution.</li>
<li>Find the mean.</li>
<li>Find the standard deviation.</li>
</ol>
<ol start="8" type="1">
<li>Approximately 10% of all people are left-handed. Consider a grouping of fifteen people.</li>
</ol>
<ol type="a">
<li>Verify that this is a binomial experiment.</li>
<li>State the random variable.</li>
<li>Create a probability distribution.</li>
<li>Find the mean and interpret the value.</li>
<li>Find the standard deviation and interpret the value.</li>
</ol>
<ol start="9" type="1">
<li>According to an article in the American Heart Association’s publication *Circulation*, 24% of patients who had been hospitalized for an acute myocardial infarction did not fill their cardiac medication by the seventh day of being discharged (Ho, Bryson &amp; Rumsfeld, 2009). Suppose there are twelve people who have been hospitalized for an acute myocardial infarction.</li>
</ol>
<ol type="a">
<li>Verify that this is a binomial experiment.</li>
<li>State the random variable.</li>
<li>Create a probability distribution.</li>
<li>Find the mean and interpret the value.</li>
<li>Find the standard deviation and interpret the value.</li>
</ol>
<ol start="10" type="1">
<li>Eyeglassomatic manufactures eyeglasses for different retailers. In March 2010, they tested to see how many defective lenses they made, and there were 16.9% defective lenses due to scratches. Suppose Eyeglassomatic examined twenty eyeglasses.</li>
</ol>
<ol type="a">
<li>Verify that this is a binomial experiment.</li>
<li>State the random variable.</li>
<li>Create a probability distribution.</li>
<li>Find the mean and interpret the value.</li>
<li>Find the standard deviation and interpret the value.</li>
</ol>
<ol start="11" type="1">
<li>The proportion of brown M&amp;M’s in a milk chocolate packet is approximately 14% (Madison, 2013). Suppose a package of M&amp;M’s typically contains 52 M&amp;M’s.</li>
</ol>
<ol type="a">
<li>Verify that this is a binomial experiment.</li>
<li>State the random variable.</li>
<li>Find the mean and interpret the value.</li>
<li>Find the standard deviation and interpret the value.</li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script>

document.addEventListener("DOMContentLoaded", function () {

  document.querySelectorAll('a[href]').forEach(function (link) {

    link.setAttribute("target", "_blank");

    link.setAttribute("rel", "noopener noreferrer");

  });

});

</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Probability.html" class="pagination-link" aria-label="Probability">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Probability</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Continuous Probability Distribution.html" class="pagination-link" aria-label="Continuous Probability Distribution">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Continuous Probability Distribution</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>