<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>8&nbsp; Estimation – Statistics Using Technology: Rguroo Edition</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Two Sample Inference.html" rel="next">
<link href="./One Sample Inference.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Estimation.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Estimation</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics Using Technology: Rguroo Edition</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Statistical Basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Statistical Basics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Graphical Description of Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Graphical Description of Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Numerical-description-of-Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Numerical Description of Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Discrete Probability Distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Discrete Probability Distribution</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Continuous Probability Distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Continuous Probability Distribution</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./One Sample Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">One Sample Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Estimation.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Two Sample Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Two Sample Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chi-Square and ANOVA Tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Chi-squared and ANOVA Tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./References.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#basics-of-confidence-intervals" id="toc-basics-of-confidence-intervals" class="nav-link active" data-scroll-target="#basics-of-confidence-intervals"><span class="header-section-number">8.1</span> Basics of Confidence Intervals</a>
  <ul class="collapse">
  <li><a href="#interpreting-a-confidence-interval" id="toc-interpreting-a-confidence-interval" class="nav-link" data-scroll-target="#interpreting-a-confidence-interval"><span class="header-section-number">8.1.1</span> Interpreting a confidence interval:</a></li>
  <li><a href="#example-stating-the-statistical-and-real-world-interpretations-for-a-confidence-interval" id="toc-example-stating-the-statistical-and-real-world-interpretations-for-a-confidence-interval" class="nav-link" data-scroll-target="#example-stating-the-statistical-and-real-world-interpretations-for-a-confidence-interval"><span class="header-section-number">8.1.2</span> Example: Stating the Statistical and Real World Interpretations for a Confidence Interval</a></li>
  <li><a href="#homework-for-basics-of-confidence-intervals-section" id="toc-homework-for-basics-of-confidence-intervals-section" class="nav-link" data-scroll-target="#homework-for-basics-of-confidence-intervals-section"><span class="header-section-number">8.1.3</span> Homework for Basics of Confidence Intervals Section</a></li>
  </ul></li>
  <li><a href="#one-sample-interval-for-the-proportion" id="toc-one-sample-interval-for-the-proportion" class="nav-link" data-scroll-target="#one-sample-interval-for-the-proportion"><span class="header-section-number">8.2</span> One-Sample Interval for the Proportion</a>
  <ul class="collapse">
  <li><a href="#confidence-interval-for-one-population-proportion-1-prop-interval" id="toc-confidence-interval-for-one-population-proportion-1-prop-interval" class="nav-link" data-scroll-target="#confidence-interval-for-one-population-proportion-1-prop-interval"><span class="header-section-number">8.2.1</span> Confidence Interval for One Population Proportion (1-Prop Interval)</a></li>
  <li><a href="#example-confidence-interval-for-the-population-proportion" id="toc-example-confidence-interval-for-the-population-proportion" class="nav-link" data-scroll-target="#example-confidence-interval-for-the-population-proportion"><span class="header-section-number">8.2.2</span> Example: Confidence Interval for the Population Proportion</a></li>
  <li><a href="#example-confidence-interval-for-the-population-proportion-1" id="toc-example-confidence-interval-for-the-population-proportion-1" class="nav-link" data-scroll-target="#example-confidence-interval-for-the-population-proportion-1"><span class="header-section-number">8.2.3</span> Example: Confidence Interval for the Population Proportion</a></li>
  <li><a href="#homework-for-one-sample-interval-for-the-proportion-section" id="toc-homework-for-one-sample-interval-for-the-proportion-section" class="nav-link" data-scroll-target="#homework-for-one-sample-interval-for-the-proportion-section"><span class="header-section-number">8.2.4</span> Homework for One-Sample Interval for the Proportion Section</a></li>
  </ul></li>
  <li><a href="#one-sample-interval-for-the-mean" id="toc-one-sample-interval-for-the-mean" class="nav-link" data-scroll-target="#one-sample-interval-for-the-mean"><span class="header-section-number">8.3</span> One-Sample Interval for the Mean</a>
  <ul class="collapse">
  <li><a href="#confidence-interval-for-one-population-mean-t-interval" id="toc-confidence-interval-for-one-population-mean-t-interval" class="nav-link" data-scroll-target="#confidence-interval-for-one-population-mean-t-interval"><span class="header-section-number">8.3.1</span> Confidence Interval for One Population Mean (t-Interval)</a></li>
  <li><a href="#example-confidence-interval-for-the-population-mean" id="toc-example-confidence-interval-for-the-population-mean" class="nav-link" data-scroll-target="#example-confidence-interval-for-the-population-mean"><span class="header-section-number">8.3.2</span> Example: Confidence Interval for the Population Mean</a></li>
  <li><a href="#example-confidence-interval-for-the-population-mean-1" id="toc-example-confidence-interval-for-the-population-mean-1" class="nav-link" data-scroll-target="#example-confidence-interval-for-the-population-mean-1"><span class="header-section-number">8.3.3</span> Example: Confidence Interval for the Population Mean</a></li>
  <li><a href="#homework-for-one-sample-interval-for-the-mean-section" id="toc-homework-for-one-sample-interval-for-the-mean-section" class="nav-link" data-scroll-target="#homework-for-one-sample-interval-for-the-mean-section"><span class="header-section-number">8.3.4</span> Homework for One-Sample Interval for the Mean Section</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Estimation</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In hypothesis tests, the purpose was to make a decision about a parameter, in terms of it being greater than, less than, or not equal to a value. But what if you want to actually know what the parameter is. You need to do estimation. There are two types of estimation -- point estimator and confidence interval. The American Statistical Association (ASA) is recommending that confidence intervals are the process that should be followed when analyzing data.</p>
<section id="basics-of-confidence-intervals" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="basics-of-confidence-intervals"><span class="header-section-number">8.1</span> Basics of Confidence Intervals</h2>
<p>A point estimator is just the statistic that you have calculated previously. As an example, when you wanted to estimate the population mean, <span class="math inline">\(\mu\)</span>, the point estimator is the sample mean, <span class="math inline">\(\bar{x}\)</span>. To estimate the population proportion, <span class="math inline">\(p\)</span>, you use the sample proportion, <span class="math inline">\(\hat{p}\)</span>. In general, if you want to estimate any population parameter, we will call it <span class="math inline">\(\theta\)</span>, you use the sample statistic, <span class="math inline">\(\hat{\theta}\)</span>.</p>
<p>Point estimators are really easy to find, but they have some drawbacks. First, if you have a large sample size, then the estimate is better. But with a point estimator, you don’t know what the sample size is. Also, you don’t know how accurate the estimate is. Both of these problems are solved with a confidence interval.</p>
<p><strong>Confidence interval</strong>: This is where you have an interval surrounding your parameter, and the interval has a chance of being a true statement. In general, a confidence interval looks like: <span class="math inline">\(\hat{\theta}\pm E\)</span>, where <span class="math inline">\(\hat{\theta}\)</span> is the point estimator and <span class="math inline">\(E\)</span> is the margin of error term that is added and subtracted from the point estimator. Thus making an interval.</p>
<section id="interpreting-a-confidence-interval" class="level3" data-number="8.1.1">
<h3 data-number="8.1.1" class="anchored" data-anchor-id="interpreting-a-confidence-interval"><span class="header-section-number">8.1.1</span> Interpreting a confidence interval:</h3>
<p>The statistical interpretation is that the confidence interval has a probability <span class="math inline">\(C=(1-\alpha)\)</span> (where <span class="math inline">\(\alpha\)</span> is the complement of the confidence level) of containing the population parameter. As an example, if you have a 95% confidence interval of $0.65 &lt; p &lt; 0.73$, then you would say, “you are 95% confident that the interval 0.65 to 0.73 contains the true population proportion.” This means that if you have 100 intervals, 95 of them will contain the true proportion, and 5 will not. The wrong interpretation is that there is a 95% confidence that the true value of <span class="math inline">\(p\)</span> will fall between 0.65 and 0.73. The reason that this interpretation is wrong is that the true value is fixed out there somewhere. You are trying to capture it with this interval. So this is the chance that your interval captures it, and not that the true value falls in the interval.</p>
<p>There is also a real world interpretation that depends on the situation. It is where you are telling people what numbers you found the parameter to lie between. So your real world is where you tell what values your parameter is between. There is no probability attached to this statement. That probability is in the statistical interpretation.</p>
<p>The common probabilities used for confidence intervals are 90%, 95%, and 99%. These are known as the confidence level. The confidence level and the alpha level are related. If you are conducting a hypothesis test with <span class="math inline">\(H_a:\mu\ne \mu_o\)</span>, then the confidence level is <span class="math inline">\(C=1-\alpha\)</span>. This is because the <span class="math inline">\(\alpha\)</span> is both tails and the confidence level is area between the two tails. As an example, for a hypothesis test <span class="math inline">\(H_a:\mu\ne \mu_o\)</span> with <span class="math inline">\(\alpha\)</span> equal to 0.05, the confidence level would be 0.95 or 95%. If you have a hypothesis test with <span class="math inline">\(H_a:\mu&lt;\mu_o\)</span>, then your <span class="math inline">\(\alpha\)</span> is only one tail of the curve. Because of symmetry the other tail is also <span class="math inline">\(\alpha\)</span>. You have <span class="math inline">\(2\alpha\)</span> with both tails. So the confidence level, which is the area between the two tails, is <span class="math inline">\(C-2\alpha\)</span>.</p>
</section>
<section id="example-stating-the-statistical-and-real-world-interpretations-for-a-confidence-interval" class="level3" data-number="8.1.2">
<h3 data-number="8.1.2" class="anchored" data-anchor-id="example-stating-the-statistical-and-real-world-interpretations-for-a-confidence-interval"><span class="header-section-number">8.1.2</span> Example: Stating the Statistical and Real World Interpretations for a Confidence Interval</h3>
<ol type="a">
<li>Suppose you have a 95% confidence interval for the mean age a woman gets married in 2013 is $26&lt;\mu&lt;28$. State the statistical and real world interpretations of this statement.</li>
<li>Suppose a 99% confidence interval for the proportion of Americans who have tried marijuana as of 2013 is $0.35&lt;p&lt;0.41$. State the statistical and real world interpretations of this statement.</li>
</ol>
<section id="solution" class="level4" data-number="8.1.2.1">
<h4 data-number="8.1.2.1" class="anchored" data-anchor-id="solution"><span class="header-section-number">8.1.2.1</span> Solution</h4>
<ol type="a">
<li>Suppose you have a 95% confidence interval for the mean age a woman gets married in 2013 is $26&lt;\mu&lt;28$. State the statistical and real world interpretations of this statement.</li>
</ol>
<p>Statistical Interpretation: You are 95% confident that the interval contains the mean age in 2013 that a woman gets married.</p>
<p>Real World Interpretation: The mean age that a woman married in 2013 is between 26 and 28 years of age.</p>
<ol start="2" type="a">
<li>Suppose a 99% confidence interval for the proportion of Americans who have tried marijuana as of 2013 is $0.35&lt;p&lt;0.41$. State the statistical and real world interpretations of this statement.</li>
</ol>
<p>Statistical Interpretation: You are 99% confident that the interval contains the proportion of Americans who have tried marijuana as of 2013.</p>
<p>Real World Interpretation: The proportion of Americans who have tried marijuana as of 2013 is between 0.35 and 0.41.</p>
<p>One last thing to know about confidence is how the sample size and confidence level affect how wide the interval is. The following discussion demonstrates what happens to the width of the interval as you get more confident.</p>
<p>Think about shooting an arrow into the target. Suppose you are really good at that and that you have a 90% chance of hitting the bull’s eye. Now the bull’s eye is very small. Since you hit the bull’s eye approximately 90% of the time, then you probably hit inside the next ring out 95% of the time. You have a better chance of doing this, but the circle is bigger. You probably have a 99% chance of hitting the target, but that is a much bigger circle to hit. You can see, as your confidence in hitting the target increases, the circle you hit gets bigger. The same is true for confidence intervals. This is demonstrated in Image \#8.1.1.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="effect_confidence_level.png" class="img-fluid figure-img" alt="Graph showing that 90% confident interval is narrower than a 95% confident interval, which is narrower than a 99% confidence interval"></p>
<figcaption>Image #8.1.1 Confidence Level Effect</figcaption>
</figure>
</div>
<p>The higher level of confidence makes a wider interval. There’s a trade off between width and confidence level. You can be really confident about your answer but your answer will not be very precise. Or you can have a precise answer (small margin of error) but not be very confident about your answer.</p>
<p>Now look at how the sample size affects the size of the interval. Suppose Image \#8.1.2 represents confidence intervals calculated on a 95% interval. A larger sample size from a representative sample makes the width of the interval narrower. This makes sense. Large samples are closer to the true population so the point estimate is pretty close to the true value.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="effect_sample_size.png" class="img-fluid figure-img" alt="Graph showing that a confident interval created with a sample size of 30 is wider than a confident interval created with a sample size of 100, which is wider than a confidence interval created with a sample size of 1000."></p>
<figcaption>Image #8.1.2 Effect of Sample size</figcaption>
</figure>
</div>
<p>Now you know everything you need to know about confidence intervals except for the actual formula. The formula depends on which parameter you are trying to estimate. With different situations you will be given the confidence interval for that parameter.</p>
</section>
</section>
<section id="homework-for-basics-of-confidence-intervals-section" class="level3" data-number="8.1.3">
<h3 data-number="8.1.3" class="anchored" data-anchor-id="homework-for-basics-of-confidence-intervals-section"><span class="header-section-number">8.1.3</span> Homework for Basics of Confidence Intervals Section</h3>
<ol type="1">
<li><p>Suppose you compute a confidence interval with a sample size of 25. What will happen to the confidence interval if the sample size increases to 50?</p></li>
<li><p>Suppose you compute a 95% confidence interval. What will happen to the confidence interval if you increase the confidence level to 99%?</p></li>
<li><p>Suppose you compute a 95% confidence interval. What will happen to the confidence interval if you decrease the confidence level to 90%?</p></li>
<li><p>Suppose you compute a confidence interval with a sample size of 100. What will happen to the confidence interval if the sample size decreases to 80?</p></li>
<li><p>A 95% confidence interval is <span class="math inline">\(6353km&lt; \mu&lt;6384km\)</span>, where <span class="math inline">\(\mu\)</span> is the mean diameter of the Earth. State the statistical interpretation.</p></li>
<li><p>A 95% confidence interval is <span class="math inline">\(6353 km &lt; \mu &lt; 6384 km\)</span>, where <span class="math inline">\(\mu\)</span> is the mean diameter of the Earth. State the real world interpretation.</p></li>
<li><p>In 2013, Gallup conducted a poll and found a 95% confidence interval of $0.52 &lt; p &lt; 0.60$, where <em>p</em> is the proportion of Americans who believe it is the government’s responsibility for health care. Give the real world interpretation.</p></li>
<li><p>In 2013, Gallup conducted a poll and found a 95% confidence interval of $0.52 &lt; p &lt; 0.60$, where <em>p</em> is the proportion of Americans who believe it is the government’s responsibility for health care. Give the statistical interpretation.</p></li>
</ol>
</section>
</section>
<section id="one-sample-interval-for-the-proportion" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="one-sample-interval-for-the-proportion"><span class="header-section-number">8.2</span> One-Sample Interval for the Proportion</h2>
<p>Suppose you want to estimate the population proportion, <em>p</em>. As an example you may be curious what proportion of students at your school smoke. Or you could wonder what is the proportion of accidents caused by teenage drivers who do not have a drivers’ education class.</p>
<section id="confidence-interval-for-one-population-proportion-1-prop-interval" class="level3" data-number="8.2.1">
<h3 data-number="8.2.1" class="anchored" data-anchor-id="confidence-interval-for-one-population-proportion-1-prop-interval"><span class="header-section-number">8.2.1</span> Confidence Interval for One Population Proportion (1-Prop Interval)</h3>
<ol type="1">
<li>State the random variable and the parameter in words.</li>
</ol>
<p><span class="math inline">\(x\)</span> = number of successes</p>
<p><span class="math inline">\(p\)</span> = proportion of successes</p>
<ol start="2" type="1">
<li>State and check the conditions for the confidence interval</li>
</ol>
<!-- -->
<ol type="a">
<li><p>State: A simple random sample of size <span class="math inline">\(n\)</span> is taken. Check: describe how sample was taken.</p></li>
<li><p>State: The condition for the binomial distribution are satisfied. Check: argue that each condition has been met.</p></li>
<li><p>State: The sampling distribution of <span class="math inline">\(\hat{p}\)</span> can be approximated by a normal distributed. check: To determine the sampling distribution of <span class="math inline">\(\hat{p}\)</span> is normally distributed, you need to show that <span class="math inline">\(n*\hat{p}\ge5\)</span> and , <span class="math inline">\(n*\hat{q}\ge5\)</span> where <span class="math inline">\(\hat{q}=1-\hat{p}\)</span>. If this requirement is true, then the sampling distribution of <span class="math inline">\(\hat{p}\)</span> is well approximated by a normal curve. (In reality this is not really true, since the correct condition deals with <span class="math inline">\(p\)</span>. However, in a confidence interval you do not know <span class="math inline">\(p\)</span>, so you must use <span class="math inline">\(\hat{p}\)</span>.)</p></li>
</ol>
<!-- -->
<ol start="3" type="1">
<li>Find the sample statistic and the confidence interval</li>
</ol>
<p>This will be conducted using rStudio. The command is</p>
<p>prop.test(r, n, conf.level=C) #type C as a decimal</p>
<ol start="4" type="1">
<li><p>Statistical Interpretation: In general this looks like, “you are C% confident that <span class="math inline">\(\hat{p}\pm E\)</span> contains the true proportion.”</p></li>
<li><p>Real World Interpretation: This is where you state what interval contains the true proportion.</p></li>
</ol>
</section>
<section id="example-confidence-interval-for-the-population-proportion" class="level3" data-number="8.2.2">
<h3 data-number="8.2.2" class="anchored" data-anchor-id="example-confidence-interval-for-the-population-proportion"><span class="header-section-number">8.2.2</span> Example: Confidence Interval for the Population Proportion</h3>
<p>A concern was raised in Australia that the percentage of deaths of Aboriginal prisoners was higher than the percent of deaths of non-Aboriginal prisoners, which is 0.27%. A sample of six years (1990-1995) of data was collected, and it was found that out of 14,495 Aboriginal prisoners, 51 died (\“Indigenous deaths in,\” 1996). Find a 95% confidence interval for the proportion of Aboriginal prisoners who died.</p>
<section id="solution-1" class="level4" data-number="8.2.2.1">
<h4 data-number="8.2.2.1" class="anchored" data-anchor-id="solution-1"><span class="header-section-number">8.2.2.1</span> Solution</h4>
<ol type="1">
<li>State the random variable and the parameter in words.</li>
</ol>
<p><span class="math inline">\(x\)</span> = number of Aboriginal prisoners who die</p>
<p><span class="math inline">\(p\)</span> = proportion of Aboriginal prisoners who die</p>
<ol start="2" type="1">
<li>State and check the conditions for the confidence interval</li>
</ol>
<!-- -->
<ol type="a">
<li><p>State: A simple random sample of 14,495 Aboriginal prisoners was taken. Check: The sample was not a random sample, since it was data from six years. It is the numbers for all prisoners in these six years, but the six years were not picked at random. Unless there was something special about the six years that were chosen, the sample is probably a representative sample. This condition is probably met.</p></li>
<li><p>State: The properties of the binomial experiment have been met. Check: There are 14,495 prisoners in this case. The prisoners are all Aboriginals, so you are not mixing Aboriginal with non-Aboriginal prisoners. There are only two outcomes, either the prisoner dies or doesn’t. The chance that one prisoner dies over another may not be constant, but if you consider all prisoners the same, then it may be close to the same probability. Thus the properties of the binomial experiment are satisfied</p></li>
<li><p>State: The sampling distribution of <span class="math inline">\(\hat{p}\)</span> can be approximated with a normal distribution. Check: <span class="math inline">\(\hat{p}*n=\frac{51}{14495}*14495=51\ge5\)</span> and <span class="math inline">\(\hat{q}*n=\frac{14495-51}{14495}*14495=14444\ge5\)</span>. The sampling distribution of <span class="math inline">\(\hat{p}\)</span> can be approximated with a normal distribution.</p></li>
</ol>
<!-- -->
<ol start="3" type="1">
<li>Find the sample statistic and the confidence interval</li>
</ol>
<p>The command in r Studio for a confidence interval for a proportion is</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="dv">51</span>,<span class="dv">14495</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1-sample proportions test with continuity correction

data:  51 out of 14495
X-squared = 14290, df = 1, p-value &lt; 2.2e-16
alternative hypothesis: true p is not equal to 0.5
95 percent confidence interval:
 0.002647440 0.004661881
sample estimates:
          p 
0.003518455 </code></pre>
</div>
</div>
<p>the 95% confidence level is <span class="math inline">\(0.002647440&lt;p&lt;0.004661881\)</span>.</p>
<ol start="4" type="1">
<li><p>Statistical Interpretation: You are 95% confident that the interval <span class="math inline">\(0.0026&lt;p&lt;0.0047\)</span> contains the proportion of Aboriginal prisoners who have died in prison.</p></li>
<li><p>Real World Interpretation: The proportion of Aboriginal prisoners who died in prison is between 0.26% and 0.47%.</p></li>
</ol>
</section>
</section>
<section id="example-confidence-interval-for-the-population-proportion-1" class="level3" data-number="8.2.3">
<h3 data-number="8.2.3" class="anchored" data-anchor-id="example-confidence-interval-for-the-population-proportion-1"><span class="header-section-number">8.2.3</span> Example: Confidence Interval for the Population Proportion</h3>
<p>A researcher who is studying the effects of income levels on breastfeeding of infants hypothesizes that countries with a low income level have a different rate of infant breastfeeding than higher income countries. It is known that in Germany, considered a high-income country by the World Bank, 22% of all babies are breastfeed. In Tajikistan, considered a low-income country by the World Bank, researchers found that in a random sample of 500 new mothers that 125 were breastfeeding their infant. Find a 90% confidence interval of the proportion of mothers in low-income countries who breastfeed their infants?</p>
<section id="solution-2" class="level4" data-number="8.2.3.1">
<h4 data-number="8.2.3.1" class="anchored" data-anchor-id="solution-2"><span class="header-section-number">8.2.3.1</span> Solution</h4>
<ol type="1">
<li>State you random variable and the parameter in words.</li>
</ol>
<p><span class="math inline">\(x\)</span> = number of woman who breastfeed in a low-income country</p>
<p><span class="math inline">\(p\)</span> = proportion of woman who breastfeed in a low-income country</p>
<ol start="2" type="1">
<li>State and check the conditions for the confidence interval</li>
</ol>
<!-- -->
<ol type="a">
<li><p>State: A simple random sample of 500 breastfeeding habits of woman in a low-income country was taken. Check: This was stated in the problem.</p></li>
<li><p>State: The properties of a Binomial Experiment have been met. Check: There were 500 women in the study. The women are considered identical, though they probably have some differences. There are only two outcomes, either the woman breastfeeds or she doesn’t. The probability of a woman breastfeeding is probably not the same for each woman, but it is probably not very different for each woman. The conditions for the binomial distribution are satisfied</p></li>
<li><p>State: The sampling distribution of <span class="math inline">\(\hat{p}\)</span> can be approximated with a normal distributed. Check:<span class="math inline">\(n*\hat{p}= 500*\frac{125}{500}=125\ge5\)</span> and <span class="math inline">\(n*\hat{q}=500*\frac{500-125}{500}=375\ge5\)</span>, so the sampling distribution of <span class="math inline">\(\hat{p}\)</span> is well approximated by a normal distribution.</p></li>
</ol>
<!-- -->
<ol start="4" type="1">
<li>Find the sample statistic and confidence interval</li>
</ol>
<p>On rstudio, use the following command</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="dv">125</span>, <span class="dv">500</span>, <span class="at">conf.level =</span> .<span class="dv">90</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1-sample proportions test with continuity correction

data:  125 out of 500
X-squared = 124, df = 1, p-value &lt; 2.2e-16
alternative hypothesis: true p is not equal to 0.5
90 percent confidence interval:
 0.2185980 0.2841772
sample estimates:
   p 
0.25 </code></pre>
</div>
</div>
<p>90% confidence interval for <span class="math inline">\(p\)</span> is <span class="math inline">\(0.2185980&lt;p&lt;0.2841772\)</span>.</p>
<ol start="4" type="1">
<li><p>Statistical Interpretation: You are 90% confident that <span class="math inline">\(0.2185980&lt;p&lt;0.2841772\)</span> contains the proportion of women in low-income countries who breastfeed their infants.</p></li>
<li><p>Real World Interpretation: The proportion of women in low-income countries who breastfeed their infants is between 0.219 and 0.284.</p></li>
</ol>
</section>
</section>
<section id="homework-for-one-sample-interval-for-the-proportion-section" class="level3" data-number="8.2.4">
<h3 data-number="8.2.4" class="anchored" data-anchor-id="homework-for-one-sample-interval-for-the-proportion-section"><span class="header-section-number">8.2.4</span> Homework for One-Sample Interval for the Proportion Section</h3>
<p><strong>In each problem show all steps of the confidence interval. If some of the conditions are not met, note that the results of the interval may not be correct and then continue the process of the confidence interval.</strong></p>
<ol type="1">
<li><p>The Arizona Republic/Morrison/Cronkite News poll published on Monday, October 20, 2016, found 390 of the registered voters surveyed favor Proposition 205, which would legalize marijuana for adults. The statewide telephone poll surveyed 779 registered voters between Oct.&nbsp;10 and Oct.&nbsp;15. (Sanchez, 2016) Find a 99% confidence interval for the proportion of Arizona’s who supported legalizing marijuana for adults.</p></li>
<li><p>In November of 1997, Australians were asked if they thought unemployment would increase. At that time 284 out of 631 said that they thought unemployment would increase (\“Morgan gallup poll,\” 2013). Estimate the proportion of Australians in November 1997 who believed unemployment would increase using a 95% confidence interval?</p></li>
<li><p>According to the February 2008 Federal Trade Commission report on consumer fraud and identity theft, Arkansas had 1,601 complaints of identity theft out of 3,482 consumer complaints (\“Consumer fraud and,\” 2008). Calculate a 90% confidence interval for the proportion of identity theft in Arkansas.</p></li>
<li><p>According to the February 2008 Federal Trade Commission report on consumer fraud and identity theft, Alaska had 321 complaints of identity theft out of 1,432 consumer complaints (\“Consumer fraud and,\” 2008). Calculate a 90% confidence interval for the proportion of identity theft in Alaska.</p></li>
<li><p>In 2013, the Gallup poll asked 1,039 American adults if they believe there was a conspiracy in the assassination of President Kennedy, and found that 634 believe there was a conspiracy (\“Gallup news service,\” 2013). Estimate the proportion of American’s who believe in this conspiracy using a 98% confidence interval.</p></li>
<li><p>In 2008, there were 507 children in Arizona out of 32,601 who were diagnosed with Autism Spectrum Disorder (ASD) (\“Autism and developmental,\” 2008). Find the proportion of ASD in Arizona with a confidence level of 99%.</p></li>
</ol>
</section>
</section>
<section id="one-sample-interval-for-the-mean" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="one-sample-interval-for-the-mean"><span class="header-section-number">8.3</span> One-Sample Interval for the Mean</h2>
<p>Suppose you want to estimate the mean height of Americans, or you want to estimate the mean salary of college graduates. A confidence interval for the mean would be the way to estimate these means.</p>
<section id="confidence-interval-for-one-population-mean-t-interval" class="level3" data-number="8.3.1">
<h3 data-number="8.3.1" class="anchored" data-anchor-id="confidence-interval-for-one-population-mean-t-interval"><span class="header-section-number">8.3.1</span> Confidence Interval for One Population Mean (t-Interval)</h3>
<ol type="1">
<li>State the random variable and the parameter in words.</li>
</ol>
<p><span class="math inline">\(x\)</span> = random variable</p>
<p><span class="math inline">\(\mu\)</span> = mean of random variable</p>
<ol start="2" type="1">
<li>State and check the conditions for the confidence interval</li>
</ol>
<!-- -->
<ol type="a">
<li><p>State: A random sample of size <span class="math inline">\(n\)</span> is taken. Check: describe how the sample was collected.</p></li>
<li><p>State: The population of the random variable is normally distributed. Check: look at density plot and normal quantile plot. Note: though the t-test is fairly robust to the condition if the sample size is large. This means that if this condition isn’t met, but your sample size is quite large, then the results of the t-test are valid.</p></li>
</ol>
<!-- -->
<ol start="3" type="1">
<li>Find the sample statistic and confidence interval</li>
</ol>
<p>Use rStudio to find the confidence interval. The command is</p>
<p>t.test(~variable, data= Data_Frame, conf.level=C) #type C as a decimal</p>
<ol start="4" type="1">
<li><p>Statistical Interpretation: In general this looks like, “You are C% confident that the interval contains the true mean.”</p></li>
<li><p>Real World Interpretation: This is where you state what interval contains the true mean.</p></li>
</ol>
</section>
<section id="example-confidence-interval-for-the-population-mean" class="level3" data-number="8.3.2">
<h3 data-number="8.3.2" class="anchored" data-anchor-id="example-confidence-interval-for-the-population-mean"><span class="header-section-number">8.3.2</span> Example: Confidence Interval for the Population Mean</h3>
<p>A random sample of 50 body mass index (BMI) were taken from the NHANES Data frame <a href="#tbl-NHANES_50" class="quarto-xref">Table&nbsp;<span>8.1</span></a>. Estimate the mean BMI of Americans at the 95% level.</p>
<div class="cell" data-tbl-alt="Head of sample of BMI of Americans">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>sample_NHANES_50<span class="ot">&lt;-</span> <span class="fu">sample_n</span>(NHANES, <span class="at">size=</span><span class="dv">50</span>) </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(sample_NHANES_50))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-NHANES_50" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Head of sample of BMI of Americans">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-NHANES_50-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8.1: BMI of Americans
</figcaption>
<div aria-describedby="tbl-NHANES_50-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">ID</th>
<th style="text-align: left;">SurveyYr</th>
<th style="text-align: left;">Gender</th>
<th style="text-align: right;">Age</th>
<th style="text-align: left;">AgeDecade</th>
<th style="text-align: right;">AgeMonths</th>
<th style="text-align: left;">Race1</th>
<th style="text-align: left;">Race3</th>
<th style="text-align: left;">Education</th>
<th style="text-align: left;">MaritalStatus</th>
<th style="text-align: left;">HHIncome</th>
<th style="text-align: right;">HHIncomeMid</th>
<th style="text-align: right;">Poverty</th>
<th style="text-align: right;">HomeRooms</th>
<th style="text-align: left;">HomeOwn</th>
<th style="text-align: left;">Work</th>
<th style="text-align: right;">Weight</th>
<th style="text-align: right;">Length</th>
<th style="text-align: right;">HeadCirc</th>
<th style="text-align: right;">Height</th>
<th style="text-align: right;">BMI</th>
<th style="text-align: left;">BMICatUnder20yrs</th>
<th style="text-align: left;">BMI_WHO</th>
<th style="text-align: right;">Pulse</th>
<th style="text-align: right;">BPSysAve</th>
<th style="text-align: right;">BPDiaAve</th>
<th style="text-align: right;">BPSys1</th>
<th style="text-align: right;">BPDia1</th>
<th style="text-align: right;">BPSys2</th>
<th style="text-align: right;">BPDia2</th>
<th style="text-align: right;">BPSys3</th>
<th style="text-align: right;">BPDia3</th>
<th style="text-align: right;">Testosterone</th>
<th style="text-align: right;">DirectChol</th>
<th style="text-align: right;">TotChol</th>
<th style="text-align: right;">UrineVol1</th>
<th style="text-align: right;">UrineFlow1</th>
<th style="text-align: right;">UrineVol2</th>
<th style="text-align: right;">UrineFlow2</th>
<th style="text-align: left;">Diabetes</th>
<th style="text-align: right;">DiabetesAge</th>
<th style="text-align: left;">HealthGen</th>
<th style="text-align: right;">DaysPhysHlthBad</th>
<th style="text-align: right;">DaysMentHlthBad</th>
<th style="text-align: left;">LittleInterest</th>
<th style="text-align: left;">Depressed</th>
<th style="text-align: right;">nPregnancies</th>
<th style="text-align: right;">nBabies</th>
<th style="text-align: right;">Age1stBaby</th>
<th style="text-align: right;">SleepHrsNight</th>
<th style="text-align: left;">SleepTrouble</th>
<th style="text-align: left;">PhysActive</th>
<th style="text-align: right;">PhysActiveDays</th>
<th style="text-align: left;">TVHrsDay</th>
<th style="text-align: left;">CompHrsDay</th>
<th style="text-align: right;">TVHrsDayChild</th>
<th style="text-align: right;">CompHrsDayChild</th>
<th style="text-align: left;">Alcohol12PlusYr</th>
<th style="text-align: right;">AlcoholDay</th>
<th style="text-align: right;">AlcoholYear</th>
<th style="text-align: left;">SmokeNow</th>
<th style="text-align: left;">Smoke100</th>
<th style="text-align: left;">Smoke100n</th>
<th style="text-align: right;">SmokeAge</th>
<th style="text-align: left;">Marijuana</th>
<th style="text-align: right;">AgeFirstMarij</th>
<th style="text-align: left;">RegularMarij</th>
<th style="text-align: right;">AgeRegMarij</th>
<th style="text-align: left;">HardDrugs</th>
<th style="text-align: left;">SexEver</th>
<th style="text-align: right;">SexAge</th>
<th style="text-align: right;">SexNumPartnLife</th>
<th style="text-align: right;">SexNumPartYear</th>
<th style="text-align: left;">SameSex</th>
<th style="text-align: left;">SexOrientation</th>
<th style="text-align: left;">PregnantNow</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">58977</td>
<td style="text-align: left;">2009_10</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">28</td>
<td style="text-align: left;">20-29</td>
<td style="text-align: right;">344</td>
<td style="text-align: left;">Mexican</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">High School</td>
<td style="text-align: left;">Married</td>
<td style="text-align: left;">25000-34999</td>
<td style="text-align: right;">30000</td>
<td style="text-align: right;">1.13</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">Rent</td>
<td style="text-align: left;">NotWorking</td>
<td style="text-align: right;">60.1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">161.3</td>
<td style="text-align: right;">23.10</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">18.5_to_24.9</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">112</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">106</td>
<td style="text-align: right;">74</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">112</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">156</td>
<td style="text-align: right;">1.147</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">Good</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">None</td>
<td style="text-align: left;">None</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Non-Smoker</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Heterosexual</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: right;">54339</td>
<td style="text-align: left;">2009_10</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">52</td>
<td style="text-align: left;">50-59</td>
<td style="text-align: right;">630</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">College Grad</td>
<td style="text-align: left;">Married</td>
<td style="text-align: left;">more 99999</td>
<td style="text-align: right;">100000</td>
<td style="text-align: right;">4.51</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Own</td>
<td style="text-align: left;">Working</td>
<td style="text-align: right;">69.6</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">166.7</td>
<td style="text-align: right;">25.05</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">25.0_to_29.9</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">111</td>
<td style="text-align: right;">65</td>
<td style="text-align: right;">108</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">108</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">114</td>
<td style="text-align: right;">64</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.37</td>
<td style="text-align: right;">4.34</td>
<td style="text-align: right;">95</td>
<td style="text-align: right;">1.979</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">Vgood</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">None</td>
<td style="text-align: left;">None</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">364</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Smoker</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Heterosexual</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: right;">56782</td>
<td style="text-align: left;">2009_10</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">0-9</td>
<td style="text-align: right;">51</td>
<td style="text-align: left;">Mexican</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">65000-74999</td>
<td style="text-align: right;">70000</td>
<td style="text-align: right;">1.74</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Own</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">18.7</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">106.9</td>
<td style="text-align: right;">16.36</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">12.0_18.5</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: right;">66817</td>
<td style="text-align: left;">2011_12</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">72</td>
<td style="text-align: left;">70+</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">High School</td>
<td style="text-align: left;">Widowed</td>
<td style="text-align: left;">5000-9999</td>
<td style="text-align: right;">7500</td>
<td style="text-align: right;">0.83</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Own</td>
<td style="text-align: left;">Looking</td>
<td style="text-align: right;">90.7</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">153.0</td>
<td style="text-align: right;">38.70</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">30.0_plus</td>
<td style="text-align: right;">54</td>
<td style="text-align: right;">128</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">130</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">128</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">128</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">44.75</td>
<td style="text-align: right;">1.34</td>
<td style="text-align: right;">6.52</td>
<td style="text-align: right;">104</td>
<td style="text-align: right;">1.156</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">Good</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">None</td>
<td style="text-align: left;">Several</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">4_hr</td>
<td style="text-align: left;">1_hr</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Smoker</td>
<td style="text-align: right;">18</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: right;">62772</td>
<td style="text-align: left;">2011_12</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">46</td>
<td style="text-align: left;">40-49</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">Mexican</td>
<td style="text-align: left;">Mexican</td>
<td style="text-align: left;">College Grad</td>
<td style="text-align: left;">NeverMarried</td>
<td style="text-align: left;">more 99999</td>
<td style="text-align: right;">100000</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">Rent</td>
<td style="text-align: left;">NotWorking</td>
<td style="text-align: right;">81.7</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">146.5</td>
<td style="text-align: right;">38.10</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">30.0_plus</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">146</td>
<td style="text-align: right;">88</td>
<td style="text-align: right;">148</td>
<td style="text-align: right;">84</td>
<td style="text-align: right;">150</td>
<td style="text-align: right;">86</td>
<td style="text-align: right;">142</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">12.39</td>
<td style="text-align: right;">1.40</td>
<td style="text-align: right;">6.98</td>
<td style="text-align: right;">74</td>
<td style="text-align: right;">0.679</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">Vgood</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">None</td>
<td style="text-align: left;">None</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">3_hr</td>
<td style="text-align: left;">3_hr</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">52</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Smoker</td>
<td style="text-align: right;">16</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Heterosexual</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: right;">66926</td>
<td style="text-align: left;">2011_12</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">51</td>
<td style="text-align: left;">50-59</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">High School</td>
<td style="text-align: left;">Married</td>
<td style="text-align: left;">more 99999</td>
<td style="text-align: right;">100000</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">Own</td>
<td style="text-align: left;">Working</td>
<td style="text-align: right;">94.5</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">166.3</td>
<td style="text-align: right;">34.20</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">30.0_plus</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">117</td>
<td style="text-align: right;">81</td>
<td style="text-align: right;">116</td>
<td style="text-align: right;">84</td>
<td style="text-align: right;">118</td>
<td style="text-align: right;">82</td>
<td style="text-align: right;">116</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">363.08</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">7.09</td>
<td style="text-align: right;">180</td>
<td style="text-align: right;">0.793</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">Vgood</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">None</td>
<td style="text-align: left;">None</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">3_hr</td>
<td style="text-align: left;">0_to_1_hr</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Smoker</td>
<td style="text-align: right;">16</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">16</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Heterosexual</td>
<td style="text-align: left;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<section id="solution-3" class="level4" data-number="8.3.2.1">
<h4 data-number="8.3.2.1" class="anchored" data-anchor-id="solution-3"><span class="header-section-number">8.3.2.1</span> Solution</h4>
<ol type="1">
<li>State the random variable and the parameter in words.</li>
</ol>
<p><span class="math inline">\(x\)</span> = BMI of an American</p>
<p><span class="math inline">\(\mu\)</span> = mean BMI of Americans</p>
<ol start="2" type="1">
<li>State and check the conditions for the confidence interval</li>
</ol>
<!-- -->
<ol type="a">
<li><p>A random sample of 50 BMI levels was taken. Check: A random sample was taken from the NHANES data frame using r Studio</p></li>
<li><p>The population of BMI levels is normally distributed. Check:</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_density</span>(<span class="sc">~</span>BMI, <span class="at">data=</span>sample_NHANES_50, <span class="at">title=</span><span class="st">"BMI of an American"</span>, <span class="at">xlab=</span><span class="st">"Body Mass Index"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-BMI-density" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Density plot of BMI. Looks somewhat skewed right">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-BMI-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Estimation_files/figure-html/fig-BMI-density-1.png" class="img-fluid figure-img" alt="Density plot of BMI. Looks somewhat skewed right" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-BMI-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.1: Density Plot of BMI from NHANES sample
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_qq</span>(<span class="sc">~</span>BMI, <span class="at">data=</span>sample_NHANES_50, <span class="at">title=</span><span class="st">"BMI of an American"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-BMI-qq" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Normal quantile plot of BMI. Looks somewhat lineart">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-BMI-qq-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Estimation_files/figure-html/fig-BMI-qq-1.png" class="img-fluid figure-img" alt="Normal quantile plot of BMI. Looks somewhat lineart" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-BMI-qq-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.2: Normal quantile Plot of BMI from NHANES sample
</figcaption>
</figure>
</div>
</div>
</div>
<p>The density plot looks somewhat skewed right and the normal quantile plot looks somewhat linear. There doesn’t seem to be strong evidence that the sample comes from a population that is normally distributed. However, since the sample is moderate to large, the t-test is robust to this condition not being met. So the results of the test are probably valid.</p>
<ol start="4" type="1">
<li>Find the sample statistic and confidence interval</li>
</ol>
<p>On r Studio, the command would be</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="sc">~</span>BMI, <span class="at">data=</span> sample_NHANES_50, <span class="at">conf.level=</span><span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  BMI
t = 28.291, df = 49, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 25.04592 28.87608
sample estimates:
mean of x 
   26.961 </code></pre>
</div>
</div>
<p>The sample statistic is the mean of <span class="math inline">\(x\)</span> in the output, and confidence interval is under the words 95 percent confidence interval.</p>
<ol start="4" type="1">
<li><p>Statistical Interpretation: You are 95% confident that <span class="math inline">\(24.87190&lt;\mu&lt;28.71422\)</span> contains the mean BMI of Americans.</p></li>
<li><p>Real World Interpretation: The mean BMI of Americans is between 24.87 and 28.71 <span class="math inline">\(kg/m^2\)</span>.</p></li>
</ol>
<p>Notice that in example the chapter 7, you were asked if the mean BMI of Americans was different from Australians’ mean BMI of 27.2 <span class="math inline">\(kg/m^2\)</span>. The interval that <a href="#example-confidence-interval-for-the-population-mean-1">Example: Confidence Interval for the Population Mean</a> calculated does contain the value of 27.2. So you can’t say that Americans’ mean BMI and Australians’ mean BMI are different.This means that you can just use confidence intervals and not conduct hypothesis tests at all if you prefer.</p>
<p>Note: When creating this book, the random samples may change. So the answers may be different from what is said in the interpretations. This shows sampling variability, so it was not adjusted to show that this could happen.</p>
</section>
</section>
<section id="example-confidence-interval-for-the-population-mean-1" class="level3" data-number="8.3.3">
<h3 data-number="8.3.3" class="anchored" data-anchor-id="example-confidence-interval-for-the-population-mean-1"><span class="header-section-number">8.3.3</span> Example: Confidence Interval for the Population Mean</h3>
<p>The data in <a href="One Sample Inference.html#tbl-Expectancy" class="quarto-xref">Table&nbsp;<span>7.5</span></a> are the life expectancies for all people in European countries (\“WHO life expectancy,\” 2013). The data in <a href="One Sample Inference.html#tbl-Expectancy-male" class="quarto-xref">Table&nbsp;<span>7.6</span></a> filtered the data frame for just males and just year 2000. The year 2000 was randomly chosen as the year to use. Estimate the mean life expectancy for a man in Europe at the 99% level.</p>
<p>Code book for data frame Expectancy is below <a href="One Sample Inference.html#tbl-Expectancy" class="quarto-xref">Table&nbsp;<span>7.5</span></a>.</p>
<section id="solution-4" class="level4" data-number="8.3.3.1">
<h4 data-number="8.3.3.1" class="anchored" data-anchor-id="solution-4"><span class="header-section-number">8.3.3.1</span> Solution</h4>
<ol type="1">
<li>State the random variable and the parameter in words.</li>
</ol>
<p><span class="math inline">\(x\)</span> = life expectancy for a European man</p>
<p><span class="math inline">\(\mu\)</span> = mean life expectancy for European men</p>
<ol start="2" type="1">
<li>State and check the conditions for the confidence interval</li>
</ol>
<!-- -->
<ol type="a">
<li><p>State: A random sample of 53 life expectancies of European men in 2000 was taken.</p>
<p>Check: The data is actually all of the life expectancies for every country that is considered part of Europe by the World Health Organization in the year 2000. Since the year 2000 was picked at random, then the sample is a random sample.</p></li>
<li><p>State: The distribution of life expectancies of European men in 2000 is normally distributed.</p>
<p>Check:</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_density</span>(<span class="sc">~</span>expect, <span class="at">data=</span>Expectancy_male, <span class="at">title=</span><span class="st">"Life Expectancy of a male"</span>, <span class="at">xlab=</span><span class="st">"Life Expectancy of a Male"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-expanctancy-male-density1" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Density plot of life expectancy of males in Europe in 2000. Looks skewed left">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-expanctancy-male-density1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Estimation_files/figure-html/fig-expanctancy-male-density1-1.png" class="img-fluid figure-img" alt="Density plot of life expectancy of males in Europe in 2000. Looks skewed left" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-expanctancy-male-density1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.3: Density Plot of Life Expectancy of Males in Europe in 2000
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_qq</span>(<span class="sc">~</span>expect, <span class="at">data=</span>Expectancy_male, <span class="at">title=</span><span class="st">"Male Life Expectancy"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-expanctancy-male-quantile1" class="quarto-float quarto-figure quarto-figure-center anchored" alt="quantile plot of life expectancy of males in Europe in 2000. Does not looks linear">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-expanctancy-male-quantile1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Estimation_files/figure-html/fig-expanctancy-male-quantile1-1.png" class="img-fluid figure-img" alt="quantile plot of life expectancy of males in Europe in 2000. Does not looks linear" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-expanctancy-male-quantile1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.4: Quantile Plot of Life Expectancy of Males in Europe in 2000
</figcaption>
</figure>
</div>
</div>
</div>
<p>This sample does not appear to come from a population that is normally distributed. This sample is moderate to large, so it is good that the t-test is robust.</p>
<ol start="3" type="1">
<li>Find the sample statistic and confidence interval</li>
</ol>
<p>On rStudio, the command would be</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="sc">~</span>expect, <span class="at">data=</span>Expectancy_male, <span class="at">conf.level=</span><span class="fl">0.99</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  expect
t = 90.919, df = 52, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 0
99 percent confidence interval:
 68.60071 72.75778
sample estimates:
mean of x 
 70.67925 </code></pre>
</div>
</div>
<p>Sample statistic is 70.68 years, and the confidence interval is <span class="math inline">\(68.60071&lt;\mu&lt;72.75778\)</span>.</p>
<ol start="4" type="1">
<li><p>Statistical Interpretation: You are 99% confident that <span class="math inline">\(68.60071&lt;\mu&lt;72.75778\)</span> contains the mean life expectancy of European men.</p></li>
<li><p>Real World Interpretation: The mean life expectancy of European men is between 68.60 and 72.76 years.</p></li>
</ol>
</section>
</section>
<section id="homework-for-one-sample-interval-for-the-mean-section" class="level3" data-number="8.3.4">
<h3 data-number="8.3.4" class="anchored" data-anchor-id="homework-for-one-sample-interval-for-the-mean-section"><span class="header-section-number">8.3.4</span> Homework for One-Sample Interval for the Mean Section</h3>
<p><strong>In each problem show all steps of the confidence interval. If some of the conditions are not met, note that the results of the interval may not be correct and then continue the process of the confidence interval.</strong></p>
<ol type="1">
<li>The Kyoto Protocol was signed in 1997, and required countries to start reducing their carbon emissions. The protocol became enforceable in February 2005. <a href="One Sample Inference.html#tbl-Emission" class="quarto-xref">Table&nbsp;<span>7.7</span></a> contains a random sample of CO2 emissions in 2010 (CO2 emissions (metric tons per capita), 2018). Find a 99% confidence interval for the mean CO-2 emissions in 2010.</li>
</ol>
<p>Code book for data frame Emission is below <a href="One Sample Inference.html#tbl-Emission" class="quarto-xref">Table&nbsp;<span>7.7</span></a>.</p>
<ol start="2" type="1">
<li>The amount of sugar in a Krispy Kream glazed donut is 10 g. Many people feel that cereal is a healthier alternative for children over glazed donuts. <a href="One Sample Inference.html#tbl-Sugar" class="quarto-xref">Table&nbsp;<span>7.8</span></a> contains the amount of sugar in a sample of cereal that is geared towards children (breakfast cereal, 2019). Estimate the mean amount of sugar in children’s cereal at the 95% confidence level.</li>
</ol>
<p>Code book for data frame Sugar is below <a href="One Sample Inference.html#tbl-Sugar" class="quarto-xref">Table&nbsp;<span>7.8</span></a>.</p>
<p>A new data frame will need to be created of just cereal for children. It is <a href="One Sample Inference.html#tbl-Sugar_children" class="quarto-xref">Table&nbsp;<span>7.9</span></a>.</p>
<ol start="3" type="1">
<li>The FDA regulates that fish that is consumed is allowed to contain 1.0 mg/kg of mercury. In Florida, bass fish were collected in 53 different lakes to measure the health of the lakes. The data frame of measurements from Florida lakes is in <a href="One Sample Inference.html#tbl-Mercury" class="quarto-xref">Table&nbsp;<span>7.10</span></a> (NISER 081107 ID Data, 2019). Calculate with 90% confidence the mean amount of mercury in fish in Florida lakes. Is there too much mercury in the fish in Florida?</li>
</ol>
<p>Code book for data frame Mercury is below <a href="One Sample Inference.html#tbl-Mercury" class="quarto-xref">Table&nbsp;<span>7.10</span></a>.</p>
<ol start="4" type="1">
<li>The data frame <a href="Numerical-description-of-Data.html#tbl-Pulse" class="quarto-xref">Table&nbsp;<span>3.7</span></a> contains various variables about a person including their pulse rates before the subject exercised and after the subject ran in place for one minute. Estimate the mean pulse rate before exercise of females who do drink alcohol with a 95% level of confidence?</li>
</ol>
<p>Code book for data frame Pulse below <a href="Numerical-description-of-Data.html#tbl-Pulse" class="quarto-xref">Table&nbsp;<span>3.7</span></a>.</p>
<p>A new data frame with just females who drink alcohol is <a href="Two Sample Inference.html#tbl-Females" class="quarto-xref">Table&nbsp;<span>9.2</span></a> from chapter 7.</p>
<ol start="5" type="1">
<li>The economic dynamism is an index of productive growth in dollars. Economic data for many countries are in <a href="One Sample Inference.html#tbl-Economics" class="quarto-xref">Table&nbsp;<span>7.12</span></a> (SOCR Data 2008 World CountriesRankings, 2019).</li>
</ol>
<p>Code book for data frame Economics is below <a href="One Sample Inference.html#tbl-Economics" class="quarto-xref">Table&nbsp;<span>7.12</span></a>.</p>
<p>A data frame that contains only middle income countries was created in chapter 7 and is <a href="One Sample Inference.html#tbl-Middle_economics" class="quarto-xref">Table&nbsp;<span>7.13</span></a>. Find a 95% confidence interval for the mean economic dynamism for middle income countries.</p>
<ol start="6" type="1">
<li><a href="Graphical Description of Data.html#tbl-Fert_prenatal" class="quarto-xref">Table&nbsp;<span>2.18</span></a> contains the percentage of woman receiving prenatal care in a sample of countries over several years. (births per woman), 2019). Estimate the average percentage of women receiving prenatal care in 2009 (p2009) with a 95% confidence interval?</li>
</ol>
<p>Code book for Data frame Fert_prenatal is below <a href="Graphical Description of Data.html#tbl-Fert_prenatal" class="quarto-xref">Table&nbsp;<span>2.18</span></a>.</p>
<ol start="7" type="1">
<li>Maintaining your balance may get harder as you grow older. A study was conducted to see how steady the elderly is on their feet. They had the subjects stand on a force platform and have them react to a noise. The force platform then measured how much they swayed forward and backward, and the data is in <a href="One Sample Inference.html#tbl-Sway" class="quarto-xref">Table&nbsp;<span>7.14</span></a> (Maintaining Balance while Concentrating, 2019). Find the mean forward/backward sway of elderly person? Use a 95% confidence level. Follow the filtering methods in other homework problems to create a data frame for only Elderly.</li>
</ol>
<p>Code book for data frame Sway is below <a href="One Sample Inference.html#tbl-Sway" class="quarto-xref">Table&nbsp;<span>7.14</span></a>.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./One Sample Inference.html" class="pagination-link" aria-label="One Sample Inference">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">One Sample Inference</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Two Sample Inference.html" class="pagination-link" aria-label="Two Sample Inference">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Two Sample Inference</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>