<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Numerical Description of Data – Statistics Using Technology: Rguroo Edition</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Probability.html" rel="next">
<link href="./Graphical Description of Data.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-231ef2f9d4ce3268f31ef752336c15d2.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Numerical-description-of-Data.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Numerical Description of Data</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics Using Technology: Rguroo Edition</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Home</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Statistical Basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Statistical Basics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Graphical Description of Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Graphical Description of Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Numerical-description-of-Data.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Numerical Description of Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Discrete Probability Distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Discrete Probability Distribution</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Continuous Probability Distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Continuous Probability Distribution</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./One Sample Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">One Sample Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Two Sample Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Two Sample Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chi-Square and ANOVA Tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Chi-squared and ANOVA Tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./References.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#measures-of-center" id="toc-measures-of-center" class="nav-link active" data-scroll-target="#measures-of-center"><span class="header-section-number">4.1</span> Measures of Center</a>
  <ul class="collapse">
  <li><a href="#population-mean" id="toc-population-mean" class="nav-link" data-scroll-target="#population-mean"><span class="header-section-number">4.1.1</span> <strong>Population Mean</strong></a></li>
  <li><a href="#sample-mean" id="toc-sample-mean" class="nav-link" data-scroll-target="#sample-mean"><span class="header-section-number">4.1.2</span> <strong>Sample Mean</strong></a></li>
  <li><a href="#example-finding-the-mean-and-median-using-rguroo" id="toc-example-finding-the-mean-and-median-using-rguroo" class="nav-link" data-scroll-target="#example-finding-the-mean-and-median-using-rguroo"><span class="header-section-number">4.1.3</span> Example: Finding the Mean and Median using Rguroo</a></li>
  <li><a href="#example-finding-mean-and-median-with-factor" id="toc-example-finding-mean-and-median-with-factor" class="nav-link" data-scroll-target="#example-finding-mean-and-median-with-factor"><span class="header-section-number">4.1.4</span> Example: Finding Mean and Median with Factor</a></li>
  <li><a href="#example-effect-of-extreme-values-on-mean-and-median" id="toc-example-effect-of-extreme-values-on-mean-and-median" class="nav-link" data-scroll-target="#example-effect-of-extreme-values-on-mean-and-median"><span class="header-section-number">4.1.5</span> Example: Effect of Extreme Values on Mean and Median</a></li>
  <li><a href="#weighted-average" id="toc-weighted-average" class="nav-link" data-scroll-target="#weighted-average"><span class="header-section-number">4.1.6</span> <strong>Weighted Average</strong></a></li>
  <li><a href="#example-weighted-average" id="toc-example-weighted-average" class="nav-link" data-scroll-target="#example-weighted-average"><span class="header-section-number">4.1.7</span> Example: Weighted Average</a></li>
  <li><a href="#example-weighted-average-1" id="toc-example-weighted-average-1" class="nav-link" data-scroll-target="#example-weighted-average-1"><span class="header-section-number">4.1.8</span> Example: Weighted Average</a></li>
  <li><a href="#homework-for-measures-of-center-section" id="toc-homework-for-measures-of-center-section" class="nav-link" data-scroll-target="#homework-for-measures-of-center-section"><span class="header-section-number">4.1.9</span> Homework for Measures of Center Section</a></li>
  </ul></li>
  <li><a href="#measures-of-spread" id="toc-measures-of-spread" class="nav-link" data-scroll-target="#measures-of-spread"><span class="header-section-number">4.2</span> Measures of Spread</a>
  <ul class="collapse">
  <li><a href="#example-range" id="toc-example-range" class="nav-link" data-scroll-target="#example-range"><span class="header-section-number">4.2.1</span> Example: Range</a></li>
  <li><a href="#example-finding-the-standard-deviation" id="toc-example-finding-the-standard-deviation" class="nav-link" data-scroll-target="#example-finding-the-standard-deviation"><span class="header-section-number">4.2.2</span> Example: Finding the Standard Deviation</a></li>
  <li><a href="#use-of-standard-deviation" id="toc-use-of-standard-deviation" class="nav-link" data-scroll-target="#use-of-standard-deviation"><span class="header-section-number">4.2.3</span> <strong>Use of Standard Deviation</strong></a></li>
  <li><a href="#example-the-general-rule" id="toc-example-the-general-rule" class="nav-link" data-scroll-target="#example-the-general-rule"><span class="header-section-number">4.2.4</span> Example: the general rule</a></li>
  <li><a href="#example-determining-if-a-value-is-unusual" id="toc-example-determining-if-a-value-is-unusual" class="nav-link" data-scroll-target="#example-determining-if-a-value-is-unusual"><span class="header-section-number">4.2.5</span> Example: Determining If a Value Is Unusual</a></li>
  <li><a href="#homework-for-measures-of-spread-section" id="toc-homework-for-measures-of-spread-section" class="nav-link" data-scroll-target="#homework-for-measures-of-spread-section"><span class="header-section-number">4.2.6</span> Homework for Measures of Spread Section</a></li>
  </ul></li>
  <li><a href="#ranking" id="toc-ranking" class="nav-link" data-scroll-target="#ranking"><span class="header-section-number">4.3</span> Ranking</a>
  <ul class="collapse">
  <li><a href="#example-interpreting-percentile" id="toc-example-interpreting-percentile" class="nav-link" data-scroll-target="#example-interpreting-percentile"><span class="header-section-number">4.3.1</span> Example: Interpreting Percentile</a></li>
  <li><a href="#example-percentile-versus-score" id="toc-example-percentile-versus-score" class="nav-link" data-scroll-target="#example-percentile-versus-score"><span class="header-section-number">4.3.2</span> Example: Percentile Versus Score</a></li>
  <li><a href="#to-find-the-quartiles" id="toc-to-find-the-quartiles" class="nav-link" data-scroll-target="#to-find-the-quartiles"><span class="header-section-number">4.3.3</span> <strong>To find the quartiles</strong>:</a></li>
  <li><a href="#example-five-number-summary-and-boxplot" id="toc-example-five-number-summary-and-boxplot" class="nav-link" data-scroll-target="#example-five-number-summary-and-boxplot"><span class="header-section-number">4.3.4</span> Example: Five-number Summary and Boxplot</a></li>
  <li><a href="#example-separating-based-on-a-factor" id="toc-example-separating-based-on-a-factor" class="nav-link" data-scroll-target="#example-separating-based-on-a-factor"><span class="header-section-number">4.3.5</span> Example: Separating based on a factor</a></li>
  <li><a href="#example-putting-it-all-together" id="toc-example-putting-it-all-together" class="nav-link" data-scroll-target="#example-putting-it-all-together"><span class="header-section-number">4.3.6</span> Example: Putting it all together</a></li>
  <li><a href="#homework-for-ranking-section" id="toc-homework-for-ranking-section" class="nav-link" data-scroll-target="#homework-for-ranking-section"><span class="header-section-number">4.3.7</span> Homework for Ranking Section</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Numerical Description of Data</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Chapter 1 discussed what a population, sample, parameter, and statistic are, and how to take different types of samples. Chapter 2 discussed ways to graphically display data. There was also a discussion of important characteristics: center, variations, distribution, outliers, and changing characteristics of the data over time. Distributions and outliers can be answered using graphical means. Finding the center and variation can be done using numerical methods that will be discussed in this chapter. Both graphical and numerical methods are part of a branch of statistics known as <strong>descriptive statistics</strong>. Later descriptive statistics will be used to make decisions and/or estimate population parameters using methods that are part of the branch called <strong>inferential statistics</strong>.</p>
<section id="measures-of-center" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="measures-of-center"><span class="header-section-number">4.1</span> Measures of Center</h2>
<p>This section focuses on measures of central tendency. Many times you are asking what to expect on average. Such as when you pick a major, you would probably ask how much you expect to earn in that field. If you are thinking of relocating to a new town, you might ask how much you can expect to pay for housing. If you are planting vegetables in the spring, you might want to know how long it will be until you can harvest. These questions, and many more, can be answered by knowing the center of the data set. There are three measures of the “center” of the data. They are the mode, median, and mean. Any of the values can be referred to as the “average.”</p>
<p>The <strong>mode</strong> is the data value that occurs the most frequently in the data. To find it, you count how often each data value occurs, and then determine which data value occurs most often. The mode is not the most useful measure of center. This is because, a data set can have more than one mode. If there is a tie between two values for the most number of times then both values are the mode and the data is called bimodal (two modes). If every data point occurs the same number of times, there is no mode. If there are more than two numbers that appear the most times, then usually there is no mode.</p>
<p>The <strong>median</strong> is the data value in the middle of a sorted list of data. To find it, you put the data in order, and then determine which data value is in the middle of the data set.</p>
<p>The <strong>mean</strong> is the arithmetic average of the numbers. This is the center that most people call the average, though all three – mean, median, and mode – really are averages.</p>
<p>There are no symbols for the mode and the median, but the mean is used a great deal, and statisticians gave it a symbol. There are actually two symbols, one for the population parameter and one for the sample statistic. In most cases you cannot find the population parameter, so you use the sample statistic to estimate the population parameter.</p>
<section id="population-mean" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="population-mean"><span class="header-section-number">4.1.1</span> <strong>Population Mean</strong></h3>
<p><span class="math inline">\(\mu=\frac{\sum{x}}{N}\)</span>, pronounced mu</p>
<p><strong>N</strong> is the size of the population.</p>
<p><strong>x</strong> represents a data value.</p>
<p><span class="math inline">\(\sum{x}\)</span> means to add up all of the data values.</p>
</section>
<section id="sample-mean" class="level3" data-number="4.1.2">
<h3 data-number="4.1.2" class="anchored" data-anchor-id="sample-mean"><span class="header-section-number">4.1.2</span> <strong>Sample Mean</strong></h3>
<p><span class="math inline">\(\bar{x}=\frac{\sum{x}}{n}\)</span>, pronounced x bar.</p>
<p><strong>n</strong> is the size of the sample.</p>
<p><strong>x</strong> represents a data value.</p>
<p><span class="math inline">\(\sum{x}\)</span> means to add up all of the data values.</p>
<p>The value for <span class="math inline">\(\bar{x}\)</span> is used to estimate <span class="math inline">\(\mu\)</span> since <span class="math inline">\(\mu\)</span> can’t be calculated in most situations.</p>
</section>
<section id="example-finding-the-mean-and-median-using-rguroo" class="level3" data-number="4.1.3">
<h3 data-number="4.1.3" class="anchored" data-anchor-id="example-finding-the-mean-and-median-using-rguroo"><span class="header-section-number">4.1.3</span> Example: Finding the Mean and Median using Rguroo</h3>
<p>Suppose a vet wants to find the average weight of cats. The weights (in kg) of cats are in <a href="#tbl-Cats" class="quarto-xref">Table&nbsp;<span>4.1</span></a>.</p>
<div class="cell" data-tbl-alt="Table showing first 6 rows of cats dataset">
<div id="tbl-Cats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Table showing first 6 rows of cats dataset">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Cats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.1: Head of Cats
</figcaption>
<div aria-describedby="tbl-Cats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Sex</th>
<th style="text-align: right;">Bwt</th>
<th style="text-align: right;">Hwt</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">F</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">7.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">F</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">7.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">F</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">9.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">F</td>
<td style="text-align: right;">2.1</td>
<td style="text-align: right;">7.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">F</td>
<td style="text-align: right;">2.1</td>
<td style="text-align: right;">7.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">F</td>
<td style="text-align: right;">2.1</td>
<td style="text-align: right;">7.6</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<!-- The head command shows the variable names and the first few unit of observation rows -->
<p>Click to expand the box below to see instructions to import and view the <span class="data">cats</span> dataset in your <strong>Data</strong> Toolbox in Rguroo.</p>
<div id="Importing-cats-to-Rguroo" class="callout callout-style-simple callout-note callout-titled" title="![](Rguroo_Icons/R_circle_logo.svg){width=22px style='vertical-align:middle;'}  Importing cats to Data Toolbox">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<img src="Rguroo_Icons/R_circle_logo.svg" class="img-fluid" style="vertical-align:middle;" width="22"> Importing cats to Data Toolbox
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Go to the <strong>Data</strong> toolbox.</li>
<li>From the <span class="dpd">Data Import</span> dropdown, select <span class="fun">Dataset Repository</span>.</li>
<li>In the top search box, type <span class="typein">MASS</span>, then select the <span class="repo">MASS</span> repository.</li>
<li>In the middle search box, type <span class="typein">cats</span>, and select the <span class="data">cats</span> dataset that appears in the lower panel.<br>
</li>
<li>Click the <span class="button">Import</span> button. The dataset will be imported into your Rguroo account.</li>
<li>Click the <span class="button">Close</span> button to close the Rguroo dialog.</li>
<li>To view the dataset, double-click <span class="data">cats</span> under the <strong>Data</strong> toolbox list.</li>
</ol>
</div>
</div>
</div>
<p>Find the mean and median of the weight of a cat.</p>
<section id="solution" class="level4" data-number="4.1.3.1">
<h4 data-number="4.1.3.1" class="anchored" data-anchor-id="solution"><span class="header-section-number">4.1.3.1</span> <strong>Solution</strong></h4>
<p>Before starting any mathematics problem, it is always a good idea to define the unknown in the problem. In statistics, you want to define the variable. The symbol for the variable is *x*.</p>
<p>The variable is <strong>x</strong> = weight of a cat</p>
<p>Click to expand the box below see how to calculate the mean and median in Rguroo.</p>
<div id="Calculating-summary-stats-in-Rguroo" class="callout callout-style-simple callout-note callout-titled" title="![](Rguroo_Icons/R_circle_logo.svg){width=22px style='vertical-align:middle;'} Calculating the Mean and Median Weight of Cats">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<img src="Rguroo_Icons/R_circle_logo.svg" class="img-fluid" style="vertical-align:middle;" width="22"> Calculating the Mean and Median Weight of Cats
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Before you begin:</strong> Make sure you have already imported the <span class="data">cats</span> dataset into your <strong>Data</strong> Toolbox, as was shown <a href="#Importing-cats-to-Rguroo">here</a>.</p>
<ol type="1">
<li>Open the <strong>Data</strong> toolbox.<br>
</li>
<li>Click on the <span class="dpd">Functions</span> dropdown, and select <span class="fun">Summary Statistic</span>. This opens the Basic Summary Statistic dialog.<br>
</li>
<li>From the <span class="dpd">Dataset</span> dropdown, select the <span class="data">cats</span> dataset.<br>
</li>
<li>From the <span class="dpd">Numerical</span> dropdown, select the <span class="var">Bwt</span> variable.<br>
</li>
<li>In the <strong>Statistics</strong> section of the dialog, select the checkbox for Mean and Median.<br>
</li>
<li>Click the preview icon <img src="Rguroo_Icons/preview_inline.png" class="img-fluid" alt="preview icon"> to see the summary statistics.</li>
</ol>
<div class="callout callout-style-simple callout-note callout-titled" title="Click here to see the Rguroo dialog">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click here to see the Rguroo dialog
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Final_output/Rguroo_dialogs/Numerical_description/summary_stat_dia_clean.png" class="img-fluid figure-img" width="500"></p>
<figcaption>Basic Summary Statistic dialog in Rguroo</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-summary-cats" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Mean and Median Output from Rguroo">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-summary-cats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Rguroo_outputs/Numerical_Description/cats_summary_output.png" class="img-fluid figure-img" style="width:70.0%" alt="Mean and Median Output from Rguroo">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-summary-cats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.1: Mean and Median Weight of Cats
</figcaption>
</figure>
</div>
</div>
</div>
<p>The mean weight is 2.72 kg.</p>
<!-- Median: To find with r Studio, perform the command: -->
<p>The median weight is 2.7 kg also. It appears the average weight is 2.7 kg of all cats.</p>
</section>
</section>
<section id="example-finding-mean-and-median-with-factor" class="level3" data-number="4.1.4">
<h3 data-number="4.1.4" class="anchored" data-anchor-id="example-finding-mean-and-median-with-factor"><span class="header-section-number">4.1.4</span> Example: Finding Mean and Median with Factor</h3>
<p>Looking at the data frame for cats weights <a href="#tbl-Cats" class="quarto-xref">Table&nbsp;<span>4.1</span></a> you see that there are several variables You may want to know what the other variables are. A Code Book describes the data set, explains what the variables are including the units, and the source of the data frame. The code book for the <span class="data">cats</span> is below.</p>
<p><strong>Image 3.1.1: Code book for cats data frame</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="code_book_cats.jpg" class="img-fluid figure-img" alt="Code book cats Dataframe"></p>
<figcaption>Code book for cats data frame</figcaption>
</figure>
</div>
<p>Suppose you want to know if male cats weigh more than female cats. Looking at the variables, you notice that there is a variable for the sex of the cat. You can look at the weights of males and females separately. This looks like:</p>
<section id="solution-1" class="level4" data-number="4.1.4.1">
<h4 data-number="4.1.4.1" class="anchored" data-anchor-id="solution-1"><span class="header-section-number">4.1.4.1</span> <strong>Solution</strong></h4>
<p>Click to expand the box below see how to calculate the mean and median, separated by sex, in Rguroo.</p>
<div class="callout callout-style-simple callout-note callout-titled" title="![](Rguroo_Icons/R_circle_logo.svg){width=22px style='vertical-align:middle;'} Calculating the Mean and Median Weight of Cats by Sex">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<img src="Rguroo_Icons/R_circle_logo.svg" class="img-fluid" style="vertical-align:middle;" width="22"> Calculating the Mean and Median Weight of Cats by Sex
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Before you begin:</strong> Make sure you have already imported the <span class="data">cats</span> dataset into your <strong>Data</strong> Toolbox, as was shown <a href="#Importing-cats-to-Rguroo">here</a>.</p>
<ol type="1">
<li>Open the <strong>Data</strong> toolbox.<br>
</li>
<li>Click on the <span class="dpd">Functions</span> dropdown, and select <span class="fun">Summary Statistic</span>. This opens the Basic Summary Statistic dialog.<br>
</li>
<li>From the <span class="dpd">Dataset</span> dropdown, select the <span class="data">cats</span> dataset.<br>
</li>
<li>From the <span class="dpd">Numerical</span> dropdown, select the <span class="var">Bwt</span> variable.</li>
<li>From the <span class="dpd">Factor 1</span> dropdown, select the <span class="des">Sex</span> factor.</li>
<li>In the <strong>Statistics</strong> section of the dialog, select the checkbox for Mean and Median.<br>
</li>
<li>Click the preview icon <img src="Rguroo_Icons/preview_inline.png" class="img-fluid" alt="preview icon"> to see the summary statistics.</li>
</ol>
<div class="callout callout-style-simple callout-note callout-titled" title="Click here to see the Rguroo dialog">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click here to see the Rguroo dialog
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Final_output/Rguroo_dialogs/Numerical_Description/cats_weight_sex.png" class="img-fluid figure-img" width="500"></p>
<figcaption>Basic Summary Statistic dialog in Rguroo</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-factor-summary-cats" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Mean and Median by Sex Output from Rguroo">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-factor-summary-cats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Rguroo_outputs/Numerical_Description/cat_wt_sex_output.png" class="img-fluid figure-img" style="width:70.0%" alt="Mean and Median by Sex Output from Rguroo">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-factor-summary-cats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.2: Mean and Median Weight of Cats by Sex
</figcaption>
</figure>
</div>
</div>
</div>
<p>Notice that the female cats’ mean weight is 2.4 kg and the male cats’ mean weight is 2.9 kg. The median weight of female cats is 2.3 kg and for males it is 2.9 kg. So it does appear that male cats weigh a bit more than the female cats.</p>
<p>There are many different summary statistics that can be found. An example is the minimum and maximum value. In this example, you will see how to find the min and max values and then filter them out of a data set to see what effect they have on the mean and median.</p>
</section>
</section>
<section id="example-effect-of-extreme-values-on-mean-and-median" class="level3" data-number="4.1.5">
<h3 data-number="4.1.5" class="anchored" data-anchor-id="example-effect-of-extreme-values-on-mean-and-median"><span class="header-section-number">4.1.5</span> Example: Effect of Extreme Values on Mean and Median</h3>
<p>Find the minimum and maximum values of cats weights.</p>
<section id="solution-2" class="level4" data-number="4.1.5.1">
<h4 data-number="4.1.5.1" class="anchored" data-anchor-id="solution-2"><span class="header-section-number">4.1.5.1</span> <strong>Solution</strong></h4>
<p>The steps to find the minimum and the maximum in Rguroo are similar to finding the mean and median. In the <strong>Statistics</strong> section of the dialog, select the checkbox for Minimum and Maximum.</p>
<p>Here is the Basic Summary Statistic Dialog and Output from Rguroo for the minimum and maximum of cats body weight.</p>
<div class="cell">
<div id="fig-max-min-cats" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-max-min-cats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="fig-max-min-cats-1" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Maximum and Minumum dialog and Output from Rguroo">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-max-min-cats-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Rguroo_dialogs/Numerical_Description/max_min_dialog.png" class="img-fluid figure-img" style="width:70.0%" data-ref-parent="fig-max-min-cats" alt="Maximum and Minumum dialog and Output from Rguroo">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-max-min-cats-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Dialog box
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div id="fig-max-min-cats-2" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Maximum and Minumum dialog and Output from Rguroo">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-max-min-cats-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Rguroo_outputs/Numerical_Description/max_min_output.png" class="img-fluid figure-img" style="width:70.0%" data-ref-parent="fig-max-min-cats" alt="Maximum and Minumum dialog and Output from Rguroo">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-max-min-cats-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Output results
</figcaption>
</figure>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-max-min-cats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.3: Maximum and Minimum Weight of Cats
</figcaption>
</figure>
</div>
</div>
<p>The minimum weight of a cat in this data frame is 2 kg and the maximum weight of a cat is 3.9 kg.</p>
<p>You can create two new data sets in Rguroo by subsetting (filtering). One data set will exclude the maximum value. Click to expand the box below to see how to subset a dataset in Rguroo:</p>
<div id="Subsetting-Data-in-Rguroo" class="callout callout-style-simple callout-note callout-titled" title="![](Rguroo_Icons/R_circle_logo.svg){width=22px style='vertical-align:middle;'} Subsetting the cats Dataset">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<img src="Rguroo_Icons/R_circle_logo.svg" class="img-fluid" style="vertical-align:middle;" width="22"> Subsetting the cats Dataset
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Before you begin:</strong> Make sure you have already imported the <span class="data">cats</span> dataset into your <strong>Data</strong> Toolbox, as was shown <a href="#Importing-cats-to-Rguroo">here</a>.</p>
<ol type="1">
<li>Open the <strong>Data</strong> toolbox.<br>
</li>
<li>Click on the <span class="dpd">Functions</span> dropdown, and select <span class="fun">Subset</span>. This opens the <span class="dialog">Data Subset</span> dialog.<br>
</li>
<li>From the <span class="dpd">Dataset</span> dropdown, select the <span class="data">cats</span> dataset.<br>
</li>
<li>Select the <span class="button">Logical Expression</span> button.<br>
</li>
<li>To create a new Logical Expression, click the green plus icon.</li>
<li>From the <span class="dpd">Variable</span> dropdown, select the <span class="var">Bwt</span>. From the <span class="dpd">Op.</span> (operations) dropwdown, select the less than symbol (&lt;). In the Value column, enter 3.9 (the maximum body weight of cats dataset). Click the <span class="button">Done</span>.</li>
<li>When you are done with your selection, click the preview icon <img src="Rguroo_Icons/preview_inline.png" class="img-fluid" alt="preview icon"> to see a preview of the scatterplot.</li>
<li>In Save As… name the new data set cats_nomax and click the <span class="button">Save As…</span>.</li>
</ol>
<div class="callout callout-style-simple callout-note callout-titled" title="Click here to see the Rguroo dialog">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click here to see the Rguroo dialog
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><img src="Rguroo_dialogs/Numerical_description/subset_nomax_cats.png" class="img-fluid" width="500" alt="Logical Expression Dialog in Rguroo"> <img src="Rguroo_dialogs/Numerical_description/logical_subset_nomax.png" class="img-fluid" width="500" alt="Data Subset Dialog in Rguroo"> <img src="Rguroo_outputs/Numerical_Description/save_data_nomax.png" class="img-fluid" alt="Save As… Dataset View"></p>
</div>
</div>
</div>
</div>
</div>
</div>
<p>Then create a data set that excludes the minimum value using the same steps shown <a href="#Subsetting-Data-in-Rguroo">here</a>. In the <span class="dialog">Logical Expression</span> dialog, choose the greater than (&gt;) operator in the <span class="dpd">Op.</span> dropdown and enter 2 in the Value column. Save this new dataset as <span class="data">cats_nomin</span>.</p>
<!-- The \<- is the way to indicate to r what the data set nomin is equivalent to what follows the symbol. Notice that it doesn't look like anything happened, but new data sets were created in the background.-->
<p>Now you can find the mean and median of each new data set using the steps described <a href="#Calculating-summary-stats-in-Rguroo">here</a> :</p>
<p>The mean without the maximum value is 2.70 kg, and the median is 2.7 kg.</p>
<p>The mean without the minimum value is 2.75 kg, and the median is 2.7 kg.</p>
<p>From <a href="#example-effect-of-extreme-values-on-mean-and-median">Example: Effect of Extreme Values on Mean and Median</a>, the mean of the <span class="data">cats</span> data set with all the values is 2.72 kg where the median is 2.7 kg. Notice that when the maximum value was excluded from the data set, the mean decreased a little but the median didn’t change, and when the minimum value was excluded from the data set, the mean increased a little but the median didn’t change. The mean is much higher than the median. Why is this? This is because the mean is affected by extreme values, while the median is not. We say the median is a resistant measure of center because it isn’t affected by extreme values as much.</p>
<p>An outlier is a data value that is very different from the rest of the data. It can be really high or really low. Extreme values may be an outlier if the extreme value is far enough from the center. If there are extreme values in the data, the median is a better measure of the center than the mean. If there are no extreme values, the mean and the median will be similar so most people use the mean. The mean is not a resistant measure because it is affected by extreme values. The median is a resistant measure because it not affected by extreme values.</p>
<p>As a consumer you need to be aware that people choose the measure of center that best supports their claim. When you read an article in the newspaper and it talks about the “average” it usually means the mean but sometimes it refers to the median. Some articles will use the word “median” instead of “average” to be more specific. If you need to make an important decision and the information says “average”, it would be wise to ask if the “average” is the mean or the median before you decide.</p>
<p>As an example, suppose that a company wants to use the mean salary as the average salary for the company. This is because the high salaries of the administrators will pull the mean higher. The company can say that the employees are paid well because the average is high. However, the employees want to use the median since it discounts the extreme values of the administration and will give a lower value of the average. This will make the salaries seem lower and that a raise is in order.</p>
<p>Why use the mean instead of the median? The reason is because when multiple samples are taken from the same population, the sample means tend to be more consistent than other measures of the center.</p>
<p>To understand how the different measures of center relate to skewed or symmetric distributions, see <a href="#fig-centers-dist" class="quarto-xref">Figure&nbsp;<span>4.4</span></a>. As you can see sometimes the mean is smaller than the median, sometimes the mean is larger than the median, and sometimes they are the same values.</p>
<p><strong><a href="#fig-centers-dist" class="quarto-xref">Figure&nbsp;<span>4.4</span></a>: Mean, Median, Mode as Related to a Distribution</strong></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-centers-dist" class="quarto-float quarto-figure quarto-figure-center anchored" alt="skewed left graph with mean, median,mode lines, then symmetric graph with all three the same line, then skewed right graph with mode, median, mean lines">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-centers-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Final_output/images/centers_distribution.png" class="img-fluid figure-img" style="width:70.0%" alt="skewed left graph with mean, median,mode lines, then symmetric graph with all three the same line, then skewed right graph with mode, median, mean lines">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-centers-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.4: Mean, median, mode as related to distribution
</figcaption>
</figure>
</div>
</div>
</div>
<p>One last type of average is a weighted average. <strong>Weighted averages</strong> are used quite often in different situations. Some teachers use them in calculating a student’s grade in the course, or a grade on a project. Some employers use them in employee evaluations. The idea is that some activities are more important than others. As an example, a full time teacher at a community college may be evaluated on their service to the college, their service to the community, whether their paperwork is turned in on time, and their teaching. However, teaching is much more important than whether their paperwork is turned in on time. When the evaluation is completed, more weight needs to be given to the teaching and less to the paperwork. This is a weighted average.</p>
</section>
</section>
<section id="weighted-average" class="level3" data-number="4.1.6">
<h3 data-number="4.1.6" class="anchored" data-anchor-id="weighted-average"><span class="header-section-number">4.1.6</span> <strong>Weighted Average</strong></h3>
<p><span class="math inline">\(\text{weighted average}=\frac{\sum{x*w}}{\sum{w}}\)</span></p>
<p>where <strong>w</strong> is the weight of the data value, <strong>x</strong>.</p>
</section>
<section id="example-weighted-average" class="level3" data-number="4.1.7">
<h3 data-number="4.1.7" class="anchored" data-anchor-id="example-weighted-average"><span class="header-section-number">4.1.7</span> Example: Weighted Average</h3>
<p>In your biology class, your final grade is based on several things: a lab score, scores on two major tests, and your score on the final exam. There are 100 points available for each score. The lab score is worth 15% of the course, the two exams are worth 25% of the course each, and the final exam is worth 35% of the course. Suppose you earned scores of 95 on the labs, 83 and 76 on the two exams, and 84 on the final exam. Compute your weighted average for the course.</p>
<section id="solution-3" class="level4" data-number="4.1.7.1">
<h4 data-number="4.1.7.1" class="anchored" data-anchor-id="solution-3"><span class="header-section-number">4.1.7.1</span> <strong>Solution</strong></h4>
<p>Variable: <strong>x</strong> = score</p>
<p>A weighted average can be found using Rguroo. First, we will create a new dataset in Rguroo. Click to expand the box below to see how to create a new dataset in Rguroo:</p>
<div id="Creating-new-dataset" class="callout callout-style-simple callout-note callout-titled" title="![](Rguroo_Icons/R_circle_logo.svg){width=22px style='vertical-align:middle;'} Creating a New Dataset">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<img src="Rguroo_Icons/R_circle_logo.svg" class="img-fluid" style="vertical-align:middle;" width="22"> Creating a New Dataset
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Open the <strong>Data</strong> toolbox.<br>
</li>
<li>Click on the <span class="dpd">Data Import</span> dropdown, and select <span class="fun">Create New Dataset</span>. This opens the <span class="dialog">Create New Dataset</span> dialog. Specify the number of rows and columns for your new dataset.<br>
</li>
<li>The default variable names will be <span class="var">Var1</span>, <span class="var">Var2</span>, etc. To change the variable name, move your cursor over the variable name on the header. You will see the Variable Context Menu icon. Click on the icon to open the variable context menu. From the menu select the option <span class="des">Rename</span>. This will bring up the <span class="dialog">Rename Variable</span> dialog box. In the dialog box, type in the new name for your variable, and press enter. The new name will now appear on the header. Note that variable names cannot have spaces.<br>
</li>
<li>Enter your data.<br>
</li>
<li>Enter a name for your dataset in the <span class="des">Save As</span> textbox on the top, and click the <span class="button">Save as</span> button to save your dataset.</li>
</ol>
<div class="callout callout-style-simple callout-note callout-titled" title="Click here to see the Rguroo dialog and new dataset">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click here to see the Rguroo dialog and new dataset
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><img src="Rguroo_dialogs/Numerical_description/new_dataset_dialog.png" class="img-fluid" width="500" alt="New Dataset Dialog"> <img src="Rguroo_outputs/Numerical_Description/biology_dataset.png" class="img-fluid" width="500" alt="Biology Class Dataset"></p>
</div>
</div>
</div>
</div>
</div>
</div>
<!-- The commands for finding the weighted mean using RStudio is as follows:

x\<-c(type in the scores with commas in between)

w\<-c(type in the weights as decimals with commas in between

weighted.mean(x,w)

The **x** and **w** represent the variables, \<- means make the variables equivalent to what follows, the c( means combine all the values in the () as one combined variable.

For this example, the commands would be -->
<p>To calculate the weighted average in Rguroo, you will follow the same steps described <a href="#Calculating-summary-stats-in-Rguroo">here</a>. In the <span class="dialog">Basic Summary Statistics</span> dialog box select the <span class="data">biology_grade</span> from the <span class="dpd">dataset</span> dropdown, select <span class="var">score</span> in the <span class="dpd">Numerical</span> dropdown, and select <span class="var">weight</span> in the <span class="dpd">frequency</span> dropdown as shown in figure <a href="#fig-weighted-mean" class="quarto-xref">Figure&nbsp;<span>4.5</span></a>.</p>
<div class="cell">
<div id="fig-weighted-mean" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-weighted-mean-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="fig-weighted-mean-1" class="quarto-float quarto-figure quarto-figure-center anchored" alt="basic summary statistics dialog box and weighted mean output">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-weighted-mean-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Rguroo_dialogs/Numerical_Description/summary_stat_dialog_weight_mean.png" class="img-fluid figure-img" style="width:70.0%" data-ref-parent="fig-weighted-mean" alt="basic summary statistics dialog box and weighted mean output">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-weighted-mean-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Basic Summary Statistics Dialog box
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div id="fig-weighted-mean-2" class="quarto-float quarto-figure quarto-figure-center anchored" alt="basic summary statistics dialog box and weighted mean output">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-weighted-mean-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Rguroo_outputs/Numerical_Description/weight_mean_bio_grade.png" class="img-fluid figure-img" style="width:70.0%" data-ref-parent="fig-weighted-mean" alt="basic summary statistics dialog box and weighted mean output">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-weighted-mean-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Output results
</figcaption>
</figure>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-weighted-mean-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.5: Weighted Mean of Biology Grade
</figcaption>
</figure>
</div>
</div>
<p>Your weighted mean in the biology class is 83.4%. Using the traditional grading scale, you have a B in the class.</p>
</section>
</section>
<section id="example-weighted-average-1" class="level3" data-number="4.1.8">
<h3 data-number="4.1.8" class="anchored" data-anchor-id="example-weighted-average-1"><span class="header-section-number">4.1.8</span> Example: Weighted Average</h3>
<p>The faculty evaluation process at John Jingle University rates a faculty member on the following activities: teaching, publishing, committee service, community service, and submitting paperwork in a timely manner. The process involves reviewing student evaluations, peer evaluations, and supervisor evaluation for each teacher and awarding him/her a score on a scale from 1 to 10 (with 10 being the best). The weights for each activity are 20 for teaching, 18 for publishing, 6 for committee service, 4 for community service, and 2 for paperwork.</p>
<ol type="a">
<li>One faculty member had the following ratings: 8 for teaching, 9 for publishing, 2 for committee work, 1 for community service, and 8 for paperwork. Compute the weighted average of the evaluation.</li>
<li>Another faculty member had ratings of 6 for teaching, 8 for publishing, 9 for committee work, 10 for community service, and 10 for paperwork. Compute the weighted average of the evaluation.</li>
<li>Which faculty member had the higher average evaluation?</li>
</ol>
<section id="solution-4" class="level4" data-number="4.1.8.1">
<h4 data-number="4.1.8.1" class="anchored" data-anchor-id="solution-4"><span class="header-section-number">4.1.8.1</span> <strong>Solution</strong></h4>
<ol type="a">
<li>One faculty member had the following ratings: 8 for teaching, 9 for publishing, 2 for committee work, 1 for community service, and 8 for paperwork. Compute the weighted average of the evaluation.</li>
</ol>
<p>Variable: <strong>x</strong> = rating, <strong>w</strong> = weight</p>
<p>To find the weighted average using Rguroo, start by creating a new dataset as described <a href="#Creating-new-dataset">here</a>. The new dataset is shown in the figure <a href="#fig-dataset-ratings" class="quarto-xref">Figure&nbsp;<span>4.6</span></a> below.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-dataset-ratings" class="quarto-float quarto-figure quarto-figure-center anchored" alt="new dataset for weight of category in a and b">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dataset-ratings-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Rguroo_outputs/Numerical_Description/ex_4_1_8_dataset.png" class="img-fluid figure-img" style="width:70.0%" alt="new dataset for weight of category in a and b">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dataset-ratings-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.6: Faculty Ratings Dataset
</figcaption>
</figure>
</div>
</div>
</div>
<p>Calculate the weighted average in Rguroo using the same steps described <a href="#Calculating-summary-stats-in-Rguroo">here</a>. In the <span class="dialog">Basic Summary Statistics</span> dialog box select the <span class="data">faculty_ratings</span> from the <span class="dpd">dataset</span> dropdown, select <span class="var">faculty_a</span> in the <span class="dpd">Numerical</span> dropdown, and select <span class="var">weight</span> in the <span class="dpd">frequency</span> dropdown as shown in figure <a href="#fig-faculty_a-weighted_mean" class="quarto-xref">Figure&nbsp;<span>4.7</span></a>.</p>
<div class="cell">
<div id="fig-faculty_a-weighted_mean" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-faculty_a-weighted_mean-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="fig-faculty_a-weighted_mean-1" class="quarto-float quarto-figure quarto-figure-center anchored" alt="basic summary statistics dialog box and weighted mean output faculty_a">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-faculty_a-weighted_mean-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Rguroo_dialogs/Numerical_Description/ex_4_1_8_a_dialog.png" class="img-fluid figure-img" style="width:70.0%" data-ref-parent="fig-faculty_a-weighted_mean" alt="basic summary statistics dialog box and weighted mean output faculty_a">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-faculty_a-weighted_mean-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Basic Summary Statistics Dialog box
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div id="fig-faculty_a-weighted_mean-2" class="quarto-float quarto-figure quarto-figure-center anchored" alt="basic summary statistics dialog box and weighted mean output faculty_a">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-faculty_a-weighted_mean-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Rguroo_outputs/Numerical_Description/ex_4_1_8_a_output.png" class="img-fluid figure-img" style="width:70.0%" data-ref-parent="fig-faculty_a-weighted_mean" alt="basic summary statistics dialog box and weighted mean output faculty_a">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-faculty_a-weighted_mean-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Output results
</figcaption>
</figure>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-faculty_a-weighted_mean-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.7: Weighted Mean of Faculty Ratings
</figcaption>
</figure>
</div>
</div>
<p>The weighted average is 7.08.</p>
<ol start="2" type="a">
<li>Another faculty member had ratings of 6 for teaching, 8 for publishing, 9 for committee work, 10 for community service, and 10 for paperwork. Compute the weighted average of the evaluation.</li>
</ol>
<p>The weighted mean can be calculated in the same fasion as part (a). In the <span class="dialog">Basic Summary Statistics</span> dialog box select the <span class="data">faculty_ratings</span> from the <span class="dpd">dataset</span> dropdown, select <span class="var">faculty_b</span> in the <span class="dpd">Numerical</span> dropdown, and select <span class="var">weight</span> in the <span class="dpd">frequency</span> dropdown as shown in figure</p>
<div class="cell">
<div id="fig-faculty_b-weighted_mean" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-faculty_b-weighted_mean-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="fig-faculty_b-weighted_mean-1" class="quarto-float quarto-figure quarto-figure-center anchored" alt="basic summary statistics dialog box and weighted mean output faculty_b">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-faculty_b-weighted_mean-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Rguroo_dialogs/Numerical_Description/ex_4_1_8_b_dialog.png" class="img-fluid figure-img" style="width:70.0%" data-ref-parent="fig-faculty_b-weighted_mean" alt="basic summary statistics dialog box and weighted mean output faculty_b">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-faculty_b-weighted_mean-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Basic Summary Statistics Dialog box
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div id="fig-faculty_b-weighted_mean-2" class="quarto-float quarto-figure quarto-figure-center anchored" alt="basic summary statistics dialog box and weighted mean output faculty_b">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-faculty_b-weighted_mean-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Rguroo_outputs/Numerical_Description/ex_4_1_8_b_output.png" class="img-fluid figure-img" style="width:70.0%" data-ref-parent="fig-faculty_b-weighted_mean" alt="basic summary statistics dialog box and weighted mean output faculty_b">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-faculty_b-weighted_mean-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Output results
</figcaption>
</figure>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-faculty_b-weighted_mean-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.8: Weighted Mean of Faculty Ratings
</figcaption>
</figure>
</div>
</div>
<p>The weighted average for this employee is 7.56.</p>
<ol start="3" type="a">
<li><p>Which faculty member had the higher average evaluation?</p>
<p>The second faculty member has a higher average evaluation.</p></li>
</ol>
<p>The last thing to mention is which average is used on which type of data.</p>
<p>Mode can be found on nominal, ordinal, interval, and ratio data, since the mode is just the data value that occurs most often. You are just counting the data values.</p>
<p>Median can be found on ordinal, interval, and ratio data, since you need to put the data in order. As long as there is order to the data you can find the median.</p>
<p>Mean can be found on interval and ratio data, since you must have numbers to add together.</p>
</section>
</section>
<section id="homework-for-measures-of-center-section" class="level3" data-number="4.1.9">
<h3 data-number="4.1.9" class="anchored" data-anchor-id="homework-for-measures-of-center-section"><span class="header-section-number">4.1.9</span> Homework for Measures of Center Section</h3>
<p><strong>Use Rguroo on all problems. State the variable on all problems.</strong></p>
<ol type="1">
<li><strong>Before you begin:</strong> Make sure you have already imported the <span class="data">cholesterol</span> dataset into your <strong>Data</strong> Toolbox, as was shown <a href="#Importing-cats-to-Rguroo">here</a> by selecting the <span class="repo">Statistics Using Technology - Kozak</span> as shown in the figure <a href="#fig-kozak-repo" class="quarto-xref">Figure&nbsp;<span>4.9</span></a>. Cholesterol levels were collected from patients a certain number of days after they had a heart attack and are in <a href="#tbl-Cholesterol" class="quarto-xref">Table&nbsp;<span>4.2</span></a>. Find the mean and median for cholesterol levels 2 days after the heart attack.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div id="fig-kozak-repo" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Repository search">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-kozak-repo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Rguroo_dialogs/Numerical_Description/chol_data_repo.png" class="img-fluid figure-img" style="width:70.0%" alt="Repository search">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-kozak-repo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.9: Repository Search Dialog
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-tbl-alt="Table showing first 6 rows of Cholesterol dataset">
<div id="tbl-Cholesterol" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Table showing first 6 rows of Cholesterol dataset">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Cholesterol-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.2: Head of Cholesterol Levels of Patients After Heart Attack
</figcaption>
<div aria-describedby="tbl-Cholesterol-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">patient</th>
<th style="text-align: right;">day2</th>
<th style="text-align: right;">day4</th>
<th style="text-align: right;">day14</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">270</td>
<td style="text-align: right;">218</td>
<td style="text-align: right;">156</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">236</td>
<td style="text-align: right;">234</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">210</td>
<td style="text-align: right;">214</td>
<td style="text-align: right;">242</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">142</td>
<td style="text-align: right;">116</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">280</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">272</td>
<td style="text-align: right;">276</td>
<td style="text-align: right;">256</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><strong>Code book for Data Frame Cholesterol</strong></p>
<p><strong>Description</strong> Cholesterol levels were collected from patients a certain number of days after they had a heart attack</p>
<p>This data frame contains the following columns:</p>
<p>Patient: Patient number</p>
<p>day2: Cholesterol level of patient 2 days after heart attack. (mg/dL)</p>
<p>day4: Cholesterol level of patient 4 days after heart attack. (mg/dL)</p>
<p>day14: Cholesterol level of patient 14 days after heart attack. (mg/dL)</p>
<p>Source Ryan, B. F., Joiner, B. L., &amp; Ryan, Jr, T. A. (1985). Cholesterol levels after heart attack. Retrieved from <a href="https://gksmyth.github.io/ozdasl/general/cholest.html">here</a></p>
<p>References Ryan, Joiner &amp; Ryan, Jr, 1985</p>
<ol start="2" type="1">
<li><strong>Before you begin:</strong> Make sure you have already imported the <span class="data">length</span> dataset into your <strong>Data</strong> Toolbox located in the <span class="repo">Statistics Using Technology - Kozak</span>. The lengths (in kilometers) of rivers on the South Island of New Zealand and what body of water they flow into are listed in <a href="#tbl-Length" class="quarto-xref">Table&nbsp;<span>4.3</span></a> (Lee, 1994). Find the mean and median length of rivers that flow into the Pacific Ocean and the mean and median length of rivers that flow into the Tasman Sea.</li>
</ol>
<div class="cell" data-tbl-alt="Table showing first 6 rows of Length dataset">
<div id="tbl-Length" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Table showing first 6 rows of Length dataset">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Length-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.3: Head of Length of New zealand rivers (km)
</figcaption>
<div aria-describedby="tbl-Length-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">river</th>
<th style="text-align: right;">length</th>
<th style="text-align: left;">flowsto</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Clarence</td>
<td style="text-align: right;">209</td>
<td style="text-align: left;">Pacific</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conway</td>
<td style="text-align: right;">48</td>
<td style="text-align: left;">Pacific</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Waiau</td>
<td style="text-align: right;">169</td>
<td style="text-align: left;">Pacific</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hurunui</td>
<td style="text-align: right;">138</td>
<td style="text-align: left;">Pacific</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Waipara</td>
<td style="text-align: right;">64</td>
<td style="text-align: left;">Pacific</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ashley</td>
<td style="text-align: right;">97</td>
<td style="text-align: left;">Pacific</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><strong>Code book for data frame Length</strong></p>
<p><strong>Description</strong> Rivers in New Zealand, the lengths of river and what body of water the river flows into</p>
<p>This data frame contains the following columns:</p>
<p>River: Name of the river</p>
<p>length: how long the river is in kilometers</p>
<p>flowsto: what body of water the river flows into Pacific Ocean is Pacific and the Tasman Sea is Tasman</p>
<p>Source Lee, A. (1994). Data analysis: An introduction based on r. Auckland. Retrieved from <a href="https://gksmyth.github.io/ozdasl/oz/nzrivers.html">here</a></p>
<p>References Lee, A. (1994). Data analysis: An introduction based on r. Auckland.</p>
<ol start="3" type="1">
<li><strong>Before you begin:</strong> Make sure you have already imported the <span class="data">pay</span> dataset into your <strong>Data</strong> Toolbox, located in the <span class="repo">Statistics Using Technology - Kozak</span>. Print-O-Matic printing company’s employees have salaries that are contained in <a href="#tbl-Pay" class="quarto-xref">Table&nbsp;<span>4.4</span></a>.</li>
</ol>
<div class="cell" data-tbl-alt="Table showing first 6 rows of Pay dataset">
<div id="tbl-Pay" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Table showing first 6 rows of Pay dataset">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Pay-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.4: Head of Salaries of Print-O-Matic Printing Company Employees
</figcaption>
<div aria-describedby="tbl-Pay-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">employee</th>
<th style="text-align: right;">salary</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">CEO</td>
<td style="text-align: right;">272500</td>
</tr>
<tr class="even">
<td style="text-align: left;">Driver</td>
<td style="text-align: right;">58456</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CD74</td>
<td style="text-align: right;">100702</td>
</tr>
<tr class="even">
<td style="text-align: left;">CD65</td>
<td style="text-align: right;">57380</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Embellisher</td>
<td style="text-align: right;">73877</td>
</tr>
<tr class="even">
<td style="text-align: left;">Folder</td>
<td style="text-align: right;">65270</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><strong>Code book for data frame Pay</strong></p>
<p><strong>Description</strong> Salaries of Print-O-Matic printing company’s employees</p>
<p>This data frame contains the following columns:</p>
<p>employee:employees position in the company</p>
<p>salary: salary of that employee (Australian dollars (AUD))</p>
<p>Source John Matic provided the data from a company he worked with. The company’s name is fictitious, but the data is from an actual company.</p>
<p>References John Matic (2013)</p>
<ol type="a">
<li><p>Find the mean and median.</p></li>
<li><p>Find the mean and median with the CEO’s salary removed.</p></li>
<li><p>What happened to the mean and median when the CEO’s salary was removed? Why?</p></li>
<li><p>If you were the CEO, who is answering concerns from the union that employees are underpaid, which average (mean or median) using the complete data set of the complete data set would you prefer? Why?</p></li>
<li><p>If you were a platen worker, who believes that the employees need a raise, which average (mean or median) using the complete data set would you prefer? Why?</p></li>
</ol>
<!-- -->
<ol start="4" type="1">
<li><strong>Before you begin:</strong> Make sure you have already imported the <span class="data">cost</span> dataset into your <strong>Data</strong> Toolbox, located in the <span class="repo">Statistics Using Technology - Kozak</span>. Print-O-Matic printing company spends specific amounts on fixed costs every month. The costs of those fixed costs are in a <a href="#tbl-Cost" class="quarto-xref">Table&nbsp;<span>4.5</span></a>.</li>
</ol>
<div class="cell" data-tbl-alt="Table showing first 6 rows of Cost dataset">
<div id="tbl-Cost" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Table showing first 6 rows of Cost dataset">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Cost-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.5: Fixed Costs for Print-O-Matic Printing Company
</figcaption>
<div aria-describedby="tbl-Cost-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">charges</th>
<th style="text-align: right;">cost</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Bank charges</td>
<td style="text-align: right;">482</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cleaning</td>
<td style="text-align: right;">2208</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Computer expensive</td>
<td style="text-align: right;">2471</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lease payments</td>
<td style="text-align: right;">2656</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Postage</td>
<td style="text-align: right;">2117</td>
</tr>
<tr class="even">
<td style="text-align: left;">Uniforms</td>
<td style="text-align: right;">2600</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><strong>Code book for data frame Cost</strong></p>
<p><strong>Description</strong> fixed monthly charges for Print-0-Matic printing company</p>
<p>This data frame contains the following columns:</p>
<p>charges: Categories of monthly fixed charges</p>
<p>cost: fixed month costs (AUD)</p>
<p>Source John Matic provided the data from a company he worked with. The company’s name is fictitious, but the data is from an actual company.</p>
<p>References John Matic (2013)</p>
<ol type="a">
<li><p>Find the mean and median.</p></li>
<li><p>Find the mean and median with the bank charges removed.</p></li>
<li><p>What happened to the mean and median when the bank charges was removed? Why?</p></li>
<li><p>If it is your job to oversee the fixed costs, which average (mean or median) using the complete data set would you prefer to use when submitting a report to administration to show that costs are low? Why?</p></li>
<li><p>If it is your job to find places in the budget to reduce costs, which average (mean or median) using the complete data set would you prefer to use when submitting a report to administration to show that fixed costs need to be reduced? Why?</p></li>
</ol>
<!-- -->
<ol start="5" type="1">
<li>Looking at graph 3.1.2, state if the graph is skewed left, skewed right, or symmetric and then state which is larger, the mean or the median?</li>
</ol>
<p><strong>Graph 3.1.2: Skewed or Symmetric Graph</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Final_output/Rguroo_outputs/Numerical_Description/skewed_right_hist.png" class="img-fluid figure-img" alt="histogram with bars on left tallest and then gradually getting shorter as you go to the right"></p>
<figcaption>Graph 3.1.2</figcaption>
</figure>
</div>
<ol start="6" type="1">
<li>Looking at graph 3.1.3, state if the graph is skewed left, skewed right, or symmetric and then state which is larger, the mean or the median?</li>
</ol>
<p><strong>Graph 3.1.3: Skewed or Symmetric Graph</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Final_output/Rguroo_outputs/Numerical_Description/skewed_left_hist.png" class="img-fluid figure-img" alt="histogram with bars on left shortest and then gradually getting taller as you go to the right"></p>
<figcaption>Graph 3.1.3</figcaption>
</figure>
</div>
<ol start="7" type="1">
<li><p>An employee at Coconino Community College (CCC) is evaluated based on goal setting and accomplishments toward the goals, job effectiveness, competencies, and CCC core values. Suppose for a specific employee, goal 1 has a weight of 30%, goal 2 has a weight of 20%, job effectiveness has a weight of 25%, competency 1 has a weight of 4%, competency 2 has a weight of 3%, competency 3 has a weight of 3%, competency 4 has a weight of 3%, competency 5 has a weight of 2%, and core values has a weight of 10%. Suppose the employee has scores of 3.0 for goal 1, 3.0 for goal 2, 2.0 for job effectiveness, 3.0 for competency 1, 2.0 for competency 2, 2.0 for competency 3, 3.0 for competency 4, 4.0 for competency 5, and 3.0 for core values. Find the weighted average score for this employee. If an employee has a score less than 2.5, they must have a Performance Enhancement Plan written. Does this employee need a plan?</p></li>
<li><p>An employee at Coconino Community College (CCC) is evaluated based on goal setting and accomplishments toward goals, job effectiveness, competencies, CCC core values. Suppose for a specific employee, goal 1 has a weight of 20%, goal 2 has a weight of 20%, goal 3 has a weight of 10%, job effectiveness has a weight of 25%, competency 1 has a weight of 4%, competency 2 has a weight of 3%, competency 3 has a weight of 3%, competency 4 has a weight of 5%, and core values has a weight of 10%. Suppose the employee has scores of 2.0 for goal 1, 2.0 for goal 2, 3.0 for goal 3, 2.0 for job effectiveness, 2.0 for competency 1, 3.0 for competency 2, 2.0 for competency 3, 3.0 for competency 4, and 4.0 for core values. Find the weighted average score for this employee. If an employee that has a score less than 2.5, they must have a Performance Enhancement Plan written. Does this employee need a plan?</p></li>
<li><p>A statistics class has the following activities and weights for determining a grade in the course: test 1 worth 15% of the grade, test 2 worth 15% of the grade, test 3 worth 15% of the grade, homework worth 10% of the grade, semester project worth 20% of the grade, and the final exam worth 25% of the grade. If a student receives an 85 on test 1, a 76 on test 2, an 83 on test 3, a 74 on the homework, a 65 on the project, and a 79 on the final, what grade did the student earn in the course?</p></li>
<li><p>A statistics class has the following activities and weights for determining a grade in the course: test 1 worth 15% of the grade, test 2 worth 15% of the grade, test 3 worth 15% of the grade, homework worth 10% of the grade, semester project worth 20% of the grade, and the final exam worth 25% of the grade. If a student receives a 92 on test 1, an 85 on test 2, a 95 on test 3, a 92 on the homework, a 55 on the project, and an 83 on the final, what grade did the student earn in the course?</p></li>
</ol>
</section>
</section>
<section id="measures-of-spread" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="measures-of-spread"><span class="header-section-number">4.2</span> Measures of Spread</h2>
<p>Variability is an important idea in statistics. If you were to measure the height of everyone in your classroom, every observation gives you a different value. That means not every student has the same height. Thus there is variability in people’s heights. If you were to take a sample of the income level of people in a town, every sample gives you different information. There is variability between samples too. Variability describes how the data are spread out. If the data are very close to each other, then there is low variability. If the data are very spread out, then there is high variability. How do you measure variability? It would be good to have a number that measures it. This section will describe some of the different measures of variability, also known as variation.</p>
<p>In [Example: Finding the Mean and Median using Rguroo], the average weight of a cat was calculated to be 2.72 kg. How much does this tell you about the weight of all cats? Can you tell if most of the weights were close to 2.72 kg or were the weights really spread out? The highest weight and the lowest weight are known, but is there more that you can tell? All you know is that the center of the weights is 2.72 kg.</p>
<p>You need more information.</p>
<p>The <strong>range</strong> of a set of data is the difference between the highest and the lowest data values (or maximum and minimum values). The <strong>interval</strong> is the lowest and highest values. The range is one value while the interval is two.</p>
<section id="example-range" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="example-range"><span class="header-section-number">4.2.1</span> Example: Range</h3>
<p>From <a href="#example-effect-of-extreme-values-on-mean-and-median">Example: Effect of Extreme Values on Mean and Median</a>, the maximum is 3.9 kg and the minimum is 2 kg. So the range is <span class="math inline">\(3.9-2=1.9 kg\)</span>. But what does that tell you? You don’t know if the weights are really spread out, or if they are close together.</p>
<p>Unfortunately, range doesn’t really provide a very accurate picture of the variability. A better way to describe how the data is spread out is needed. Instead of looking at the distance the highest value is from the lowest how about looking at the distance each value is from the mean. This distance is called the <strong>deviation</strong>. You might want to find the average of the deviation. Though the calculation for finding the average deviation is not very straight forward, you end up with a value called the <strong>variance</strong>. The symbol for the population variance is <span class="math inline">\(\sigma^2\)</span>, and it is the average squared distance from the mean. Statisticians like the variance, but many other people who work with statistics use a descriptive statistic which is the square root of the variance. This gives you the average distance from the mean. This is called the <strong>standard deviation</strong>, and the population standard deviation is denoted with the letter <span class="math inline">\(\sigma\)</span>.</p>
<p>The standard deviation is the average (mean) distance from a data point to the mean. It can be thought of as how much a typical data point differs from the mean.</p>
<p>The <strong>sample variance</strong> formula: <span class="math inline">\(s^2=\frac{\sum\left(x-\bar{x}\right)^2}{n-1}\)</span>, where <span class="math inline">\(\bar{x}\)</span> is the sample mean, <span class="math inline">\(n\)</span> is the sample size, and <span class="math inline">\(\sum{}\)</span> means to find the sum of the values. The <span class="math inline">\(n-1\)</span> on the bottom has to do with a concept called degrees of freedom. Basically, it makes the sample variance a better approximation of the population variance.</p>
<p>The <strong>sample standard deviation</strong> formula: <span class="math inline">\(s=\sqrt{ \frac{\sum\left(x-\bar{x}\right)^2}{n-1}}\)</span>.</p>
<p>The <strong>population variance</strong> formula: <span class="math inline">\(\sigma^2 = \frac{\sum\left(x-\mu \right)^2}{N}\)</span>, where <span class="math inline">\(\sigma\)</span> is the Greek letter sigma and <span class="math inline">\(\sigma^2\)</span> represents the population variance, <span class="math inline">\(\mu\)</span> is the population mean, and <span class="math inline">\(N\)</span> is the size of the population.</p>
<p>The <strong>population standard deviation</strong> formula: <span class="math inline">\(\sigma =\sqrt{ \frac{\sum\left(x-\mu \right)^2}{N}}\)</span></p>
<p>Both the sample variance and sample standard deviation can be found using technology. If using Rguroo, you would perform the same steps as described <a href="#Calculating-summary-stats-in-Rguroo">here</a> and select <span class="def">standard deviation</span> and <span class="def">variance</span> as shown in the figure <span class="quarto-unresolved-ref">?fig-sd-dialog</span>. <code>{r,echo=FALSE #| fig-alt: "Dialog box for standard deviation and variance" #| warning: FALSE #| label: fig-sd-dialog #| fig-cap: "Basic Summary Statistic Dialog for Standard Deviation and Variance " #| out-width: "70%" knitr::include_graphics("Rguroo_dialogs/Numerical_Description/sd_var_cats_dialog.png")</code></p>
<!--df_stats(\~variable, data=data_frame, var, sd)-->
<p>The next example will demonstrate this command.</p>
</section>
<section id="example-finding-the-standard-deviation" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="example-finding-the-standard-deviation"><span class="header-section-number">4.2.2</span> Example: Finding the Standard Deviation</h3>
<p>For the data frame Cats <a href="#tbl-Cats" class="quarto-xref">Table&nbsp;<span>4.1</span></a> find the variance and standard derivation for weight of cats. Then find the variance and standard deviation separated by sex of the cat.</p>
<section id="solution-5" class="level4" data-number="4.2.2.1">
<h4 data-number="4.2.2.1" class="anchored" data-anchor-id="solution-5"><span class="header-section-number">4.2.2.1</span> <strong>Solution</strong></h4>
<p>The variance and standard deviation for all cats is found by performing the command:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-sd-output" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Standard Deviation and Variance of Cats Weights">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sd-output-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Rguroo_outputs/Numerical_Description/sd_var_cats_output.png" class="img-fluid figure-img" style="width:70.0%" alt="Standard Deviation and Variance of Cats Weights">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sd-output-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.10: Standard Deviation and Variance of Weights of Cats
</figcaption>
</figure>
</div>
</div>
</div>
<p>The variance for all cats is 0.24 <span class="math inline">\(kg^2\)</span> and the standard deviation is 0.49 kg.</p>
<p>To find out the mean, variance, and standard deviation for each sex of the cats, use the command:</p>
<p>You can see that the mean weight of females cats is 2.36 kg, the variance is 0.075 <span class="math inline">\(kg^2\)</span>, and the standard deviation is 0.27 kg. For males cats, the mean is 2.9 kg, the variance is 0.22 <span class="math inline">\(kg^2\)</span>, and the standard deviation is 0.47 kg. This means that female cats weigh less than males and since the variance and standard deviations are much less for female cats than males cats, female cats’ weights are more consistent than male cats.</p>
<p>In general a “small” variance and standard deviation means the data is close together (more consistent) and a “large” variance and standard deviation means the data is spread out (less consistent). Sometimes you want consistent data and sometimes you don’t. As an example if you are making bolts, you want the lengths to be very consistent so you want a small standard deviation. If you are administering a test to see who can be a pilot, you want a large standard deviation so you can tell who are the good pilots and who are the not so good pilots.</p>
<p>What do “small” and “large” standard deviation mean? To a bicyclist whose average speed is 20 mph, <span class="math inline">\(s = 20 mph\)</span> is huge. To an airplane whose average speed is 500 mph, <span class="math inline">\(s = 20 mph\)</span> is nothing. The “size” of the variation depends on the size of the numbers in the problem and the mean. Another situation where you can determine whether a standard deviation is small or large is when you are comparing two different samples such as in <a href="#example-finding-the-standard-deviation">Example: Finding the Standard Deviation</a>. A sample with a smaller standard deviation is more consistent than a sample with a larger standard deviation.</p>
<p>Many other books and authors stress that there is a computational formula for calculating the standard deviation. However, this formula doesn’t give you an idea of what standard deviation is and what you are doing. It is only good for doing the calculations quickly. It goes back to the days when standard deviations were calculated by hand, and the person needed a quick way to calculate the standard deviation. It is an archaic formula that this author is trying to eradicate. It is not necessary anymore, computers will do the calculations for you with as much meaning as this formula gives. It is suggested that you never use it. If you want to understand what the standard deviation is doing, then you should use the definition formula. If you want an answer quickly, use a computer.</p>
</section>
</section>
<section id="use-of-standard-deviation" class="level3" data-number="4.2.3">
<h3 data-number="4.2.3" class="anchored" data-anchor-id="use-of-standard-deviation"><span class="header-section-number">4.2.3</span> <strong>Use of Standard Deviation</strong></h3>
<p>One of the uses of the standard deviation is to describe how a population is distributed. This describes where much of the data is for most distributions. A general rule is that about 95% of the data is within 2 standard deviations of the mean. This is not perfect, but is works for many distributions. There are rules like the empirical rule and Chebyshev’s theorem that give you more detailed percentages, but 95% in 2 standard deviations is a very good approximation.</p>
</section>
<section id="example-the-general-rule" class="level3" data-number="4.2.4">
<h3 data-number="4.2.4" class="anchored" data-anchor-id="example-the-general-rule"><span class="header-section-number">4.2.4</span> Example: the general rule</h3>
<p>The U.S. Weather Service has provided the information in <a href="#tbl-Tornado" class="quarto-xref">Table&nbsp;<span>4.6</span></a> about the total monthly/annual number of reported tornadoes in Oklahoma for the years 1950 to 2018. (US Department of Commerce &amp; Noaa, 2016)</p>
<div class="cell" data-tbl-alt="Table showing first 6 rows of Tornado dataset">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>Tornado<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">"https://krkozak.github.io/MAT160/Tornado_OK.csv"</span>) </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(Tornado))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-Tornado" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Table showing first 6 rows of Tornado dataset">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Tornado-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.6: Monthly/Annual Number of tornadoes in Oklahoma
</figcaption>
<div aria-describedby="tbl-Tornado-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Year</th>
<th style="text-align: right;">Jan</th>
<th style="text-align: right;">Feb</th>
<th style="text-align: right;">Mar</th>
<th style="text-align: right;">Apr</th>
<th style="text-align: right;">May</th>
<th style="text-align: right;">Jun</th>
<th style="text-align: right;">Jul</th>
<th style="text-align: right;">Aug</th>
<th style="text-align: right;">Sep</th>
<th style="text-align: right;">Oct</th>
<th style="text-align: right;">Nov</th>
<th style="text-align: right;">Dec</th>
<th style="text-align: right;">Annual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1950</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
</tr>
<tr class="even">
<td style="text-align: right;">1951</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">43</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1952</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">22</td>
</tr>
<tr class="even">
<td style="text-align: right;">1953</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">54</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1954</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">53</td>
</tr>
<tr class="even">
<td style="text-align: right;">1955</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">77</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><strong>Code book for data frame Tornado</strong></p>
<p><strong>Description</strong> The U.S. Weather Service has collected data on the monthly and annual number of tornadoes in Oklahoma.</p>
<p>This data frame contains the following columns:</p>
<p>Year: Year from 1950-2018</p>
<p>Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec: Tornado numbers in each moth of the year</p>
<p>Annual: Total number of tornadoes for each year</p>
<p>Source US Department of Commerce, &amp; Noaa. (2016, November 15). 1950 Oklahoma Tornadoes. Retrieved from https://www.weather.gov/oun/tornadodata-ok-1950</p>
<p>References The data was supplied by The U.S. Weather Service</p>
<p>Find the general interval that contains about 95% of the data.</p>
<section id="solution-6" class="level4" data-number="4.2.4.1">
<h4 data-number="4.2.4.1" class="anchored" data-anchor-id="solution-6"><span class="header-section-number">4.2.4.1</span> <strong>Solution</strong></h4>
<p>Variable: <span class="math inline">\(x\)</span> = number of annual tornadoes in Oklahoma</p>
<p>Find the mean and standard deviation:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">df_stats</span>(<span class="sc">~</span>Annual, <span class="at">data=</span>Tornado, mean, sd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  response     mean       sd
1   Annual 56.02899 27.56061</code></pre>
</div>
</div>
<p>The mean is <span class="math inline">\(\mu=56\)</span> tornadoes and the standard deviation is <span class="math inline">\(\sigma=27.6\)</span> tornadoes. The interval will be <span class="math inline">\(\mu\pm2*\sigma=56\pm2*27.6=(0.8,111.2)\)</span></p>
<p>About 95% of the years have between 0.8 or 1 and 111 tornadoes in Oklahoma.</p>
<p>The general rule says that about 95% of the data is within two standard deviations of the mean. That percentage is fairly high. There isn’t much data outside two standard deviations. A rule that can be followed is that if a data value is within two standard deviations, then that value is a common data value. If the data value is outside two standard deviations of the mean, either above or below, then the number is uncommon. It could even be called unusual. An easy calculation that you can do to figure it out is to find the difference between the data point and the mean, and then divide that answer by the standard deviation. As a formula this would be</p>
<p><span class="math inline">\(z=\frac{x-\mu}{\sigma}\)</span></p>
<p>If you don’t know the population mean, <span class="math inline">\(\mu\)</span>, and the population standard deviation, <span class="math inline">\(\sigma\)</span>, then use the sample mean, <span class="math inline">\(\bar{x}\)</span>, and the sample standard deviation, <span class="math inline">\(s\)</span>, to estimate the population parameter values. Realize that using the sample standard deviation may not actually be very accurate.</p>
</section>
</section>
<section id="example-determining-if-a-value-is-unusual" class="level3" data-number="4.2.5">
<h3 data-number="4.2.5" class="anchored" data-anchor-id="example-determining-if-a-value-is-unusual"><span class="header-section-number">4.2.5</span> Example: Determining If a Value Is Unusual</h3>
<ol type="a">
<li>In 1974, there were 45 tornadoes in Oklahoma. Is this value unusual? Why or why not?</li>
<li>In 1999, there were 145 tornadoes in the Oklahoma. Is this value unusual? Why or why not?</li>
</ol>
<section id="solution-7" class="level4" data-number="4.2.5.1">
<h4 data-number="4.2.5.1" class="anchored" data-anchor-id="solution-7"><span class="header-section-number">4.2.5.1</span> <strong>Solution</strong></h4>
<ol type="a">
<li><p>In 1974, there were 45 tornadoes in Oklahoma. Is this value unusual? Why or why not?</p>
<p>Variable: <span class="math inline">\(x\)</span> = number of tornadoes in Oklahoma</p></li>
</ol>
<p>To answer this question, first find how many standard deviations 45 is from the mean. From 3.2.4 example, we know <span class="math inline">\(\mu=56\)</span> and <span class="math inline">\(\sigma=27.6\)</span>. For <span class="math inline">\(x\)</span>=45, <span class="math inline">\(z=\frac{45-56}{27.6}=-0.399\)</span></p>
<p>Since this value is between -2 and 2, then it is not unusual to have 45 tornadoes in a year in Oklahoma. The z value is negative, so that means that 45 is less than the mean number of tornadoes.</p>
<ol start="2" type="a">
<li><p>In 1999, there were 145 tornadoes in the Oklahoma. Is this value unusual? Why or why not?</p>
<p>Variable: <span class="math inline">\(x\)</span> = number of tornadoes in Oklahoma</p></li>
</ol>
<p>For this question the <span class="math inline">\(x\)</span> = 145, <span class="math inline">\(z=\frac{145-56}{27.6}=3.22\)</span></p>
<p>Since this value is more than 2, then it is unusual to have only 145 tornadoes in a year in Oklahoma.</p>
</section>
</section>
<section id="homework-for-measures-of-spread-section" class="level3" data-number="4.2.6">
<h3 data-number="4.2.6" class="anchored" data-anchor-id="homework-for-measures-of-spread-section"><span class="header-section-number">4.2.6</span> Homework for Measures of Spread Section</h3>
<p><strong>Use Technology on all problems. State the variable on all problems.</strong></p>
<ol type="1">
<li>Cholesterol levels were collected from patients certain days after they had a heart attack and are in <a href="#tbl-Cholesterol" class="quarto-xref">Table&nbsp;<span>4.2</span></a>. Find the mean, median, range, variance, and standard deviation for cholesterol levels 2 days after the heart attack.</li>
</ol>
<p><strong>Code book for Data Frame Cholesterol</strong> is below <a href="#tbl-Cholesterol" class="quarto-xref">Table&nbsp;<span>4.2</span></a>.</p>
<ol start="2" type="1">
<li>The lengths (in kilometers) of rivers on the South Island of New Zealand and what body of water they flow into are listed in <a href="#tbl-Length" class="quarto-xref">Table&nbsp;<span>4.3</span></a> (Lee, 1994). Find the mean, median, range, variance, and standard deviation of the length of rivers that flow into the Pacific Ocean and the mean, median, range, variance, and standard deviation of the length of rivers that flow into the Tasman Sea. Compare and contrast the length of rivers that flow to the Pacific Ocean versus the ones that flow into the Tasman Sea using both measures of spread and measures of variability.</li>
</ol>
<p><strong>Code book for data frame Length</strong> is below <a href="#tbl-Length" class="quarto-xref">Table&nbsp;<span>4.3</span></a>.</p>
<ol start="3" type="1">
<li>Print-O-Matic printing company’s employees have salaries that are contained in <a href="#tbl-Pay" class="quarto-xref">Table&nbsp;<span>4.4</span></a>. Find the mean, median, range, variance, and standard deviation for the salaries of all employees.</li>
</ol>
<p><strong>Code book for data frame Pay</strong> below <a href="#tbl-Pay" class="quarto-xref">Table&nbsp;<span>4.4</span></a>.</p>
<ol start="4" type="1">
<li>Print-O-Matic printing company spends specific amounts on fixed costs every month. The costs of those fixed costs are in <a href="#tbl-Cost" class="quarto-xref">Table&nbsp;<span>4.5</span></a>. Find the mean, median, range, variance, and standard deviation for the fixed costs.</li>
</ol>
<p><strong>Code book for Data frame Cost</strong> is below <a href="#tbl-Cost" class="quarto-xref">Table&nbsp;<span>4.5</span></a>.</p>
<ol start="5" type="1">
<li>The data frame Pulse <a href="#tbl-Pulse" class="quarto-xref">Table&nbsp;<span>4.7</span></a> contains various variables about a person including their pulse rates before the subject exercised and after the subject ran in place for one minute.</li>
</ol>
<div class="cell" data-tbl-alt="Table showing first 6 rows of Pulse dataset">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>Pulse<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">"https://krkozak.github.io/MAT160/pulse.csv"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(Pulse))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-Pulse" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Table showing first 6 rows of Pulse dataset">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Pulse-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.7: Head of Pulse Rates of people Before and After Exercise
</figcaption>
<div aria-describedby="tbl-Pulse-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 4%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 4%">
<col style="width: 15%">
<col style="width: 14%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">height</th>
<th style="text-align: right;">weight</th>
<th style="text-align: right;">age</th>
<th style="text-align: left;">gender</th>
<th style="text-align: left;">smokes</th>
<th style="text-align: left;">alcohol</th>
<th style="text-align: left;">exercise</th>
<th style="text-align: left;">ran</th>
<th style="text-align: right;">pulse_before</th>
<th style="text-align: right;">pulse_after</th>
<th style="text-align: right;">year</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">170</td>
<td style="text-align: right;">68</td>
<td style="text-align: right;">22</td>
<td style="text-align: left;">male</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">moderate</td>
<td style="text-align: left;">sat</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">93</td>
</tr>
<tr class="even">
<td style="text-align: right;">182</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">26</td>
<td style="text-align: left;">male</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">moderate</td>
<td style="text-align: left;">sat</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">93</td>
</tr>
<tr class="odd">
<td style="text-align: right;">180</td>
<td style="text-align: right;">85</td>
<td style="text-align: right;">19</td>
<td style="text-align: left;">male</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">moderate</td>
<td style="text-align: left;">ran</td>
<td style="text-align: right;">68</td>
<td style="text-align: right;">125</td>
<td style="text-align: right;">95</td>
</tr>
<tr class="even">
<td style="text-align: right;">182</td>
<td style="text-align: right;">85</td>
<td style="text-align: right;">20</td>
<td style="text-align: left;">male</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">low</td>
<td style="text-align: left;">sat</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">68</td>
<td style="text-align: right;">95</td>
</tr>
<tr class="odd">
<td style="text-align: right;">167</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">22</td>
<td style="text-align: left;">male</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">low</td>
<td style="text-align: left;">sat</td>
<td style="text-align: right;">92</td>
<td style="text-align: right;">84</td>
<td style="text-align: right;">96</td>
</tr>
<tr class="even">
<td style="text-align: right;">178</td>
<td style="text-align: right;">86</td>
<td style="text-align: right;">21</td>
<td style="text-align: left;">male</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">low</td>
<td style="text-align: left;">sat</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">98</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><strong>Code book for data frame Pulse</strong></p>
<p>Description Students in an introductory statistics class (MS212 taught by Professor John Eccleston and Dr Richard Wilson at The University of Queensland) participated in a simple experiment. The students took their own pulse rate. They were then asked to flip a coin. If the coin came up heads, they were to run in place for one minute. Otherwise they sat for one minute. Then everyone took their pulse again. The pulse rates and other physiological and lifestyle data are given in the data.</p>
<p>Five class groups between 1993 and 1998 participated in the experiment. The lecturer, Richard Wilson, was concerned that some students would choose the less strenuous option of sitting rather than running even if their coin came up heads, In the years 1995-1998 a different method of random assignment was used. In these years, data forms were handed out to the class before the experiment. The forms were pre-assigned to either running or non-running and there were an equal number of each. In 1995 and 1998 not all of the forms were returned so the numbers running and sitting was still not entirely controlled.</p>
<p>This data frame contains the following columns:</p>
<p>height: height of subject in cm</p>
<p>weight: weight of subject in kg</p>
<p>age: age of subject in years</p>
<p>gender: sex of subject, male, female</p>
<p>Smokes: whether a subject regularly smokes, yes means does smoke, no means does not smoke</p>
<p>alcohol: whether a subject regularly drinks alcohol, yes means the person does, no means the person does not</p>
<p>exercise: whether a subject exercises, low, moderate, high</p>
<p>ran: whether a subject ran one minute between pulse measurements (ran) or sat between pulse measurement (sat)</p>
<p>pulse_before: the pulse rate before a subject either ran or sat (bpm)</p>
<p>pulse_after: the pulse rate after a subject either ran or sat (bpm)</p>
<p>year: what year the data was collected (93-98)</p>
<p>Source Pulse rates before and after exercise. (2013, September 25). Retrieved from http://www.statsci.org/data/oz/ms212.html</p>
<p>References The data was supplied by Dr Richard J. Wilson, Department of Mathematics, University of Queensland.</p>
<p>Create a data frame that contains only males, who drink alcohol, but do not smoke. Then compare the pulse before and the pulse after using the mean and standard deviation. Discuss whether pulse before or pulse after has a higher mean and larger spread. The following command creates a new data frame with just males, who drink alcohol, but do not smoke, use the following command, where the new name is Males in <a href="#tbl-Males" class="quarto-xref">Table&nbsp;<span>4.8</span></a>.</p>
<div class="cell" data-tbl-alt="Table showing first 6 rows of Males dataset">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>Males<span class="ot">&lt;-</span> Pulse <span class="sc">|&gt;</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(gender<span class="sc">==</span><span class="st">"male"</span>, smokes <span class="sc">==</span> <span class="st">"no"</span>, alcohol <span class="sc">==</span> <span class="st">"yes"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(Males))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-Males" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Table showing first 6 rows of Males dataset">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Males-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.8: Head of Pulse Rates of Nonsmoking Males Before and After Exercise
</figcaption>
<div aria-describedby="tbl-Males-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 4%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 4%">
<col style="width: 15%">
<col style="width: 14%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">height</th>
<th style="text-align: right;">weight</th>
<th style="text-align: right;">age</th>
<th style="text-align: left;">gender</th>
<th style="text-align: left;">smokes</th>
<th style="text-align: left;">alcohol</th>
<th style="text-align: left;">exercise</th>
<th style="text-align: left;">ran</th>
<th style="text-align: right;">pulse_before</th>
<th style="text-align: right;">pulse_after</th>
<th style="text-align: right;">year</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">195</td>
<td style="text-align: right;">84</td>
<td style="text-align: right;">18</td>
<td style="text-align: left;">male</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">high</td>
<td style="text-align: left;">sat</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">73</td>
<td style="text-align: right;">93</td>
</tr>
<tr class="even">
<td style="text-align: right;">184</td>
<td style="text-align: right;">74</td>
<td style="text-align: right;">22</td>
<td style="text-align: left;">male</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">low</td>
<td style="text-align: left;">ran</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">141</td>
<td style="text-align: right;">93</td>
</tr>
<tr class="odd">
<td style="text-align: right;">168</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">23</td>
<td style="text-align: left;">male</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">moderate</td>
<td style="text-align: left;">ran</td>
<td style="text-align: right;">88</td>
<td style="text-align: right;">150</td>
<td style="text-align: right;">93</td>
</tr>
<tr class="even">
<td style="text-align: right;">170</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">20</td>
<td style="text-align: left;">male</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">high</td>
<td style="text-align: left;">ran</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">88</td>
<td style="text-align: right;">93</td>
</tr>
<tr class="odd">
<td style="text-align: right;">187</td>
<td style="text-align: right;">59</td>
<td style="text-align: right;">18</td>
<td style="text-align: left;">male</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">high</td>
<td style="text-align: left;">sat</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">82</td>
<td style="text-align: right;">93</td>
</tr>
<tr class="even">
<td style="text-align: right;">180</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">18</td>
<td style="text-align: left;">male</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">moderate</td>
<td style="text-align: left;">sat</td>
<td style="text-align: right;">69</td>
<td style="text-align: right;">67</td>
<td style="text-align: right;">93</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<ol start="6" type="1">
<li><p>The data frame Pulse <a href="#tbl-Pulse" class="quarto-xref">Table&nbsp;<span>4.7</span></a> contains various variables about a person including their pulse rates before the subject exercised and after the subject ran in place for one minute. Create a data frame that contains females, who do not smoke but do drink alcohol. Compare the pulse rate before and after exercise using the mean and standard deviation. Discuss whether pulse before or pulse after has a higher mean and larger spread.</p></li>
<li><p>To determine if Reiki is an effective method for treating pain, a pilot study was carried out where a certified second-degree Reiki therapist provided treatment on volunteers. Pain was measured using a visual analogue scale (VAS) and a likert scale immediately before and after the Reiki treatment (Olson &amp; Hanson, 1997) and the data is in <a href="#tbl-Reiki" class="quarto-xref">Table&nbsp;<span>4.9</span></a>.</p></li>
</ol>
<div class="cell" data-tbl-alt="Table showing first 6 rows of Reiki dataset">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>Reiki<span class="ot">&lt;-</span> <span class="fu">read.csv</span>( <span class="st">"https://krkozak.github.io/MAT160/reki.csv"</span>) </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(Reiki))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-Reiki" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Table showing first 6 rows of Reiki dataset">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Reiki-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.9: Head of Pain Measurements Before and After Reiki Treatment
</figcaption>
<div aria-describedby="tbl-Reiki-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">vas.before</th>
<th style="text-align: right;">vas.after</th>
<th style="text-align: right;">likert_before</th>
<th style="text-align: right;">likert_after</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">9</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><strong>Code book for data frame Reiki</strong></p>
<p><strong>Description</strong> The purpose of this study was to explore the usefulness of Reiki as an adjuvant to opioid therapy in the management of pain. Since no studies in this area could be found, a pilot study was carried out involving 20 volunteers experiencing pain at 55 sites for a variety of reasons, including cancer. All Reiki treatments were provided by a certified second-degree Reiki therapist. Pain was measured using both a visual analogue scale (VAS) and a Likert scale immediately before and after the Reiki treatment. Both instruments showed a highly significant (p &lt; 0.0001) reduction in pain following the Reiki treatment.</p>
<p>This data frame contains the following columns:</p>
<p>vas.before: pain measured using a visual analogue scale (VAS) before Reiki treatment</p>
<p>vas.after: pain measured using a visual analogue scale (VAS) after Reiki treatment</p>
<p>likert_before: pain measured using a likert before Reiki treatment</p>
<p>likert_after: pain measured using a likert after Reiki treatment</p>
<p>Source Olson, K., &amp; Hanson, J. (1997). Using reiki to manage pain: a preliminary report. Cancer Prev Control, 1(2), 108-13. Retrieved from http://www.ncbi.nlm.nih.gov/pubmed/9765732</p>
<p>References** Using Reiki to manage pain: a preliminary report. Olson K1, Hanson J., Cancer Prev Control 1997, Jun; 1(2): 108-13.</p>
<p>Since the data was collected both before and after the treatment for all of the units of observations, you want to look at the effect size of the treatment. You want to find the difference between before and after for the pain scale. First you must create a new data frame that adds a column for the difference in before and after. This data is known as paired data. To create the new column in a new data frame called Newreiki use the following commands, <a href="#tbl-Newreiki" class="quarto-xref">Table&nbsp;<span>4.10</span></a>.</p>
<div class="cell" data-tbl-alt="Table showing first 6 rows of New Reiki dataset">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>Newreiki<span class="ot">&lt;-</span>Reiki <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">vas.diff=</span>vas.before<span class="sc">-</span>vas.after) </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(Newreiki))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-Newreiki" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Table showing first 6 rows of New Reiki dataset">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Newreiki-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.10: Head of Pain Measurements Before and After Reiki Treatment with Difference column
</figcaption>
<div aria-describedby="tbl-Newreiki-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">vas.before</th>
<th style="text-align: right;">vas.after</th>
<th style="text-align: right;">likert_before</th>
<th style="text-align: right;">likert_after</th>
<th style="text-align: right;">vas.diff</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">9</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Now find the mean and standard deviation of the vas.diff variable in Newreiki. Perform similar commands to create the likert.diff variable. Then find the mean and standard deviation for likert.diff, and compare and contrast the vas and likert methods for describing pain.</p>
<p>8.Yearly rainfall amounts (in millimeters) in Sydney, Australia, are in <a href="#tbl-Rainfall" class="quarto-xref">Table&nbsp;<span>4.11</span></a> (Annual maximums of, 2013). a. Calculate the mean and standard deviation. b. Suppose Sydney, Australia received 300 mm of rainfall in a year. Would this be unusual?</p>
<div class="cell" data-tbl-alt="Table showing first 6 rows of Rainfall dataset">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>Rainfall<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">"https://krkozak.github.io/MAT160/rainfall.csv"</span>) </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(Rainfall))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-Rainfall" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Table showing first 6 rows of Rainfall dataset">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Rainfall-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.11: Head of Yearly rainfall amounts in Sydney, Australia
</figcaption>
<div aria-describedby="tbl-Rainfall-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">amount</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">146.8</td>
</tr>
<tr class="even">
<td style="text-align: right;">383.0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">90.9</td>
</tr>
<tr class="even">
<td style="text-align: right;">178.1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">267.5</td>
</tr>
<tr class="even">
<td style="text-align: right;">95.5</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><strong>Code book for data frame Rainfall</strong></p>
<p><strong>Description</strong> Daily rainfall (in millimeters) was recorded over a 47-year period in Turramurra, Sydney, Australia. For each year, the wettest day was identified (that having the greatest rainfall). The data show the rainfall recorded for the 47 annual maxima.</p>
<p>This data frame contains the following columns:</p>
<p>amount: daily rainfall (mm)</p>
<p>Source Annual maximums of daily rainfall in Sydney. (2013, September 25). Retrieved from http://www.statsci.org/data/oz/sydrain.html</p>
<p>References Rayner J.C.W. and Best D.J. (1989) Smooth tests of goodness of fit. Oxford: Oxford University Press. Hand D.J., Daly F., Lunn A.D., McConway K.J., Ostrowski E. (1994). A Handbook of Small Data Sets. London: Chapman &amp; Hall. Data set 157. Thanks to Jim Irish of the University of Technology, Sydney, for assistance in identifying the correct units for this data.</p>
</section>
</section>
<section id="ranking" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="ranking"><span class="header-section-number">4.3</span> Ranking</h2>
<p>Along with the center and the variability, another useful numerical measure is the ranking of a number. A <strong>percentile</strong> is a measure of ranking. It represents a location measurement of a data value to the rest of the values. Many standardized tests give the results as a percentile. Doctors also use percentiles to track a child’s growth.</p>
<p>The <span class="math inline">\(k^{th}\)</span> <strong>percentile</strong> is the data value that has k% of the data at or below that value.</p>
<section id="example-interpreting-percentile" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="example-interpreting-percentile"><span class="header-section-number">4.3.1</span> Example: Interpreting Percentile</h3>
<ol type="a">
<li>What does a score of the <span class="math inline">\(90^{th}\)</span> percentile mean?</li>
<li>What does a score of the <span class="math inline">\(70^{th}\)</span> percentile mean?</li>
</ol>
<section id="solution-8" class="level4" data-number="4.3.1.1">
<h4 data-number="4.3.1.1" class="anchored" data-anchor-id="solution-8"><span class="header-section-number">4.3.1.1</span> <strong>Solution</strong></h4>
<ol type="a">
<li><p>What does a score of the <span class="math inline">\(90^{th}\)</span> percentile mean?</p>
<p>This means that 90% of the scores were at or below this score. (A person did the same as or better than 90% of the test takers.)</p></li>
<li><p>What does a score of the <span class="math inline">\(70^{th}\)</span> percentile mean?</p>
<p>This means that 70% of the scores were at or below this score.</p></li>
</ol>
</section>
</section>
<section id="example-percentile-versus-score" class="level3" data-number="4.3.2">
<h3 data-number="4.3.2" class="anchored" data-anchor-id="example-percentile-versus-score"><span class="header-section-number">4.3.2</span> Example: Percentile Versus Score</h3>
<p>If the test was out of 100 points and you scored at the <span class="math inline">\(80^{th}\)</span> percentile, what was your score on the test?</p>
<section id="solution-9" class="level4" data-number="4.3.2.1">
<h4 data-number="4.3.2.1" class="anchored" data-anchor-id="solution-9"><span class="header-section-number">4.3.2.1</span> <strong>Solution</strong></h4>
<p>You don’t know! All you know is that you scored the same as or better than 80% of the people who took the test. If all the scores were really low, you could have still failed the test. On the other hand, if many of the scores were high you could have gotten a 95% or more.</p>
<p>There are special percentiles called <strong>quartiles</strong>. Quartiles are numbers that divide the data into fourths. One fourth (or a quarter) of the data falls between consecutive quartiles.</p>
</section>
</section>
<section id="to-find-the-quartiles" class="level3" data-number="4.3.3">
<h3 data-number="4.3.3" class="anchored" data-anchor-id="to-find-the-quartiles"><span class="header-section-number">4.3.3</span> <strong>To find the quartiles</strong>:</h3>
<p>The command in rStudio is</p>
<p>df_stats(~variable, data=data_frame, summary)</p>
<p>If you record the quartiles together with the maximum and minimum you have five numbers. This is known as the five-number summary. The five-number summary consists of the minimum, the first quartile (<span class="math inline">\(Q1\)</span>), the median, the third quartile (<span class="math inline">\(Q3\)</span>), and the maximum (in that order).</p>
<p>The interquartile range, <span class="math inline">\(IQR\)</span>, is the difference between the first and third quartiles, <span class="math inline">\(Q1\)</span> and $Q3$. Half of the data (50%) falls in the interquartile range. If the <span class="math inline">\(IQR\)</span> is “large” the data is spread out and if the <span class="math inline">\(IQR\)</span> is “small” the data is closer together.</p>
<p>Interquartile Range (<span class="math inline">\(IQR\)</span>)</p>
<p>Determining probable outliers from <span class="math inline">\(IQR\)</span>: <strong>fences</strong></p>
<p>A value that is less than <span class="math inline">\(Q1-1.5*IQR\)</span> (this value is often referred to as a <strong>low fence</strong>) is considered an outlier.</p>
<p>Similarly, a value that is more than <span class="math inline">\(Q3+1.5*IQR\)</span> (the <strong>high fence</strong>) is considered an outlier.</p>
<p>A boxplot (or box-and-whisker plot) is a graphical display of the five-number summary. It can be drawn vertically or horizontally. The basic format is a box from <span class="math inline">\(Q1\)</span> to <span class="math inline">\(Q3\)</span>, a vertical line across the box for the median and horizontal lines as whiskers extending out each end to the minimum and maximum. The minimum and maximum can be represented with dots. Don’t forget to label the tick marks on the number line and give the graph a title.</p>
<p>An alternate form of a Boxplot, known as a modified box plot, only extends the left line to the smallest value greater than the <strong>low fence</strong>, and extends the left line to the largest value less than the <strong>high fence</strong>, and displays markers (dots, circles or asterisks) for each outlier.</p>
<p>If the data are <strong>symmetrical</strong>, then the box plot will be visibly symmetrical. If the data distribution has a left skew or a right skew, the line on that side of the box plot will be visibly long. If the plot is symmetrical, and the four quartiles are all about the same length, then the data are likely a near <strong>uniform</strong> distribution. If a box plot is symmetrical, and both outside lines are noticeably longer than the <span class="math inline">\(Q1\)</span> to median and median to <span class="math inline">\(Q3\)</span> distance, the distribution is then probably <strong>bell-shaped</strong>.</p>
</section>
<section id="example-five-number-summary-and-boxplot" class="level3" data-number="4.3.4">
<h3 data-number="4.3.4" class="anchored" data-anchor-id="example-five-number-summary-and-boxplot"><span class="header-section-number">4.3.4</span> Example: Five-number Summary and Boxplot</h3>
<p>Find the five-number summary, the interquartile range (*IQR*), and draw a box-and-whiskers plot for the weight of cats <a href="#tbl-Cats" class="quarto-xref">Table&nbsp;<span>4.1</span></a>.</p>
<section id="solution-10" class="level4" data-number="4.3.4.1">
<h4 data-number="4.3.4.1" class="anchored" data-anchor-id="solution-10"><span class="header-section-number">4.3.4.1</span> <strong>Solution</strong></h4>
<p>Variable: <span class="math inline">\(x\)</span> = weight of cats To compute the five-number summary on RStudio, use the command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">df_stats</span>(<span class="sc">~</span>Bwt, <span class="at">data=</span>cats, summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  response Min. 1st Qu. Median     Mean 3rd Qu. Max.
1      Bwt    2     2.3    2.7 2.723611   3.025  3.9</code></pre>
</div>
</div>
<p>Note rStudio also calculates the mean as part of the summary command, but the five-number summary is just the five numbers:</p>
<p>Minimum: 2 kg <span class="math inline">\(Q1\)</span>: 2.3 kg Median: 2.7 kg <span class="math inline">\(Q3\)</span>: 3.025 kg Maximum: 3.9 kg</p>
<p>To find the interquartile range, <span class="math inline">\(IQR\)</span> find $Q3-Q1$, so <span class="math inline">\(IQR=3.025-2.3=0.725 kg\)</span></p>
<p>To create a boxplot use the command</p>
<p>gf_boxplot(~variable, data=data_frame)</p>
<p>This is a modified boxplot which shows the outliers in the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_boxplot</span>(<span class="sc">~</span>Bwt, <span class="at">data=</span>cats, <span class="at">title=</span><span class="st">"Weight of Cats"</span>, <span class="at">xlab=</span><span class="st">"Body Weight (kg)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Cats-boxplot" class="quarto-float quarto-figure quarto-figure-center anchored" alt="box plot of weight of Cats median 2.7, Q1 at 2.3, lower fence at 2.0, Q3 at 3.0, upper fence at 3.8.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-Cats-boxplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Numerical-description-of-Data_files/figure-html/fig-Cats-boxplot-1.png" class="img-fluid figure-img" alt="box plot of weight of Cats median 2.7, Q1 at 2.3, lower fence at 2.0, Q3 at 3.0, upper fence at 3.8." width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-Cats-boxplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.11: Weight of Cats
</figcaption>
</figure>
</div>
</div>
</div>
<p>There are no outliers since there are no dots outside of the fences.</p>
</section>
</section>
<section id="example-separating-based-on-a-factor" class="level3" data-number="4.3.5">
<h3 data-number="4.3.5" class="anchored" data-anchor-id="example-separating-based-on-a-factor"><span class="header-section-number">4.3.5</span> Example: Separating based on a factor</h3>
<p>Find the five-number summary of the weights of cats separated by the sex of the cat. Then create a box plot of the weights of cats for each sex of the cat.</p>
<section id="solution-11" class="level4" data-number="4.3.5.1">
<h4 data-number="4.3.5.1" class="anchored" data-anchor-id="solution-11"><span class="header-section-number">4.3.5.1</span> <strong>Solution</strong></h4>
<p>Variable: <span class="math inline">\(x_1\)</span> = weight of female cat</p>
<p>Variable: <span class="math inline">\(x_2\)</span> = weight of male cat</p>
<p>To find the five-number summary separated based on gender use the following command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">df_stats</span>(<span class="sc">~</span>Bwt<span class="sc">|</span>Sex, <span class="at">data=</span>cats, summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  response Sex Min. 1st Qu. Median     Mean 3rd Qu. Max.
1      Bwt   F    2    2.15    2.3 2.359574     2.5  3.0
2      Bwt   M    2    2.50    2.9 2.900000     3.2  3.9</code></pre>
</div>
</div>
<p>The five-number summary for female cats is (in kg)</p>
<p>Minimum: 2 <span class="math inline">\(Q1\)</span>: 2.15 Median: 2.3 <span class="math inline">\(Q3\)</span>: 2.5 Maximum: 3.0</p>
<p>The five-number summary for male cats is (in kg)</p>
<p>Minimum: 2 <span class="math inline">\(Q1\)</span>: 2.50 Median: 2.9 <span class="math inline">\(Q3\)</span>: 3.2 Maximum: 3.9</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_boxplot</span>(<span class="sc">~</span>Bwt<span class="sc">|</span>Sex, <span class="at">data=</span>cats, <span class="at">title=</span><span class="st">"Weights of Cats"</span>, <span class="at">xlab=</span><span class="st">"Body Weight in (kg)"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Cats-boxplot-sex" class="quarto-float quarto-figure quarto-figure-center anchored" alt="box plot of weight of Cats female lower 2.0, Q1 22, Median 2.3, Q3 3.0, upper 3.0, male 2.0, 2.5, 2.9, 3, 3.8">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-Cats-boxplot-sex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Numerical-description-of-Data_files/figure-html/fig-Cats-boxplot-sex-1.png" class="img-fluid figure-img" alt="box plot of weight of Cats female lower 2.0, Q1 22, Median 2.3, Q3 3.0, upper 3.0, male 2.0, 2.5, 2.9, 3, 3.8" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-Cats-boxplot-sex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.12: Weight of Cats Faceted by Sex
</figcaption>
</figure>
</div>
</div>
</div>
<p>Notice that the weights of female cats has a median less than male cats, and in fact it can be seen that the <span class="math inline">\(Q1\)</span> to <span class="math inline">\(Q3\)</span> of the female cats is less than the <span class="math inline">\(Q1\)</span> to <span class="math inline">\(Q3\)</span> of the male cats.</p>
</section>
</section>
<section id="example-putting-it-all-together" class="level3" data-number="4.3.6">
<h3 data-number="4.3.6" class="anchored" data-anchor-id="example-putting-it-all-together"><span class="header-section-number">4.3.6</span> Example: Putting it all together</h3>
<p>The time (in 1/50 seconds) between successive pulses along a nerve fiber (“Time between nerve,” 2013) are given in <a href="#tbl-Nerve" class="quarto-xref">Table&nbsp;<span>4.12</span></a>.</p>
<div class="cell" data-tbl-alt="Table showing first 6 rows of Nerve dataset">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>Nerve<span class="ot">&lt;-</span><span class="fu">read.csv</span>( <span class="st">"https://krkozak.github.io/MAT160/Nerve_pulse.csv"</span>) </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(Nerve))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-Nerve" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Table showing first 6 rows of Nerve dataset">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Nerve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.12: Head of Successive pulses along a nerve fiber
</figcaption>
<div aria-describedby="tbl-Nerve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">time</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">10.5</td>
</tr>
<tr class="even">
<td style="text-align: right;">1.5</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2.5</td>
</tr>
<tr class="even">
<td style="text-align: right;">5.5</td>
</tr>
<tr class="odd">
<td style="text-align: right;">29.5</td>
</tr>
<tr class="even">
<td style="text-align: right;">3.0</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><strong>Code book for data frame Nerve</strong></p>
<p><strong>Description</strong> The data gives the time between 800 successive pulses along a nerve fiber. There are 799 observations rounded to the nearest half in units of 1/50 second.</p>
<p>This data frame contains the following columns:</p>
<p>time: time between successive Pulses along a nerve fiber, 1/50 second.</p>
<p>Source Time between nerve pulses. (2019, July 3). Retrieved from &lt;http://www.statsci.org/data/general/nerve.html</p>
<p>References Fatt, P., and Katz, B. (1952). Spontaneous subthreshold activity at motor nerve endings. Journal of Physiology 117, 109-128.</p>
<p>Cox, D. R., and Lewis, P. A. W. (1966). The Statistical Analysis of Series of Events. Methuen, London.</p>
<p>Jorgensen, B. (1982). The Generalized Inverse-Gaussian Distribution. Springer-Verlag.</p>
<section id="solution-12" class="level4" data-number="4.3.6.1">
<h4 data-number="4.3.6.1" class="anchored" data-anchor-id="solution-12"><span class="header-section-number">4.3.6.1</span> <strong>Solution</strong></h4>
<p>First, it might be useful to look at a visualization of the data, so create a density plot</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_density</span>(<span class="sc">~</span>time, <span class="at">data=</span>Nerve, <span class="at">title=</span><span class="st">"Time between Successive Nerve Pulses"</span>, <span class="at">xlab=</span><span class="st">"Time (1/50 second)"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Pulse-density-1" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Density plot with peak on left and lower on the right">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-Pulse-density-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Numerical-description-of-Data_files/figure-html/fig-Pulse-density-1-1.png" class="img-fluid figure-img" alt="Density plot with peak on left and lower on the right" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-Pulse-density-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.13: Weight of Cats Faceted by Sex
</figcaption>
</figure>
</div>
</div>
</div>
<p>From the graph <a href="#fig-Pulse-density-1" class="quarto-xref">Figure&nbsp;<span>4.13</span></a> the data appears to be skewed right. Most of the time between successive nerve pulses appear to be around 5 or 10 1/50 second, but there are some times that are 60 1/50 second.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">df_stats</span>(<span class="sc">~</span>time, <span class="at">data=</span>Nerve, mean, median, sd, summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  response     mean median       sd Min. 1st Qu. Median     Mean 3rd Qu. Max.
1     time 10.95119    7.5 10.45956  0.5     3.5    7.5 10.95119      15   69</code></pre>
</div>
</div>
<p>Numerical descriptions might also be useful. Using technology, the mean is 11 1/50 second,the median is 7.5 1/50 second, the standard deviation is 10.5 1/50 second, and the five-number summary is minimum = 3.5, Q1 = 3.5, median = 7.5, Q3 = 15, and maximum = 69 1/50 second.</p>
<p>To visualize the five-number summary, create a box plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_boxplot</span>(<span class="sc">~</span>time, <span class="at">data=</span>Nerve, <span class="at">title=</span><span class="st">"Nerve Pulses"</span>, <span class="at">xlab=</span><span class="st">"Time (1/50 second)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Nerve-box" class="quarto-float quarto-figure quarto-figure-center anchored" alt="box plot lower fence 0, Q1 5, median 8, Q3 17, upper fence 31, many outliers above upper fence">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-Nerve-box-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Numerical-description-of-Data_files/figure-html/fig-Nerve-box-1.png" class="img-fluid figure-img" alt="box plot lower fence 0, Q1 5, median 8, Q3 17, upper fence 31, many outliers above upper fence" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-Nerve-box-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.14: Boxplot of Nerve Pulses
</figcaption>
</figure>
</div>
</div>
</div>
<p>Since there are many dots outside the upper fence the data has many outliers. From all of this information, one could say that nerve pulses between successive pulses is around 11 1/50 second, with a spread of 19.5 1/50 second. Most of the values are round 11 1/50 second, but they are not very consistent. The density plot and boxplot show that there is a great deal of spread of the data and it is skewed to the right. This means mostly the speed is around 11 1/50 second, but there is a great deal of variability in the values.</p>
</section>
</section>
<section id="homework-for-ranking-section" class="level3" data-number="4.3.7">
<h3 data-number="4.3.7" class="anchored" data-anchor-id="homework-for-ranking-section"><span class="header-section-number">4.3.7</span> Homework for Ranking Section</h3>
<p><strong>Use Technology on all problems. State the variable on all problems.</strong></p>
<ol type="1">
<li><p>Suppose you take a standardized test and you are in the <span class="math inline">\(10^{th}\)</span> percentile. What does this percentile mean? Can you say that you failed the test? Explain.</p></li>
<li><p>Suppose your child takes a standardized test in mathematics and scores in the <span class="math inline">\(96^{th}\)</span> percentile. What does this percentile mean? Can you say your child passed the test? Explain.</p></li>
<li><p>Suppose your child is in the <span class="math inline">\(83^{rd}\)</span> percentile in height and <span class="math inline">\(24^{th}\)</span> percentile in weight. Describe what this tells you about your child’s stature.</p></li>
<li><p>Suppose your work evaluates the employees and places them on a percentile ranking. If your evaluation is in the <span class="math inline">\(65^{th}\)</span> percentile, do you think you are working hard enough? Explain.</p></li>
<li><p>Cholesterol levels were collected from patients certain days after they had a heart attack and are in table <a href="#tbl-Cholesterol" class="quarto-xref">Table&nbsp;<span>4.2</span></a>.</p></li>
</ol>
<p><strong>Code book for Data Frame Cholesterol</strong> below <a href="#tbl-Cholesterol" class="quarto-xref">Table&nbsp;<span>4.2</span></a>.</p>
<p>Find the five-number summary and interquartile range (IQR) for the cholesterol level on day 2, and draw a boxplot</p>
<ol start="6" type="1">
<li>The lengths (in kilometers) of rivers on the South Island of New Zealand and what body of water they flow into are listed in table <a href="#tbl-Length" class="quarto-xref">Table&nbsp;<span>4.3</span></a> (Lee, 1994).</li>
</ol>
<p><strong>Code book for data frame Length</strong> below <a href="#tbl-Length" class="quarto-xref">Table&nbsp;<span>4.3</span></a>.</p>
<p>Find the five-number summary and interquartile range (IQR) for the lengths of rivers that go to the Pacific Ocean and ones that go to the Tasman Sea, and draw a boxplot of both.</p>
<ol start="7" type="1">
<li>Print-O-Matic printing company’s employees have salaries that are contained in <a href="#tbl-Pay" class="quarto-xref">Table&nbsp;<span>4.4</span></a> Find the five number summary and draw a boxplot for the salaries of all employees.</li>
</ol>
<p><strong>Code book for data frame Pay</strong> below <a href="#tbl-Pay" class="quarto-xref">Table&nbsp;<span>4.4</span></a>.</p>
<ol start="8" type="1">
<li>The data frame Pulse <a href="#tbl-Pulse" class="quarto-xref">Table&nbsp;<span>4.7</span></a> contains various variables about a person including their pulse rates before the subject exercised and after after the subject ran in place for one minute.</li>
</ol>
<p><strong>Code book for data frame Pulse</strong> below <a href="#tbl-Pulse" class="quarto-xref">Table&nbsp;<span>4.7</span></a>.</p>
<p>Create a data frame that contains only people who drink alcohol, but do not smoke. Then find the five number summary and draw a boxplot for both males and females separately.</p>
<ol start="9" type="1">
<li>To determine if Reiki is an effective method for treating pain, a pilot study was carried out where a certified second-degree Reiki therapist provided treatment on volunteers. Pain was measured using a visual analogue scale (VAS) and a likert scale immediately before and after the Reiki treatment (Olson &amp; Hanson, 1997) and the data is in <a href="#tbl-Reiki" class="quarto-xref">Table&nbsp;<span>4.9</span></a>.</li>
</ol>
<p><strong>Code book for data frame Reiki</strong> below <a href="#tbl-Reiki" class="quarto-xref">Table&nbsp;<span>4.9</span></a>.</p>
<p>Find the five number summary for both the before and after VAS scores and draw boxplots of before and after VAS scores. To draw two boxplots at the same time, after the command to create the first box plot type the piping symbol |&gt; (base r) or %&gt;% (magrittr package) before pressing enter. (Note: |&gt; and %&gt;% are piping symbols that can be thought of as “and then.”) Then type the command for the second boxplot after the + symbol or on the next line in the r chunk if using an rmd or qmd file. Then press enter. You may want to graph each boxplot as a different color. To do this, the command would be</p>
<p>gf_boxplot(~variable, data=data_frame, color=“red”, xlab=“type a label”)</p>
<p>You can pick any color you want. Just replace the word red with the color you want to use. Now compare and contrast the before and after VAS scores.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Graphical Description of Data.html" class="pagination-link" aria-label="Graphical Description of Data">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Graphical Description of Data</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Probability.html" class="pagination-link" aria-label="Probability">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Probability</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>