<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>11&nbsp; Regression – Statistics Using Technology: Rguroo Edition</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Chi-Square and ANOVA Tests.html" rel="next">
<link href="./Two Sample Inference.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Regression.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics Using Technology: Rguroo Edition</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Home</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Statistical Basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Statistical Basics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Graphical Description of Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Graphical Description of Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Numerical Description of Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Numerical Description of Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Discrete Probability Distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Discrete Probability Distribution</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Continuous Probability Distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Continuous Probability Distribution</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./One Sample Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">One Sample Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Two Sample Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Two Sample Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chi-Square and ANOVA Tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Chi-squared and ANOVA Tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./References.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#regression" id="toc-regression" class="nav-link active" data-scroll-target="#regression"><span class="header-section-number">11.1</span> Regression</a>
  <ul class="collapse">
  <li><a href="#example-determining-if-there-is-a-relationship" id="toc-example-determining-if-there-is-a-relationship" class="nav-link" data-scroll-target="#example-determining-if-there-is-a-relationship"><span class="header-section-number">11.1.1</span> Example: Determining if there is a Relationship</a></li>
  <li><a href="#find-the-regression-equation-also-known-as-best-fitting-line-or-least-squares-line" id="toc-find-the-regression-equation-also-known-as-best-fitting-line-or-least-squares-line" class="nav-link" data-scroll-target="#find-the-regression-equation-also-known-as-best-fitting-line-or-least-squares-line"><span class="header-section-number">11.1.2</span> Find the regression equation (also known as best fitting line or least squares line)</a></li>
  <li><a href="#example-find-the-equation-of-the-regression-line" id="toc-example-find-the-equation-of-the-regression-line" class="nav-link" data-scroll-target="#example-find-the-equation-of-the-regression-line"><span class="header-section-number">11.1.3</span> Example: Find the Equation of the Regression Line</a></li>
  <li><a href="#homework-for-regression-section" id="toc-homework-for-regression-section" class="nav-link" data-scroll-target="#homework-for-regression-section"><span class="header-section-number">11.1.4</span> Homework for Regression Section</a></li>
  </ul></li>
  <li><a href="#correlation" id="toc-correlation" class="nav-link" data-scroll-target="#correlation"><span class="header-section-number">11.2</span> Correlation</a>
  <ul class="collapse">
  <li><a href="#example-find-the-coefficient-of-determination-r2" id="toc-example-find-the-coefficient-of-determination-r2" class="nav-link" data-scroll-target="#example-find-the-coefficient-of-determination-r2"><span class="header-section-number">11.2.1</span> Example: Find the coefficient of determination <span class="math inline">\(R^2\)</span></a></li>
  <li><a href="#interpretation-of-the-correlation-coefficient" id="toc-interpretation-of-the-correlation-coefficient" class="nav-link" data-scroll-target="#interpretation-of-the-correlation-coefficient"><span class="header-section-number">11.2.2</span> Interpretation of the correlation coefficient</a></li>
  <li><a href="#example-calculating-the-linear-correlation-coefficient-r" id="toc-example-calculating-the-linear-correlation-coefficient-r" class="nav-link" data-scroll-target="#example-calculating-the-linear-correlation-coefficient-r"><span class="header-section-number">11.2.3</span> Example: Calculating the Linear Correlation Coefficient, <span class="math inline">\(r\)</span></a></li>
  <li><a href="#causation" id="toc-causation" class="nav-link" data-scroll-target="#causation"><span class="header-section-number">11.2.4</span> Causation</a></li>
  <li><a href="#example-correlation-versus-causation" id="toc-example-correlation-versus-causation" class="nav-link" data-scroll-target="#example-correlation-versus-causation"><span class="header-section-number">11.2.5</span> Example: Correlation Versus Causation</a></li>
  <li><a href="#homework-for-correlation-section" id="toc-homework-for-correlation-section" class="nav-link" data-scroll-target="#homework-for-correlation-section"><span class="header-section-number">11.2.6</span> Homework for Correlation Section</a></li>
  </ul></li>
  <li><a href="#inference-for-regression-and-correlation" id="toc-inference-for-regression-and-correlation" class="nav-link" data-scroll-target="#inference-for-regression-and-correlation"><span class="header-section-number">11.3</span> Inference for Regression and Correlation</a>
  <ul class="collapse">
  <li><a href="#example-finding-the-standard-error-of-the-estimate" id="toc-example-finding-the-standard-error-of-the-estimate" class="nav-link" data-scroll-target="#example-finding-the-standard-error-of-the-estimate"><span class="header-section-number">11.3.1</span> Example: Finding the Standard Error of the Estimate</a></li>
  <li><a href="#prediction-interval" id="toc-prediction-interval" class="nav-link" data-scroll-target="#prediction-interval"><span class="header-section-number">11.3.2</span> Prediction Interval</a></li>
  <li><a href="#prediction-interval-for-an-individual-y" id="toc-prediction-interval-for-an-individual-y" class="nav-link" data-scroll-target="#prediction-interval-for-an-individual-y"><span class="header-section-number">11.3.3</span> Prediction Interval for an Individual <span class="math inline">\(y\)</span></a></li>
  <li><a href="#example-10.3.2-find-the-prediction-interval" id="toc-example-10.3.2-find-the-prediction-interval" class="nav-link" data-scroll-target="#example-10.3.2-find-the-prediction-interval"><span class="header-section-number">11.3.4</span> Example \#10.3.2: Find the Prediction Interval</a></li>
  <li><a href="#hypothesis-test-for-correlation-or-slope" id="toc-hypothesis-test-for-correlation-or-slope" class="nav-link" data-scroll-target="#hypothesis-test-for-correlation-or-slope"><span class="header-section-number">11.3.5</span> Hypothesis Test for Correlation or Slope:</a></li>
  <li><a href="#example-testing-the-claim-of-a-linear-correlation" id="toc-example-testing-the-claim-of-a-linear-correlation" class="nav-link" data-scroll-target="#example-testing-the-claim-of-a-linear-correlation"><span class="header-section-number">11.3.6</span> Example: Testing the Claim of a Linear Correlation</a></li>
  <li><a href="#homework-for-inference-for-regression-and-correlation-section" id="toc-homework-for-inference-for-regression-and-correlation-section" class="nav-link" data-scroll-target="#homework-for-inference-for-regression-and-correlation-section"><span class="header-section-number">11.3.7</span> Homework for Inference for Regression and Correlation Section</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Regression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>The previous chapter looked at comparing populations to see if there is a difference between the two. That involved two random variables that are similar measures. This chapter will look at two random variables that do not need to be similar measures, and see if there is a relationship between the two or more variables. To do this, you look at regression, which finds the linear relationship, and correlation, which measures the strength of a linear relationship.</p>
<p>Please note: there are many other types of relationships besides linear that can be found for the data. This book will only explore linear, but realize that there are other relationships that can be used to describe data.</p>
<section id="regression" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="regression"><span class="header-section-number">11.1</span> Regression</h2>
<p>When comparing different variables, two questions come to mind: “Is there a relationship between two variables?” and “How strong is that relationship?” These questions can be answered using <strong>regression</strong> and <strong>correlation</strong>. Regression answers whether there is a relationship (again this book will explore linear only) and correlation answers how strong the linear relationship is. The variable that are used to explain the change in the other variable is called the <strong>explanatory variable</strong> while the variable that is changing is called the <strong>response variable</strong>. Other variables that help to explain the changes are known as <strong>covariates</strong>. To introduce the concepts of regression and correlation it is easier to look at a set of data.</p>
<section id="example-determining-if-there-is-a-relationship" class="level3" data-number="11.1.1">
<h3 data-number="11.1.1" class="anchored" data-anchor-id="example-determining-if-there-is-a-relationship"><span class="header-section-number">11.1.1</span> Example: Determining if there is a Relationship</h3>
<p>Is there a relationship between the alcohol content and the number of calories in 12-ounce beer? To determine if there is one, we explore a sample of 227 beers’ alcohol content and their calories (Find Out How Many Calories in Beer?, 2019). <a href="#tbl-Beer" class="quarto-xref">Table&nbsp;<span>11.1</span></a> shows the first five rows of the dataset.</p>
<div class="cell" data-tbl-alt="Head of beer data frame">
<div id="tbl-Beer" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Head of beer data frame">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Beer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11.1: Alcohol and Calorie Content in Beer
</figcaption>
<div aria-describedby="tbl-Beer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 38%">
<col style="width: 19%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">beer</th>
<th style="text-align: left;">brewery</th>
<th style="text-align: left;">location</th>
<th style="text-align: right;">alcohol</th>
<th style="text-align: right;">calories</th>
<th style="text-align: right;">carbs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">American Amber Lager</td>
<td style="text-align: left;">Straub Brewery</td>
<td style="text-align: left;">domestic</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">136</td>
<td style="text-align: right;">10.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Lager</td>
<td style="text-align: left;">Straub Brewery</td>
<td style="text-align: left;">domestic</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">132</td>
<td style="text-align: right;">10.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">American Light</td>
<td style="text-align: left;">Straub Brewery</td>
<td style="text-align: left;">domestic</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">7.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Anchor Porter</td>
<td style="text-align: left;">Anchor</td>
<td style="text-align: left;">domestic</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">209</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Anchor Steam</td>
<td style="text-align: left;">Anchor</td>
<td style="text-align: left;">domestic</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">153</td>
<td style="text-align: right;">16.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Anheuser Busch Natural Light</td>
<td style="text-align: left;">Anheuser Busch</td>
<td style="text-align: left;">domestic</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">95</td>
<td style="text-align: right;">3.2</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled" title="![](Rguroo_Icons/R_circle_logo.svg){width=22px style='vertical-align:middle;'}  For instructions to import and view the Beer dataset in your Rguroo account, click here">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<img src="Rguroo_Icons/R_circle_logo.svg" class="img-fluid" style="vertical-align:middle;" width="22"> For instructions to import and view the Beer dataset in your Rguroo account, click here
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Go to your Rguroo account.</li>
<li>Open the <strong>Data</strong> toolbox.</li>
<li>Click on <span class="dpd">Data Import</span> dropdown and select <span class="fun">Dataset Repository</span>.</li>
<li>In the searchbox on the top type in the keyword <span class="typein">kozak</span>. Then select the ``<em>Statistics Using Technology - Kozak</em>’’ repository.</li>
<li>In the middle <em>searchbox</em> type in <span class="typein">beer</span> and select the <span class="data">beer_data</span> dataset.</li>
<li>Click the <span class="button">Import</span> button. The dataset will be imported to your Rguroo account.</li>
<li>Click the <span class="button">Close</span> button to close the Rguroo dialog.</li>
<li>To view the dataset, click on the <span class="data">beer_data</span> under the <strong>Data</strong> toolbox.</li>
</ol>
</div>
</div>
</div>
<p><strong>Code book for data frame Beer</strong></p>
<p><strong>Description</strong> Collection of the most popular beers from large breweries. The data is of the calories, carbs and alcohol of a specific beer. The data is shown for a 12 ounce serving. The collection includes both domestic and import beer. For the imported beers the information is per 12 oz. serving even though many imports come in pints.</p>
<p>This dataset contains the following columns:</p>
<p>beer: The name of the beer.</p>
<p>brewery: the brewery that brews the beer.</p>
<p>location: whether the beer is brewed in the U.S. (domestic) or brewed in another country (import).</p>
<p>alcohol: the alcohol content of the beer.</p>
<p>calories: the number of calories in the beer.</p>
<p>carbs: the amount of carbohydrates in the beer (g).</p>
<p>Source Find Out How Many Calories in Beer? (n.d.). Retrieved July 21, 2019, from <a href="https://www.beer100.com/beer-calories/"></a></p>
<p>References (Find Out How Many Calories in Beer?, 2019)</p>
<section id="solution" class="level4" data-number="11.1.1.1">
<h4 data-number="11.1.1.1" class="anchored" data-anchor-id="solution"><span class="header-section-number">11.1.1.1</span> Solution</h4>
<p>To aid in figuring out if there is a relationship, it helps to draw a scatter plot of the data. First it is helpful to state the random variables, and since in an algebra class the variables are represented as <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>, those labels will be used here. It helps to state which variable is <span class="math inline">\(x\)</span> and which is <span class="math inline">\(y\)</span>.</p>
<p>State random variables</p>
<p><span class="math inline">\(x\)</span> = alcohol content in the beer</p>
<p><span class="math inline">\(y\)</span> = calories in 12 ounce beer</p>
<div class="callout callout-style-simple callout-note callout-titled" title="![](Rguroo_Icons/R_circle_logo.svg){width=22px style='vertical-align:middle;'} To see how to create the scatterplot of calories vs. alcohol content in Rguroo, click here">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<img src="Rguroo_Icons/R_circle_logo.svg" class="img-fluid" style="vertical-align:middle;" width="22"> To see how to create the scatterplot of calories vs.&nbsp;alcohol content in Rguroo, click here
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Go to your Rguroo account. Make sure that you have already imported the <span class="data">beer_data</span> dataset by following the instructions given above.<br>
</li>
<li>Open the <strong>Plots</strong> toolbox.<br>
</li>
<li>Click on the <span class="dpd">Create Plot</span> dropdown, and select <span class="fun">Scatterplot</span>. This opens the Scatterplot dialog.<br>
</li>
<li>From the <span class="dpd">Dataset</span> dropdown, select the <span class="data">beer_data</span> dataset.<br>
</li>
<li>From the <span class="dpd">Predictor (x)</span> dropdown, select the <span class="var">alcohol</span> variable.<br>
</li>
<li>From the <span class="dpd">Response (y)</span> dropdown, select the <span class="var">calories</span> variable.<br>
</li>
<li><strong>(Optional)</strong> In the <strong>Label</strong> section of the dialog:
<ul>
<li>In the <span class="des">Title</span> textbox, enter <span class="typein">Calories versus Alcohol Content in Beer</span>.<br>
</li>
<li>In the <span class="des">X-Axis</span> textbox, enter <span class="typein">Alcohol Content</span>.<br>
</li>
<li>In the <span class="des">Y-Axis</span> textbox, enter <span class="typein">Number of Calories</span>.<br>
</li>
</ul></li>
<li>Click the preview icon <img src="Rguroo_Icons/preview_inline.png" class="img-fluid" alt="preview icon"> to see a preview of the scatterplot.</li>
</ol>
<div class="callout callout-style-simple callout-note callout-titled" title="Click here to see the Rguroo dialog">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click here to see the Rguroo dialog
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Rguroo_images/Regression/Scatterplot_dialog.png" class="img-fluid figure-img" width="500"></p>
<figcaption>Scatterplot dialog in Rguroo</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-Beer-point" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Scatter plot of alcohol content versus calories with dots following somewhat along a line">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-Beer-point-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Rguroo_outputs/Regression/AlcoholCaloryScatter.svg" class="img-fluid figure-img" style="width:70.0%" alt="Scatter plot of alcohol content versus calories with dots following somewhat along a line">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-Beer-point-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11.1: Calories versus Alcohol Content in Beer
</figcaption>
</figure>
</div>
</div>
</div>
<p>This scatter plot shown in <a href="#fig-Beer-point" class="quarto-xref">Figure&nbsp;<span>11.1</span></a> looks fairly linear.</p>
<p>To find the equation for the linear relationship, the process of regression is used to find the line that best fits the data (sometimes called the best fitting line). The process is to draw the line through the data and then find the vertical distance from a point to the line. These are called the <strong>residuals</strong>. The regression line is the line that makes the square of the residuals as small as possible, so the regression line is also sometimes called the least squares line. The regression line on the scatter plot is displayed in <a href="#fig-Beer-point-line" class="quarto-xref">Figure&nbsp;<span>11.2</span></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(alcohol<span class="sc">~</span>calories, <span class="at">data=</span>Beer, <span class="at">title=</span><span class="st">"Calories versus Alcohol Content in Beer"</span>, <span class="at">xlab=</span><span class="st">"Alcohol Content"</span>, <span class="at">ylab=</span><span class="st">"Number of Calories"</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_lm</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Beer-point-line" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Scatter plot with regression line on plot">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-Beer-point-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Regression_files/figure-html/fig-Beer-point-line-1.png" class="img-fluid figure-img" alt="Scatter plot with regression line on plot" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-Beer-point-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11.2: Scatter Plot of Beer Data with Regression Line
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="find-the-regression-equation-also-known-as-best-fitting-line-or-least-squares-line" class="level3" data-number="11.1.2">
<h3 data-number="11.1.2" class="anchored" data-anchor-id="find-the-regression-equation-also-known-as-best-fitting-line-or-least-squares-line"><span class="header-section-number">11.1.2</span> Find the regression equation (also known as best fitting line or least squares line)</h3>
<p>Given a collection of paired sample data, the regression equation is <span class="math inline">\(\hat{y}=mx+b\)</span></p>
<p>where the slope = <span class="math inline">\(m\)</span> and <span class="math inline">\(y\)</span>-intercept = <span class="math inline">\((0,b)\)</span></p>
<p>To find the linear model using r Studio, use the command:</p>
<p>lm(response_variable~explanatory_variable, data=Data_Frame</p>
<p>The <strong>residuals</strong> are the difference between the actual values and the estimated values.</p>
<p>The <strong>independent variable</strong>, also called the <strong>explanatory variable</strong> or <strong>predictor variable</strong>, is the <span class="math inline">\(x\)</span>-value in the equation. The independent variable is the one that you use to predict what the other variable is. The <strong>dependent variable</strong> depends on what independent value you pick. It also responds to the explanatory variable and is usually called the <strong>response variable</strong>. In the alcohol content and calorie example, it makes slightly more sense to say that you would use the alcohol content on a beer to predict the number of calories in the beer.</p>
<p>Conditions of the regression line when creating a regression line from a sample:</p>
<ol type="1">
<li><p>The set of ordered pairs is a random sample from the population of all such possible pairs.</p></li>
<li><p>For each fixed value of <span class="math inline">\(x\)</span>, the <span class="math inline">\(y\)</span>-values have a normal distribution. All of the <span class="math inline">\(y\)</span> distributions have the same variance, and for a given <span class="math inline">\(x\)</span>-value, the distribution of <span class="math inline">\(y\)</span>-values has a mean that lies on the least squares line. You also assume that for a fixed <span class="math inline">\(y\)</span>, each <span class="math inline">\(x\)</span> has its own normal distribution. This is difficult to figure out, so you can use the following to determine if you have a normal distribution.</p></li>
</ol>
<!-- -->
<ol type="i">
<li><p>Look to see if the scatter plot has a linear pattern.</p></li>
<li><p>Examine the residuals to see if there is randomness in the residuals. If there is a pattern to the residuals, then there is an issue in the data.</p></li>
</ol>
</section>
<section id="example-find-the-equation-of-the-regression-line" class="level3" data-number="11.1.3">
<h3 data-number="11.1.3" class="anchored" data-anchor-id="example-find-the-equation-of-the-regression-line"><span class="header-section-number">11.1.3</span> Example: Find the Equation of the Regression Line</h3>
<p>Is there a relationship between the alcohol content and the number of calories in 12-ounce beer? To determine if there is one a sample of beer’s alcohol content and calories (Find Out How Many Calories in Beer?, 2019), is in <a href="#tbl-Beer" class="quarto-xref">Table&nbsp;<span>11.1</span></a>.</p>
<ol type="a">
<li>Find the regression equation between alcohol content and calories.</li>
<li>Use the regression equation to find the number of calories when the alcohol content is 7.00%.</li>
<li>Use the regression equation to find the number of calories when the alcohol content is 14%.</li>
</ol>
<section id="solution-1" class="level4" data-number="11.1.3.1">
<h4 data-number="11.1.3.1" class="anchored" data-anchor-id="solution-1"><span class="header-section-number">11.1.3.1</span> Solution</h4>
<ol type="a">
<li>Find the regression equation between alcohol content and calories.</li>
</ol>
<p>State random variables</p>
<p><span class="math inline">\(x\)</span> = alcohol content in the beer</p>
<p><span class="math inline">\(y\)</span> = calories in 12 ounce beer</p>
<p>To find the regression equation using rStudio for this example, the command would be</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(calories<span class="sc">~</span>alcohol, <span class="at">data=</span>Beer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = calories ~ alcohol, data = Beer)

Coefficients:
(Intercept)      alcohol  
      14.53      2672.36  </code></pre>
</div>
</div>
<p>From this you can see that the y-intercept is 14.53 and the slope is 2672.36. So the regression equation is <span class="math inline">\(\hat{y}=2672x+14.3\)</span>.</p>
<p>Remember, this is an estimate for the true regression. A different sample would produce a different estimate.</p>
<p>Conditions check:</p>
<ol type="1">
<li><p>State: A random sample of alcohol content and calories was taken.</p>
<p>Check: There is no guarantee that this was a random sample. The data was collected off of a website, and the website does not say how the data was obtained. However, it is a collection of most popular beers from large breweries, so it may be alright that it isn’t a random sample.</p></li>
<li><p>State: The distribution for each calorie value is normally distributed for every value of alcohol content in the beer.</p></li>
</ol>
<p>Check:</p>
<ol type="i">
<li><p>From <a href="#fig-Beer-point" class="quarto-xref">Figure&nbsp;<span>11.1</span></a>, the scatter plot looks fairly linear.</p></li>
<li><p>To graph the residuals, first the residuals need to be calculated. This means that for every <span class="math inline">\(x\)</span> value, you need to calculate the <span class="math inline">\(y\)</span> value that can be found from the regression equation. Then subtract the <span class="math inline">\(y\)</span> value that was measured from this calculated <span class="math inline">\(y\)</span> value. This is <span class="math inline">\(\hat{y}-y\)</span>. Luckily, rStudio will calculate these for you. The command is:</p></li>
</ol>
<div class="cell" data-tbl-alt="Residuals for Alcohol and Calorie Content in Beer">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>lm_out_beer<span class="ot">&lt;-</span><span class="fu">lm</span>(calories<span class="sc">~</span>alcohol, <span class="at">data=</span>Beer) </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">residuals</span>(lm_out_beer))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-Beer-residuals" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Residuals for Alcohol and Calorie Content in Beer">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Beer-residuals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11.2: Residuals for Alcohol and Calorie Content in Beer
</figcaption>
<div aria-describedby="tbl-Beer-residuals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">14.5785382</td>
</tr>
<tr class="even">
<td style="text-align: right;">10.5785382</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1.3021259</td>
</tr>
<tr class="even">
<td style="text-align: right;">34.1313626</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">-26.4214618</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-17.8686374</td>
</tr>
<tr class="even">
<td style="text-align: right;">-27.4214618</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">20.1313626</td>
</tr>
<tr class="odd">
<td style="text-align: right;">28.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">20.1313626</td>
</tr>
<tr class="odd">
<td style="text-align: right;">14.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">5.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">14.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">4.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">22.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">21.1313626</td>
</tr>
<tr class="odd">
<td style="text-align: right;">18.1313626</td>
</tr>
<tr class="even">
<td style="text-align: right;">-18.1450496</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-51.8686374</td>
</tr>
<tr class="even">
<td style="text-align: right;">-33.1450496</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-11.4214618</td>
</tr>
<tr class="even">
<td style="text-align: right;">-5.4214618</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-37.8686374</td>
</tr>
<tr class="even">
<td style="text-align: right;">-3.1450496</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-28.8686374</td>
</tr>
<tr class="even">
<td style="text-align: right;">-22.4214618</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-12.9742863</td>
</tr>
<tr class="even">
<td style="text-align: right;">-15.1450496</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-5.8686374</td>
</tr>
<tr class="even">
<td style="text-align: right;">-26.4214618</td>
</tr>
<tr class="odd">
<td style="text-align: right;">16.5785382</td>
</tr>
<tr class="even">
<td style="text-align: right;">-0.8686374</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">-17.4214618</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">5.1313626</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-11.5922251</td>
</tr>
<tr class="even">
<td style="text-align: right;">3.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-6.3158129</td>
</tr>
<tr class="even">
<td style="text-align: right;">9.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-9.8686374</td>
</tr>
<tr class="even">
<td style="text-align: right;">-22.2101640</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-24.8686374</td>
</tr>
<tr class="even">
<td style="text-align: right;">15.9605993</td>
</tr>
<tr class="odd">
<td style="text-align: right;">32.2370115</td>
</tr>
<tr class="even">
<td style="text-align: right;">-10.1450496</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-4.5922251</td>
</tr>
<tr class="even">
<td style="text-align: right;">9.6841871</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-20.8686374</td>
</tr>
<tr class="even">
<td style="text-align: right;">-7.3158129</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-11.8686374</td>
</tr>
<tr class="even">
<td style="text-align: right;">-13.5922251</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-19.1450496</td>
</tr>
<tr class="even">
<td style="text-align: right;">6.2370115</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-17.1450496</td>
</tr>
<tr class="even">
<td style="text-align: right;">-0.1450496</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">-18.8686374</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-0.1450496</td>
</tr>
<tr class="even">
<td style="text-align: right;">13.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-42.8686374</td>
</tr>
<tr class="even">
<td style="text-align: right;">-25.8686374</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-18.4214618</td>
</tr>
<tr class="even">
<td style="text-align: right;">-4.1450496</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-4.1450496</td>
</tr>
<tr class="even">
<td style="text-align: right;">-11.4214618</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-10.4214618</td>
</tr>
<tr class="even">
<td style="text-align: right;">-18.4214618</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-32.8686374</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">14.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">3.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">21.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">17.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">16.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">-16.4214618</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-11.4214618</td>
</tr>
<tr class="even">
<td style="text-align: right;">11.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">-17.8686374</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-3.1450496</td>
</tr>
<tr class="even">
<td style="text-align: right;">17.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">3.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-11.4214618</td>
</tr>
<tr class="even">
<td style="text-align: right;">26.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-8.4214618</td>
</tr>
<tr class="even">
<td style="text-align: right;">-26.4214618</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-17.8686374</td>
</tr>
<tr class="even">
<td style="text-align: right;">-17.8686374</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-11.4214618</td>
</tr>
<tr class="even">
<td style="text-align: right;">-5.1450496</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-11.4214618</td>
</tr>
<tr class="even">
<td style="text-align: right;">-30.6978741</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-5.1450496</td>
</tr>
<tr class="even">
<td style="text-align: right;">-11.4214618</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-25.4214618</td>
</tr>
<tr class="even">
<td style="text-align: right;">6.5785382</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-11.4214618</td>
</tr>
<tr class="even">
<td style="text-align: right;">-11.4214618</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-11.4214618</td>
</tr>
<tr class="even">
<td style="text-align: right;">6.5785382</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-23.4214618</td>
</tr>
<tr class="even">
<td style="text-align: right;">-30.8686374</td>
</tr>
<tr class="odd">
<td style="text-align: right;">30.1313626</td>
</tr>
<tr class="even">
<td style="text-align: right;">-1.5922251</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-1.5922251</td>
</tr>
<tr class="even">
<td style="text-align: right;">-8.1450496</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">6.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-13.3158129</td>
</tr>
<tr class="even">
<td style="text-align: right;">-3.1450496</td>
</tr>
<tr class="odd">
<td style="text-align: right;">55.4728892</td>
</tr>
<tr class="even">
<td style="text-align: right;">-7.4214618</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-2.1450496</td>
</tr>
<tr class="even">
<td style="text-align: right;">-14.8686374</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-26.3158129</td>
</tr>
<tr class="even">
<td style="text-align: right;">-8.3158129</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-2.1450496</td>
</tr>
<tr class="even">
<td style="text-align: right;">-4.1450496</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-27.6978741</td>
</tr>
<tr class="even">
<td style="text-align: right;">25.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-1.1450496</td>
</tr>
<tr class="even">
<td style="text-align: right;">4.1313626</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-13.5922251</td>
</tr>
<tr class="even">
<td style="text-align: right;">-6.1450496</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-28.1450496</td>
</tr>
<tr class="even">
<td style="text-align: right;">11.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">17.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">46.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.1313626</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-2.4214618</td>
</tr>
<tr class="even">
<td style="text-align: right;">-3.1450496</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-6.1450496</td>
</tr>
<tr class="even">
<td style="text-align: right;">-2.1450496</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-11.4214618</td>
</tr>
<tr class="even">
<td style="text-align: right;">10.1313626</td>
</tr>
<tr class="odd">
<td style="text-align: right;">15.1313626</td>
</tr>
<tr class="even">
<td style="text-align: right;">48.2370115</td>
</tr>
<tr class="odd">
<td style="text-align: right;">12.4077749</td>
</tr>
<tr class="even">
<td style="text-align: right;">8.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">15.1313626</td>
</tr>
<tr class="even">
<td style="text-align: right;">13.4077749</td>
</tr>
<tr class="odd">
<td style="text-align: right;">29.4077749</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.1313626</td>
</tr>
<tr class="odd">
<td style="text-align: right;">16.4077749</td>
</tr>
<tr class="even">
<td style="text-align: right;">19.1313626</td>
</tr>
<tr class="odd">
<td style="text-align: right;">50.1313626</td>
</tr>
<tr class="even">
<td style="text-align: right;">9.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">31.5785382</td>
</tr>
<tr class="even">
<td style="text-align: right;">4.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-25.1450496</td>
</tr>
<tr class="even">
<td style="text-align: right;">-6.3158129</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-6.3158129</td>
</tr>
<tr class="even">
<td style="text-align: right;">-14.8686374</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">-8.4214618</td>
</tr>
<tr class="odd">
<td style="text-align: right;">20.1313626</td>
</tr>
<tr class="even">
<td style="text-align: right;">-1.1450496</td>
</tr>
<tr class="odd">
<td style="text-align: right;">14.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">7.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">13.5785382</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">12.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-1.1450496</td>
</tr>
<tr class="even">
<td style="text-align: right;">-3.1450496</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">13.5785382</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-23.4214618</td>
</tr>
<tr class="even">
<td style="text-align: right;">13.5785382</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-22.4214618</td>
</tr>
<tr class="even">
<td style="text-align: right;">-2.1450496</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-14.8686374</td>
</tr>
<tr class="even">
<td style="text-align: right;">-2.1450496</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-5.1450496</td>
</tr>
<tr class="even">
<td style="text-align: right;">-3.9742863</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-2.1450496</td>
</tr>
<tr class="even">
<td style="text-align: right;">6.5785382</td>
</tr>
<tr class="odd">
<td style="text-align: right;">24.5785382</td>
</tr>
<tr class="even">
<td style="text-align: right;">7.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-0.1450496</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">18.4077749</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">16.5785382</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">-6.1450496</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-3.1450496</td>
</tr>
<tr class="even">
<td style="text-align: right;">31.5785382</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-6.1450496</td>
</tr>
<tr class="even">
<td style="text-align: right;">1.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">21.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">-22.4214618</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-13.5922251</td>
</tr>
<tr class="even">
<td style="text-align: right;">4.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">14.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">4.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13.2370115</td>
</tr>
<tr class="even">
<td style="text-align: right;">4.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-4.8686374</td>
</tr>
<tr class="even">
<td style="text-align: right;">14.0257137</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">-38.1450496</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-6.1450496</td>
</tr>
<tr class="even">
<td style="text-align: right;">38.5785382</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">9.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">25.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">9.5785382</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-16.5922251</td>
</tr>
<tr class="even">
<td style="text-align: right;">-0.1450496</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1.8549504</td>
</tr>
<tr class="even">
<td style="text-align: right;">-10.1450496</td>
</tr>
<tr class="odd">
<td style="text-align: right;">31.5785382</td>
</tr>
<tr class="even">
<td style="text-align: right;">6.5785382</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-41.5922251</td>
</tr>
<tr class="even">
<td style="text-align: right;">3.4077749</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-2.1450496</td>
</tr>
<tr class="even">
<td style="text-align: right;">4.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">20.5785382</td>
</tr>
<tr class="even">
<td style="text-align: right;">11.8549504</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4.8549504</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>lm_out_beer saves the linear model into a variable called lm_out_beer</p>
<p>residuals(lm_out_beer) finds the residuals for each <span class="math inline">\(x\)</span> value based on the linear model, lm_out_beer, and displays them.</p>
<p>Now graph the residuals to see if there is any pattern to the residuals. The command in rStudio is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">residuals</span>(lm_out_beer)<span class="sc">~</span>alcohol, <span class="at">data=</span>Beer, <span class="at">title=</span><span class="st">"Residuals for Calories in beer"</span>, <span class="at">xlab=</span><span class="st">"Alcohol Content"</span>, <span class="at">ylab=</span><span class="st">"Residuals for Number of Calories"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Beer-residuals" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Residual plot of beer data, looks random">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-Beer-residuals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Regression_files/figure-html/fig-Beer-residuals-1.png" class="img-fluid figure-img" alt="Residual plot of beer data, looks random" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-Beer-residuals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11.3: Residual Plot of Beer Data
</figcaption>
</figure>
</div>
</div>
</div>
<p>The residual versus the <span class="math inline">\(x-\)</span>values plot <a href="#fig-Beer-residuals" class="quarto-xref">Figure&nbsp;<span>11.3</span></a> looks fairly random.</p>
<p>It appears that the distribution for calories is a normal distribution.</p>
<ol start="2" type="a">
<li>Use the regression equation to find the number of calories when the alcohol content is 7.00%.</li>
</ol>
<p><span class="math inline">\(\hat{y}=2672*0.07+14.3=201.34\)</span> If you are drinking a beer that is 7.00% alcohol content, then it is probably close to 200 calories.</p>
<p>The mean number of calories is 154.5 calories. This value of 201 seems like a better estimate than the mean when looking at the data since all the beers with 7% alcohol have between 160 and 231 calories. The regression equation is a better estimate than just the mean.</p>
<ol start="3" type="a">
<li>Use the regression equation to find the number of calories when the alcohol content is 14%.</li>
</ol>
<p><span class="math inline">\(\hat{y}=2672*0.14+14.3=388.38\)</span></p>
<p>If you are drinking a beer that is 14% alcohol content, then it has probably close to 389 calories. Since 12% alcohol beer has 330 calories you might think that 14% would have more calories than this. This estimate is what is called <strong>extrapolation</strong>. It is not a good idea to predict values that are far outside the range of the original data. This is because you can never be sure that the regression equation is valid for data outside the original data.</p>
<p>Notice, that the 7.00% value falls into the range of the original <span class="math inline">\(x\)</span>-values. The processes of predicting values using an <span class="math inline">\(x\)</span> within the range of original <span class="math inline">\(x\)</span>-values is called <strong>interpolating</strong>. The 14.00% value is outside the range of original <span class="math inline">\(x\)</span>-values. Using an <span class="math inline">\(x\)</span>-value that is outside the range of the original <span class="math inline">\(x\)</span>-values is called <strong>extrapolating</strong>. When predicting values using interpolation, you can usually feel pretty confident that that value will be close to the true value. When you extrapolate, you are not really sure that the predicted value is close to the true value. This is because when you interpolate, you know the equation that predicts, but when you extrapolate, you are not really sure that your relationship is still valid. The relationship could in fact change for different <span class="math inline">\(x\)</span>-values.</p>
<p>An example of this is when you use regression to come up with an equation to predict the growth of a city, like Flagstaff, AZ. Based on analysis it was determined that the population of Flagstaff would be well over 50,000 by 1995. However, when a census was undertaken in 1995, the population was less than 50,000. This is because they extrapolated and the growth factor they were using had obviously changed from the early 1990’s. Growth factors can change for many reasons, such as employment growth, employment stagnation, disease, articles saying great place to live, etc. Realize that when you extrapolate, your predicted value may not be anywhere close to the actual value that you observe.</p>
<p>What does the slope mean in the context of this problem?</p>
<p>The calories increase 26.72 calories for every 1% increase in alcohol content.</p>
<p>The <span class="math inline">\(y\)</span>-intercept in many cases is meaningless. In this case, it means that if a drink has 0 alcohol content, then it would have 14.3 calories. This may be reasonable, but remember this value is an extrapolation so it may be wrong.</p>
<p>Consider the residuals again. According to the data, a beer with 7.0% alcohol has between 160 and 231 calories. The predicted value is 201 calories. This variation means that the actual value was between 40 calories below and 30 calories above the predicted value. That isn’t that far off. Some of the actual values differ by a large amount from the predicted value. This is due to variability in the response variable. The larger the residuals the less the model explains the variability in the response variable. There needs to be a way to calculate how well the model explains the variability in the response variable. This will be explored in the next section.</p>
<p>On last thing to look at here, is that you may wonder if import beer has a different amount of calories than domestic beer. The location is a co-variate, a third variable that affects the calories, and you can graph a scatter plot that separates based on the co-variate. Here is how to do this in r Studio.</p>
<p>(ref:Beer10a-point-lm) Calories versus Alcohol Content Separated by Location of Beer Data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(calories<span class="sc">~</span>alcohol, <span class="at">data=</span>Beer, <span class="at">title=</span><span class="st">"Calories versus Alcohol Content of Beer separated by Location"</span>, <span class="at">color=</span><span class="sc">~</span>location, <span class="at">xlab=</span><span class="st">"Alcohol Content"</span>, <span class="at">ylab=</span><span class="st">"Number of calories"</span>) <span class="sc">|&gt;</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_lm</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Beer-point-lm" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Scatter plot with linear regression line faccetted by domestic and import.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-Beer-point-lm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Regression_files/figure-html/fig-Beer-point-lm-1.png" class="img-fluid figure-img" alt="Scatter plot with linear regression line faccetted by domestic and import." width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-Beer-point-lm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11.4: Calories versus Alcohol Content of Beer separated by Location
</figcaption>
</figure>
</div>
</div>
</div>
<p>Looking at the scatter plot, there doesn’t appear to be an affect from domestic or import. This is what is nice about scatter plots, You can visually see a possible relationships.</p>
</section>
</section>
<section id="homework-for-regression-section" class="level3" data-number="11.1.4">
<h3 data-number="11.1.4" class="anchored" data-anchor-id="homework-for-regression-section"><span class="header-section-number">11.1.4</span> Homework for Regression Section</h3>
<p><strong>For each problem, state the random variables. The Data Frame in this section are used in the homework for sections 10.2 and 10.3 also.</strong></p>
<ol type="1">
<li>When an anthropologist finds skeletal remains, they need to figure out the height of the person. The height of a person (in cm) and the length of their metacarpal bone 1 (in mm) were collected and are in <span class="quarto-unresolved-ref">?tbl-Metacarpal</span> (\“Prediction of height,\” 2013). Create a scatter plot and find a regression equation between the height of a person and the length of their metacarpal. Then use the regression equation to find the height of a person for a metacarpal length of 44 mm and for a metacarpal length of 55 mm. Which height that you calculated do you think is closer to the true height of the person? Why?</li>
</ol>
<p><strong>Code book for Data Frame Metacarpal is below <span class="quarto-unresolved-ref">?tbl-Metacarpal</span>.</strong></p>
<ol start="2" type="1">
<li><span class="quarto-unresolved-ref">?tbl-House</span> contains the value of the house and the amount of rental income in a year that the house brings in (\“Capital and rental,\” 2013). Create a scatter plot and find a regression equation between house value and rental income. Then use the regression equation to find the rental income of a house worth \$230,000 and for a house worth \$400,000. Which rental income that you calculated do you think is closer to the true rental income? Why?</li>
</ol>
<p><strong>Code book for Data Frame House is below <span class="quarto-unresolved-ref">?tbl-House</span>.</strong></p>
<ol start="3" type="1">
<li>The World Bank collects information on the life expectancy of a person in each country (\“Life expectancy at,\” 2013) and the fertility rate per woman in the country (\“Fertility rate,\” 2013). The Data Frame for countries for the year 2011 are in <span class="quarto-unresolved-ref">?tbl-Fertility</span>. Create a scatter plot of the Data Frame and find a linear regression equation between fertility rate and life expectancy in 2011. Then use the regression equation to find the life expectancy for a country that has a fertility rate of 2.7 and for a country with fertility rate of 8.1. Which life expectancy that you calculated do you think is closer to the true life expectancy? Why?</li>
</ol>
<p><strong>Code book for Data Frame Fertility is below <span class="quarto-unresolved-ref">?tbl-Fertility</span>.</strong></p>
<ol start="4" type="1">
<li>The World Bank collected data on the percentage of gross domestic product (GDP) that a country spends on health expenditures (Current health expenditure (% of GDP), 2019), the fertility rate of the country (Fertility rate, total (births per woman), 2019), and the percentage of woman receiving prenatal care (Pregnant women receiving prenatal care (%), 2019). The Data Frame for the countries where this information is available in <span class="quarto-unresolved-ref">?tbl-Fert_prenatal</span>. Create a scatter plot of the Data Frame and find a regression equation between percentage spent on health expenditure and the percentage of women receiving prenatal care. Then use the regression equation to find the percent of women receiving prenatal care for a country that spends 5.0% of GDP on health expenditure and for a country that spends 12.0% of GDP. Which prenatal care percentage that you calculated do you think is closer to the true percentage? Why?</li>
</ol>
<p><strong>Code book for Data Frame Fert_prenatal is below <span class="quarto-unresolved-ref">?tbl-Fert_prenatal</span>.</strong></p>
<ol start="5" type="1">
<li>The height and weight of baseball players are in <a href="#tbl-Baseball" class="quarto-xref">Table&nbsp;<span>11.3</span></a> (\“MLB heightsweights,\” 2013). Create a scatter plot and find a regression equation between height and weight of baseball players. Then use the regression equation to find the weight of a baseball player that is 75 inches tall and for a baseball player that is 68 inches tall. Which weight that you calculated do you think is closer to the true weight? Why?</li>
</ol>
<div class="cell" data-tbl-alt="Head of Heights and Weights of Baseball Players data frame">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>Baseball <span class="ot">&lt;-</span> <span class="fu">read.csv</span>( <span class="st">"https://krkozak.github.io/MAT160/baseball.csv"</span>) </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(Baseball))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-Baseball" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Head of Heights and Weights of Baseball Players data frame">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Baseball-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11.3: Heights and Weights of Baseball Players
</figcaption>
<div aria-describedby="tbl-Baseball-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">player</th>
<th style="text-align: right;">height</th>
<th style="text-align: right;">weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">65.78</td>
<td style="text-align: right;">112.99</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">71.52</td>
<td style="text-align: right;">136.49</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">69.40</td>
<td style="text-align: right;">153.03</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">68.22</td>
<td style="text-align: right;">142.34</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">67.79</td>
<td style="text-align: right;">144.30</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">68.70</td>
<td style="text-align: right;">123.30</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><strong>Code book for Data Frame Baseball</strong></p>
<p><strong>Description</strong></p>
<p>The heights and weights of MLB players.</p>
<p>Format</p>
<p>This Data Frame contains the following columns:</p>
<p>Player: Player in the sample</p>
<p>height: height of baseball player (inches)</p>
<p>weight: weight of baseball player (pounds)</p>
<p>Source MLB heightsweights. (2013, November 16). Retrieved from http://wiki.stat.ucla.edu/socr/index.php/SOCR_Data_MLB_HeightsWeights</p>
<p>References SOCR Data Frame of MLB Heights Weights from UCLA.</p>
<ol start="6" type="1">
<li>Different species have different body weights and brain weights are in <a href="#tbl-Body" class="quarto-xref">Table&nbsp;<span>11.4</span></a>. (\“Brain2bodyweight,\” 2013). Create a scatter plot and find a regression equation between body weights and brain weights. Then use the regression equation to find the brain weight for a species that has a body weight of 62 kg and for a species that has a body weight of 180,000 kg. Which brain weight that you calculated do you think is closer to the true brain weight? Why?</li>
</ol>
<div class="cell" data-tbl-alt="Head of Body Weights and Brain Weights of Species">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>Body <span class="ot">&lt;-</span> <span class="fu">read.csv</span>( <span class="st">"https://krkozak.github.io/MAT160/body.csv"</span>) </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(Body))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-Body" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Head of Body Weights and Brain Weights of Species">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Body-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11.4: Body Weights and Brain Weights of Species
</figcaption>
<div aria-describedby="tbl-Body-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">species</th>
<th style="text-align: right;">bodyweight</th>
<th style="text-align: right;">brainweight</th>
<th style="text-align: right;">brainbodyproportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Newborn_Human</td>
<td style="text-align: right;">3.20</td>
<td style="text-align: right;">0.3749848</td>
<td style="text-align: right;">0.1171828</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adult_Human</td>
<td style="text-align: right;">73.00</td>
<td style="text-align: right;">1.3499816</td>
<td style="text-align: right;">0.0184929</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pithecanthropus_Man</td>
<td style="text-align: right;">70.00</td>
<td style="text-align: right;">0.9250109</td>
<td style="text-align: right;">0.0132144</td>
</tr>
<tr class="even">
<td style="text-align: left;">Squirrel</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">0.0076204</td>
<td style="text-align: right;">0.0095254</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hamster</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.0014061</td>
<td style="text-align: right;">0.0093742</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chimpanzee</td>
<td style="text-align: right;">50.00</td>
<td style="text-align: right;">0.4199812</td>
<td style="text-align: right;">0.0083996</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><strong>Code book for Data Frame Body</strong></p>
<p><strong>Description</strong></p>
<p>The body weight, brain weight, and brain/body proportion of different species of animals.</p>
<p>Format</p>
<p>This Data Frame contains the following columns:</p>
<p>species: species of animal</p>
<p>bodyweight: the body weight of the species (kg)</p>
<p>brainweight: the brain weight of the species (kg)</p>
<p>brainbodyproportion: the ratio of brain weight to body weight of the species</p>
<p>Source Brain2bodyweight. (2013, November 16). Retrieved from http://wiki.stat.ucla.edu/socr/index.php/SOCR_Data_Brain2BodyWeight</p>
<p>References SOCR Data of species body weights and brain weights from UCLA.</p>
<ol start="7" type="1">
<li>A sample of hot dogs was taken and the amount of sodium (in mg) and calories were measured. (\“Data hotdogs,\” 2013) The Data Frame are in <span class="quarto-unresolved-ref">?tbl-Hotdog</span>. Create a scatter plot and find a regression equation between amount of calories and amount of sodium. Then use the regression equation to find the amount of sodium a hot dog has if it is 170 calories and if it is 120 calories. Which sodium level that you calculated do you think is closer to the true sodium level? Why?</li>
</ol>
<p><strong>Code book for data frame Hotdog is below <span class="quarto-unresolved-ref">?tbl-Hotdog</span>.</strong></p>
<ol start="8" type="1">
<li>Per capita income in 1960 dollars for European countries and the percent of the labor force that works in agriculture in 1960 are in <a href="#tbl-Agriculture" class="quarto-xref">Table&nbsp;<span>11.5</span></a> (\“OECD economic development,\” 2013). Create a scatter plot and find a regression equation between percent of labor force in agriculture and per capita income. Then use the regression equation to find the per capita income in a country that has 21 percent of labor in agriculture and in a country that has 2 percent of labor in agriculture. Which per capita income that you calculated do you think is closer to the true income? Why?</li>
</ol>
<div class="cell" data-tbl-alt="Head of Percent of Labor in Agriculture and Per Capita Income for European Countries">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>Agriculture <span class="ot">&lt;-</span> <span class="fu">read.csv</span>( <span class="st">"https://krkozak.github.io/MAT160/agriculture.csv"</span>) </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(Agriculture))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-Agriculture" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Head of Percent of Labor in Agriculture and Per Capita Income for European Countries">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Agriculture-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11.5: Percent of Labor in Agriculture and Per Capita Income for European Countries
</figcaption>
<div aria-describedby="tbl-Agriculture-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">country</th>
<th style="text-align: right;">percapita</th>
<th style="text-align: right;">agriculture</th>
<th style="text-align: right;">industry</th>
<th style="text-align: right;">services</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SWEEDEN</td>
<td style="text-align: right;">1644</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">53</td>
<td style="text-align: right;">33</td>
</tr>
<tr class="even">
<td style="text-align: left;">SWITZERLAND</td>
<td style="text-align: right;">1361</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">33</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LUXEMBOURG</td>
<td style="text-align: right;">1242</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">51</td>
<td style="text-align: right;">34</td>
</tr>
<tr class="even">
<td style="text-align: left;">U. KINGDOM</td>
<td style="text-align: right;">1105</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">40</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DENMARK</td>
<td style="text-align: right;">1049</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">37</td>
</tr>
<tr class="even">
<td style="text-align: left;">W. GERMANY</td>
<td style="text-align: right;">1035</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">25</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><strong>Code book for Data Frame Agriculture</strong></p>
<p><strong>Description</strong></p>
<p>The per capita income and percent in different industries in European countries</p>
<p>Format</p>
<p>This Data Frame contains the following columns:</p>
<p>country: country in Europe</p>
<p>percapita: per captia income</p>
<p>agriculture: percentage of workforce in agriculture</p>
<p>industry: percentage of workforce in industry</p>
<p>services: percentage of workforce in services</p>
<p>Source OECD economic development. (2013, December 04). Retrieved from http://lib.stat.cmu.edu/DASL/Datafiles/oecdat.html</p>
<p>References Data And Story Library</p>
<ol start="9" type="1">
<li>Cigarette smoking and cancer have been linked. The number of deaths per one hundred thousand from bladder cancer and the number of cigarettes sold per capita in 1960 are in table \#10.1.11 (\“Smoking and cancer,\” 2013). Create a scatter plot and find a regression equation between number of cigarettes smoked and number of deaths from bladder cancer. Then use the regression equation to find the number of deaths from bladder cancer when the cigarette sales were 20 per capita and when the cigarette sales were 6 per capita. Which number of deaths that you calculated do you think is closer to the true number? Why?</li>
</ol>
<div class="cell" data-tbl-alt="Head of Number of Cigarettes and Number of Bladder Cancer Deaths">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>Cancer <span class="ot">&lt;-</span> <span class="fu">read.csv</span>( <span class="st">"https://krkozak.github.io/MAT160/cancer_1.csv"</span>) </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(Cancer))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-Cancer" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Head of Number of Cigarettes and Number of Bladder Cancer Deaths">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Cancer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11.6: Number of Cigarettes and Number of Bladder Cancer Deaths
</figcaption>
<div aria-describedby="tbl-Cancer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">state</th>
<th style="text-align: right;">cig</th>
<th style="text-align: right;">bladder</th>
<th style="text-align: right;">lung</th>
<th style="text-align: right;">kidney</th>
<th style="text-align: right;">leukemia</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">AL</td>
<td style="text-align: right;">18.20</td>
<td style="text-align: right;">2.90</td>
<td style="text-align: right;">17.05</td>
<td style="text-align: right;">1.59</td>
<td style="text-align: right;">6.15</td>
</tr>
<tr class="even">
<td style="text-align: left;">AZ</td>
<td style="text-align: right;">25.82</td>
<td style="text-align: right;">3.52</td>
<td style="text-align: right;">19.80</td>
<td style="text-align: right;">2.75</td>
<td style="text-align: right;">6.61</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AR</td>
<td style="text-align: right;">18.24</td>
<td style="text-align: right;">2.99</td>
<td style="text-align: right;">15.98</td>
<td style="text-align: right;">2.02</td>
<td style="text-align: right;">6.94</td>
</tr>
<tr class="even">
<td style="text-align: left;">CA</td>
<td style="text-align: right;">28.60</td>
<td style="text-align: right;">4.46</td>
<td style="text-align: right;">22.07</td>
<td style="text-align: right;">2.66</td>
<td style="text-align: right;">7.06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CT</td>
<td style="text-align: right;">31.10</td>
<td style="text-align: right;">5.11</td>
<td style="text-align: right;">22.83</td>
<td style="text-align: right;">3.35</td>
<td style="text-align: right;">7.20</td>
</tr>
<tr class="even">
<td style="text-align: left;">DE</td>
<td style="text-align: right;">33.60</td>
<td style="text-align: right;">4.78</td>
<td style="text-align: right;">24.55</td>
<td style="text-align: right;">3.36</td>
<td style="text-align: right;">6.45</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><strong>Code book for Data Frame Cancer</strong></p>
<p><strong>Description</strong> This data frame contains the number of cigarette sales (per Capita), number of cancer Deaths (per 100 Thousand) from bladder, lung, kidney, and leukemia.</p>
<p>Format</p>
<p>This Data Frame contains the following columns:</p>
<p>state: state in US</p>
<p>cig: the number of cigarette sales (per capita)</p>
<p>bladder: number of deaths per 100 thousand from bladder cancer</p>
<p>lung: number of deaths per 100 thousand from lung cancer</p>
<p>kidney: number of deaths per 100 thousand from kidney cancer</p>
<p>leukemia: number of deaths per 100 thousand from leukemia</p>
<p>Source Smoking and cancer. (2013, December 04). Retrieved from http://lib.stat.cmu.edu/DASL/Datafiles/cigcancerdat.html</p>
<p>References Data And Story Library</p>
<ol start="10" type="1">
<li>The weight of a car can influence the mileage that the car can obtain. A random sample of cars’ weights and mileage was collected and are in <a href="#tbl-Cars" class="quarto-xref">Table&nbsp;<span>11.7</span></a> (\“us auto mileage,\” 2019). Create a scatter plot and find a regression equation between weight of cars and mileage. Then use the regression equation to find the mileage on a car that weighs 3800 pounds and on a car that weighs 2000 pounds. Which mileage that you calculated do you think is closer to the true mileage? Why?</li>
</ol>
<div class="cell" data-tbl-alt="Head of Weights and Mileages of Carss">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>Cars<span class="ot">&lt;-</span> <span class="fu">read.csv</span>( <span class="st">"https://krkozak.github.io/MAT160/cars.csv"</span>) </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(Cars))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-Cars" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-alt="Head of Weights and Mileages of Carss">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Cars-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11.7: Weights and Mileages of Cars
</figcaption>
<div aria-describedby="tbl-Cars-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">make</th>
<th style="text-align: right;">vol</th>
<th style="text-align: right;">hp</th>
<th style="text-align: right;">mpg</th>
<th style="text-align: right;">sp</th>
<th style="text-align: right;">wt</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">GM/GeoMetroXF1</td>
<td style="text-align: right;">89</td>
<td style="text-align: right;">49</td>
<td style="text-align: right;">65.4</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">17.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">GM/GeoMetro</td>
<td style="text-align: right;">92</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">56.0</td>
<td style="text-align: right;">97</td>
<td style="text-align: right;">20.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GM/GeoMetroLSI</td>
<td style="text-align: right;">92</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">55.9</td>
<td style="text-align: right;">97</td>
<td style="text-align: right;">20.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">SuzukiSwift</td>
<td style="text-align: right;">92</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">49.0</td>
<td style="text-align: right;">105</td>
<td style="text-align: right;">20.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DaihatsuCharade</td>
<td style="text-align: right;">92</td>
<td style="text-align: right;">53</td>
<td style="text-align: right;">46.5</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">20.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">GM/GeoSprintTurbo</td>
<td style="text-align: right;">89</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">46.2</td>
<td style="text-align: right;">105</td>
<td style="text-align: right;">20.0</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><strong>Code book for Data Frame Cars</strong></p>
<p><strong>Description</strong> Variation in gasoline mileage among makes and models of automobiles is influenced substantially by the weight and horsepower of the vehicles. When miles per gallon and horsepower are transformed to logarithms, the linearity of the regression is improved. A negative second order term is required to fit the logarithmic mileage to weight relation. If the logged variables are standardized, the coefficients of the first order terms indicate the standard units change in log mileage per one standard unit change in the predictor variable at the (logarithmic) mean. This change is constant in the case of mileage to horsepower, but not for mileage to weight. The coefficient of the second order weight term indicates the change in standardized slope associated with a one standard deviation increase in the logarithm of weight.</p>
<p>Format</p>
<p>This Data Frame contains the following columns:</p>
<p>make: the type of car</p>
<p>vol: cubic feet of cab space</p>
<p>hp: engine horsepower</p>
<p>npg: the average mileage of the car</p>
<p>sp: top speed (mph)</p>
<p>wt: the weight of the car (100 pounds)</p>
<p>Source (n.d.). Retrieved July 21, 2019, from https://www3.nd.edu/~busiforc/handouts/Data and Stories/regression/us auto mileage/usautomileage.html</p>
<p>References R.M. Heavenrich, J.D. Murrell, and K.H. Hellman, Light Duty Automotive Technology and Fuel Economy Trends Through 1991, U.S. Environmental Protection Agency, 1991 (EPA/AA/CTAB/91-02).</p>
<p>**\ **</p>
</section>
</section>
<section id="correlation" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="correlation"><span class="header-section-number">11.2</span> Correlation</h2>
<p>A <strong>correlation</strong> exists between two variables when the values of one variable are somehow associated with the values of the other variable. Correlation is a word used in every day life and many people think they understand what it means. What it really means is a measure of how strong the linear relationship is between two variables. However, it doesn’t give you a strong indication of how well the relationship explains the variability in the response variable, and it doesn’t work for more than two variables. There is a way to look at how much of the relationship explains the variability in the response variable.</p>
<p>There are many types of patterns one can see in the data. Common types of patterns are linear, exponential, logarithmic, or periodic. To see this pattern, you can draw a scatter plot of the data.This course will mostly deal with linear, but the other patterns exist.</p>
<p>There is some variability in the response variable values, such as calories. Some of the variation in calories is due to alcohol content and some is due to other factors. How much of the variation in the calories is due to alcohol content?</p>
<p>When considering this question, you want to look at how much of the variation in calories is explained by alcohol content and how much is explained by other variables. Realize that some of the changes in calories have to do with other ingredients. You can have two beers at the same alcohol content, but one beer has higher calories because of the other ingredients. Some variability is explained by the model and some variability is not explained. Together, both of these give the total variability. This is (total variation)=(explained variation)+(unexplained variation)</p>
<p>The proportion of the variation that is explained by the model is <span class="math inline">\(R^2=\frac{\text{explained variation}}{\text{total variation}}\)</span></p>
<p>This is known as the <strong>coefficient of determination</strong>.</p>
<p>To find the coefficient of determination, on r Studio, the command is to first name the linear model to be something and then you can find the summary of that named linear model. The next example shows how to find this.</p>
<section id="example-find-the-coefficient-of-determination-r2" class="level3" data-number="11.2.1">
<h3 data-number="11.2.1" class="anchored" data-anchor-id="example-find-the-coefficient-of-determination-r2"><span class="header-section-number">11.2.1</span> Example: Find the coefficient of determination <span class="math inline">\(R^2\)</span></h3>
<p>How well does the alcohol content of a beer explain the variability in the number of calories in 12-ounce beer? To determine this a sample of beer’s alcohol content and calories (Find Out How Many Calories in Beer?, 2019), is in <a href="#tbl-Beer" class="quarto-xref">Table&nbsp;<span>11.1</span></a>.</p>
<section id="solution-2" class="level4" data-number="11.2.1.1">
<h4 data-number="11.2.1.1" class="anchored" data-anchor-id="solution-2"><span class="header-section-number">11.2.1.1</span> Solution</h4>
<p>State random variables</p>
<p><span class="math inline">\(x\)</span> = alcohol content in the beer</p>
<p><span class="math inline">\(y\)</span> = calories in 12 ounce beer</p>
<p>First find and name the linear model, how about lm_out_beer, so you can refer to it. Then use the command</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>lm_out_beer<span class="ot">&lt;-</span><span class="fu">lm</span>(calories<span class="sc">~</span>alcohol, <span class="at">data=</span>Beer) <span class="co">#creates the linear model and calls it lm_out_beer </span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rsquared</span>(lm_out_beer) <span class="co">#finds the rsquared of the linear model created.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8164314</code></pre>
</div>
</div>
<p>The <span class="math inline">\(R^2=0.8164\)</span>. Thus, 81.64% of the variation in calories is explained to the linear relationship between alcohol content and calories. The other 18.36% of the variation is due to other factors. A really good coefficient of determination has a very small, unexplained part. So this means you probably don’t need to look for a co-variate.</p>
<p>This is all you have to do to find how much of the variability in the response variable is explained by the linear model.</p>
<p>If you do want to talk about correlation, correlation is another measure of the strength of the linear relationship. The symbol for the coefficient correlation is <span class="math inline">\(r\)</span>. To find <span class="math inline">\(r\)</span>, it is the square root of <span class="math inline">\(R^2\)</span>. So <span class="math inline">\(r=\sqrt{R^2}\)</span>. So all you need to do is take the square root of the answer you already found. The only thing is that when you take a square root of both sides of an equation you need the <span class="math inline">\(\pm\)</span> symbol. This is because you don’t know if you want the positive or negative root. However, remember to read graphs from left to right, the same as you read words. If the graph goes up the correlation is positive and if the graph goes down the correlation is negative. Just affix the correct sign to the <span class="math inline">\(r\)</span> value. You can also use this command and r will give you the correct sign.</p>
<p>cor(respose_variable~explanatory_variable, data=Data_Frame)</p>
<p>The <strong>linear correlation coefficient</strong> is a number that describes the strength of the linear relationship between the two variables. It is also called the Pearson correlation coefficient after Karl Pearson who developed it.</p>
</section>
</section>
<section id="interpretation-of-the-correlation-coefficient" class="level3" data-number="11.2.2">
<h3 data-number="11.2.2" class="anchored" data-anchor-id="interpretation-of-the-correlation-coefficient"><span class="header-section-number">11.2.2</span> Interpretation of the correlation coefficient</h3>
<p><span class="math inline">\(r\)</span> is always between <span class="math inline">\(-1\)</span> and 1. <span class="math inline">\(r\)</span> = <span class="math inline">\(-1\)</span> means there is a perfect negative linear correlation and <span class="math inline">\(r\)</span> = 1 means there is a perfect positive correlation. The closer <span class="math inline">\(r\)</span> is to 1 or <span class="math inline">\(-1\)</span>, the stronger the correlation. The closer <span class="math inline">\(r\)</span> is to 0, the weaker the correlation. CAREFUL: <span class="math inline">\(r\)</span> = 0 does not mean there is no correlation. It just means there is <strong>no linear correlation</strong>. There might be a very strong curved pattern.</p>
</section>
<section id="example-calculating-the-linear-correlation-coefficient-r" class="level3" data-number="11.2.3">
<h3 data-number="11.2.3" class="anchored" data-anchor-id="example-calculating-the-linear-correlation-coefficient-r"><span class="header-section-number">11.2.3</span> Example: Calculating the Linear Correlation Coefficient, <span class="math inline">\(r\)</span></h3>
<p>How strong is the positive relationship between the alcohol content and the number of calories in 12-ounce beer? To determine if there is a linear correlation, a random sample was taken of beer’s alcohol content and calories for several different beers (\“Calories in beer,,\” 2011), and the Data Frame are in <a href="#tbl-Beer" class="quarto-xref">Table&nbsp;<span>11.1</span></a>. Find the correlation coefficient and interpret that value.</p>
<section id="solution-3" class="level4" data-number="11.2.3.1">
<h4 data-number="11.2.3.1" class="anchored" data-anchor-id="solution-3"><span class="header-section-number">11.2.3.1</span> Solution</h4>
<p>State random variables</p>
<p><span class="math inline">\(x\)</span> = alcohol content in the beer</p>
<p><span class="math inline">\(y\)</span> = calories in 12 ounce beer</p>
<p>From example 10.2.1, <span class="math inline">\(R^2=0.8164\)</span>. The correlation coefficient = <span class="math inline">\(r=\sqrt{r^2}=\sqrt{0.8164}=0.9035486\)</span>, or use this command in r</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(calories<span class="sc">~</span>alcohol, <span class="at">data=</span>Beer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9035659</code></pre>
</div>
</div>
<p>The scatter graph went up from left to right, so the correlation coefficient is positive. Since 0.90 is close to 1, then that means there is a fairly strong positive correlation.</p>
</section>
</section>
<section id="causation" class="level3" data-number="11.2.4">
<h3 data-number="11.2.4" class="anchored" data-anchor-id="causation"><span class="header-section-number">11.2.4</span> Causation</h3>
<p>One common mistake people make is to assume that because there is a correlation, then one variable causes the other. This is usually not the case. That would be like saying the amount of alcohol in the beer causes it to have a certain number of calories. However, fermentation of sugars is what causes the alcohol content. The more sugars you have, the more alcohol can be made, and the more sugar, the higher the calories. It is actually the amount of sugar that causes both. Do not confuse the idea of correlation with the concept of causation. Just because two variables are correlated does not mean one causes the other to happen. However, the new theory is showing that if you have a relationship between two variables and a strong correlation, and you can show that there are no other variables that could explain the change, then you can show causation. This is how doctors have shown that smoking causes kidney cancer. Just realize that proving that one caused the other is a difficult process, and causation should not be just assumed.</p>
</section>
<section id="example-correlation-versus-causation" class="level3" data-number="11.2.5">
<h3 data-number="11.2.5" class="anchored" data-anchor-id="example-correlation-versus-causation"><span class="header-section-number">11.2.5</span> Example: Correlation Versus Causation</h3>
<ol type="a">
<li>A study showed a strong linear correlation between per capita beer consumption and teacher’s salaries. Does giving a teacher a raise cause people to buy more beer? Does buying more beer cause teachers to get a raise?</li>
<li>A study shows that there is a correlation between people who have had a root canal and those that have cancer. Does that mean having a root canal causes cancer?</li>
</ol>
<section id="solution-4" class="level4" data-number="11.2.5.1">
<h4 data-number="11.2.5.1" class="anchored" data-anchor-id="solution-4"><span class="header-section-number">11.2.5.1</span> Solution</h4>
<ol type="a">
<li><p>A study showed a strong linear correlation between per capita beer consumption and teacher’s salaries. Does giving a teacher a raise cause people to buy more beer? Does buying more beer cause teachers to get a raise?</p>
<p>There is probably some other factor causing both of them to increase at the same time. Think about this: In a town where people have little extra money, they won’t have money for beer and they won’t give teachers raises. In another town where people have more extra money to spend it will be easier for them to buy more beer and they would be more willing to give teachers raises.</p></li>
</ol>
<!-- -->
<ol start="2" type="a">
<li><p>A study shows that there is a correlation between people who have had a root canal and those that have cancer. Does that mean having a root canal causes cancer?</p>
<p>Just because there is positive correlation doesn’t mean that one caused the other. It turns out that there is a positive correlation between eating carrots and cancer, but that doesn’t mean that eating carrots causes cancer. In other words, there are lots of relationships you can find between two variables, but that doesn’t mean that one caused the other.</p></li>
</ol>
<p>Remember a correlation only means a pattern exists. It does not mean that one variable causes the other variable to change.</p>
</section>
</section>
<section id="homework-for-correlation-section" class="level3" data-number="11.2.6">
<h3 data-number="11.2.6" class="anchored" data-anchor-id="homework-for-correlation-section"><span class="header-section-number">11.2.6</span> Homework for Correlation Section</h3>
<p><strong>For each problem, state the random variables.The Data Frame in this section are in section 10.1 and will be used in section 10.3.</strong></p>
<ol type="1">
<li>When an anthropologist finds skeletal remains, they need to figure out the height of the person. The height of a person (in cm) and the length of their metacarpal bone 1 (in mm) were collected and are in <span class="quarto-unresolved-ref">?tbl-Metacarpal</span> (\“Prediction of height,\” 2013). Find the coefficient of determination and the correlation coefficient, then interpret both.</li>
</ol>
<p><strong>Code book for Data Frame Metacarpal is below</strong> <span class="quarto-unresolved-ref">?tbl-Metacarpal</span>.</p>
<ol start="2" type="1">
<li><span class="quarto-unresolved-ref">?tbl-House</span> contains the value of the house and the amount of rental income in a year that the house brings in (\“Capital and rental,\” 2013). Find the coefficient of determination and the correlation coefficient, then interpret both.</li>
</ol>
<p><strong>Code book for Data Frame House is below <span class="quarto-unresolved-ref">?tbl-House</span>.</strong></p>
<ol start="3" type="1">
<li>The World Bank collects information on the life expectancy of a person in each country (\“Life expectancy at,\” 2013) and the fertility rate per woman in the country (\“Fertility rate,\” 2013). The Data Frame for countries for the year 2011 are in <span class="quarto-unresolved-ref">?tbl-Fertility</span>. Find the coefficient of determination and the correlation coefficient, then interpret both.</li>
</ol>
<p><strong>Code book for Data Frame Fertility is below <span class="quarto-unresolved-ref">?tbl-Fertility</span>.</strong></p>
<ol start="4" type="1">
<li>The World Bank collected data on the percentage of gross domestic product (GDP) that a country spends on health expenditures (Current health expenditure (% of GDP), 2019), the fertility rate of the country (Fertility rate, total (births per woman), 2019), and the percentage of woman receiving prenatal care (Pregnant women receiving prenatal care (%), 2019). The Data Frame for the countries where this information is available in <span class="quarto-unresolved-ref">?tbl-Fert_prenatal</span>. Find the coefficient of determination and the correlation coefficient between the percentage spent on health expenditure and the percentage of women receiving prenatal care, then interpret both.</li>
</ol>
<p><strong>Code book for Data Frame Fert_prenatal is below <span class="quarto-unresolved-ref">?tbl-Fert_prenatal</span>.</strong></p>
<ol start="5" type="1">
<li>The height and weight of baseball players are in <a href="#tbl-Baseball" class="quarto-xref">Table&nbsp;<span>11.3</span></a> (\“MLB heightsweights,\” 2013). Find the coefficient of determination and the correlation coefficient, then interpret both.</li>
</ol>
<p><strong>Code book for Data Frame Baseball is below <a href="#tbl-Baseball" class="quarto-xref">Table&nbsp;<span>11.3</span></a>.</strong></p>
<ol start="6" type="1">
<li>Different species have different body weights and brain weights are in <a href="#tbl-Body" class="quarto-xref">Table&nbsp;<span>11.4</span></a> (\“Brain2bodyweight,\” 2013). Find the coefficient of determination and the correlation coefficient, then interpret both.</li>
</ol>
<p><strong>Code book for Data Frame Body is below <a href="#tbl-Body" class="quarto-xref">Table&nbsp;<span>11.4</span></a>.</strong></p>
<ol start="7" type="1">
<li>A sample of hot dogs was taken and the amount of sodium (in mg) and calories were measured. (\“Data hotdogs,\” 2013) The Data Frame are in <span class="quarto-unresolved-ref">?tbl-Hotdog</span>. Find the coefficient of determination and the correlation coefficient, then interpret both.</li>
</ol>
<p><strong>Code book for data frame Hotdog is below <span class="quarto-unresolved-ref">?tbl-Hotdog</span>.</strong></p>
<ol start="8" type="1">
<li>Per capita income in 1960 dollars for European countries and the percent of the labor force that works in agriculture in 1960 are in <a href="#tbl-Agriculture" class="quarto-xref">Table&nbsp;<span>11.5</span></a> (\“OECD economic development,\” 2013). Find the coefficient of determination and the correlation coefficient, then interpret both.</li>
</ol>
<p><strong>Code book for Data Frame Agriculture is <a href="#tbl-Agriculture" class="quarto-xref">Table&nbsp;<span>11.5</span></a>.</strong></p>
<ol start="9" type="1">
<li>Cigarette smoking and cancer have been linked. The number of deaths per one hundred thousand from bladder cancer and the number of cigarettes sold per capita in 1960 are in <a href="#tbl-Cancer" class="quarto-xref">Table&nbsp;<span>11.6</span></a> (\“Smoking and cancer,\” 2013). Find the coefficient of determination and the correlation coefficient, then interpret both.</li>
</ol>
<p><strong>Code book for Data Frame Cancer is below <a href="#tbl-Cancer" class="quarto-xref">Table&nbsp;<span>11.6</span></a>.</strong></p>
<ol start="10" type="1">
<li>The weight of a car can influence the mileage that the car can obtain. A random sample of cars’ weights and mileage was collected and are in <a href="#tbl-Cars" class="quarto-xref">Table&nbsp;<span>11.7</span></a> (\“us auto mileage,\” 2019). Find the coefficient of determination and the correlation coefficient, then interpret both.</li>
</ol>
<p><strong>Code book for Data Frame Cars is below <a href="#tbl-Cars" class="quarto-xref">Table&nbsp;<span>11.7</span></a>.</strong></p>
<ol start="11" type="1">
<li><p>There is a correlation between police expenditure and crime rate. Does this mean that spending more money on police causes the crime rate to decrease? Explain your answer.</p></li>
<li><p>There is a correlation between tobacco sales and alcohol sales. Does that mean that using tobacco causes a person to also drink alcohol? Explain your answer.</p></li>
<li><p>There is a correlation between the average temperature in a location and the mortality rate from breast cancer. Does that mean that higher temperatures cause more women to die of breast cancer? Explain your answer.</p></li>
<li><p>There is a correlation between the length of time a tableware company polishes a dish and the price of the dish. Does that mean that the time a plate is polished determines the price of the dish? Explain your answer.</p></li>
</ol>
</section>
</section>
<section id="inference-for-regression-and-correlation" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="inference-for-regression-and-correlation"><span class="header-section-number">11.3</span> Inference for Regression and Correlation</h2>
<p>The idea behind regression is to find an equation that relates the response variable to the explanatory variables, and then use that equation to predict values of the response variable from values of the explanatory variables. But how do you now how good that estimate is? First you need a measure of the variability in the estimate, called the standard error of the estimate. The definition of the <strong>standard error of the estimate</strong> is how much error is in the estimate from the regression equation.</p>
<p><strong>Standard Error of the Estimate</strong> formula <span class="math inline">\(S_e=\sum{(\hat{y}-y)^2}\)</span></p>
<p>This formula is hard to work with but luckily r Studio will calculate it for you. In fact the command has already been used, so this information is already found. The command is</p>
<p>summary(lm_out) #lm_out is the name you gave the linear model</p>
<section id="example-finding-the-standard-error-of-the-estimate" class="level3" data-number="11.3.1">
<h3 data-number="11.3.1" class="anchored" data-anchor-id="example-finding-the-standard-error-of-the-estimate"><span class="header-section-number">11.3.1</span> Example: Finding the Standard Error of the Estimate</h3>
<p>Is there a relationship between the alcohol content and the number of calories in 12-ounce beer? To determine if there is a sample of beer’s alcohol content and calories (Find Out How Many Calories in Beer?, 2019), in <a href="#tbl-Beer" class="quarto-xref">Table&nbsp;<span>11.1</span></a>. Find the standard error of the estimate.</p>
<p><strong>Code book for data frame Beer is below <a href="#tbl-Beer" class="quarto-xref">Table&nbsp;<span>11.1</span></a>.</strong></p>
<section id="solution-5" class="level4" data-number="11.3.1.1">
<h4 data-number="11.3.1.1" class="anchored" data-anchor-id="solution-5"><span class="header-section-number">11.3.1.1</span> Solution</h4>
<p><span class="math inline">\(x\)</span> = alcohol content in the beer</p>
<p><span class="math inline">\(y\)</span> = calories in 12 ounce beer</p>
<p>First save the linear model with a name like lm_out_beer. Then use summary(lm_out_beer) to find the standard error of the estimate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>lm_out_beer<span class="ot">=</span><span class="fu">lm</span>(calories<span class="sc">~</span>alcohol, <span class="at">data=</span>Beer) </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_out_beer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = calories ~ alcohol, data = Beer)

Residuals:
    Min      1Q  Median      3Q     Max 
-51.869 -11.421  -0.145  11.855  55.473 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   14.527      4.577   3.174  0.00171 ** 
alcohol     2672.359     84.478  31.634  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 17.62 on 225 degrees of freedom
Multiple R-squared:  0.8164,    Adjusted R-squared:  0.8156 
F-statistic:  1001 on 1 and 225 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The standard error of the estimate is the residual standard error in the output. So the standard error of the estimate for the number of calories in a beer related to alcohol content is <span class="math inline">\(S_e=17.62\)</span></p>
</section>
</section>
<section id="prediction-interval" class="level3" data-number="11.3.2">
<h3 data-number="11.3.2" class="anchored" data-anchor-id="prediction-interval"><span class="header-section-number">11.3.2</span> Prediction Interval</h3>
<p>Using the regression equation you can predict the number of calories from the alcohol content. However, you only find one value. The problem is that beers vary a bit in calories even if they have the same alcohol content. It would be nice to have a range instead of a single value. The range is called a prediction interval.</p>
</section>
<section id="prediction-interval-for-an-individual-y" class="level3" data-number="11.3.3">
<h3 data-number="11.3.3" class="anchored" data-anchor-id="prediction-interval-for-an-individual-y"><span class="header-section-number">11.3.3</span> Prediction Interval for an Individual <span class="math inline">\(y\)</span></h3>
<p>Given the fixed value <span class="math inline">\(x\)</span>, the prediction interval for an individual <span class="math inline">\(y\)</span> is <span class="math inline">\(\hat{y}\pm E\)</span> where <span class="math inline">\(E\)</span> is the error of the estimate.</p>
<p>r will produce the prediction interval for you. The process follows</p>
<p>To calculate the linear model. Note this may already been done.</p>
<p>lm_out = lm(explanatory_variable~ response_variable)</p>
<p>The following will compute a prediction interval. For the prediction variable set to a particular value (put that value in place of the word value), at a particular C level (given as a decimal).</p>
<p>predict(lm_out, newdata=list(prediction_variable = value), interval=“prediction”, level=C)</p>
</section>
<section id="example-10.3.2-find-the-prediction-interval" class="level3" data-number="11.3.4">
<h3 data-number="11.3.4" class="anchored" data-anchor-id="example-10.3.2-find-the-prediction-interval"><span class="header-section-number">11.3.4</span> Example \#10.3.2: Find the Prediction Interval</h3>
<p>Is there a relationship between the alcohol content and the number of calories in 12-ounce beer? To determine if there is a sample of beer’s alcohol content and calories (Find Out How Many Calories in Beer?, 2019), in <a href="#tbl-Beer" class="quarto-xref">Table&nbsp;<span>11.1</span></a>. Find a 95% prediction interval for the number of calories when the alcohol content is 7.0%. content and calories (\“Calories in beer,,\” 2011). The Data Frame is in <a href="#tbl-Beer" class="quarto-xref">Table&nbsp;<span>11.1</span></a>.</p>
<section id="solution-6" class="level4" data-number="11.3.4.1">
<h4 data-number="11.3.4.1" class="anchored" data-anchor-id="solution-6"><span class="header-section-number">11.3.4.1</span> Solution</h4>
<p><span class="math inline">\(x\)</span> = alcohol content in the beer</p>
<p><span class="math inline">\(y\)</span> = calories in 12 ounce beer</p>
<p>Computing the prediction interval using r Studio</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(lm_out_beer, <span class="at">newdata=</span><span class="fu">list</span>(<span class="at">alcohol=</span><span class="fl">0.07</span>), <span class="at">interval =</span> <span class="st">"prediction"</span>, <span class="at">level=</span><span class="fl">0.95</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr     upr
1 201.5922 166.6664 236.518</code></pre>
</div>
</div>
<p>the fit = 201.5922 is the number of calories in the beer when the alcohol content is 7.0%. The prediction interval is between the lower (lwr) and upper (upr). The prediction interval is 166.6664 and 236.528. That means that 95% of all beer that has 7.0% alcohol has between 167 and 237 calories.</p>
</section>
</section>
<section id="hypothesis-test-for-correlation-or-slope" class="level3" data-number="11.3.5">
<h3 data-number="11.3.5" class="anchored" data-anchor-id="hypothesis-test-for-correlation-or-slope"><span class="header-section-number">11.3.5</span> Hypothesis Test for Correlation or Slope:</h3>
<p>How do you really say you have a correlation or a linear relationship? Can you test to see if there really is a correlation or linear relationship? Of course, the answer is yes. The hypothesis test for correlation is as follows.</p>
<ol type="1">
<li>State the random variables in words.</li>
</ol>
<p><span class="math inline">\(x\)</span> = explanatory variable</p>
<p><span class="math inline">\(y\)</span> = response variable</p>
<ol start="2" type="1">
<li>State the null and alternative hypotheses and the level of significance</li>
</ol>
<p><span class="math inline">\(H_o: \text{there is not a correlation or linear relationship}\)</span></p>
<p><span class="math inline">\(H_a: \text{there is a correlation or linear relationship}\)</span></p>
<p>Also, state your <span class="math inline">\(\alpha\)</span> level here.</p>
<ol start="3" type="1">
<li>State and check the conditions for the hypothesis test</li>
</ol>
<p>The conditions for the hypothesis test are the same conditions for regression and correlation.</p>
<ol start="4" type="1">
<li>Find the test statistic and p-value</li>
</ol>
<p>The test statistic and p-value is already in the summary(lm_out) output.</p>
<ol start="5" type="1">
<li>Conclusion</li>
</ol>
<p>This is where you write reject <span class="math inline">\(H_o\)</span> or fail to reject <span class="math inline">\(H_o\)</span>. The rule is: if the p-value <span class="math inline">\(&lt;\alpha\)</span>, then reject <span class="math inline">\(H_o\)</span>. If the p-value <span class="math inline">\(\ge \alpha\)</span>, then fail to reject <span class="math inline">\(H_o\)</span></p>
<ol start="6" type="1">
<li>Interpretation</li>
</ol>
<p>This is where you interpret in real world terms the conclusion to the test. The conclusion for a hypothesis test is that you either have enough evidence to support <span class="math inline">\(H_a\)</span>, or you do not have enough evidence to support <span class="math inline">\(H_a\)</span>.</p>
</section>
<section id="example-testing-the-claim-of-a-linear-correlation" class="level3" data-number="11.3.6">
<h3 data-number="11.3.6" class="anchored" data-anchor-id="example-testing-the-claim-of-a-linear-correlation"><span class="header-section-number">11.3.6</span> Example: Testing the Claim of a Linear Correlation</h3>
<p>Is there a linear relationship, or correlation, between the alcohol content and the number of calories in 12-ounce beer? To determine if there is a sample of beer’s alcohol content and calories (Find Out How Many Calories in Beer?, 2019), in <a href="#tbl-Beer" class="quarto-xref">Table&nbsp;<span>11.1</span></a>. Test at the 5% level.</p>
<section id="solution-7" class="level4" data-number="11.3.6.1">
<h4 data-number="11.3.6.1" class="anchored" data-anchor-id="solution-7"><span class="header-section-number">11.3.6.1</span> Solution</h4>
<ol type="1">
<li>State the random variables in words.</li>
</ol>
<p><span class="math inline">\(x\)</span> = alcohol content in the beer</p>
<p><span class="math inline">\(y\)</span> = calories in 12 ounce beer</p>
<ol start="2" type="1">
<li>State the null and alternative hypotheses and the level of significance</li>
</ol>
<p><span class="math inline">\(H_o: \text{there is not a correlation or linear relationship}\)</span></p>
<p><span class="math inline">\(H_a: \text{there is a correlation or linear relationship}\)</span></p>
<p>level of significance <span class="math inline">\(\alpha=0.05\)</span></p>
<ol start="3" type="1">
<li>State and check the conditions for the hypothesis test</li>
</ol>
<p>The conditions for the hypothesis test were already checked in <a href="#example-find-the-equation-of-the-regression-line">Example: Find the Equation of the Regression Line</a></p>
<ol start="4" type="1">
<li>Find the test statistic and p-value</li>
</ol>
<p>The command on r Studio is</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>lm_out_beer<span class="ot">&lt;-</span><span class="fu">lm</span>(calories<span class="sc">~</span>alcohol, <span class="at">data=</span>Beer) </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_out_beer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = calories ~ alcohol, data = Beer)

Residuals:
    Min      1Q  Median      3Q     Max 
-51.869 -11.421  -0.145  11.855  55.473 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   14.527      4.577   3.174  0.00171 ** 
alcohol     2672.359     84.478  31.634  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 17.62 on 225 degrees of freedom
Multiple R-squared:  0.8164,    Adjusted R-squared:  0.8156 
F-statistic:  1001 on 1 and 225 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The test statistic is the t value in the table for the explanatory variable. In this case that is 31.634. The p-value is the Pr(&gt;|t|) which is <span class="math inline">\(2.2X10^{-16}\)</span>.</p>
<ol start="5" type="1">
<li>Conclusion</li>
</ol>
<p>Reject <span class="math inline">\(H_o\)</span> since the p-value is less than 0.05.</p>
<ol start="6" type="1">
<li>Interpretation</li>
</ol>
<p>There is enough evidence to show that there is a correlation and linear relationship between alcohol content and number of calories in a 12-ounce bottle of beer.</p>
</section>
</section>
<section id="homework-for-inference-for-regression-and-correlation-section" class="level3" data-number="11.3.7">
<h3 data-number="11.3.7" class="anchored" data-anchor-id="homework-for-inference-for-regression-and-correlation-section"><span class="header-section-number">11.3.7</span> Homework for Inference for Regression and Correlation Section</h3>
<p><strong>For each problem, state the random variables. The Data Frame in this section are in the homework for section 10.1 and were also used in section 10.2.</strong></p>
<ol type="1">
<li>When an anthropologist finds skeletal remains, they need to figure out the height of the person. The height of a person (in cm) and the length of their metacarpal bone 1 (in mm) were collected and are in <span class="quarto-unresolved-ref">?tbl-Metacarpal</span> (\“Prediction of height,\” 2013).</li>
</ol>
<p><strong>Code book for Data Frame Metacarpal is below <span class="quarto-unresolved-ref">?tbl-Metacarpal</span>.</strong></p>
<ol type="a">
<li>Find the standard error of the estimate.</li>
<li>Compute a 99% prediction interval for height of a person with a metacarpal length of 44 mm.</li>
<li>Test at the 1% level for a correlation or linear relationship between length of metacarpal bone 1 and height of a person.</li>
</ol>
<!-- -->
<ol start="2" type="1">
<li><span class="quarto-unresolved-ref">?tbl-House</span> contains the value of the house and the amount of rental income in a year that the house brings in (\“Capital and rental,\” 2013).</li>
</ol>
<p><strong>Code book for Data Frame House is below <span class="quarto-unresolved-ref">?tbl-House</span>.</strong></p>
<ol type="a">
<li>Find the standard error of the estimate.</li>
<li>Compute a 95% prediction interval for the rental income on a house worth \$230,000.</li>
<li>Test at the 5% level for a correlation or linear relationship between house value and rental amount.</li>
</ol>
<!-- -->
<ol start="3" type="1">
<li>The World Bank collects information on the life expectancy of a person in each country (\“Life expectancy at,\” 2013) and the fertility rate per woman in the country (\“Fertility rate,\” 2013). The Data Frame for countries for the year 2011 is in <span class="quarto-unresolved-ref">?tbl-Fertility</span>.</li>
</ol>
<p><strong>Code book for Data Frame Fertility is below <span class="quarto-unresolved-ref">?tbl-Fertility</span>.</strong></p>
<ol type="a">
<li>Find the standard error of the estimate.</li>
<li>Compute a 99% prediction interval for the life expectancy for a country that has a fertility rate of 2.7.</li>
<li>Test at the 1% level for a correlation or linear relationship between fertility rate and life expectancy.</li>
</ol>
<!-- -->
<ol start="4" type="1">
<li>The World Bank collected data on the percentage of gross domestic product (GDP) that a country spends on health expenditures (Current health expenditure (% of GDP), 2019), the fertility rate of the country (Fertility rate, total (births per woman), 2019), and the percentage of woman receiving prenatal care (Pregnant women receiving prenatal care (%), 2019). The Data Frame for the countries where this information is available in <span class="quarto-unresolved-ref">?tbl-Fert_prenatal</span>.</li>
</ol>
<p><strong>Code book for Data Frame Fert_prenatal is below <span class="quarto-unresolved-ref">?tbl-Fert_prenatal</span>.</strong></p>
<ol type="a">
<li>Find the standard error of the estimate.</li>
<li>Compute a 95% prediction interval for the percentage of woman receiving prenatal care for a country that spends 5.0 % of GDP on health expenditure.</li>
<li>Test at the 5% level for a correlation or linear relationship between percentage spent on health expenditure and the percentage of women receiving prenatal care.</li>
</ol>
<!-- -->
<ol start="5" type="1">
<li>The height and weight of baseball players are in <a href="#tbl-Baseball" class="quarto-xref">Table&nbsp;<span>11.3</span></a> (\“MLB heightsweights,\” 2013).</li>
</ol>
<p><strong>Code book for Data Frame Baseball is below <a href="#tbl-Baseball" class="quarto-xref">Table&nbsp;<span>11.3</span></a>.</strong></p>
<ol type="a">
<li>Find the standard error of the estimate.</li>
<li>Compute a 95% prediction interval for the weight of a baseball player that is 75 inches tall.</li>
<li>Test at the 5% level for a correlation or linear relationship between height and weight of baseball players.</li>
</ol>
<!-- -->
<ol start="6" type="1">
<li>Different species have different body weights and brain weights are in <a href="#tbl-Body" class="quarto-xref">Table&nbsp;<span>11.4</span></a> (\“Brain2bodyweight,\” 2013).</li>
</ol>
<p><strong>Code book for Data Frame Body is below <a href="#tbl-Body" class="quarto-xref">Table&nbsp;<span>11.4</span></a>.</strong></p>
<ol type="a">
<li>Find the standard error of the estimate.</li>
<li>Compute a 99% prediction interval for the brain weight for a species that has a body weight of 62 kg.</li>
<li>Test at the 1% level for a correlation or linear relationship between body weights and brain weights.</li>
</ol>
<!-- -->
<ol start="7" type="1">
<li>A sample of hot dogs was taken and the amount of sodium (in mg) and calories were measured. (\“Data hotdogs,\” 2013) The Data Frame are in <span class="quarto-unresolved-ref">?tbl-Hotdog</span>.</li>
</ol>
<p><strong>Code book for data frame Hotdog is below <span class="quarto-unresolved-ref">?tbl-Hotdog</span>.</strong></p>
<ol type="a">
<li>Find the standard error of the estimate.</li>
<li>Compute a 95% prediction interval for the amount of sodium a beef hot dog has if it is 170 calories.</li>
<li>Test at the 5% level for a correlation or linear relationship between amount of calories and amount of sodium.</li>
</ol>
<!-- -->
<ol start="8" type="1">
<li>Per capita income in 1960 dollars for European countries and the percent of the labor force that works in agriculture in 1960 are in <a href="#tbl-Agriculture" class="quarto-xref">Table&nbsp;<span>11.5</span></a> (\“OECD economic development,\” 2013).</li>
</ol>
<p><strong>Code book for Data Frame Agriculture is below <a href="#tbl-Agriculture" class="quarto-xref">Table&nbsp;<span>11.5</span></a>.</strong></p>
<ol type="a">
<li>Find the standard error of the estimate.</li>
<li>Compute a 90% prediction interval for the per capita income in a country that has 21 percent of labor in agriculture.</li>
<li>Test at the 5% level for a correlation or linear relationship between percent of labor force in agriculture and per capita income.</li>
</ol>
<!-- -->
<ol start="9" type="1">
<li>Cigarette smoking and cancer have been linked. The number of deaths per one hundred thousand from bladder cancer and the number of cigarettes sold per capita in 1960 are in <a href="#tbl-Cancer" class="quarto-xref">Table&nbsp;<span>11.6</span></a> (“Smoking and cancer,” 2013).</li>
</ol>
<p><strong>Code book for Data Frame Cancer is below <a href="#tbl-Cancer" class="quarto-xref">Table&nbsp;<span>11.6</span></a>.</strong></p>
<ol type="a">
<li>Find the standard error of the estimate.</li>
<li>Compute a 99% prediction interval for the number of deaths from bladder cancer when the cigarette sales were 20 per capita.</li>
<li>Test at the 1% level for a correlation or linear relationship between cigarette smoking and deaths of bladder cancer.</li>
</ol>
<!-- -->
<ol start="10" type="1">
<li>The weight of a car can influence the mileage that the car can obtain. A random sample of cars’ weights and mileage was collected and are in <a href="#tbl-Cars" class="quarto-xref">Table&nbsp;<span>11.7</span></a> (“us auto mileage,” 2019).</li>
</ol>
<p><strong>Code book for Data Frame Cars is below <a href="#tbl-Cars" class="quarto-xref">Table&nbsp;<span>11.7</span></a>.</strong></p>
<ol type="a">
<li>Find the standard error of the estimate.</li>
<li>Compute a 95% prediction interval for the mileage on a car that weighs 3800 pounds.</li>
<li>Test at the 5% level for a correlation or linear relationship between the weight of cars and mileage.</li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Two Sample Inference.html" class="pagination-link" aria-label="Two Sample Inference">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Two Sample Inference</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Chi-Square and ANOVA Tests.html" class="pagination-link" aria-label="Chi-squared and ANOVA Tests">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Chi-squared and ANOVA Tests</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>